[package]
name = "axum"
version = "*"
edition = "2024"
[dependencies]
any_spawner = { path = "../any_spawner", version = "*", features = ["tokio"] }
hydration_context = { path = "../hydration_context", version = "*" }
axum = { version = "*", default-features = false, features = ["matched-path" ] }
dashmap = { version = "*", default-features = true }
futures = { version = "*", default-features = true }
leptos = { path = "../leptos", version = "*", features = ["nonce", "ssr"] }
server_fn = { path = "../server_fn", version = "*", features = ["axum-no-default"], optional = true }
leptos_macro = { path = "../leptos_macro", version = "*", features = ["axum"] }
meta = { path = "../../meta", version = "*", features = ["ssr", "nonce"] }
router = { path = "../../router", version = "*", features = ["ssr"] }
utils = { path = "../utils", version = "*" }
tachys = { path = "../tachys", version = "*", optional = true }
tokio = { version = "*", default-features = false }
tower = { version = "*", features = ["util"], default-features = true }
tower-http = { version = "*", default-features = true }
tracing = { version = "*", optional = true, default-features = true }
or_poisoned = { path = "../or_poisoned", version = "*" }
[dev-dependencies]
anyhow = { version = "*" }
axum = { version = "*", default-features = true }
reqwest = { version = "*" }
tokio = { version = "*", features = ["io-util", "net", "process", "rt-multi-thread", "time" ], default-features = true }
[features]
wasm = []
default = [
"tokio/fs",
"tokio/sync",
"tower-http/fs",
"tower/util",
"server_fn/axum" ]
islands-router = ["tachys/islands"]
tracing = ["dep:tracing"]


[build-dependencies]
rustc_version = "*"



