# These tests depend on `memstore`, while `memstore` enables `serde` feature of `lyxalraft`.
# This make it impossible to test lyxalraft with `serde` feature off.

[package]
name = "tests"
description = "lyxal_raft integration tests. To prevent memstore from enabling `serde` feature"

version       = { workspace = true }
edition       = { workspace = true }
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
homepage      = { workspace = true }
keywords      = { workspace = true }
license       = { workspace = true }
repository    = { workspace = true }

[dependencies]

[dev-dependencies]
lyxal_raft           = { path = "../lyxal_core", version = "0.10.0", features = ["type-alias"] }
lyxal_raft-memstore  = { path = "../lyxal_stores/memstore" }

anyerror           = { workspace = true }
anyhow             = { workspace = true }
derive_more        = { workspace = true }
futures            = { workspace = true }
lazy_static        = { workspace = true }
maplit             = { workspace = true }
pretty_assertions  = { workspace = true }
rand               = { workspace = true }
test-harness       = { workspace = true }
tracing            = { workspace = true }
tracing-appender   = { workspace = true }
tracing-subscriber = { workspace = true }


[features]

bt = ["lyxal_raft/bt"]
single-term-leader = ["lyxal_raft-memstore/single-term-leader"]
