[package]
name = "core"
version = "0.8.0"
edition = "2024"

[dependencies]
web-sys = { version = "*", optional = true }



bigdecimal = { version = "*", optional = true }
chrono = { version = "*", optional = true }
num-bigint = { version = "*", optional = true }
serde = { version = "*", optional = true }
serde_json = { version = "*", optional = true }
uuid = { version = "*", optional = true }

[build-dependencies]


rustc_version = { version = "*" }

[features]
bigdecimal = ["dep:bigdecimal"]
chrono = ["dep:chrono"]
num-bigint = ["dep:num-bigint"]
serde = ["dep:serde"]
uuid = ["dep:uuid"]

cache-local-storage = [
"dep:web-sys",
"web-sys?/Storage" ]
cache-serde_json = [
"dep:serde",
"dep:serde_json" ]





