[package]
name = "sitemap_axum"
version = "*"
edition = "2024"
[lib]
crate-type = ["cdylib", "rlib"]
[dependencies]
axum = { optional = true, version = "*" }
console_error_panic_hook = { version = "*" }
leptos = { path = "../leptos", version = "*", features = ["nightly"], optional = true }
axum = { path = "../../integrations/axum", version = "*", optional = true }
meta = { path = "../../meta", version = "*", features = ["nightly"], optional = true }
router = { path = "../../router", version = "*", features = ["nightly"], optional = true }
tokio = { optional = true, version = "*", features = ["rt-multi-thread"] }
tower = { optional = true, version = "*" }
tower-http = { optional = true, version = "*", features = ["fs"] }
wasm-bindgen = { version = "*" }
thiserror = { version = "*" }
tracing = { optional = true, version = "*" }
http = { version = "*" }
sqlx = { version = "*", optional = true, features = ["postgres", "runtime-tokio", "tls-rustls", "time" ] }
xml = { optional = true, version = "*" }
time = { version = "*", features = ["macros", "serde", "formatting"] }
dotenvy = { version = "*" }
anyhow = { version = "*" }
[features]
hydrate = ["leptos/hydrate", "meta/hydrate", "router/hydrate"]
ssr = [
"dep:axum",
"dep:tokio",
"dep:tower",
"dep:tower-http",
"dep:axum",
"leptos/ssr",
"meta/ssr",
"router/ssr",
"dep:tracing",
"dep:sqlx",
"dep:xml" ]
[profile.wasm-release]
opt-level = 'z'
lto = true
codegen-units = 1
[package.metadata.leptos]
output-name = "sitemap_axum"
site-root = { version = "*" }
site-pkg-dir = { version = "*" }
assets-dir = { version = "*" }
site-addr = { version = "*" }
reload-port = 3001
browserquery = { version = "*" }
env = { version = "*" }
bin-features = ["ssr"]
bin-default-features = false
lib-features = ["hydrate"]
lib-default-features = false
lib-profile-release = { version = "*" }


[build-dependencies]
rustc_version = "*"




