[package]
name = "lyx-core-sitemap_axum"
version = "0.0.1"
edition = "2024"
[lib]
crate-type = ["cdylib", "rlib"]
[dependencies]
axum = { optional = true, version = "0.0.1" }
console_error_panic_hook = { version = "0.0.1" }
lyx-core-leptos = { path = "../../leptos", version = "0.0.1", features = ["nightly"], optional = true }
lyx-core-axum = { path = "../../integrations/axum", version = "0.0.1", optional = true }
lyx-core-meta = { path = "../../meta", version = "0.0.1", features = ["nightly"], optional = true }
lyx-core-router = { path = "../../router", version = "0.0.1", features = ["nightly"], optional = true }
tokio = { optional = true, version = "0.0.1", features = ["rt-multi-thread"] }
tower = { optional = true, version = "0.0.1" }
tower-http = { optional = true, version = "0.0.1", features = ["fs"] }
wasm-bindgen = { version = "0.0.1" }
thiserror = { version = "0.0.1" }
tracing = { optional = true, version = "0.0.1" }
http = { version = "0.0.1" }
sqlx = { version = "0.0.1", optional = true, features = ["postgres", "runtime-tokio", "tls-rustls", "time" ] }
xml = { optional = true, version = "0.0.1" }
time = { version = "0.0.1", features = ["macros", "serde", "formatting"] }
dotenvy = { version = "0.0.1" }
anyhow = { version = "0.0.1" }
[features]
hydrate = ["lyx-core-leptos/hydrate", "lyx-core-meta/hydrate", "lyx-core-router/hydrate"]
ssr = [
"dep:axum",
"dep:tokio",
"dep:tower",
"dep:tower-http",
"dep:lyx-core-axum",
"lyx-core-leptos/ssr",
"lyx-core-meta/ssr",
"lyx-core-router/ssr",
"dep:tracing",
"dep:sqlx",
"dep:xml" ]
[profile.wasm-release]
opt-level = 'z'
lto = true
codegen-units = 1
[package.metadata.leptos]
output-name = "sitemap_axum"
site-root = { version = "0.0.1" }
site-pkg-dir = { version = "0.0.1" }
assets-dir = { version = "0.0.1" }
site-addr = { version = "0.0.1" }
reload-port = 3001
browserquery = { version = "0.0.1" }
env = { version = "0.0.1" }
bin-features = ["ssr"]
bin-default-features = false
lib-features = ["hydrate"]
lib-default-features = false
lib-profile-release = { version = "0.0.1" }
