[package]
name = "leptos_integration_utils"
version = "0.8.8"
authors = ["Greg Johnston"]
license = "MIT"
repository = "https://github.com/leptos-rs/leptos"
description = "Utilities for Leptos integrations."
edition.workspace = true
rust-version.workspace = true

[dependencies]
futures = { workspace = true, optional = true }
leptos_config = { workspace = true }
tracing = { workspace = true, optional = true }

[features]
ssr = ["dep:futures", "dep:tracing"]
