[package]
name = "lyxal_types_proxy"
version.workspace = true
readme = "README.md"
edition.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
prost.workspace = true
serde = { workspace = true, features = ["derive"] }
