[package]
name = "reactive_stores"
version = "0.8.0"
edition = "2024"
[dependencies]
guardian = { version = "*", default-features = true }
itertools = { version = "*", default-features = true }
or_poisoned = { path = "../or_poisoned", version = "*" }
paste = { version = "*", default-features = true }
reactive_graph = { path = "../reactive_graph", version = "*" }
rustc-hash = { version = "*", default-features = true }
reactive_stores_macro = { path = "../reactive_stores_macro", version = "*" }
dashmap = { version = "*", default-features = true }
send_wrapper = { version = "*", default-features = true }
[dev-dependencies]
tokio = { version = "*", features = ["rt-multi-thread", "macros" ], default-features = true }
tokio-test = { version = "*", default-features = true }
any_spawner = { path = "../any_spawner", version = "*", features = ["futures-executor", "tokio"] }
reactive_graph = { path = "../reactive_graph", version = "*", features = ["effects"] }
leptos = { path = "../leptos", version = "*", features = ["csr"] }


[build-dependencies]
rustc_version = "*"



