[package]
name = "test-bench"
version = "*"
edition = "2024"
[dependencies]
console_error_panic_hook = { version = "*" }
gloo = { version = "*", features = ["futures"] }
leptos = { path = "../leptos", version = "*", features = ["nightly", "csr", "tracing"] }
tracing = { version = "*" }
tracing-subscriber = { version = "*" }
tracing-subscriber-wasm = { version = "*" }


[build-dependencies]
rustc_version = "*"


