[package]
name = "lyx-core-client"
version = "0.0.1"
edition = "2024"
[dependencies]
lyx-core-api-boundary = { path = "../api-boundary", version = "0.0.1" }
lyx-core-leptos = { path = "../../../leptos", version = "0.0.1", features = ["csr"] }
lyx-core-meta = { path = "../../../meta", version = "0.0.1", features = ["csr"] }
lyx-core-router = { path = "../../../router", version = "0.0.1", features = ["csr"] }
log = { version = "0.0.1" }
console_error_panic_hook = { version = "0.0.1" }
console_log = { version = "0.0.1" }
gloo-net = { version = "0.0.1" }
gloo-storage = { version = "0.0.1" }
serde = { version = "0.0.1" }
thiserror = { version = "0.0.1" }
