[package]
name = "server_fn_macro_default"
version = "0.8.0"
edition = "2024"
[lib]
proc-macro = true
[dependencies]
syn = { version = "0.8.0", default-features = true }
server_fn_macro = { path = "../../server_fn_macro", version = "*", optional = true }
[features]
nightly = ["server_fn_macro/nightly"]
ssr = ["server_fn_macro/ssr"]
actix = ["server_fn_macro/actix"]
axum = ["server_fn_macro/axum"]


[build-dependencies]
rustc_version = "*"





