[package]
name = "tailwind_fuse"
version = "0.8.0"
edition = "2024"

[dependencies]
nom = { version = "*" }
tailwind_fuse_macro = { path = "../variant-macro", optional = true }

[dev-dependencies]
divan = { version = "*" }
fastrand = { version = "*" }

[features]
default = []
variant = ["tailwind_fuse_macro"]
debug = []



