-- Seeds pour les villes du pays: BN --

CREATE base_city:bn_9820 SET state = base_state:bn_be, key.name = i18n_key:i18n_city_bn_9820_name, native = 'Kuala Belait', location = (114.23120000, 4.58361000), timezone = base_timezone:asia_manila, wikiDataId = 'Q588045';
CREATE base_city:bn_9823 SET state = base_state:bn_be, key.name = i18n_key:i18n_city_bn_9823_name, native = 'Dia akan menjadi', location = (114.32476000, 4.60637000), timezone = base_timezone:asia_manila, wikiDataId = 'Q2159472';
CREATE base_city:bn_9816 SET state = base_state:bn_bm, key.name = i18n_key:i18n_city_bn_9816_name, native = 'Bandar Seri Begawan', location = (114.94006000, 4.89035000), timezone = base_timezone:asia_manila, wikiDataId = 'Q9279';
CREATE base_city:bn_9818 SET state = base_state:bn_bm, key.name = i18n_key:i18n_city_bn_9818_name, native = 'Berakas A', location = (114.92989000, 4.97032000), timezone = base_timezone:asia_manila, wikiDataId = 'Q1125479';
CREATE base_city:bn_9819 SET state = base_state:bn_bm, key.name = i18n_key:i18n_city_bn_9819_name, native = 'Saya akan mendapat', location = (115.04664000, 5.02447000), timezone = base_timezone:asia_manila, wikiDataId = 'Q1125479';
CREATE base_city:bn_9821 SET state = base_state:bn_bm, key.name = i18n_key:i18n_city_bn_9821_name, native = 'Berbohong', location = (115.02078000, 4.97058000), timezone = base_timezone:asia_manila, wikiDataId = 'Q588045';
CREATE base_city:bn_9822 SET state = base_state:bn_bm, key.name = i18n_key:i18n_city_bn_9822_name, native = 'Terasa', location = (115.05841000, 5.01718000), timezone = base_timezone:asia_manila, wikiDataId = 'Q588045';
CREATE base_city:bn_9817 SET state = base_state:bn_te, key.name = i18n_key:i18n_city_bn_9817_name, native = 'Bahagian', location = (115.07167000, 4.70861000), timezone = base_timezone:asia_manila, wikiDataId = 'Q1125479';
CREATE base_city:bn_9824 SET state = base_state:bn_tu, key.name = i18n_key:i18n_city_bn_9824_name, native = 'Tutong', location = (114.64917000, 4.80278000), timezone = base_timezone:asia_manila, wikiDataId = 'Q2299301';
