[package]
name = "experimentation_platform"
version = "0.8.0"
edition = "2024"

[dependencies]
actix-web = { version = "*" }
actix-http = { version = "*" }
anyhow = { version = "*" }
blake3 = { version = "*" }
cac_client = { path = "../cac_client" }
chrono = { version = "*" }
diesel = { version = "*" }
experimentation_client = { path = "../experimentation_client" }
log = { version = "*" }
reqwest = { version = "*" }
serde = { version = "*" }
serde_json = { version = "*" }
service_utils = { path = "../service_utils" }
superposition_derives = { path = "../superposition_derives" }
superposition_macros = { path = "../superposition_macros" }
superposition_types = { path = "../superposition_types", features = ["api", "experimentation", "result", "diesel_derives", "server" ], optional = true }

[features]
disable_db_data_validation = ["superposition_types/disable_db_data_validation"]







