[package]
name = "app"
version = "0.8.0"
edition = "2024"

[dependencies]
leptos_axum = { ${2, optional = true }, optional = true }
leptos_query = { ${2}, optional = true }
leptos_query_devtools = { ${2}, optional = true }

[features]
default = []
hydrate = ["leptos/hydrate", "leptos_meta/hydrate", "leptos_router/hydrate", "leptos_query/hydrate", "leptos_query_devtools/csr"]
ssr = ["leptos/ssr", "leptos_meta/ssr", "leptos_router/ssr", "dep:leptos_axum", "leptos_query/ssr"]










