[package]
name = "app"
version = "0.0.1"
edition = "2024"

[dependencies]
leptos_axum = { version = "0.0.1", path = "../../../../../core/lyx-core-leptos/integrations/axum", optional = true }
leptos_query = { version = "0.0.1", path = "../../../query", optional = true }
leptos_query_devtools = { version = "0.0.1", path = "../../../devtools", optional = true }

[features]
default = []
hydrate = ["leptos/hydrate", "leptos_meta/hydrate", "leptos_router/hydrate", "leptos_query/hydrate", "leptos_query_devtools/csr"]
ssr = ["leptos/ssr", "leptos_meta/ssr", "leptos_router/ssr", "dep:leptos_axum", "leptos_query/ssr"]
