-- Batch 22: Cles i18n pour 100 tools

CREATE i18n_key:tool_tapfiliate_programAffiliate_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_tapfiliate_programAffiliate_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_tapfiliate_programAffiliate_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_tapfiliate_programAffiliate_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_tapfiliate_programAffiliate_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_tapfiliate_programAffiliate_getMany_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_tapfiliate_programAffiliate_getMany_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_tapfiliate_programAffiliate_getMany_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_tapfiliate_programAffiliate_getMany_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_tapfiliate_programAffiliate_getMany_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_tapfiliate_affiliatemetadata_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_tapfiliate_affiliatemetadata_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_tapfiliate_affiliatemetadata_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_tapfiliate_affiliatemetadata_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_tapfiliate_affiliatemetadata_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_tapfiliate_affiliatemetadata_getMany_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_tapfiliate_affiliatemetadata_getMany_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_tapfiliate_affiliatemetadata_getMany_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_tapfiliate_affiliatemetadata_getMany_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_tapfiliate_affiliatemetadata_getMany_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_tapfiliate_programaffiliate_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_tapfiliate_programaffiliate_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_tapfiliate_programaffiliate_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_tapfiliate_programaffiliate_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_tapfiliate_programaffiliate_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_tapfiliate_programaffiliate_getMany_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_tapfiliate_programaffiliate_getMany_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_tapfiliate_programaffiliate_getMany_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_tapfiliate_programaffiliate_getMany_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_tapfiliate_programaffiliate_getMany_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_telegram_chat_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_telegram_chat_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_telegram_chat_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_telegram_chat_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_telegram_chat_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_telegram_chat_administrators_name SET description = "Nom du tool Get Administrators";
CREATE i18n_key:tool_telegram_chat_administrators_desc SET description = "Description du tool Get Administrators";
CREATE i18n_key:tool_telegram_chat_administrators_tooltip SET description = "Tooltip du tool Get Administrators";
CREATE i18n_key:tool_telegram_chat_administrators_success SET description = "Message de succes du tool Get Administrators";
CREATE i18n_key:tool_telegram_chat_administrators_error SET description = "Message d'erreur du tool Get Administrators";

CREATE i18n_key:tool_telegram_chat_member_name SET description = "Nom du tool Get Member";
CREATE i18n_key:tool_telegram_chat_member_desc SET description = "Description du tool Get Member";
CREATE i18n_key:tool_telegram_chat_member_tooltip SET description = "Tooltip du tool Get Member";
CREATE i18n_key:tool_telegram_chat_member_success SET description = "Message de succes du tool Get Member";
CREATE i18n_key:tool_telegram_chat_member_error SET description = "Message d'erreur du tool Get Member";

CREATE i18n_key:tool_telegram_chat_leave_name SET description = "Nom du tool Leave";
CREATE i18n_key:tool_telegram_chat_leave_desc SET description = "Description du tool Leave";
CREATE i18n_key:tool_telegram_chat_leave_tooltip SET description = "Tooltip du tool Leave";
CREATE i18n_key:tool_telegram_chat_leave_success SET description = "Message de succes du tool Leave";
CREATE i18n_key:tool_telegram_chat_leave_error SET description = "Message d'erreur du tool Leave";

CREATE i18n_key:tool_telegram_chat_setDescription_name SET description = "Nom du tool Set Description";
CREATE i18n_key:tool_telegram_chat_setDescription_desc SET description = "Description du tool Set Description";
CREATE i18n_key:tool_telegram_chat_setDescription_tooltip SET description = "Tooltip du tool Set Description";
CREATE i18n_key:tool_telegram_chat_setDescription_success SET description = "Message de succes du tool Set Description";
CREATE i18n_key:tool_telegram_chat_setDescription_error SET description = "Message d'erreur du tool Set Description";

CREATE i18n_key:tool_telegram_chat_setTitle_name SET description = "Nom du tool Set Title";
CREATE i18n_key:tool_telegram_chat_setTitle_desc SET description = "Description du tool Set Title";
CREATE i18n_key:tool_telegram_chat_setTitle_tooltip SET description = "Tooltip du tool Set Title";
CREATE i18n_key:tool_telegram_chat_setTitle_success SET description = "Message de succes du tool Set Title";
CREATE i18n_key:tool_telegram_chat_setTitle_error SET description = "Message d'erreur du tool Set Title";

CREATE i18n_key:tool_telegram_callback_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_telegram_callback_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_telegram_callback_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_telegram_callback_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_telegram_callback_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_telegram_callback_administrators_name SET description = "Nom du tool Get Administrators";
CREATE i18n_key:tool_telegram_callback_administrators_desc SET description = "Description du tool Get Administrators";
CREATE i18n_key:tool_telegram_callback_administrators_tooltip SET description = "Tooltip du tool Get Administrators";
CREATE i18n_key:tool_telegram_callback_administrators_success SET description = "Message de succes du tool Get Administrators";
CREATE i18n_key:tool_telegram_callback_administrators_error SET description = "Message d'erreur du tool Get Administrators";

CREATE i18n_key:tool_telegram_callback_member_name SET description = "Nom du tool Get Member";
CREATE i18n_key:tool_telegram_callback_member_desc SET description = "Description du tool Get Member";
CREATE i18n_key:tool_telegram_callback_member_tooltip SET description = "Tooltip du tool Get Member";
CREATE i18n_key:tool_telegram_callback_member_success SET description = "Message de succes du tool Get Member";
CREATE i18n_key:tool_telegram_callback_member_error SET description = "Message d'erreur du tool Get Member";

CREATE i18n_key:tool_telegram_callback_leave_name SET description = "Nom du tool Leave";
CREATE i18n_key:tool_telegram_callback_leave_desc SET description = "Description du tool Leave";
CREATE i18n_key:tool_telegram_callback_leave_tooltip SET description = "Tooltip du tool Leave";
CREATE i18n_key:tool_telegram_callback_leave_success SET description = "Message de succes du tool Leave";
CREATE i18n_key:tool_telegram_callback_leave_error SET description = "Message d'erreur du tool Leave";

CREATE i18n_key:tool_telegram_callback_setDescription_name SET description = "Nom du tool Set Description";
CREATE i18n_key:tool_telegram_callback_setDescription_desc SET description = "Description du tool Set Description";
CREATE i18n_key:tool_telegram_callback_setDescription_tooltip SET description = "Tooltip du tool Set Description";
CREATE i18n_key:tool_telegram_callback_setDescription_success SET description = "Message de succes du tool Set Description";
CREATE i18n_key:tool_telegram_callback_setDescription_error SET description = "Message d'erreur du tool Set Description";

CREATE i18n_key:tool_telegram_callback_setTitle_name SET description = "Nom du tool Set Title";
CREATE i18n_key:tool_telegram_callback_setTitle_desc SET description = "Description du tool Set Title";
CREATE i18n_key:tool_telegram_callback_setTitle_tooltip SET description = "Tooltip du tool Set Title";
CREATE i18n_key:tool_telegram_callback_setTitle_success SET description = "Message de succes du tool Set Title";
CREATE i18n_key:tool_telegram_callback_setTitle_error SET description = "Message d'erreur du tool Set Title";

CREATE i18n_key:tool_telegram_file_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_telegram_file_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_telegram_file_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_telegram_file_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_telegram_file_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_telegram_file_administrators_name SET description = "Nom du tool Get Administrators";
CREATE i18n_key:tool_telegram_file_administrators_desc SET description = "Description du tool Get Administrators";
CREATE i18n_key:tool_telegram_file_administrators_tooltip SET description = "Tooltip du tool Get Administrators";
CREATE i18n_key:tool_telegram_file_administrators_success SET description = "Message de succes du tool Get Administrators";
CREATE i18n_key:tool_telegram_file_administrators_error SET description = "Message d'erreur du tool Get Administrators";

CREATE i18n_key:tool_telegram_file_member_name SET description = "Nom du tool Get Member";
CREATE i18n_key:tool_telegram_file_member_desc SET description = "Description du tool Get Member";
CREATE i18n_key:tool_telegram_file_member_tooltip SET description = "Tooltip du tool Get Member";
CREATE i18n_key:tool_telegram_file_member_success SET description = "Message de succes du tool Get Member";
CREATE i18n_key:tool_telegram_file_member_error SET description = "Message d'erreur du tool Get Member";

CREATE i18n_key:tool_telegram_file_leave_name SET description = "Nom du tool Leave";
CREATE i18n_key:tool_telegram_file_leave_desc SET description = "Description du tool Leave";
CREATE i18n_key:tool_telegram_file_leave_tooltip SET description = "Tooltip du tool Leave";
CREATE i18n_key:tool_telegram_file_leave_success SET description = "Message de succes du tool Leave";
CREATE i18n_key:tool_telegram_file_leave_error SET description = "Message d'erreur du tool Leave";

CREATE i18n_key:tool_telegram_file_setDescription_name SET description = "Nom du tool Set Description";
CREATE i18n_key:tool_telegram_file_setDescription_desc SET description = "Description du tool Set Description";
CREATE i18n_key:tool_telegram_file_setDescription_tooltip SET description = "Tooltip du tool Set Description";
CREATE i18n_key:tool_telegram_file_setDescription_success SET description = "Message de succes du tool Set Description";
CREATE i18n_key:tool_telegram_file_setDescription_error SET description = "Message d'erreur du tool Set Description";

CREATE i18n_key:tool_telegram_file_setTitle_name SET description = "Nom du tool Set Title";
CREATE i18n_key:tool_telegram_file_setTitle_desc SET description = "Description du tool Set Title";
CREATE i18n_key:tool_telegram_file_setTitle_tooltip SET description = "Tooltip du tool Set Title";
CREATE i18n_key:tool_telegram_file_setTitle_success SET description = "Message de succes du tool Set Title";
CREATE i18n_key:tool_telegram_file_setTitle_error SET description = "Message d'erreur du tool Set Title";

CREATE i18n_key:tool_telegram_message_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_telegram_message_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_telegram_message_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_telegram_message_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_telegram_message_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_telegram_message_administrators_name SET description = "Nom du tool Get Administrators";
CREATE i18n_key:tool_telegram_message_administrators_desc SET description = "Description du tool Get Administrators";
CREATE i18n_key:tool_telegram_message_administrators_tooltip SET description = "Tooltip du tool Get Administrators";
CREATE i18n_key:tool_telegram_message_administrators_success SET description = "Message de succes du tool Get Administrators";
CREATE i18n_key:tool_telegram_message_administrators_error SET description = "Message d'erreur du tool Get Administrators";

CREATE i18n_key:tool_telegram_message_member_name SET description = "Nom du tool Get Member";
CREATE i18n_key:tool_telegram_message_member_desc SET description = "Description du tool Get Member";
CREATE i18n_key:tool_telegram_message_member_tooltip SET description = "Tooltip du tool Get Member";
CREATE i18n_key:tool_telegram_message_member_success SET description = "Message de succes du tool Get Member";
CREATE i18n_key:tool_telegram_message_member_error SET description = "Message d'erreur du tool Get Member";

CREATE i18n_key:tool_telegram_message_leave_name SET description = "Nom du tool Leave";
CREATE i18n_key:tool_telegram_message_leave_desc SET description = "Description du tool Leave";
CREATE i18n_key:tool_telegram_message_leave_tooltip SET description = "Tooltip du tool Leave";
CREATE i18n_key:tool_telegram_message_leave_success SET description = "Message de succes du tool Leave";
CREATE i18n_key:tool_telegram_message_leave_error SET description = "Message d'erreur du tool Leave";

CREATE i18n_key:tool_telegram_message_setDescription_name SET description = "Nom du tool Set Description";
CREATE i18n_key:tool_telegram_message_setDescription_desc SET description = "Description du tool Set Description";
CREATE i18n_key:tool_telegram_message_setDescription_tooltip SET description = "Tooltip du tool Set Description";
CREATE i18n_key:tool_telegram_message_setDescription_success SET description = "Message de succes du tool Set Description";
CREATE i18n_key:tool_telegram_message_setDescription_error SET description = "Message d'erreur du tool Set Description";

CREATE i18n_key:tool_telegram_message_setTitle_name SET description = "Nom du tool Set Title";
CREATE i18n_key:tool_telegram_message_setTitle_desc SET description = "Description du tool Set Title";
CREATE i18n_key:tool_telegram_message_setTitle_tooltip SET description = "Tooltip du tool Set Title";
CREATE i18n_key:tool_telegram_message_setTitle_success SET description = "Message de succes du tool Set Title";
CREATE i18n_key:tool_telegram_message_setTitle_error SET description = "Message d'erreur du tool Set Title";

CREATE i18n_key:tool_thehive_alert_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_thehive_alert_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_thehive_alert_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_thehive_alert_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_thehive_alert_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_thehive_alert_getMany_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_thehive_alert_getMany_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_thehive_alert_getMany_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_thehive_alert_getMany_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_thehive_alert_getMany_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_thehive_case_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_thehive_case_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_thehive_case_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_thehive_case_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_thehive_case_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_thehive_case_getMany_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_thehive_case_getMany_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_thehive_case_getMany_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_thehive_case_getMany_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_thehive_case_getMany_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_thehive_log_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_thehive_log_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_thehive_log_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_thehive_log_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_thehive_log_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_thehive_log_getMany_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_thehive_log_getMany_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_thehive_log_getMany_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_thehive_log_getMany_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_thehive_log_getMany_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_thehive_observable_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_thehive_observable_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_thehive_observable_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_thehive_observable_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_thehive_observable_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_thehive_observable_getMany_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_thehive_observable_getMany_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_thehive_observable_getMany_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_thehive_observable_getMany_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_thehive_observable_getMany_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_thehive_task_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_thehive_task_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_thehive_task_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_thehive_task_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_thehive_task_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_thehive_task_getMany_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_thehive_task_getMany_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_thehive_task_getMany_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_thehive_task_getMany_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_thehive_task_getMany_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_thehiveproject_thehiveproject_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_thehiveproject_thehiveproject_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_thehiveproject_thehiveproject_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_thehiveproject_thehiveproject_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_thehiveproject_thehiveproject_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_thehiveproject_thehiveproject_getMany_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_thehiveproject_thehiveproject_getMany_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_thehiveproject_thehiveproject_getMany_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_thehiveproject_thehiveproject_getMany_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_thehiveproject_thehiveproject_getMany_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_timescaledb_timescaledb_executeQuery_name SET description = "Nom du tool Execute Query";
CREATE i18n_key:tool_timescaledb_timescaledb_executeQuery_desc SET description = "Description du tool Execute Query";
CREATE i18n_key:tool_timescaledb_timescaledb_executeQuery_tooltip SET description = "Tooltip du tool Execute Query";
CREATE i18n_key:tool_timescaledb_timescaledb_executeQuery_success SET description = "Message de succes du tool Execute Query";
CREATE i18n_key:tool_timescaledb_timescaledb_executeQuery_error SET description = "Message d'erreur du tool Execute Query";

CREATE i18n_key:tool_timescaledb_timescaledb_insert_name SET description = "Nom du tool Insert";
CREATE i18n_key:tool_timescaledb_timescaledb_insert_desc SET description = "Description du tool Insert";
CREATE i18n_key:tool_timescaledb_timescaledb_insert_tooltip SET description = "Tooltip du tool Insert";
CREATE i18n_key:tool_timescaledb_timescaledb_insert_success SET description = "Message de succes du tool Insert";
CREATE i18n_key:tool_timescaledb_timescaledb_insert_error SET description = "Message d'erreur du tool Insert";

CREATE i18n_key:tool_timescaledb_timescaledb_update_name SET description = "Nom du tool Update";
CREATE i18n_key:tool_timescaledb_timescaledb_update_desc SET description = "Description du tool Update";
CREATE i18n_key:tool_timescaledb_timescaledb_update_tooltip SET description = "Tooltip du tool Update";
CREATE i18n_key:tool_timescaledb_timescaledb_update_success SET description = "Message de succes du tool Update";
CREATE i18n_key:tool_timescaledb_timescaledb_update_error SET description = "Message d'erreur du tool Update";

CREATE i18n_key:tool_todoist_todoist_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_todoist_todoist_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_todoist_todoist_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_todoist_todoist_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_todoist_todoist_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_todoist_todoist_getMany_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_todoist_todoist_getMany_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_todoist_todoist_getMany_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_todoist_todoist_getMany_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_todoist_todoist_getMany_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_todoistv1_task_close_name SET description = "Nom du tool Close";
CREATE i18n_key:tool_todoistv1_task_close_desc SET description = "Description du tool Close";
CREATE i18n_key:tool_todoistv1_task_close_tooltip SET description = "Tooltip du tool Close";
CREATE i18n_key:tool_todoistv1_task_close_success SET description = "Message de succes du tool Close";
CREATE i18n_key:tool_todoistv1_task_close_error SET description = "Message d'erreur du tool Close";

CREATE i18n_key:tool_todoistv1_task_create_name SET description = "Nom du tool Create";
CREATE i18n_key:tool_todoistv1_task_create_desc SET description = "Description du tool Create";
CREATE i18n_key:tool_todoistv1_task_create_tooltip SET description = "Tooltip du tool Create";
CREATE i18n_key:tool_todoistv1_task_create_success SET description = "Message de succes du tool Create";
CREATE i18n_key:tool_todoistv1_task_create_error SET description = "Message d'erreur du tool Create";

CREATE i18n_key:tool_todoistv1_task_delete_name SET description = "Nom du tool Delete";
CREATE i18n_key:tool_todoistv1_task_delete_desc SET description = "Description du tool Delete";
CREATE i18n_key:tool_todoistv1_task_delete_tooltip SET description = "Tooltip du tool Delete";
CREATE i18n_key:tool_todoistv1_task_delete_success SET description = "Message de succes du tool Delete";
CREATE i18n_key:tool_todoistv1_task_delete_error SET description = "Message d'erreur du tool Delete";

CREATE i18n_key:tool_todoistv1_task_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_todoistv1_task_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_todoistv1_task_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_todoistv1_task_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_todoistv1_task_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_todoistv1_task_getAll_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_todoistv1_task_getAll_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_todoistv1_task_getAll_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_todoistv1_task_getAll_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_todoistv1_task_getAll_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_todoistv1_task_move_name SET description = "Nom du tool Move";
CREATE i18n_key:tool_todoistv1_task_move_desc SET description = "Description du tool Move";
CREATE i18n_key:tool_todoistv1_task_move_tooltip SET description = "Tooltip du tool Move";
CREATE i18n_key:tool_todoistv1_task_move_success SET description = "Message de succes du tool Move";
CREATE i18n_key:tool_todoistv1_task_move_error SET description = "Message d'erreur du tool Move";

CREATE i18n_key:tool_todoistv1_task_reopen_name SET description = "Nom du tool Reopen";
CREATE i18n_key:tool_todoistv1_task_reopen_desc SET description = "Description du tool Reopen";
CREATE i18n_key:tool_todoistv1_task_reopen_tooltip SET description = "Tooltip du tool Reopen";
CREATE i18n_key:tool_todoistv1_task_reopen_success SET description = "Message de succes du tool Reopen";
CREATE i18n_key:tool_todoistv1_task_reopen_error SET description = "Message d'erreur du tool Reopen";

CREATE i18n_key:tool_todoistv1_task_update_name SET description = "Nom du tool Update";
CREATE i18n_key:tool_todoistv1_task_update_desc SET description = "Description du tool Update";
CREATE i18n_key:tool_todoistv1_task_update_tooltip SET description = "Tooltip du tool Update";
CREATE i18n_key:tool_todoistv1_task_update_success SET description = "Message de succes du tool Update";
CREATE i18n_key:tool_todoistv1_task_update_error SET description = "Message d'erreur du tool Update";

CREATE i18n_key:tool_todoistv2_task_close_name SET description = "Nom du tool Close";
CREATE i18n_key:tool_todoistv2_task_close_desc SET description = "Description du tool Close";
CREATE i18n_key:tool_todoistv2_task_close_tooltip SET description = "Tooltip du tool Close";
CREATE i18n_key:tool_todoistv2_task_close_success SET description = "Message de succes du tool Close";
CREATE i18n_key:tool_todoistv2_task_close_error SET description = "Message d'erreur du tool Close";

CREATE i18n_key:tool_todoistv2_task_create_name SET description = "Nom du tool Create";
CREATE i18n_key:tool_todoistv2_task_create_desc SET description = "Description du tool Create";
CREATE i18n_key:tool_todoistv2_task_create_tooltip SET description = "Tooltip du tool Create";
CREATE i18n_key:tool_todoistv2_task_create_success SET description = "Message de succes du tool Create";
CREATE i18n_key:tool_todoistv2_task_create_error SET description = "Message d'erreur du tool Create";

CREATE i18n_key:tool_todoistv2_task_delete_name SET description = "Nom du tool Delete";
CREATE i18n_key:tool_todoistv2_task_delete_desc SET description = "Description du tool Delete";
CREATE i18n_key:tool_todoistv2_task_delete_tooltip SET description = "Tooltip du tool Delete";
CREATE i18n_key:tool_todoistv2_task_delete_success SET description = "Message de succes du tool Delete";
CREATE i18n_key:tool_todoistv2_task_delete_error SET description = "Message d'erreur du tool Delete";

CREATE i18n_key:tool_todoistv2_task_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_todoistv2_task_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_todoistv2_task_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_todoistv2_task_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_todoistv2_task_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_todoistv2_task_getAll_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_todoistv2_task_getAll_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_todoistv2_task_getAll_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_todoistv2_task_getAll_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_todoistv2_task_getAll_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_todoistv2_task_move_name SET description = "Nom du tool Move";
CREATE i18n_key:tool_todoistv2_task_move_desc SET description = "Description du tool Move";
CREATE i18n_key:tool_todoistv2_task_move_tooltip SET description = "Tooltip du tool Move";
CREATE i18n_key:tool_todoistv2_task_move_success SET description = "Message de succes du tool Move";
CREATE i18n_key:tool_todoistv2_task_move_error SET description = "Message d'erreur du tool Move";

CREATE i18n_key:tool_todoistv2_task_quickAdd_name SET description = "Nom du tool Quick Add";
CREATE i18n_key:tool_todoistv2_task_quickAdd_desc SET description = "Description du tool Quick Add";
CREATE i18n_key:tool_todoistv2_task_quickAdd_tooltip SET description = "Tooltip du tool Quick Add";
CREATE i18n_key:tool_todoistv2_task_quickAdd_success SET description = "Message de succes du tool Quick Add";
CREATE i18n_key:tool_todoistv2_task_quickAdd_error SET description = "Message d'erreur du tool Quick Add";

CREATE i18n_key:tool_todoistv2_task_reopen_name SET description = "Nom du tool Reopen";
CREATE i18n_key:tool_todoistv2_task_reopen_desc SET description = "Description du tool Reopen";
CREATE i18n_key:tool_todoistv2_task_reopen_tooltip SET description = "Tooltip du tool Reopen";
CREATE i18n_key:tool_todoistv2_task_reopen_success SET description = "Message de succes du tool Reopen";
CREATE i18n_key:tool_todoistv2_task_reopen_error SET description = "Message d'erreur du tool Reopen";

CREATE i18n_key:tool_todoistv2_task_update_name SET description = "Nom du tool Update";
CREATE i18n_key:tool_todoistv2_task_update_desc SET description = "Description du tool Update";
CREATE i18n_key:tool_todoistv2_task_update_tooltip SET description = "Tooltip du tool Update";
CREATE i18n_key:tool_todoistv2_task_update_success SET description = "Message de succes du tool Update";
CREATE i18n_key:tool_todoistv2_task_update_error SET description = "Message d'erreur du tool Update";

CREATE i18n_key:tool_todoistv2_project_close_name SET description = "Nom du tool Close";
CREATE i18n_key:tool_todoistv2_project_close_desc SET description = "Description du tool Close";
CREATE i18n_key:tool_todoistv2_project_close_tooltip SET description = "Tooltip du tool Close";
CREATE i18n_key:tool_todoistv2_project_close_success SET description = "Message de succes du tool Close";
CREATE i18n_key:tool_todoistv2_project_close_error SET description = "Message d'erreur du tool Close";

CREATE i18n_key:tool_todoistv2_project_create_name SET description = "Nom du tool Create";
CREATE i18n_key:tool_todoistv2_project_create_desc SET description = "Description du tool Create";
CREATE i18n_key:tool_todoistv2_project_create_tooltip SET description = "Tooltip du tool Create";
CREATE i18n_key:tool_todoistv2_project_create_success SET description = "Message de succes du tool Create";
CREATE i18n_key:tool_todoistv2_project_create_error SET description = "Message d'erreur du tool Create";

CREATE i18n_key:tool_todoistv2_project_delete_name SET description = "Nom du tool Delete";
CREATE i18n_key:tool_todoistv2_project_delete_desc SET description = "Description du tool Delete";
CREATE i18n_key:tool_todoistv2_project_delete_tooltip SET description = "Tooltip du tool Delete";
CREATE i18n_key:tool_todoistv2_project_delete_success SET description = "Message de succes du tool Delete";
CREATE i18n_key:tool_todoistv2_project_delete_error SET description = "Message d'erreur du tool Delete";

CREATE i18n_key:tool_todoistv2_project_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_todoistv2_project_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_todoistv2_project_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_todoistv2_project_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_todoistv2_project_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_todoistv2_project_getAll_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_todoistv2_project_getAll_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_todoistv2_project_getAll_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_todoistv2_project_getAll_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_todoistv2_project_getAll_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_todoistv2_project_move_name SET description = "Nom du tool Move";
CREATE i18n_key:tool_todoistv2_project_move_desc SET description = "Description du tool Move";
CREATE i18n_key:tool_todoistv2_project_move_tooltip SET description = "Tooltip du tool Move";
CREATE i18n_key:tool_todoistv2_project_move_success SET description = "Message de succes du tool Move";
CREATE i18n_key:tool_todoistv2_project_move_error SET description = "Message d'erreur du tool Move";

CREATE i18n_key:tool_todoistv2_project_quickAdd_name SET description = "Nom du tool Quick Add";
CREATE i18n_key:tool_todoistv2_project_quickAdd_desc SET description = "Description du tool Quick Add";
CREATE i18n_key:tool_todoistv2_project_quickAdd_tooltip SET description = "Tooltip du tool Quick Add";
CREATE i18n_key:tool_todoistv2_project_quickAdd_success SET description = "Message de succes du tool Quick Add";
CREATE i18n_key:tool_todoistv2_project_quickAdd_error SET description = "Message d'erreur du tool Quick Add";

CREATE i18n_key:tool_todoistv2_project_reopen_name SET description = "Nom du tool Reopen";
CREATE i18n_key:tool_todoistv2_project_reopen_desc SET description = "Description du tool Reopen";
CREATE i18n_key:tool_todoistv2_project_reopen_tooltip SET description = "Tooltip du tool Reopen";
CREATE i18n_key:tool_todoistv2_project_reopen_success SET description = "Message de succes du tool Reopen";
CREATE i18n_key:tool_todoistv2_project_reopen_error SET description = "Message d'erreur du tool Reopen";

CREATE i18n_key:tool_todoistv2_project_update_name SET description = "Nom du tool Update";
CREATE i18n_key:tool_todoistv2_project_update_desc SET description = "Description du tool Update";
CREATE i18n_key:tool_todoistv2_project_update_tooltip SET description = "Tooltip du tool Update";
CREATE i18n_key:tool_todoistv2_project_update_success SET description = "Message de succes du tool Update";
CREATE i18n_key:tool_todoistv2_project_update_error SET description = "Message d'erreur du tool Update";

CREATE i18n_key:tool_todoistv2_section_close_name SET description = "Nom du tool Close";
CREATE i18n_key:tool_todoistv2_section_close_desc SET description = "Description du tool Close";
CREATE i18n_key:tool_todoistv2_section_close_tooltip SET description = "Tooltip du tool Close";
CREATE i18n_key:tool_todoistv2_section_close_success SET description = "Message de succes du tool Close";
CREATE i18n_key:tool_todoistv2_section_close_error SET description = "Message d'erreur du tool Close";

CREATE i18n_key:tool_todoistv2_section_create_name SET description = "Nom du tool Create";
CREATE i18n_key:tool_todoistv2_section_create_desc SET description = "Description du tool Create";
CREATE i18n_key:tool_todoistv2_section_create_tooltip SET description = "Tooltip du tool Create";
CREATE i18n_key:tool_todoistv2_section_create_success SET description = "Message de succes du tool Create";
CREATE i18n_key:tool_todoistv2_section_create_error SET description = "Message d'erreur du tool Create";

CREATE i18n_key:tool_todoistv2_section_delete_name SET description = "Nom du tool Delete";
CREATE i18n_key:tool_todoistv2_section_delete_desc SET description = "Description du tool Delete";
CREATE i18n_key:tool_todoistv2_section_delete_tooltip SET description = "Tooltip du tool Delete";
CREATE i18n_key:tool_todoistv2_section_delete_success SET description = "Message de succes du tool Delete";
CREATE i18n_key:tool_todoistv2_section_delete_error SET description = "Message d'erreur du tool Delete";

CREATE i18n_key:tool_todoistv2_section_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_todoistv2_section_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_todoistv2_section_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_todoistv2_section_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_todoistv2_section_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_todoistv2_section_getAll_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_todoistv2_section_getAll_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_todoistv2_section_getAll_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_todoistv2_section_getAll_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_todoistv2_section_getAll_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_todoistv2_section_move_name SET description = "Nom du tool Move";
CREATE i18n_key:tool_todoistv2_section_move_desc SET description = "Description du tool Move";
CREATE i18n_key:tool_todoistv2_section_move_tooltip SET description = "Tooltip du tool Move";
CREATE i18n_key:tool_todoistv2_section_move_success SET description = "Message de succes du tool Move";
CREATE i18n_key:tool_todoistv2_section_move_error SET description = "Message d'erreur du tool Move";

CREATE i18n_key:tool_todoistv2_section_quickAdd_name SET description = "Nom du tool Quick Add";
CREATE i18n_key:tool_todoistv2_section_quickAdd_desc SET description = "Description du tool Quick Add";
CREATE i18n_key:tool_todoistv2_section_quickAdd_tooltip SET description = "Tooltip du tool Quick Add";
CREATE i18n_key:tool_todoistv2_section_quickAdd_success SET description = "Message de succes du tool Quick Add";
CREATE i18n_key:tool_todoistv2_section_quickAdd_error SET description = "Message d'erreur du tool Quick Add";

CREATE i18n_key:tool_todoistv2_section_reopen_name SET description = "Nom du tool Reopen";
CREATE i18n_key:tool_todoistv2_section_reopen_desc SET description = "Description du tool Reopen";
CREATE i18n_key:tool_todoistv2_section_reopen_tooltip SET description = "Tooltip du tool Reopen";
CREATE i18n_key:tool_todoistv2_section_reopen_success SET description = "Message de succes du tool Reopen";
CREATE i18n_key:tool_todoistv2_section_reopen_error SET description = "Message d'erreur du tool Reopen";

CREATE i18n_key:tool_todoistv2_section_update_name SET description = "Nom du tool Update";
CREATE i18n_key:tool_todoistv2_section_update_desc SET description = "Description du tool Update";
CREATE i18n_key:tool_todoistv2_section_update_tooltip SET description = "Tooltip du tool Update";
CREATE i18n_key:tool_todoistv2_section_update_success SET description = "Message de succes du tool Update";
CREATE i18n_key:tool_todoistv2_section_update_error SET description = "Message d'erreur du tool Update";

CREATE i18n_key:tool_todoistv2_comment_close_name SET description = "Nom du tool Close";
CREATE i18n_key:tool_todoistv2_comment_close_desc SET description = "Description du tool Close";
CREATE i18n_key:tool_todoistv2_comment_close_tooltip SET description = "Tooltip du tool Close";
CREATE i18n_key:tool_todoistv2_comment_close_success SET description = "Message de succes du tool Close";
CREATE i18n_key:tool_todoistv2_comment_close_error SET description = "Message d'erreur du tool Close";

CREATE i18n_key:tool_todoistv2_comment_create_name SET description = "Nom du tool Create";
CREATE i18n_key:tool_todoistv2_comment_create_desc SET description = "Description du tool Create";
CREATE i18n_key:tool_todoistv2_comment_create_tooltip SET description = "Tooltip du tool Create";
CREATE i18n_key:tool_todoistv2_comment_create_success SET description = "Message de succes du tool Create";
CREATE i18n_key:tool_todoistv2_comment_create_error SET description = "Message d'erreur du tool Create";

CREATE i18n_key:tool_todoistv2_comment_delete_name SET description = "Nom du tool Delete";
CREATE i18n_key:tool_todoistv2_comment_delete_desc SET description = "Description du tool Delete";
CREATE i18n_key:tool_todoistv2_comment_delete_tooltip SET description = "Tooltip du tool Delete";
CREATE i18n_key:tool_todoistv2_comment_delete_success SET description = "Message de succes du tool Delete";
CREATE i18n_key:tool_todoistv2_comment_delete_error SET description = "Message d'erreur du tool Delete";

CREATE i18n_key:tool_todoistv2_comment_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_todoistv2_comment_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_todoistv2_comment_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_todoistv2_comment_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_todoistv2_comment_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_todoistv2_comment_getAll_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_todoistv2_comment_getAll_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_todoistv2_comment_getAll_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_todoistv2_comment_getAll_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_todoistv2_comment_getAll_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_todoistv2_comment_move_name SET description = "Nom du tool Move";
CREATE i18n_key:tool_todoistv2_comment_move_desc SET description = "Description du tool Move";
CREATE i18n_key:tool_todoistv2_comment_move_tooltip SET description = "Tooltip du tool Move";
CREATE i18n_key:tool_todoistv2_comment_move_success SET description = "Message de succes du tool Move";
CREATE i18n_key:tool_todoistv2_comment_move_error SET description = "Message d'erreur du tool Move";

CREATE i18n_key:tool_todoistv2_comment_quickAdd_name SET description = "Nom du tool Quick Add";
CREATE i18n_key:tool_todoistv2_comment_quickAdd_desc SET description = "Description du tool Quick Add";
CREATE i18n_key:tool_todoistv2_comment_quickAdd_tooltip SET description = "Tooltip du tool Quick Add";
CREATE i18n_key:tool_todoistv2_comment_quickAdd_success SET description = "Message de succes du tool Quick Add";
CREATE i18n_key:tool_todoistv2_comment_quickAdd_error SET description = "Message d'erreur du tool Quick Add";

CREATE i18n_key:tool_todoistv2_comment_reopen_name SET description = "Nom du tool Reopen";
CREATE i18n_key:tool_todoistv2_comment_reopen_desc SET description = "Description du tool Reopen";
CREATE i18n_key:tool_todoistv2_comment_reopen_tooltip SET description = "Tooltip du tool Reopen";
CREATE i18n_key:tool_todoistv2_comment_reopen_success SET description = "Message de succes du tool Reopen";
CREATE i18n_key:tool_todoistv2_comment_reopen_error SET description = "Message d'erreur du tool Reopen";

CREATE i18n_key:tool_todoistv2_comment_update_name SET description = "Nom du tool Update";
CREATE i18n_key:tool_todoistv2_comment_update_desc SET description = "Description du tool Update";
CREATE i18n_key:tool_todoistv2_comment_update_tooltip SET description = "Tooltip du tool Update";
CREATE i18n_key:tool_todoistv2_comment_update_success SET description = "Message de succes du tool Update";
CREATE i18n_key:tool_todoistv2_comment_update_error SET description = "Message d'erreur du tool Update";

CREATE i18n_key:tool_todoistv2_label_close_name SET description = "Nom du tool Close";
CREATE i18n_key:tool_todoistv2_label_close_desc SET description = "Description du tool Close";
CREATE i18n_key:tool_todoistv2_label_close_tooltip SET description = "Tooltip du tool Close";
CREATE i18n_key:tool_todoistv2_label_close_success SET description = "Message de succes du tool Close";
CREATE i18n_key:tool_todoistv2_label_close_error SET description = "Message d'erreur du tool Close";

CREATE i18n_key:tool_todoistv2_label_create_name SET description = "Nom du tool Create";
CREATE i18n_key:tool_todoistv2_label_create_desc SET description = "Description du tool Create";
CREATE i18n_key:tool_todoistv2_label_create_tooltip SET description = "Tooltip du tool Create";
CREATE i18n_key:tool_todoistv2_label_create_success SET description = "Message de succes du tool Create";
CREATE i18n_key:tool_todoistv2_label_create_error SET description = "Message d'erreur du tool Create";

CREATE i18n_key:tool_todoistv2_label_delete_name SET description = "Nom du tool Delete";
CREATE i18n_key:tool_todoistv2_label_delete_desc SET description = "Description du tool Delete";
CREATE i18n_key:tool_todoistv2_label_delete_tooltip SET description = "Tooltip du tool Delete";
CREATE i18n_key:tool_todoistv2_label_delete_success SET description = "Message de succes du tool Delete";
CREATE i18n_key:tool_todoistv2_label_delete_error SET description = "Message d'erreur du tool Delete";

CREATE i18n_key:tool_todoistv2_label_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_todoistv2_label_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_todoistv2_label_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_todoistv2_label_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_todoistv2_label_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_todoistv2_label_getAll_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_todoistv2_label_getAll_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_todoistv2_label_getAll_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_todoistv2_label_getAll_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_todoistv2_label_getAll_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_todoistv2_label_move_name SET description = "Nom du tool Move";
CREATE i18n_key:tool_todoistv2_label_move_desc SET description = "Description du tool Move";
CREATE i18n_key:tool_todoistv2_label_move_tooltip SET description = "Tooltip du tool Move";
CREATE i18n_key:tool_todoistv2_label_move_success SET description = "Message de succes du tool Move";
CREATE i18n_key:tool_todoistv2_label_move_error SET description = "Message d'erreur du tool Move";

CREATE i18n_key:tool_todoistv2_label_quickAdd_name SET description = "Nom du tool Quick Add";
CREATE i18n_key:tool_todoistv2_label_quickAdd_desc SET description = "Description du tool Quick Add";
CREATE i18n_key:tool_todoistv2_label_quickAdd_tooltip SET description = "Tooltip du tool Quick Add";
CREATE i18n_key:tool_todoistv2_label_quickAdd_success SET description = "Message de succes du tool Quick Add";
CREATE i18n_key:tool_todoistv2_label_quickAdd_error SET description = "Message d'erreur du tool Quick Add";

CREATE i18n_key:tool_todoistv2_label_reopen_name SET description = "Nom du tool Reopen";
CREATE i18n_key:tool_todoistv2_label_reopen_desc SET description = "Description du tool Reopen";
CREATE i18n_key:tool_todoistv2_label_reopen_tooltip SET description = "Tooltip du tool Reopen";
CREATE i18n_key:tool_todoistv2_label_reopen_success SET description = "Message de succes du tool Reopen";
CREATE i18n_key:tool_todoistv2_label_reopen_error SET description = "Message d'erreur du tool Reopen";

CREATE i18n_key:tool_todoistv2_label_update_name SET description = "Nom du tool Update";
CREATE i18n_key:tool_todoistv2_label_update_desc SET description = "Description du tool Update";
CREATE i18n_key:tool_todoistv2_label_update_tooltip SET description = "Tooltip du tool Update";
CREATE i18n_key:tool_todoistv2_label_update_success SET description = "Message de succes du tool Update";
CREATE i18n_key:tool_todoistv2_label_update_error SET description = "Message d'erreur du tool Update";

