[package]
name = "lyx-platform-frontend"
version = "0.8.0"
edition = "2024"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "lyx-platform-frontend"
path = "src/lib.rs"

[dependencies]
cfg-if = { version = "*" }
console_error_panic_hook = { version = "*" }
console_log = { version = "*" }
leptos = { path = "../core/lyx-core-leptos/leptos" }
log = { version = "*" }
server_fn = { path = "../../../core/leptos/server_fn" }
wasm-bindgen = { version = "*" }
lyx-platform-app = { path = "../app" }

[features]
csr = ["leptos/csr", "lyx-platform-app/csr"]
hydrate = ["leptos/hydrate", "lyx-platform-app/hydrate"]










