[package]
name = "leptos_dom"
version = "0.8.0"
edition = "2024"

[dependencies]
server_fn = { path = "../server_fn", version = "0.8.0", optional = true }
tachys = { path = "../tachys", version = "*" }
reactive_graph = { path = "../reactive_graph", version = "*" }
or_poisoned = { path = "../or_poisoned", version = "*" }
wasm-bindgen = { version = "*" }
web-sys = { version = "*", features = ["Location", "Element", "Node"] }

[features]
islands = ["tachys/islands"]
nonce = []
nightly = []
csr = ["tachys/csr"]
ssr = ["tachys/ssr", "dep:server_fn"]
hydrate = ["tachys/hydrate"]


[build-dependencies]
rustc_version = "*"





