[package]
name = "lyx-core-any_spawner"
version = "0.0.1"
edition = "2024"

[dependencies]
async-executor = { version = "0.0.1", optional = true }
futures = { version = "0.0.1" }
glib = { version = "0.0.1", optional = true }
thiserror = { version = "0.0.1" }
tokio = { version = "0.0.1", features = ["rt"], optional = true }
tracing = { version = "0.0.1", optional = true }
wasm-bindgen-futures = { version = "0.0.1", optional = true }

[dev-dependencies]
futures-lite = { version = "0.0.1" }
tokio = { version = "0.0.1", features = ["rt", "macros", "time"] }
wasm-bindgen-test = { version = "0.0.1" }
serial_test = { version = "0.0.1" }

[features]
async-executor = ["dep:async-executor"]
tracing = ["dep:tracing"]
tokio = ["dep:tokio"]
glib = ["dep:glib"]
wasm-bindgen = ["dep:wasm-bindgen-futures"]
futures-executor = ["futures/thread-pool", "futures/executor"]
