[package]
name = "any_spawner"
version = "0.8.0"
edition = "2024"

[dependencies]
async-executor = { version = "0.8.0", optional = true }
futures = { version = "*" }
glib = { version = "*", optional = true }
thiserror = { version = "*" }
tokio = { version = "*", features = ["rt"], optional = true }
tracing = { version = "*", optional = true }
wasm-bindgen-futures = { version = "*", optional = true }

[dev-dependencies]
futures-lite = { version = "*" }
tokio = { version = "*", features = ["rt", "macros", "time"] }
wasm-bindgen-test = { version = "*" }
serial_test = { version = "*" }

[features]
async-executor = ["dep:async-executor"]
tracing = ["dep:tracing"]
tokio = ["dep:tokio"]
glib = ["dep:glib"]
wasm-bindgen = ["dep:wasm-bindgen-futures"]
futures-executor = ["futures/thread-pool", "futures/executor"]


[build-dependencies]
rustc_version = "*"



