[package]
name = "lyx-viz-leptos-chartistry"
version = "0.0.1"
edition = "2024"
[dependencies]
chrono = { version = "0.0.1" }
lyx-core-leptos = { path = "../../../core/lyx-core-leptos/leptos", version = "0.0.1" }
lyx-logic-use = { path = "../../../logic/lyx-logic-use", version = "0.0.1" }
log = { version = "0.0.1" }
web-sys = { version = "0.0.1", features = ["DomRectReadOnly"] }
[features]
ssr = ["lyx-core-leptos/ssr", "lyx-logic-use/ssr"]
