[package]
name = "utils"
version = "0.8.0"
edition = "2024"
[dependencies]
futures = { version = "*", default-features = true }
hydration_context = { path = "../hydration_context", version = "*" }
leptos = { path = "../leptos", version = "*", features = ["nonce"] }
leptos_meta = { path = "../../meta", version = "*", features = ["ssr"] }
leptos_router = { path = "../../router", version = "*", features = ["ssr"] }
leptos_config = { path = "../leptos_config", version = "*" }
reactive_graph = { path = "../reactive_graph", version = "*", features = ["sandboxed-arenas"] }


[build-dependencies]
rustc_version = "*"




