[workspace]
resolver = "2"
members = [
    "crates/ui-foundations/lyx-found-tailwind/fuse",
    "crates/ui-foundations/lyx-found-tailwind/variant-macro",
    "crates/ui-foundations/lyx-found-theme",
    "crates/ui-kits/lyx-ui-leptonic/leptonic",
    "crates/ui-kits/lyx-ui-leptonic/leptonic-theme",
    "crates/logic/lyx-logic-use"
]

[patch.crates-io]
  any_spawner = { path = "./crates/core/lyx-core-leptos/any_spawner/" }
  leptos_router = { path = "./crates/core/lyx-core-leptos/router/" }
  leptos-use = { path = "./crates/logic/lyx-logic-use/" }
  server_fn_macro = { path = "./crates/core/lyx-core-leptos/server_fn_macro/" }
  any_error = { path = "./crates/core/lyx-core-leptos/any_error/" }
  leptos = { path = "./crates/core/lyx-core-leptos/leptos/" }
  reactive_stores_macro = { path = "./crates/core/lyx-core-leptos/reactive_stores_macro/" }
  leptos_axum = { path = "./crates/core/lyx-core-leptos/integrations/axum/" }
  hydration_context = { path = "./crates/core/lyx-core-leptos/hydration_context/" }
  oco = { path = "./crates/core/lyx-core-leptos/oco/" }
  leptos_meta = { path = "./crates/core/lyx-core-leptos/meta/" }
  leptos_dom = { path = "./crates/core/lyx-core-leptos/leptos_dom/" }
  leptos_macro = { path = "./crates/core/lyx-core-leptos/leptos_macro/" }
  leptos_actix = { path = "./crates/core/lyx-core-leptos/integrations/actix/" }
  server_fn = { path = "./crates/core/lyx-core-leptos/server_fn/" }
  leptos_config = { path = "./crates/core/lyx-core-leptos/leptos_config/" }
  or_poisoned = { path = "./crates/core/lyx-core-leptos/or_poisoned/" }
  reactive_stores = { path = "./crates/core/lyx-core-leptos/reactive_stores/" }
  tachys = { path = "./crates/core/lyx-core-leptos/tachys/" }
  reactive_graph = { path = "./crates/core/lyx-core-leptos/reactive_graph/" }
  tailwind_fuse = { path = "./crates/ui-foundations/lyx-found-tailwind/fuse" }
  tailwind_fuse_macro = { path = "./crates/ui-foundations/lyx-found-tailwind/variant-macro" }
  leptos_theme = { path = "./crates/ui-foundations/lyx-found-theme" }
  leptonic-theme = { path = "./crates/ui-kits/lyx-ui-leptonic/leptonic-theme" }
  leptonic = { path = "./crates/ui-kits/lyx-ui-leptonic/leptonic" }

