[package]
name = "lib"
version = "0.8.0"
edition = "2024"

[features]
nightly = ["reactive_graph/nightly"]

[dependencies]
futures = { version = "*" }
reactive_graph = { path = "../../leptos/reactive_graph" }
macros = { path = "../macros" }
smallvec = { version = "*" }
tracing = { version = "*" }
wasm-bindgen-futures = { version = "*" }

[dev-dependencies]
# leptos = { ${2}, features = ["nightly"] }
leptos = { path = "../../leptos/leptos" }











