[package]
name = "lyxal_network"
edition.workspace = true
rust-version = { workspace = true }
description = "Peer-to-peer networking library"
version = "0.56.1"

[features]
full = [
    "autonat",
    "cbor",
    "dcutr",
    "dns",
    "ecdsa",
    "ed25519",
    "floodsub",
    "gossipsub",
    "identify",
    "json",
    "kad",
    "macros",
    "mdns",
    "memory-connection-limits",
    "metrics",
    "noise",
    "ping",
    "plaintext",
    "pnet",
    "quic",
    "relay",
    "rendezvous",
    "request-response",
    "rsa",
    "secp256k1",
    "serde",
    "tcp",
    "tls",
    "tokio",
    "uds",
    "wasm-bindgen",
    "webrtc-websys",
    "websocket-websys",
    "websocket",
    "webtransport-websys",
    "yamux",
    "upnp",
]

autonat = ["dep:lyxal_network-autonat"]
cbor = ["lyxal_network-request-response?/cbor"]
dcutr = ["dep:lyxal_network-dcutr", "lyxal_network-metrics?/dcutr"]
dns = ["dep:lyxal_network-dns"]
ecdsa = ["lyxal_network-identity/ecdsa"]
ed25519 = ["lyxal_network-identity/ed25519"]
floodsub = ["dep:lyxal_network-floodsub"]
gossipsub = ["dep:lyxal_network-gossipsub", "lyxal_network-metrics?/gossipsub"]
identify = ["dep:lyxal_network-identify", "lyxal_network-metrics?/identify"]
json = ["lyxal_network-request-response?/json"]
kad = ["dep:lyxal_network-kad", "lyxal_network-metrics?/kad"]
macros = ["lyxal_network-swarm/macros"]
mdns = ["dep:lyxal_network-mdns"]
memory-connection-limits = ["dep:lyxal_network-memory-connection-limits"]
metrics = ["dep:lyxal_network-metrics", "lyxal_network-gossipsub?/metrics"]
noise = ["dep:lyxal_network-noise"]
ping = ["dep:lyxal_network-ping", "lyxal_network-metrics?/ping"]
plaintext = ["dep:lyxal_network-plaintext"]
pnet = ["dep:lyxal_network-pnet"]
quic = ["dep:lyxal_network-quic"]
relay = ["dep:lyxal_network-relay", "lyxal_network-metrics?/relay"]
rendezvous = ["dep:lyxal_network-rendezvous"]
request-response = ["dep:lyxal_network-request-response"]
rsa = ["lyxal_network-identity/rsa"]
secp256k1 = ["lyxal_network-identity/secp256k1"]
serde = ["lyxal_network-core/serde", "lyxal_network-kad?/serde", "lyxal_network-gossipsub?/serde"]
tcp = ["dep:lyxal_network-tcp"]
tls = ["dep:lyxal_network-tls"]
tokio = ["lyxal_network-swarm/tokio", "lyxal_network-mdns?/tokio", "lyxal_network-tcp?/tokio", "lyxal_network-dns?/tokio", "lyxal_network-quic?/tokio", "lyxal_network-upnp?/tokio"]
uds = ["dep:lyxal_network-uds"]
wasm-bindgen = ["futures-timer/wasm-bindgen", "getrandom/js", "lyxal_network-swarm/wasm-bindgen", "lyxal_network-gossipsub?/wasm-bindgen"]
webrtc-websys = ['dep:lyxal_network-webrtc-websys']
websocket-websys = ["dep:lyxal_network-websocket-websys"]
websocket = ["dep:lyxal_network-websocket"]
webtransport-websys = ["dep:lyxal_network-webtransport-websys"]
yamux = ["dep:lyxal_network-yamux"]
upnp = ["dep:lyxal_network-upnp"]

[dependencies]
bytes = "1"
either = "1.9.0"
futures = { workspace = true }
futures-timer = "3.0.2" # Explicit dependency to be used in `wasm-bindgen` feature
getrandom = { workspace = true } # Explicit dependency to be used in `wasm-bindgen` feature
# TODO feature flag?
rw-stream-sink = { workspace = true }
lyxal_network-allow-block-list = { workspace = true }
lyxal_network-autonat = { workspace = true, optional = true }
lyxal_network-connection-limits = { workspace = true }
lyxal_network-core = { workspace = true }
lyxal_network-dcutr = { workspace = true, optional = true }
lyxal_network-floodsub = { workspace = true, optional = true }
lyxal_network-gossipsub = { workspace = true, optional = true }
lyxal_network-identify = { workspace = true, optional = true }
lyxal_network-identity = { workspace = true, features = ["rand"] }
lyxal_network-kad = { workspace = true, optional = true }
lyxal_network-metrics = { workspace = true, optional = true }
lyxal_network-noise = { workspace = true, optional = true }
lyxal_network-ping = { workspace = true, optional = true }
lyxal_network-plaintext = { workspace = true, optional = true }
lyxal_network-pnet = { workspace = true, optional = true }
lyxal_network-relay = { workspace = true, optional = true }
lyxal_network-rendezvous = { workspace = true, optional = true }
lyxal_network-request-response = { workspace = true, optional = true }
lyxal_network-swarm = { workspace = true }
lyxal_network-yamux = { workspace = true, optional = true }
multiaddr = { workspace = true }
pin-project = "1.0.0"
thiserror = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
lyxal_network-webrtc-websys = { workspace = true, optional = true }
lyxal_network-websocket-websys = { workspace = true, optional = true }
lyxal_network-webtransport-websys = { workspace = true, optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
lyxal_network-dns = { workspace = true, optional = true }
lyxal_network-mdns = { workspace = true, optional = true }
lyxal_network-memory-connection-limits = { workspace = true, optional = true }
lyxal_network-quic = { workspace = true, optional = true }
lyxal_network-tcp = { workspace = true, optional = true }
lyxal_network-tls = { workspace = true, optional = true }
lyxal_network-uds = { workspace = true, optional = true }
lyxal_network-upnp = { workspace = true, optional = true }
lyxal_network-websocket = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["io-util", "io-std", "macros", "rt", "rt-multi-thread"] }

lyxal_network-mplex = { workspace = true }
lyxal_network-tcp = { workspace = true, features = ["tokio"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

# Passing arguments to the docsrs builder in order to properly document cfg's.
# More information: https://docs.rs/about/builds#cross-compiling
[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true
