[package]
name = "lyx-tooling-formatter"
version = "0.8.0"
edition = "2024"

[dependencies]

rstml = { version = "*" }
syn = { version = "*" }
proc-macro2 = { version = "*" }
thiserror = { version = "*" }
crop = { version = "*" }
serde = { version = "*", features = ["derive"] }
quote = { version = "*" }
rustywind_core = { version = "*" }

[dev-dependencies]
indoc = { version = "*" }
insta = { version = "*" }
quote = { version = "*" }




