[package]
name = "lyx-tooling-formatter"
version = "0.0.1"
edition = "2024"

[dependencies]

rstml = { version = "0.0.1" }
syn = { version = "0.0.1" }
proc-macro2 = { version = "0.0.1" }
thiserror = { version = "0.0.1" }
crop = { version = "0.0.1" }
serde = { version = "0.0.1", features = ["derive"] }
quote = { version = "0.0.1" }
rustywind_core = { version = "0.0.1" }

[dev-dependencies]
indoc = { version = "0.0.1" }
insta = { version = "0.0.1" }
quote = { version = "0.0.1" }
