-- Seeds pour les villes du pays: KY --

CREATE base_city:ky_153943 SET state = base_state:ky_02, key.name = i18n_key:i18n_city_ky_153943_name, native = 'Cayman Brac', location = (-79.89072660, 19.71999700), timezone = base_timezone:america_lima, wikiDataId = 'Q111386576';
CREATE base_city:ky_153938 SET state = base_state:ky_01, key.name = i18n_key:i18n_city_ky_153938_name, native = 'Bodden Town', location = (-81.27779990, 19.27966930), timezone = base_timezone:america_lima, wikiDataId = 'Q4936407';
CREATE base_city:ky_153939 SET state = base_state:ky_01, key.name = i18n_key:i18n_city_ky_153939_name, native = 'East End', location = (-81.11961380, 19.29958980), timezone = base_timezone:america_lima, wikiDataId = 'Q5328285';
CREATE base_city:ky_153940 SET state = base_state:ky_01, key.name = i18n_key:i18n_city_ky_153940_name, native = 'George Town', location = (-81.44333720, 19.29023260), timezone = base_timezone:america_lima, wikiDataId = 'Q172996';
CREATE base_city:ky_153941 SET state = base_state:ky_01, key.name = i18n_key:i18n_city_ky_153941_name, native = 'North Side', location = (-81.51398130, 19.33620470), timezone = base_timezone:america_lima, wikiDataId = 'Q7056735';
CREATE base_city:ky_153942 SET state = base_state:ky_01, key.name = i18n_key:i18n_city_ky_153942_name, native = 'West Bay', location = (-81.43170260, 19.36651530), timezone = base_timezone:america_lima, wikiDataId = 'Q7984402';
CREATE base_city:ky_153944 SET state = base_state:ky_03, key.name = i18n_key:i18n_city_ky_153944_name, native = 'Little Cayman', location = (-80.11830190, 19.68567390), timezone = base_timezone:america_lima, wikiDataId = 'Q27347438';
