[package]
name = "lyx-specialized-start-axum"
version = "0.8.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
leptos_axum = { version = "*", optional = true, features = ["macros"] }
console_error_panic_hook = { version = "*" }
leptos = { path = "../../../../core/lyx-core-leptos/leptos", features = ["nightly"] }
leptos_axum = { path = "../../../../core/lyx-core-leptos/integrations/axum", optional = true }
leptos_meta = { path = "../../../../core/lyx-core-leptos/meta", features = ["nightly"] }
leptos_router = { path = "../../../../core/lyx-core-leptos/router", features = ["nightly"] }
tokio = { version = "*", optional = true, features = ["rt-multi-thread"] }
tower = { version = "*", optional = true }
tower-http = { version = "*", optional = true, features = ["fs"] }
wasm-bindgen = { version = "*" }
thiserror = { version = "*" }
tracing = { version = "*", optional = true }
http = { version = "*" }

cfg-if = { version = "*" }
lyx-spec-image = { path = "../../" }
simple_logger = { version = "*" }
log = { version = "*" }

[features]
hydrate = ["leptos/hydrate", "leptos_meta/hydrate", "leptos_router/hydrate", "lyx-spec-image/hydrate"]
ssr = [
"dep:axum",
"dep:tokio",
"dep:tower",
"dep:tower-http",
"dep:leptos_axum",
"leptos/ssr",
"leptos_meta/ssr",
"leptos_router/ssr",
"dep:tracing",
"lyx-spec-image/ssr"
]











