[package]
name = "src-orig"
version = "*"
edition = "2024"
[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
[[bin]]
name = "src-orig"
path = "src/lib.rs"
[dependencies]
axum = { version = "*", optional = true }
axum-macros = { version = "*", optional = true }
console_error_panic_hook = { version = "*", optional = true }
leptos = { path = "../leptos", version = "*", optional = true }
axum = { path = "../../../integrations/axum", version = "*", optional = true }
meta = { path = "../../../meta", version = "*", optional = true }
server_fn = { path = "../server_fn", version = "*", optional = true }
tokio = { version = "*", optional = true, features = ["rt-multi-thread"] }
tower = { version = "*", optional = true }
tower-http = { version = "*", optional = true, features = ["fs", "cors"] }
wasm-bindgen = { version = "*", optional = true }
[features]
csr = ["leptos/csr", "dep:server_fn"]
hydrate = [
"leptos/hydrate",
"dep:meta",
"dep:console_error_panic_hook",
"dep:wasm-bindgen"
]
ssr = [
"dep:axum",
"dep:axum-macros",
"leptos/ssr",
"dep:axum",
"dep:meta",
"meta/ssr",
"dep:tower-http",
"dep:tower",
"dep:tokio" ]


[build-dependencies]
rustc_version = "*"




