[workspace]
members = [
    "core",
    "hole-punching-tests",
    "identity",
    "interop-tests",
    "lyxal_network",
    "misc/allow-block-list",
    "misc/connection-limits",
    "misc/keygen",
    "misc/memory-connection-limits",
    "misc/metrics",
    "misc/multistream-select",
    "misc/peer-store",
    "misc/quick-protobuf-codec",
    "misc/quickcheck-ext",
    "misc/rw-stream-sink",
    "misc/server",
    "misc/webrtc-utils",
    "multiaddr",
    "muxers/mplex",
    "muxers/test-harness",
    "muxers/yamux",
    "protocols/autonat",
    "protocols/dcutr",
    "protocols/floodsub",
    "protocols/gossipsub",
    "protocols/identify",
    "protocols/kad",
    "protocols/mdns",
    "protocols/perf",
    "protocols/ping",
    "protocols/relay",
    "protocols/rendezvous",
    "protocols/request-response",
    "protocols/sfu",
    "protocols/stream",
    "protocols/upnp",
    "swarm-derive",
    "swarm-test",
    "swarm",
    "transports/dns",
    "transports/noise",
    "transports/plaintext",
    "transports/pnet",
    "transports/quic",
    "transports/rtc/rtc",
    "transports/rtc/rtc-datachannel",
    "transports/rtc/rtc-dtls",
    "transports/rtc/rtc-ice",
    "transports/rtc/rtc-interceptor",
    "transports/rtc/rtc-interceptor-derive",
    "transports/rtc/rtc-mdns",
    "transports/rtc/rtc-media",
    "transports/rtc/rtc-rtcp",
    "transports/rtc/rtc-rtp",
    "transports/rtc/rtc-sctp",
    "transports/rtc/rtc-sdp",
    "transports/rtc/rtc-shared",
    "transports/rtc/rtc-srtp",
    "transports/rtc/rtc-stun",
    "transports/rtc/rtc-turn",
    "transports/rtc/sansio",
    "transports/tcp",
    "transports/tls",
    "transports/uds",
    "transports/webrtc-websys",
    "transports/webrtc",
    "transports/websocket-websys",
    "transports/websocket",
    "transports/webtransport-websys",
]
resolver = "2"

[workspace.package]
rust-version = "1.85.0"
edition = "2024"
version = "0.7.4"

[workspace.dependencies]
datachannel = { version = "0.7.4", path = "transports/rtc/rtc-datachannel", package = "rtc-datachannel" }
dtls = { version = "0.7.4", path = "transports/rtc/rtc-dtls", package = "rtc-dtls" }
ice = { version = "0.7.4", path = "transports/rtc/rtc-ice", package = "rtc-ice" }
interceptor = { version = "0.7.4", path = "transports/rtc/rtc-interceptor", package = "rtc-interceptor" }
interceptor-derive = { version = "0.7.4", path = "transports/rtc/rtc-interceptor-derive", package = "rtc-interceptor-derive" }
lyxal_network = { version = "0.56.1", path = "lyxal_network" }
lyxal_network-allow-block-list = { version = "0.6.0", path = "misc/allow-block-list" }
lyxal_network-autonat = { version = "0.15.0", path = "protocols/autonat" }
lyxal_network-connection-limits = { version = "0.6.0", path = "misc/connection-limits" }
lyxal_network-core = { version = "0.43.2", path = "core" }
lyxal_network-dcutr = { version = "0.14.1", path = "protocols/dcutr" }
lyxal_network-dns = { version = "0.44.0", path = "transports/dns" }
lyxal_network-floodsub = { version = "0.47.0", path = "protocols/floodsub" }
lyxal_network-gossipsub = { version = "0.50.0", path = "protocols/gossipsub" }
lyxal_network-identify = { version = "0.47.0", path = "protocols/identify" }
lyxal_network-identity = { version = "0.2.13" }
lyxal_network-kad = { version = "0.49.0", path = "protocols/kad" }
lyxal_network-mdns = { version = "0.48.0", path = "protocols/mdns" }
lyxal_network-memory-connection-limits = { version = "0.5.0", path = "misc/memory-connection-limits" }
lyxal_network-metrics = { version = "0.17.1", path = "misc/metrics" }
lyxal_network-mplex = { version = "0.43.1", path = "muxers/mplex" }
lyxal_network-noise = { version = "0.46.1", path = "transports/noise" }
lyxal_network-peer-store = { version = "0.1.0", path = "misc/peer-store" }
lyxal_network-perf = { version = "0.4.0", path = "protocols/perf" }
lyxal_network-ping = { version = "0.47.0", path = "protocols/ping" }
lyxal_network-plaintext = { version = "0.43.0", path = "transports/plaintext" }
lyxal_network-pnet = { version = "0.26.0", path = "transports/pnet" }
lyxal_network-quic = { version = "0.13.0", path = "transports/quic" }
lyxal_network-relay = { version = "0.21.1", path = "protocols/relay" }
lyxal_network-rendezvous = { version = "0.17.0", path = "protocols/rendezvous" }
lyxal_network-request-response = { version = "0.29.0", path = "protocols/request-response" }
lyxal_network-server = { version = "0.12.7", path = "misc/server" }
lyxal_network-stream = { version = "0.4.0-alpha", path = "protocols/stream" }
lyxal_network-swarm = { version = "0.47.1", path = "swarm" }
lyxal_network-swarm-derive = { version = "=0.35.1", path = "swarm-derive" }
lyxal_network-swarm-test = { version = "0.6.0", path = "swarm-test" }
lyxal_network-tcp = { version = "0.44.1", path = "transports/tcp" }
lyxal_network-tls = { version = "0.6.2", path = "transports/tls" }
lyxal_network-uds = { version = "0.43.1", path = "transports/uds" }
lyxal_network-upnp = { version = "0.6.0", path = "protocols/upnp" }
lyxal_network-webrtc = { version = "0.9.0-alpha.2", path = "transports/webrtc" }
lyxal_network-webrtc-utils = { version = "0.4.0", path = "misc/webrtc-utils" }
lyxal_network-webrtc-websys = { version = "0.4.0", path = "transports/webrtc-websys" }
lyxal_network-websocket = { version = "0.45.2", path = "transports/websocket" }
lyxal_network-websocket-websys = { version = "0.5.0", path = "transports/websocket-websys" }
lyxal_network-webtransport-websys = { version = "0.5.2", path = "transports/webtransport-websys" }
lyxal_network-yamux = { version = "0.47.0", path = "muxers/yamux" }
mdns = { version = "0.7.4", path = "transports/rtc/rtc-mdns", package = "rtc-mdns" }
media = { version = "0.7.4", path = "transports/rtc/rtc-media", package = "rtc-media" }
multiaddr = { package = "lyxal_network-multiaddr", version = "0.18.3", path = "multiaddr" }
rtcp = { version = "0.7.4", path = "transports/rtc/rtc-rtcp", package = "rtc-rtcp" }
rtp = { version = "0.7.4", path = "transports/rtc/rtc-rtp", package = "rtc-rtp" }
sansio = { version = "1.0.1", path = "transports/rtc/sansio" }
sctp = { version = "0.7.4", path = "transports/rtc/rtc-sctp", package = "rtc-sctp" }
sdp = { version = "0.7.4", path = "transports/rtc/rtc-sdp", package = "rtc-sdp" }
shared = { version = "0.7.4", path = "transports/rtc/rtc-shared", package = "rtc-shared", default-features = false }
srtp = { version = "0.7.4", path = "transports/rtc/rtc-srtp", package = "rtc-srtp" }
stun = { version = "0.7.4", path = "transports/rtc/rtc-stun", package = "rtc-stun" }
turn = { version = "0.7.4", path = "transports/rtc/rtc-turn", package = "rtc-turn" }

# External dependencies
asynchronous-codec = { version = "0.7.0" }
env_logger = "0.11"
futures = "0.3.30"
futures-bounded = { version = "0.2.4" }
futures-rustls = { version = "0.26.0", default-features = false }
getrandom = "0.2"
if-watch = "3.2.1"
hickory-proto = { version = "0.25.2", default-features = false }
hickory-resolver = { version = "0.25.2", default-features = false }
multihash = "0.19.1"
multistream-select = { version = "0.13.0", path = "misc/multistream-select" }
prometheus-client = "0.24"
quick-protobuf-codec = { version = "0.3.1", path = "misc/quick-protobuf-codec" }
quickcheck = { package = "quickcheck-ext", path = "misc/quickcheck-ext" }
rcgen = "0.13"
ring = "0.17.12"
rw-stream-sink = { version = "0.4.0", path = "misc/rw-stream-sink" }
thiserror = "2"
tokio = { version = "1.38", default-features = false }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
unsigned-varint = { version = "0.8.0" }
web-time = "1.1.0"
hashlink = "0.10.0"

[patch.crates-io]

# Patch away `lyxal_network-identity` in our dependency tree with the workspace version.
# `lyxal_network-identity` is a leaf dependency and used within `rust-multiaddr` which is **not** part of the workspace.
# As a result, we cannot just reference the workspace version in our crates because the types would mismatch with what
# we import via `rust-multiaddr`.
# This is expected to stay here until we move `lyxal_network-identity` to a separate repository which makes the dependency relationship more obvious.
lyxal_network-identity = { path = "identity" }

[workspace.lints]
rust.unreachable_pub = "warn"
clippy.used_underscore_binding = "warn"
clippy.pedantic = { level = "allow", priority = -1 }
clippy.type_complexity = "allow"
clippy.unnecessary_wraps = "warn"
clippy.manual_let-else = "warn"
clippy.dbg_macro = "warn"
