[package]
name = "lyxal_network-stream"
version = "0.4.0-alpha"
edition.workspace = true
rust-version.workspace = true
description = "Generic stream protocols for lyxal_network"

[dependencies]
futures = { workspace = true }
lyxal_network-core = { workspace = true }
lyxal_network-identity = { workspace = true, features = ["peerid"] }
lyxal_network-swarm = { workspace = true }
tracing = { workspace = true }
rand = "0.8"

[dev-dependencies]
lyxal_network-swarm-test = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[lints]
workspace = true
