-- Clés i18n pour les villes du pays: DJ --

CREATE i18n_key:i18n_city_dj_30561_name SET description = 'Nom pour la ville \'\\'Ali Sabieh\'';
CREATE i18n_key:i18n_city_dj_30567_name SET description = 'Nom pour la ville \'Goubétto\'';
CREATE i18n_key:i18n_city_dj_30569_name SET description = 'Nom pour la ville \'Holhol\'';
CREATE i18n_key:i18n_city_dj_30563_name SET description = 'Nom pour la ville \'Arta\'';
CREATE i18n_key:i18n_city_dj_30564_name SET description = 'Nom pour la ville \'Dikhil\'';
CREATE i18n_key:i18n_city_dj_30568_name SET description = 'Nom pour la ville \'Gâlâfi\'';
CREATE i18n_key:i18n_city_dj_30565_name SET description = 'Nom pour la ville \'Djibouti\'';
CREATE i18n_key:i18n_city_dj_30570_name SET description = 'Nom pour la ville \'Loyada\'';
CREATE i18n_key:i18n_city_dj_30562_name SET description = 'Nom pour la ville \'Alaïli Ḏaḏḏa‘\'';
CREATE i18n_key:i18n_city_dj_30571_name SET description = 'Nom pour la ville \'Obock\'';
CREATE i18n_key:i18n_city_dj_30566_name SET description = 'Nom pour la ville \'Dorra\'';
CREATE i18n_key:i18n_city_dj_30572_name SET description = 'Nom pour la ville \'Tadjourah\'';
