[package]
name = "e2e"
version = "0.8.0"
edition = "2024"
[dev-dependencies]
anyhow = { version = "*" }
async-trait = { version = "*" }
cucumber = { version = "*", features = ["tracing", "macros"] }
pretty_assertions = { version = "*" }
serde_json = { version = "*" }
tokio = { version = "*", features = ["macros", "rt-multi-thread", "time"] }
url = { version = "*" }
reqwest = { version = "*" }
tracing = { version = "*" }
chromiumoxide = { version = "*", default-features = false, features = ["tokio-runtime" ] }
fake = { version = "*" }
tokio-tungstenite = { version = "*" }
futures-util = { version = "*" }
uuid = { version = "*", features = ["serde"] }
futures = { version = "*" }
[[test]]
name = "e2e"
harness = false
[features]
ssr = []
[dependencies]
regex = { version = "*" }


[build-dependencies]
rustc_version = "*"




