[package]
name = "server_fn_macro"
version = "0.8.0"
edition = "2024"
[dependencies]
quote = { version = "*", default-features = true }
syn = { version = "*", features = ["full", "parsing", "extra-traits" ], default-features = true }
proc-macro2 = { version = "*", default-features = true }
xxhash-rust = { version = "*", features = ["const_xxh64" ], default-features = true }
const_format = { version = "*", default-features = true }
convert_case = { version = "*", default-features = true }
[build-dependencies]
rustc_version = { version = "*", default-features = true }
[features]
nightly = []
ssr = []
actix = []
axum = []
generic = []
reqwest = []




