[package]
name = "leptos_i18n_build"
version = "0.8.0"
edition = "2024"

[dependencies]


proc-macro2 = { version = "*" }
leptos_i18n_parser = { path = "../leptos_i18n_parser", optional = true }
leptos_i18n_codegen = { path = "../leptos_i18n_codegen", optional = true }

icu_provider_export = { version = "*", features = ["baked_exporter"] }
icu_provider_source = { version = "*", features = ["networking"] }
icu = { version = "*", features = ["experimental"] }
icu_provider = { version = "*" }
icu_locale = { version = "*" }

prettyplease = { version = "*", optional = true, features = ["verbatim"] }
syn = { version = "*" }

[features]
default = []
islands = ["leptos_i18n_codegen/islands"]
dynamic_load = ["leptos_i18n_codegen/dynamic_load"]
hydrate = ["leptos_i18n_codegen/hydrate"]
csr = ["leptos_i18n_codegen/csr"]
ssr = ["leptos_i18n_codegen/ssr"]
plurals = ["leptos_i18n_parser/plurals", "leptos_i18n_codegen/plurals"]
format_datetime = [
"leptos_i18n_parser/format_datetime",
"leptos_i18n_codegen/format_datetime" ]
format_list = [
"leptos_i18n_parser/format_list",
"leptos_i18n_codegen/format_list" ]
format_nums = [
"leptos_i18n_parser/format_nums",
"leptos_i18n_codegen/format_nums" ]
format_currency = [
"leptos_i18n_parser/format_currency",
"format_nums",
"leptos_i18n_codegen/format_currency" ]

# This is to format the code after codegen, helpfull for debugging
pretty_print = ["dep:prettyplease"]







