[package]
name = "lyx-logic-leptos_form"
version = "0.0.1"
edition = "2024"

[dependencies]
lyx-logic-core = { path = "../core", version = "0.0.1" }


js-sys = { version = "0.0.1", optional = true }

web-sys = { version = "0.0.1", optional = true }

[dev-dependencies]



uuid = { version = "0.0.1", features = ["v4"] }

[build-dependencies]


rustc_version = { version = "0.0.1" }

[features]
bigdecimal = ["lyx-logic-core/bigdecimal"]
cache-local-storage = [
"dep:js-sys",
"lyx-logic-core/cache-local-storage",
"dep:web-sys",
"web-sys/Storage" ]
cache-serde_json = [
"lyx-logic-core/cache-serde_json" ]
chrono = ["lyx-logic-core/chrono"]
num-bigint = ["lyx-logic-core/num-bigint"]
uuid = ["lyx-logic-core/uuid"]
