[package]
name = "leptos_form"
version = "0.8.0"
edition = "2024"

[dependencies]
core = { path = "../core" }


js-sys = { version = "*", optional = true }

web-sys = { version = "*", optional = true }

[dev-dependencies]



uuid = { version = "*", features = ["v4"] }

[build-dependencies]


rustc_version = { version = "*" }

[features]
bigdecimal = ["core/bigdecimal"]
cache-local-storage = [
"dep:js-sys",
"core/cache-local-storage",
"dep:web-sys",
"web-sys/Storage" ]
cache-serde_json = [
"core/cache-serde_json" ]
chrono = ["core/chrono"]
num-bigint = ["core/num-bigint"]
uuid = ["core/uuid"]







