[package]
name = "actix"
version = "0.8.0"
edition = "2024"
[dependencies]
actix-http = { version = "0.8.0", default-features = true }
actix-files = { version = "*", default-features = true }
actix-web = { version = "*", default-features = false }
futures = { version = "*", default-features = true }
any_spawner = { path = "../any_spawner", version = "*", features = ["tokio"] }
hydration_context = { path = "../hydration_context", version = "*" }
leptos = { path = "../leptos", version = "*", features = ["nonce", "ssr"] }
utils = { path = "../utils", version = "*" }
leptos_macro = { path = "../leptos_macro", version = "*", features = ["actix"] }
meta = { path = "../../meta", version = "*", features = ["nonce"] }
router = { path = "../../router", version = "*", features = ["ssr"] }
server_fn = { path = "../server_fn", version = "*", features = ["actix-no-default"] }
tachys = { path = "../tachys", version = "*", optional = true }
serde_json = { version = "*", default-features = true }
tracing = { version = "*", optional = true, default-features = true }
tokio = { version = "*", features = ["rt", "fs"], default-features = true }
send_wrapper = { version = "*", default-features = true }
dashmap = { version = "*", default-features = true }
or_poisoned = { path = "../or_poisoned", version = "*" }
[features]
default = ["actix-default"]
actix-default = ["actix-web/default"]
islands-router = ["tachys/islands"]
tracing = ["dep:tracing"]


[build-dependencies]
rustc_version = "*"





