[package]
name = "lyx-ui-thaw_components"
version = "0.8.0"
edition = "2024"
[dependencies]
leptos = { path = "../core/lyx-core-leptos/leptos" }
thaw_utils = { path = "../thaw_utils" }
web-sys = { version = "*", features = ["DomRect"] }
cfg-if = { version = "*" }
uuid = { version = "*", features = ["v4", "js"] }
send_wrapper = { version = "*" }
[features]
csr = ["leptos/csr"]
ssr = ["leptos/ssr"]
hydrate = ["leptos/hydrate"]










