[package]
name = "lyxal-revision"
publish = false
edition.workspace = true
version.workspace = true
authors.workspace = true
description = "A serialization and deserialization implementation which allows for schema-evolution."
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
license-file.workspace = true

[features]
default = ["specialised-vectors"]
specialised-vectors = []
fixed-width-encoding = []

[dependencies]

# Lyxal internal crates
lyxal-revision-derive.workspace = true

# External crates
bytes = { workspace = true, optional = true }
chrono = { workspace = true, optional = true }
geo = { workspace = true, optional = true }
imbl = { workspace = true, optional = true }
ordered-float = { workspace = true, optional = true }
regex = { workspace = true, optional = true }
roaring = { workspace = true, optional = true }
rust_decimal = { workspace = true, optional = true }
uuid = { workspace = true, optional = true }

[dev-dependencies]
bincode.workspace = true
criterion.workspace = true
paste.workspace = true
rand.workspace = true
serde.workspace = true

[lints]
workspace = true

[[bench]]
name = "roaring"
harness = false
required-features = ["roaring"]

[[bench]]
name = "generic"
harness = false

[[bench]]
name = "vec_i8_comparison"
harness = false

[[bench]]
name = "vec_i16_comparison"
harness = false

[[bench]]
name = "vec_i32_comparison"
harness = false

[[bench]]
name = "vec_i64_comparison"
harness = false

[[bench]]
name = "vec_i128_comparison"
harness = false

[[bench]]
name = "vec_u8_comparison"
harness = false

[[bench]]
name = "vec_u16_comparison"
harness = false

[[bench]]
name = "vec_u32_comparison"
harness = false

[[bench]]
name = "vec_u64_comparison"
harness = false

[[bench]]
name = "vec_u128_comparison"
harness = false

[[bench]]
name = "vec_f32_comparison"
harness = false

[[bench]]
name = "vec_f64_comparison"
harness = false

[[bench]]
name = "vec_string_comparison"
harness = false

[[bench]]
name = "specialisation_comparison"
harness = false

[[bench]]
name = "ordmap_comparison"
harness = false
required-features = ["imbl"]

[[bench]]
name = "varint_comparison"
harness = false

[[bench]]
name = "vec_bool_comparison"
harness = false
