-- Seeds pour les villes du pays: SM --

CREATE base_city:sm_104693 SET state = base_state:sm_01, key.name = i18n_key:i18n_city_sm_104693_name, native = 'Acquaviva', location = (12.41850000, 43.94593000), timezone = base_timezone:europe_paris, wikiDataId = 'Q289747';
CREATE base_city:sm_104694 SET state = base_state:sm_06, key.name = i18n_key:i18n_city_sm_104694_name, native = 'Borgo Maggiore', location = (12.44738000, 43.94193000), timezone = base_timezone:europe_paris, wikiDataId = 'Q289747';
CREATE base_city:sm_104699 SET state = base_state:sm_02, key.name = i18n_key:i18n_city_sm_104699_name, native = 'Poggio di Chiesanuova', location = (12.42142000, 43.90451000), timezone = base_timezone:europe_paris, wikiDataId = 'Q289747';
CREATE base_city:sm_104695 SET state = base_state:sm_03, key.name = i18n_key:i18n_city_sm_104695_name, native = 'Domagnano', location = (12.46828000, 43.94961000), timezone = base_timezone:europe_paris, wikiDataId = 'Q289747';
CREATE base_city:sm_104696 SET state = base_state:sm_04, key.name = i18n_key:i18n_city_sm_104696_name, native = 'Condizione', location = (12.49798000, 43.92831000), timezone = base_timezone:europe_paris, wikiDataId = 'Q289747';
CREATE base_city:sm_104697 SET state = base_state:sm_05, key.name = i18n_key:i18n_city_sm_104697_name, native = 'Fiorentino', location = (12.45738000, 43.91001000), timezone = base_timezone:europe_paris, wikiDataId = 'Q289747';
CREATE base_city:sm_104698 SET state = base_state:sm_08, key.name = i18n_key:i18n_city_sm_104698_name, native = 'Monte Giardino', location = (12.48201000, 43.90878000), timezone = base_timezone:europe_paris, wikiDataId = 'Q289747';
CREATE base_city:sm_104700 SET state = base_state:sm_07, key.name = i18n_key:i18n_city_sm_104700_name, native = 'San Marino', location = (12.44639000, 43.93667000), timezone = base_timezone:europe_paris, wikiDataId = 'Q1848';
CREATE base_city:sm_104701 SET state = base_state:sm_09, key.name = i18n_key:i18n_city_sm_104701_name, native = 'Serravalle', location = (12.48167000, 43.96897000), timezone = base_timezone:europe_paris, wikiDataId = 'Q1848';
