[package]
name = "src-tauri"
version = "0.8.0"
edition = "2024"
[lib]
name = "src_tauri"
path = "src/lib.rs"
[build-dependencies]
rustc_version = "*"
tauri-build = { version = "*", features = [] }
[dependencies]
log = { version = "*" }
serde = { version = "*", features = ["derive"] }
tauri = { version = "*", features = ["devtools"] }
tauri-plugin-http = { version = "*" }
[features]
custom-protocol = ["tauri/custom-protocol"]





