[package]
name = "service_utils"
version = "0.8.0"
edition = "2024"

[dependencies]
actix-web = { version = "*" }
aes-gcm = { version = "*" }
anyhow = { version = "*" }
aws-config = { version = "*", features = ["behavior-version-latest"] }
aws-sdk-kms = { version = "*" }
base64 = { version = "*" }
chrono = { version = "*" }
derive_more = { version = "*" }
diesel = { version = "*" }
fred = { version = "*", optional = true }
futures-util = { version = "*" }
jsonschema = { version = "*" }
log = { version = "*" }
once_cell = { version = "*" }
openidconnect = { version = "*" }
rand = { version = "*" }
tracing = { version = "*" }
regex = { version = "*" }
reqwest = { version = "*" }
rs-snowflake = { version = "*" }
secrecy = { version = "*" }
serde = { version = "*" }
serde_json = { version = "*" }
strum_macros = { version = "*" }
superposition_macros = { path = "../superposition_macros" }
superposition_types = { path = "../superposition_types", features = ["result", "api", "diesel_derives" ] }
url = { version = "*" }
urlencoding = { version = "*" }
tracing-actix-web = { version = "*" }

[features]
high-performance-mode = ["dep:fred"]







