[package]
name = "lyx-ui-foundations-dioxus"
version = "0.8.0"
edition = "2024"

[features]
icons = ["dep:lyx-ui-foundations-dioxus", "lyx-ui-foundations-dioxus/all-icons"]

[dependencies]

dioxus = { version = "*", features = ["web"] }

lyx-ui-foundations-dioxus = { path = "../../packages/dioxus", optional = true }





