-- ===== CISCO I18N TRANSLATIONS =====
-- ===== Date: 2025-11-05 =====
-- ===== Langues: FR, EN, IT, DE, ES =====
-- ===== Total: 5 traductions =====

BEGIN

-- CISCO PROVIDER
-- CISCO NAME
RELATE i18n_key:provider_cisco_name->translation->language:fr SET text = "CISCO";
RELATE i18n_key:provider_cisco_name->translation->language:en SET text = "CISCO";
RELATE i18n_key:provider_cisco_name->translation->language:it SET text = "CISCO";
RELATE i18n_key:provider_cisco_name->translation->language:de SET text = "CISCO";
RELATE i18n_key:provider_cisco_name->translation->language:es SET text = "CISCO";

-- CISCO DESCRIPTION
RELATE i18n_key:provider_cisco_description->translation->language:fr SET text = "CISCO Provider";
RELATE i18n_key:provider_cisco_description->translation->language:en SET text = "CISCO Provider";
RELATE i18n_key:provider_cisco_description->translation->language:it SET text = "CISCO Provider";
RELATE i18n_key:provider_cisco_description->translation->language:de SET text = "CISCO Provider";
RELATE i18n_key:provider_cisco_description->translation->language:es SET text = "CISCO Provider";

--CISCO TOOLTIP
RELATE i18n_key:provider_cisco_tooltip->translation->language:fr SET text = "Pour CISCO";
RELATE i18n_key:provider_cisco_tooltip->translation->language:en SET text = "For CISCO";
RELATE i18n_key:provider_cisco_tooltip->translation->language:it SET text = "Per CISCO";
RELATE i18n_key:provider_cisco_tooltip->translation->language:de SET text = "Für CISCO";
RELATE i18n_key:provider_cisco_tooltip->translation->language:es SET text = "Para CISCO";

COMMIT;