[package]
name = "server_fn"
version = "0.8.0"
edition = "2024"

[dependencies]
any_error = { path = "../any_error", version = "0.8.0" }
server_fn_macro_default = { path = "server_fn_macro_default", version = "*" }
const_format = { version = "*" }
const-str = { version = "*" }
rustversion = { version = "*" }
xxhash-rust = { version = "*", features = ["const_xxh64"] }
serde = { version = "*", features = ["derive"] }
send_wrapper = { version = "*", optional = true, features = ["futures"] }
thiserror = { version = "*" }
inventory = { version = "*", optional = true }
dashmap = { version = "*" }
serde_qs = { version = "*" }
serde_json = { version = "*" }
futures = { version = "*" }
http = { version = "*" }
bytes = { version = "*" }
url = { version = "*" }
pin-project-lite = { version = "*" }

[features]
multipart = []
url = []
browser = []
actix-no-default = []
axum-no-default = []
ssr = ["dep:inventory"]
cbor = []
axum = []
actix = []
rsc = []


[build-dependencies]
rustc_version = "*"





