[package]
name = "lyx-ui-foundations-stylers"
version = "0.8.0"
edition = "2024"

[dependencies]
glob = { version = "*" }
syn = { version = "*", features = ["full"] }
lyx-ui-foundations-stylers_core = { path = "../stylers_core" }
lyx-ui-foundations-stylers_macro = { path = "../stylers_macro" }
proc-macro2 = { version = "*" }





