[package]
name = "lyx-comm-socket"
version = "0.8.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = { version = "*" }
leptos_axum = { version = "*", optional = true, features = ["macros"] }
cookie = { version = "*", optional = true }
futures-util = { version = "*", optional = true }
leptos = { path = "../../core/lyx-core-leptos/leptos" }
leptos-use = { path = "../../logic/lyx-logic-use", features = ["use_websocket" ] }
leptos_axum = { path = "../../core/lyx-core-leptos/integrations/axum", optional = true }
regex = { version = "*", optional = true }
serde = { version = "*", features = ["derive"] }
serde_json = { version = "*" }
serde_urlencoded = { version = "*" }
tokio = { version = "*", optional = true, features = ["rt-multi-thread"] }
tracing = { version = "*" }
uuid = { version = "*", features = ["v4", "serde"] }

[features]
ssr = [
"dep:axum",
"dep:cookie",
"dep:tokio",
"dep:leptos_axum",
"dep:regex",
"leptos/ssr",
"leptos-use/ssr",
"leptos-use/axum",
"dep:futures-util" ]
hydrate = ["leptos/hydrate", "uuid/js"]










