-- Seeds pour les villes du pays: VU --

CREATE base_city:vu_130637 SET state = base_state:vu_map, key.name = i18n_key:i18n_city_vu_130637_name, native = 'Lakatoro', location = (167.41636000, -16.09992000), timezone = base_timezone:asia_sakhalin, wikiDataId = 'Q669361';
CREATE base_city:vu_130639 SET state = base_state:vu_map, key.name = i18n_key:i18n_city_vu_130639_name, native = 'Norsup', location = (167.39714000, -16.06536000), timezone = base_timezone:asia_sakhalin, wikiDataId = 'Q876557';
CREATE base_city:vu_130638 SET state = base_state:vu_sam, key.name = i18n_key:i18n_city_vu_130638_name, native = 'Luganville', location = (167.16235000, -15.51989000), timezone = base_timezone:asia_sakhalin, wikiDataId = 'Q876557';
CREATE base_city:vu_130640 SET state = base_state:vu_sam, key.name = i18n_key:i18n_city_vu_130640_name, native = 'Port-Olry', location = (167.07265000, -15.04175000), timezone = base_timezone:asia_sakhalin, wikiDataId = 'Q1050300';
CREATE base_city:vu_130641 SET state = base_state:vu_see, key.name = i18n_key:i18n_city_vu_130641_name, native = 'Port-Vila', location = (168.31366000, -17.73648000), timezone = base_timezone:asia_sakhalin, wikiDataId = 'Q37806';
CREATE base_city:vu_130636 SET state = base_state:vu_tae, key.name = i18n_key:i18n_city_vu_130636_name, native = 'Isangel', location = (169.28167000, -19.54167000), timezone = base_timezone:asia_sakhalin, wikiDataId = 'Q1070178';
CREATE base_city:vu_130642 SET state = base_state:vu_tob, key.name = i18n_key:i18n_city_vu_130642_name, native = 'Sola', location = (167.55167000, -13.87611000), timezone = base_timezone:asia_sakhalin, wikiDataId = 'Q1423143';
