[package]
name = "lyxal_network-metrics"
edition.workspace = true
rust-version = { workspace = true }
description = "Metrics for lyxal_network"
version = "0.17.1"

[features]
dcutr = ["lyxal_network-dcutr"]
gossipsub = ["lyxal_network-gossipsub"]
identify = ["lyxal_network-identify"]
kad = ["lyxal_network-kad"]
ping = ["lyxal_network-ping"]
relay = ["lyxal_network-relay"]

[dependencies]
futures = { workspace = true }
web-time = { workspace = true }
lyxal_network-core = { workspace = true }
lyxal_network-dcutr = { workspace = true, optional = true }
lyxal_network-gossipsub = { workspace = true, optional = true }
lyxal_network-identify = { workspace = true, optional = true }
lyxal_network-identity = { workspace = true }
lyxal_network-kad = { workspace = true, optional = true }
lyxal_network-ping = { workspace = true, optional = true }
lyxal_network-relay = { workspace = true, optional = true }
lyxal_network-swarm = { workspace = true }
pin-project = "1.1.5"
prometheus-client = { workspace = true }

[dev-dependencies]
lyxal_network-identity = { workspace = true, features = ["rand"] }

# Passing arguments to the docsrs builder in order to properly document cfg's.
# More information: https://docs.rs/about/builds#cross-compiling
[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true
