[package]
name = "leptos_theme"
version = "0.8.0"
edition = "2024"

[dependencies]
leptos = { path = "../../core/lyx-core-leptos/leptos" }
leptos-use = { path = "../../logic/lyx-logic-use" }
serde = { version = "*" }
serde_json = { version = "*" }
wasm-bindgen = { version = "*" }
web-sys = { version = "*" }
