[package]
name = "lyx-platform-src-tauri"
version = "0.0.1"
edition = "2024"

[lib]
name = "lyx-platform-src-tauri"
path = "src/lib.rs"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "0.0.1", features = [] }

[dependencies]
tauri = { version = "0.0.1", features = ["devtools"] }
serde_json = { version = "0.0.1" }
#tauri-plugin-devtools = { version = "0.0.1" }

[features]
#default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
