[package]
name = "leptos_i18n_parser"
version = "0.8.0"
edition = "2024"

[dependencies]


icu_provider = { version = "*" }
icu_locale = { version = "*" }
icu_plurals = { version = "*", features = ["compiled_data"] }
serde = { version = "*", features = ["rc"] }
serde_json = { version = "*" }
serde_yaml = { version = "*" }
toml = { version = "*" }
fixed_decimal = { version = "*", features = ["ryu"] }
json5 = { version = "*" }
quote = { version = "*" }
syn = { version = "*" }
proc-macro2 = { version = "*" }
tinystr = { version = "*" }

[features]
plurals = []
format_datetime = []
format_list = []
format_nums = []
format_currency = ["format_nums"]





