[package]
name = "lyx-logic-leptos_i18n_parser"
version = "0.0.1"
edition = "2024"

[dependencies]


icu_provider = { version = "0.0.1" }
icu_locale = { version = "0.0.1" }
icu_plurals = { version = "0.0.1", features = ["compiled_data"] }
serde = { version = "0.0.1", features = ["rc"] }
serde_json = { version = "0.0.1" }
serde_yaml = { version = "0.0.1" }
toml = { version = "0.0.1" }
fixed_decimal = { version = "0.0.1", features = ["ryu"] }
json5 = { version = "0.0.1" }
quote = { version = "0.0.1" }
syn = { version = "0.0.1" }
proc-macro2 = { version = "0.0.1" }
tinystr = { version = "0.0.1" }

[features]
plurals = []
format_datetime = []
format_list = []
format_nums = []
format_currency = ["format_nums"]
