[package]
name = "lyx-comm-server-signal"
version = "0.8.0"
edition = "2024"

[dependencies]
cfg-if = { version = "*" }
js-sys = { version = "*" }
json-patch = { version = "*" }
leptos = { path = "../../core/lyx-core-leptos/leptos" }
serde = { version = "*", features = ["derive"] }
serde_json = { version = "*" }
wasm-bindgen = { version = "*", default-features = false }
web-sys = { version = "*", features = ["WebSocket", "MessageEvent", "Window"] }
thiserror = { version = "*", optional = true }

# Actix
actix-ws = { version = "*", optional = true }

# Axum
leptos_axum = { version = "*", optional = true, default-features = false, features = ["ws"] }
futures = { version = "*", optional = true, default-features = false }

[features]
default = []
ssr = []
actix = ["dep:actix-ws", "dep:thiserror"]
axum = ["dep:axum", "dep:futures", "dep:thiserror"]










