[package]
name = "leptos_server"
version = "0.8.0"
edition = "2024"
[dependencies]
base64 = { version = "*", default-features = true }
codee = { version = "*", features = ["json_serde"], default-features = true }
hydration_context = { path = "../hydration_context", version = "*" }
reactive_graph = { path = "../reactive_graph", version = "*", features = ["hydration"] }
server_fn = { path = "../server_fn", version = "*" }
tracing = { version = "*", optional = true, default-features = true }
futures = { version = "*", default-features = true }
any_spawner = { path = "../any_spawner", version = "*" }
or_poisoned = { path = "../or_poisoned", version = "*" }
tachys = { path = "../tachys", version = "*", features = ["reactive_graph"], optional = true }
send_wrapper = { version = "*", default-features = true }
serde = { version = "*", default-features = true }
js-sys = { version = "*", default-features = true }
wasm-bindgen = { version = "*", default-features = true }
serde_json = { version = "*", default-features = true }
[features]
ssr = []
hydration = []
miniserde = ["codee/miniserde"]
rkyv = ["codee/rkyv"]
serde-wasm-bindgen = ["codee/json_serde_wasm"]
serde-lite = ["codee/serde_lite"]
tachys = ["dep:tachys"]
tracing = ["dep:tracing"]


[build-dependencies]
rustc_version = "*"





