[package]
name = "tests_ssr"
version = "0.8.0"
edition = "2024"

[dependencies]
any_spawner = { path = "../../leptos/any_spawner", features = ["tokio"] }
expect-test = { version = "*" }
futures = { version = "*" }
leptos = { path = "../../leptos/leptos", features = ["ssr"] }
async-signal = { ${2} }
reactive_graph = { path = "../../leptos/reactive_graph" }











