[package]
name = "hexagonal-architecture"
version = "0.8.0"
edition = "2024"
[lib]
crate-type = ["cdylib", "rlib"]
[dependencies]
leptos = { path = "../leptos", version = "0.8.0", optional = true }
leptos_router = { path = "../../router", version = "*", optional = true }
leptos_axum = { version = "*", optional = true }
console_error_panic_hook = { version = "*" }
leptos_axum = { path = "../../integrations/axum", version = "*", optional = true }
leptos_meta = { path = "../../meta", version = "*", optional = true }
tokio = { version = "*", optional = true, features = ["rt-multi-thread"] }
tower = { version = "*", optional = true }
tower-http = { version = "*", optional = true, features = ["fs"] }
wasm-bindgen = { version = "*" }
thiserror = { version = "*" }
tracing = { version = "*", optional = true }
http = { version = "*" }
mockall = { version = "*" }
cfg-if = { version = "*" }
serde = { version = "*" }
pin-project-lite = { version = "*" }
[features]
config_1 = []
hydrate = ["leptos/hydrate"]
ssr = [
"dep:axum",
"dep:tokio",
"dep:tower",
"dep:tower-http",
"dep:axum",
"leptos/ssr",
"meta/ssr",
"router/ssr",
"dep:tracing" ]
[profile.wasm-release]
opt-level = 'z'
lto = true
codegen-units = 1


[build-dependencies]
rustc_version = "*"






