[package]
name = "leptos_i18n_macro"
version = "0.8.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]


serde = { version = "*", features = ["rc"] }
serde_json = { version = "*" }
proc-macro2 = { version = "*" }
quote = { version = "*" }
syn = { version = "*" }
toml = { version = "*" }
icu_locale = { version = "*", features = ["compiled_data"] }
fixed_decimal = { version = "*", features = ["ryu"] }
leptos_i18n_parser = { path = "../leptos_i18n_parser", optional = true }
tinystr = { version = "*" }
leptos_i18n_codegen = { path = "../leptos_i18n_codegen", optional = true }

[features]
default = []
# nightly = []
islands = ["leptos_i18n_codegen/islands"]
dynamic_load = ["leptos_i18n_codegen/dynamic_load"]
hydrate = ["leptos_i18n_codegen/hydrate"]
csr = ["leptos_i18n_codegen/csr"]
ssr = ["leptos_i18n_codegen/ssr"]
plurals = ["leptos_i18n_parser/plurals", "leptos_i18n_codegen/plurals"]
format_datetime = [
"leptos_i18n_parser/format_datetime",
"leptos_i18n_codegen/format_datetime" ]
format_list = [
"leptos_i18n_parser/format_list",
"leptos_i18n_codegen/format_list" ]
format_nums = [
"leptos_i18n_parser/format_nums",
"leptos_i18n_codegen/format_nums" ]
format_currency = [
"leptos_i18n_parser/format_currency",
"format_nums",
"leptos_i18n_codegen/format_currency" ]
icu_compiled_data = []







