[package]
name = "leptonic"
version = "0.8.0"
edition = "2024"
[build-dependencies]
anyhow = { version = "*" }
cargo_toml = { version = "*" }
lazy_static = { version = "*" }
leptonic-theme = { path = "../leptonic-theme" }
leptos-tiptap-build = { version = "*", optional = true }
[dependencies]
cfg-if = { version = "*" }
indexmap = { version = "*" }
indoc = { version = "*" }
itertools = { version = "*" }
js-sys = { version = "*" }
leptos = { path = "../../../core/lyx-core-leptos/leptos" }
leptos_reactive = { version = "*" }
leptos-tiptap = { version = "*", optional = true }
leptos-use = { path = "../../../logic/lyx-logic-use", features = ["math"] }
icondata = { version = "*" }
leptos_meta = { path = "../../../core/lyx-core-leptos/meta", features = [] }
leptos_router = { path = "../../../core/lyx-core-leptos/router" }
serde = { version = "*" }
serde-wasm-bindgen = { version = "*" }
serde_json = { version = "*" }
strum = { version = "*", features = ["derive"] }
time = { version = "*", features = ["wasm-bindgen", "macros", "serde", "serde-well-known" ] }
tracing = { version = "*" }
uuid = { version = "*", features = ["v4", "v7", "js", "serde"] }
wasm-bindgen = { version = "*" }
wasm-bindgen-futures = { version = "*" }
# TODO: What of all below is really required?
web-sys = { version = "*", features = ["DomRect", "Event", "EventTarget", "ScrollIntoViewOptions", "HtmlFormElement", "HtmlInputElement", "Storage" ] }
educe = { version = "*" }
[dev-dependencies]
wasm-bindgen = { version = "*" }
wasm-bindgen-test = { version = "*" }
web-sys = { version = "*" }
[features]
default = ["hooks"]
csr = ["leptos/csr"]
ssr = ["leptos/ssr", "leptos-use/ssr", "leptos-tiptap?/ssr"]
hydrate = ["leptos/hydrate"]
# Core functionality. Hooks provide low level functions like `usePress` which hande interactions, aria attributes and more.
# Use hooks to build your own set of components.
hooks = []
# Atoms are headless / unstyled Leptos components. All atoms render a single html element and are therefore easy to style.
# Atoms use hooks and allow you to build more complex component without requring too much knowledge about hooks.
atoms = ["hooks"]
# Components provide headless, pre-build, complex functionality, building on atoms.
components = ["atoms"]
# Themes for atoms and components. Copied on build to your applicaiton root directory.
themes = []
# Enables clipboard support. Requires `[build] rustflags = ["--cfg=web_sys_unstable_apis"]` in your cargo.toml.
clipboard = ["components", "web-sys/Clipboard"]
# Enables tiptap editor support. Tiptap related JS files will be copied to your proect directory when running a build.
tiptap = ["components", "dep:leptos-tiptap", "dep:leptos-tiptap-build"]
full = ["hooks", "atoms", "components", "clipboard", "tiptap"]
nightly = ["leptos/nightly"]
# Disable the build script when running on docs.rs
docsrs = []











