[package]
name = "lyx-ui-leptonic"
version = "0.0.1"
edition = "2024"
[build-dependencies]
anyhow = { version = "0.0.1" }
cargo_toml = { version = "0.0.1" }
lazy_static = { version = "0.0.1" }
leptonic-theme = { path = "../leptonic-theme", version = "0.0.1" }
leptos-tiptap-build = { version = "0.0.1", optional = true }
[dependencies]
cfg-if = { version = "0.0.1" }
indexmap = { version = "0.0.1" }
indoc = { version = "0.0.1" }
itertools = { version = "0.0.1" }
js-sys = { version = "0.0.1" }
lyx-core-leptos = { path = "../../../core/lyx-core-leptos/leptos", version = "0.0.1" }
leptos_reactive = { version = "0.0.1" }
leptos-tiptap = { version = "0.0.1", optional = true }
lyx-logic-use = { path = "../../../logic/lyx-logic-use", version = "0.0.1", features = ["math"] }
icondata = { version = "0.0.1" }
lyx-core-meta = { path = "../../../core/lyx-core-leptos/meta", version = "0.0.1", features = [] }
lyx-core-router = { path = "../../../core/lyx-core-leptos/router", version = "0.0.1" }
serde = { version = "0.0.1" }
serde-wasm-bindgen = { version = "0.0.1" }
serde_json = { version = "0.0.1" }
strum = { version = "0.0.1", features = ["derive"] }
time = { version = "0.0.1", features = ["wasm-bindgen", "macros", "serde", "serde-well-known" ] }
tracing = { version = "0.0.1" }
uuid = { version = "0.0.1", features = ["v4", "v7", "js", "serde"] }
wasm-bindgen = { version = "0.0.1" }
wasm-bindgen-futures = { version = "0.0.1" }
# TODO: What of all below is really required?
web-sys = { version = "0.0.1", features = ["DomRect", "Event", "EventTarget", "ScrollIntoViewOptions", "HtmlFormElement", "HtmlInputElement", "Storage" ] }
educe = { version = "0.0.1" }
[dev-dependencies]
wasm-bindgen = { version = "0.0.1" }
wasm-bindgen-test = { version = "0.0.1" }
web-sys = { version = "0.0.1" }
[features]
default = ["hooks"]
csr = ["lyx-core-leptos/csr"]
ssr = ["lyx-core-leptos/ssr", "lyx-logic-use/ssr", "leptos-tiptap?/ssr"]
hydrate = ["lyx-core-leptos/hydrate"]
# Core functionality. Hooks provide low level functions like `usePress` which hande interactions, aria attributes and more.
# Use hooks to build your own set of components.
hooks = []
# Atoms are headless / unstyled Leptos components. All atoms render a single html element and are therefore easy to style.
# Atoms use hooks and allow you to build more complex component without requring too much knowledge about hooks.
atoms = ["hooks"]
# Components provide headless, pre-build, complex functionality, building on atoms.
components = ["atoms"]
# Themes for atoms and components. Copied on build to your applicaiton root directory.
themes = []
# Enables clipboard support. Requires `[build] rustflags = ["--cfg=web_sys_unstable_apis"]` in your cargo.toml.
clipboard = ["components", "web-sys/Clipboard"]
# Enables tiptap editor support. Tiptap related JS files will be copied to your proect directory when running a build.
tiptap = ["components", "dep:leptos-tiptap", "dep:leptos-tiptap-build"]
full = ["hooks", "atoms", "components", "clipboard", "tiptap"]
nightly = ["lyx-core-leptos/nightly"]
# Disable the build script when running on docs.rs
docsrs = []
