[package]
name = "lyxal_revision-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
lyxal_revision = { path = ".." }

[[bin]]
name = "deserialize_fuzzer"
path = "deserialize_fuzzer.rs"
test = false
doc = false

# Cette section isole le projet de fuzzing du workspace parent
[workspace]