[package]
name = "lyx-ui-foundations-leptos"
version = "0.8.0"
edition = "2024"

[features]
default = []
icons = ["dep:lyx-ui-foundations-leptos", "lyx-ui-foundations-leptos/all-icons"]

[dependencies]

leptos = { path = "../../../../core/lyx-core-leptos/leptos", features = ["csr"] }

lyx-ui-foundations-leptos = { path = "../../packages/leptos", optional = true }










