[package]
name = "lyx-ui-foundations-book-examples"
version = "0.8.0"
edition = "2024"

[features]
default = ["arrow", "flip", "placement", "shift", "size", "virtual"]
arrow = []
flip = []
placement = []
shift = []
size = []
virtual = []

[dependencies]

convert_case = { version = "*" }

leptos = { path = "../../../core/lyx-core-leptos/leptos", features = ["csr"] }
tailwind_fuse = { path = "../../lyx-found-tailwind/fuse" }










