-- Batch 12: 200 traductions Lyxal (5 langues)

-- Merge V2
RELATE i18n_key:service_mergev2_name->translation->language:fr SET text = "Merge V2";
RELATE i18n_key:service_mergev2_name->translation->language:en SET text = "Merge V2";
RELATE i18n_key:service_mergev2_name->translation->language:it SET text = "Merge V2";
RELATE i18n_key:service_mergev2_name->translation->language:de SET text = "Merge V2";
RELATE i18n_key:service_mergev2_name->translation->language:es SET text = "Merge V2";
RELATE i18n_key:service_mergev2_desc->translation->language:fr SET text = "Service Merge V2 pour automatisation";
RELATE i18n_key:service_mergev2_desc->translation->language:en SET text = "Merge V2 service for automation";
RELATE i18n_key:service_mergev2_desc->translation->language:it SET text = "Servizio Merge V2 per automazione";
RELATE i18n_key:service_mergev2_desc->translation->language:de SET text = "Merge V2-Dienst für Automatisierung";
RELATE i18n_key:service_mergev2_desc->translation->language:es SET text = "Servicio Merge V2 para automatización";

-- Merge V3
RELATE i18n_key:service_mergev3_name->translation->language:fr SET text = "Merge V3";
RELATE i18n_key:service_mergev3_name->translation->language:en SET text = "Merge V3";
RELATE i18n_key:service_mergev3_name->translation->language:it SET text = "Merge V3";
RELATE i18n_key:service_mergev3_name->translation->language:de SET text = "Merge V3";
RELATE i18n_key:service_mergev3_name->translation->language:es SET text = "Merge V3";
RELATE i18n_key:service_mergev3_desc->translation->language:fr SET text = "Service Merge V3 pour automatisation";
RELATE i18n_key:service_mergev3_desc->translation->language:en SET text = "Merge V3 service for automation";
RELATE i18n_key:service_mergev3_desc->translation->language:it SET text = "Servizio Merge V3 per automazione";
RELATE i18n_key:service_mergev3_desc->translation->language:de SET text = "Merge V3-Dienst für Automatisierung";
RELATE i18n_key:service_mergev3_desc->translation->language:es SET text = "Servicio Merge V3 para automatización";

-- Message Bird
RELATE i18n_key:service_messagebird_name->translation->language:fr SET text = "Message Bird";
RELATE i18n_key:service_messagebird_name->translation->language:en SET text = "Message Bird";
RELATE i18n_key:service_messagebird_name->translation->language:it SET text = "Message Bird";
RELATE i18n_key:service_messagebird_name->translation->language:de SET text = "Message Bird";
RELATE i18n_key:service_messagebird_name->translation->language:es SET text = "Message Bird";
RELATE i18n_key:service_messagebird_desc->translation->language:fr SET text = "Service Message Bird pour automatisation";
RELATE i18n_key:service_messagebird_desc->translation->language:en SET text = "Message Bird service for automation";
RELATE i18n_key:service_messagebird_desc->translation->language:it SET text = "Servizio Message Bird per automazione";
RELATE i18n_key:service_messagebird_desc->translation->language:de SET text = "Message Bird-Dienst für Automatisierung";
RELATE i18n_key:service_messagebird_desc->translation->language:es SET text = "Servicio Message Bird para automatización";

-- Metabase
RELATE i18n_key:service_metabase_name->translation->language:fr SET text = "Metabase";
RELATE i18n_key:service_metabase_name->translation->language:en SET text = "Metabase";
RELATE i18n_key:service_metabase_name->translation->language:it SET text = "Metabase";
RELATE i18n_key:service_metabase_name->translation->language:de SET text = "Metabase";
RELATE i18n_key:service_metabase_name->translation->language:es SET text = "Metabase";
RELATE i18n_key:service_metabase_desc->translation->language:fr SET text = "Service Metabase pour automatisation";
RELATE i18n_key:service_metabase_desc->translation->language:en SET text = "Metabase service for automation";
RELATE i18n_key:service_metabase_desc->translation->language:it SET text = "Servizio Metabase per automazione";
RELATE i18n_key:service_metabase_desc->translation->language:de SET text = "Metabase-Dienst für Automatisierung";
RELATE i18n_key:service_metabase_desc->translation->language:es SET text = "Servicio Metabase para automatización";

-- Azure Cosmos Db
RELATE i18n_key:service_azurecosmosdb_name->translation->language:fr SET text = "Azure Cosmos Db";
RELATE i18n_key:service_azurecosmosdb_name->translation->language:en SET text = "Azure Cosmos Db";
RELATE i18n_key:service_azurecosmosdb_name->translation->language:it SET text = "Azure Cosmos Db";
RELATE i18n_key:service_azurecosmosdb_name->translation->language:de SET text = "Azure Cosmos Db";
RELATE i18n_key:service_azurecosmosdb_name->translation->language:es SET text = "Azure Cosmos Db";
RELATE i18n_key:service_azurecosmosdb_desc->translation->language:fr SET text = "Service Azure Cosmos Db pour automatisation";
RELATE i18n_key:service_azurecosmosdb_desc->translation->language:en SET text = "Azure Cosmos Db service for automation";
RELATE i18n_key:service_azurecosmosdb_desc->translation->language:it SET text = "Servizio Azure Cosmos Db per automazione";
RELATE i18n_key:service_azurecosmosdb_desc->translation->language:de SET text = "Azure Cosmos Db-Dienst für Automatisierung";
RELATE i18n_key:service_azurecosmosdb_desc->translation->language:es SET text = "Servicio Azure Cosmos Db para automatización";

-- Microsoft Dynamics Crm
RELATE i18n_key:service_microsoftdynamicscrm_name->translation->language:fr SET text = "Microsoft Dynamics Crm";
RELATE i18n_key:service_microsoftdynamicscrm_name->translation->language:en SET text = "Microsoft Dynamics Crm";
RELATE i18n_key:service_microsoftdynamicscrm_name->translation->language:it SET text = "Microsoft Dynamics Crm";
RELATE i18n_key:service_microsoftdynamicscrm_name->translation->language:de SET text = "Microsoft Dynamics Crm";
RELATE i18n_key:service_microsoftdynamicscrm_name->translation->language:es SET text = "Microsoft Dynamics Crm";
RELATE i18n_key:service_microsoftdynamicscrm_desc->translation->language:fr SET text = "Service Microsoft Dynamics Crm pour automatisation";
RELATE i18n_key:service_microsoftdynamicscrm_desc->translation->language:en SET text = "Microsoft Dynamics Crm service for automation";
RELATE i18n_key:service_microsoftdynamicscrm_desc->translation->language:it SET text = "Servizio Microsoft Dynamics Crm per automazione";
RELATE i18n_key:service_microsoftdynamicscrm_desc->translation->language:de SET text = "Microsoft Dynamics Crm-Dienst für Automatisierung";
RELATE i18n_key:service_microsoftdynamicscrm_desc->translation->language:es SET text = "Servicio Microsoft Dynamics Crm para automatización";

-- Microsoft Entra
RELATE i18n_key:service_microsoftentra_name->translation->language:fr SET text = "Microsoft Entra";
RELATE i18n_key:service_microsoftentra_name->translation->language:en SET text = "Microsoft Entra";
RELATE i18n_key:service_microsoftentra_name->translation->language:it SET text = "Microsoft Entra";
RELATE i18n_key:service_microsoftentra_name->translation->language:de SET text = "Microsoft Entra";
RELATE i18n_key:service_microsoftentra_name->translation->language:es SET text = "Microsoft Entra";
RELATE i18n_key:service_microsoftentra_desc->translation->language:fr SET text = "Service Microsoft Entra pour automatisation";
RELATE i18n_key:service_microsoftentra_desc->translation->language:en SET text = "Microsoft Entra service for automation";
RELATE i18n_key:service_microsoftentra_desc->translation->language:it SET text = "Servizio Microsoft Entra per automazione";
RELATE i18n_key:service_microsoftentra_desc->translation->language:de SET text = "Microsoft Entra-Dienst für Automatisierung";
RELATE i18n_key:service_microsoftentra_desc->translation->language:es SET text = "Servicio Microsoft Entra para automatización";

-- Microsoft Excel
RELATE i18n_key:service_microsoftexcel_name->translation->language:fr SET text = "Microsoft Excel";
RELATE i18n_key:service_microsoftexcel_name->translation->language:en SET text = "Microsoft Excel";
RELATE i18n_key:service_microsoftexcel_name->translation->language:it SET text = "Microsoft Excel";
RELATE i18n_key:service_microsoftexcel_name->translation->language:de SET text = "Microsoft Excel";
RELATE i18n_key:service_microsoftexcel_name->translation->language:es SET text = "Microsoft Excel";
RELATE i18n_key:service_microsoftexcel_desc->translation->language:fr SET text = "Service Microsoft Excel pour automatisation";
RELATE i18n_key:service_microsoftexcel_desc->translation->language:en SET text = "Microsoft Excel service for automation";
RELATE i18n_key:service_microsoftexcel_desc->translation->language:it SET text = "Servizio Microsoft Excel per automazione";
RELATE i18n_key:service_microsoftexcel_desc->translation->language:de SET text = "Microsoft Excel-Dienst für Automatisierung";
RELATE i18n_key:service_microsoftexcel_desc->translation->language:es SET text = "Servicio Microsoft Excel para automatización";

-- Microsoft Excel V1
RELATE i18n_key:service_microsoftexcelv1_name->translation->language:fr SET text = "Microsoft Excel V1";
RELATE i18n_key:service_microsoftexcelv1_name->translation->language:en SET text = "Microsoft Excel V1";
RELATE i18n_key:service_microsoftexcelv1_name->translation->language:it SET text = "Microsoft Excel V1";
RELATE i18n_key:service_microsoftexcelv1_name->translation->language:de SET text = "Microsoft Excel V1";
RELATE i18n_key:service_microsoftexcelv1_name->translation->language:es SET text = "Microsoft Excel V1";
RELATE i18n_key:service_microsoftexcelv1_desc->translation->language:fr SET text = "Service Microsoft Excel V1 pour automatisation";
RELATE i18n_key:service_microsoftexcelv1_desc->translation->language:en SET text = "Microsoft Excel V1 service for automation";
RELATE i18n_key:service_microsoftexcelv1_desc->translation->language:it SET text = "Servizio Microsoft Excel V1 per automazione";
RELATE i18n_key:service_microsoftexcelv1_desc->translation->language:de SET text = "Microsoft Excel V1-Dienst für Automatisierung";
RELATE i18n_key:service_microsoftexcelv1_desc->translation->language:es SET text = "Servicio Microsoft Excel V1 para automatización";

-- Microsoft Excel V2
RELATE i18n_key:service_microsoftexcelv2_name->translation->language:fr SET text = "Microsoft Excel V2";
RELATE i18n_key:service_microsoftexcelv2_name->translation->language:en SET text = "Microsoft Excel V2";
RELATE i18n_key:service_microsoftexcelv2_name->translation->language:it SET text = "Microsoft Excel V2";
RELATE i18n_key:service_microsoftexcelv2_name->translation->language:de SET text = "Microsoft Excel V2";
RELATE i18n_key:service_microsoftexcelv2_name->translation->language:es SET text = "Microsoft Excel V2";
RELATE i18n_key:service_microsoftexcelv2_desc->translation->language:fr SET text = "Service Microsoft Excel V2 pour automatisation";
RELATE i18n_key:service_microsoftexcelv2_desc->translation->language:en SET text = "Microsoft Excel V2 service for automation";
RELATE i18n_key:service_microsoftexcelv2_desc->translation->language:it SET text = "Servizio Microsoft Excel V2 per automazione";
RELATE i18n_key:service_microsoftexcelv2_desc->translation->language:de SET text = "Microsoft Excel V2-Dienst für Automatisierung";
RELATE i18n_key:service_microsoftexcelv2_desc->translation->language:es SET text = "Servicio Microsoft Excel V2 para automatización";

-- Microsoft Graph Security
RELATE i18n_key:service_microsoftgraphsecurity_name->translation->language:fr SET text = "Microsoft Graph Security";
RELATE i18n_key:service_microsoftgraphsecurity_name->translation->language:en SET text = "Microsoft Graph Security";
RELATE i18n_key:service_microsoftgraphsecurity_name->translation->language:it SET text = "Microsoft Graph Security";
RELATE i18n_key:service_microsoftgraphsecurity_name->translation->language:de SET text = "Microsoft Graph Security";
RELATE i18n_key:service_microsoftgraphsecurity_name->translation->language:es SET text = "Microsoft Graph Security";
RELATE i18n_key:service_microsoftgraphsecurity_desc->translation->language:fr SET text = "Service Microsoft Graph Security pour automatisation";
RELATE i18n_key:service_microsoftgraphsecurity_desc->translation->language:en SET text = "Microsoft Graph Security service for automation";
RELATE i18n_key:service_microsoftgraphsecurity_desc->translation->language:it SET text = "Servizio Microsoft Graph Security per automazione";
RELATE i18n_key:service_microsoftgraphsecurity_desc->translation->language:de SET text = "Microsoft Graph Security-Dienst für Automatisierung";
RELATE i18n_key:service_microsoftgraphsecurity_desc->translation->language:es SET text = "Servicio Microsoft Graph Security para automatización";

-- Microsoft One Drive
RELATE i18n_key:service_microsoftonedrive_name->translation->language:fr SET text = "Microsoft One Drive";
RELATE i18n_key:service_microsoftonedrive_name->translation->language:en SET text = "Microsoft One Drive";
RELATE i18n_key:service_microsoftonedrive_name->translation->language:it SET text = "Microsoft One Drive";
RELATE i18n_key:service_microsoftonedrive_name->translation->language:de SET text = "Microsoft One Drive";
RELATE i18n_key:service_microsoftonedrive_name->translation->language:es SET text = "Microsoft One Drive";
RELATE i18n_key:service_microsoftonedrive_desc->translation->language:fr SET text = "Service Microsoft One Drive pour automatisation";
RELATE i18n_key:service_microsoftonedrive_desc->translation->language:en SET text = "Microsoft One Drive service for automation";
RELATE i18n_key:service_microsoftonedrive_desc->translation->language:it SET text = "Servizio Microsoft One Drive per automazione";
RELATE i18n_key:service_microsoftonedrive_desc->translation->language:de SET text = "Microsoft One Drive-Dienst für Automatisierung";
RELATE i18n_key:service_microsoftonedrive_desc->translation->language:es SET text = "Servicio Microsoft One Drive para automatización";

-- Microsoft Outlook
RELATE i18n_key:service_microsoftoutlook_name->translation->language:fr SET text = "Microsoft Outlook";
RELATE i18n_key:service_microsoftoutlook_name->translation->language:en SET text = "Microsoft Outlook";
RELATE i18n_key:service_microsoftoutlook_name->translation->language:it SET text = "Microsoft Outlook";
RELATE i18n_key:service_microsoftoutlook_name->translation->language:de SET text = "Microsoft Outlook";
RELATE i18n_key:service_microsoftoutlook_name->translation->language:es SET text = "Microsoft Outlook";
RELATE i18n_key:service_microsoftoutlook_desc->translation->language:fr SET text = "Service Microsoft Outlook pour automatisation";
RELATE i18n_key:service_microsoftoutlook_desc->translation->language:en SET text = "Microsoft Outlook service for automation";
RELATE i18n_key:service_microsoftoutlook_desc->translation->language:it SET text = "Servizio Microsoft Outlook per automazione";
RELATE i18n_key:service_microsoftoutlook_desc->translation->language:de SET text = "Microsoft Outlook-Dienst für Automatisierung";
RELATE i18n_key:service_microsoftoutlook_desc->translation->language:es SET text = "Servicio Microsoft Outlook para automatización";

-- Microsoft Outlook V1
RELATE i18n_key:service_microsoftoutlookv1_name->translation->language:fr SET text = "Microsoft Outlook V1";
RELATE i18n_key:service_microsoftoutlookv1_name->translation->language:en SET text = "Microsoft Outlook V1";
RELATE i18n_key:service_microsoftoutlookv1_name->translation->language:it SET text = "Microsoft Outlook V1";
RELATE i18n_key:service_microsoftoutlookv1_name->translation->language:de SET text = "Microsoft Outlook V1";
RELATE i18n_key:service_microsoftoutlookv1_name->translation->language:es SET text = "Microsoft Outlook V1";
RELATE i18n_key:service_microsoftoutlookv1_desc->translation->language:fr SET text = "Service Microsoft Outlook V1 pour automatisation";
RELATE i18n_key:service_microsoftoutlookv1_desc->translation->language:en SET text = "Microsoft Outlook V1 service for automation";
RELATE i18n_key:service_microsoftoutlookv1_desc->translation->language:it SET text = "Servizio Microsoft Outlook V1 per automazione";
RELATE i18n_key:service_microsoftoutlookv1_desc->translation->language:de SET text = "Microsoft Outlook V1-Dienst für Automatisierung";
RELATE i18n_key:service_microsoftoutlookv1_desc->translation->language:es SET text = "Servicio Microsoft Outlook V1 para automatización";

-- Microsoft Outlook V2
RELATE i18n_key:service_microsoftoutlookv2_name->translation->language:fr SET text = "Microsoft Outlook V2";
RELATE i18n_key:service_microsoftoutlookv2_name->translation->language:en SET text = "Microsoft Outlook V2";
RELATE i18n_key:service_microsoftoutlookv2_name->translation->language:it SET text = "Microsoft Outlook V2";
RELATE i18n_key:service_microsoftoutlookv2_name->translation->language:de SET text = "Microsoft Outlook V2";
RELATE i18n_key:service_microsoftoutlookv2_name->translation->language:es SET text = "Microsoft Outlook V2";
RELATE i18n_key:service_microsoftoutlookv2_desc->translation->language:fr SET text = "Service Microsoft Outlook V2 pour automatisation";
RELATE i18n_key:service_microsoftoutlookv2_desc->translation->language:en SET text = "Microsoft Outlook V2 service for automation";
RELATE i18n_key:service_microsoftoutlookv2_desc->translation->language:it SET text = "Servizio Microsoft Outlook V2 per automazione";
RELATE i18n_key:service_microsoftoutlookv2_desc->translation->language:de SET text = "Microsoft Outlook V2-Dienst für Automatisierung";
RELATE i18n_key:service_microsoftoutlookv2_desc->translation->language:es SET text = "Servicio Microsoft Outlook V2 para automatización";

-- Microsoft Share Point
RELATE i18n_key:service_microsoftsharepoint_name->translation->language:fr SET text = "Microsoft Share Point";
RELATE i18n_key:service_microsoftsharepoint_name->translation->language:en SET text = "Microsoft Share Point";
RELATE i18n_key:service_microsoftsharepoint_name->translation->language:it SET text = "Microsoft Share Point";
RELATE i18n_key:service_microsoftsharepoint_name->translation->language:de SET text = "Microsoft Share Point";
RELATE i18n_key:service_microsoftsharepoint_name->translation->language:es SET text = "Microsoft Share Point";
RELATE i18n_key:service_microsoftsharepoint_desc->translation->language:fr SET text = "Service Microsoft Share Point pour automatisation";
RELATE i18n_key:service_microsoftsharepoint_desc->translation->language:en SET text = "Microsoft Share Point service for automation";
RELATE i18n_key:service_microsoftsharepoint_desc->translation->language:it SET text = "Servizio Microsoft Share Point per automazione";
RELATE i18n_key:service_microsoftsharepoint_desc->translation->language:de SET text = "Microsoft Share Point-Dienst für Automatisierung";
RELATE i18n_key:service_microsoftsharepoint_desc->translation->language:es SET text = "Servicio Microsoft Share Point para automatización";

-- Microsoft Sql
RELATE i18n_key:service_microsoftsql_name->translation->language:fr SET text = "Microsoft Sql";
RELATE i18n_key:service_microsoftsql_name->translation->language:en SET text = "Microsoft Sql";
RELATE i18n_key:service_microsoftsql_name->translation->language:it SET text = "Microsoft Sql";
RELATE i18n_key:service_microsoftsql_name->translation->language:de SET text = "Microsoft Sql";
RELATE i18n_key:service_microsoftsql_name->translation->language:es SET text = "Microsoft Sql";
RELATE i18n_key:service_microsoftsql_desc->translation->language:fr SET text = "Service Microsoft Sql pour automatisation";
RELATE i18n_key:service_microsoftsql_desc->translation->language:en SET text = "Microsoft Sql service for automation";
RELATE i18n_key:service_microsoftsql_desc->translation->language:it SET text = "Servizio Microsoft Sql per automazione";
RELATE i18n_key:service_microsoftsql_desc->translation->language:de SET text = "Microsoft Sql-Dienst für Automatisierung";
RELATE i18n_key:service_microsoftsql_desc->translation->language:es SET text = "Servicio Microsoft Sql para automatización";

-- Azure Storage
RELATE i18n_key:service_azurestorage_name->translation->language:fr SET text = "Azure Storage";
RELATE i18n_key:service_azurestorage_name->translation->language:en SET text = "Azure Storage";
RELATE i18n_key:service_azurestorage_name->translation->language:it SET text = "Azure Storage";
RELATE i18n_key:service_azurestorage_name->translation->language:de SET text = "Azure Storage";
RELATE i18n_key:service_azurestorage_name->translation->language:es SET text = "Azure Storage";
RELATE i18n_key:service_azurestorage_desc->translation->language:fr SET text = "Service Azure Storage pour automatisation";
RELATE i18n_key:service_azurestorage_desc->translation->language:en SET text = "Azure Storage service for automation";
RELATE i18n_key:service_azurestorage_desc->translation->language:it SET text = "Servizio Azure Storage per automazione";
RELATE i18n_key:service_azurestorage_desc->translation->language:de SET text = "Azure Storage-Dienst für Automatisierung";
RELATE i18n_key:service_azurestorage_desc->translation->language:es SET text = "Servicio Azure Storage para automatización";

-- Microsoft Teams
RELATE i18n_key:service_microsoftteams_name->translation->language:fr SET text = "Microsoft Teams";
RELATE i18n_key:service_microsoftteams_name->translation->language:en SET text = "Microsoft Teams";
RELATE i18n_key:service_microsoftteams_name->translation->language:it SET text = "Microsoft Teams";
RELATE i18n_key:service_microsoftteams_name->translation->language:de SET text = "Microsoft Teams";
RELATE i18n_key:service_microsoftteams_name->translation->language:es SET text = "Microsoft Teams";
RELATE i18n_key:service_microsoftteams_desc->translation->language:fr SET text = "Service Microsoft Teams pour automatisation";
RELATE i18n_key:service_microsoftteams_desc->translation->language:en SET text = "Microsoft Teams service for automation";
RELATE i18n_key:service_microsoftteams_desc->translation->language:it SET text = "Servizio Microsoft Teams per automazione";
RELATE i18n_key:service_microsoftteams_desc->translation->language:de SET text = "Microsoft Teams-Dienst für Automatisierung";
RELATE i18n_key:service_microsoftteams_desc->translation->language:es SET text = "Servicio Microsoft Teams para automatización";

-- Microsoft Teams V1
RELATE i18n_key:service_microsoftteamsv1_name->translation->language:fr SET text = "Microsoft Teams V1";
RELATE i18n_key:service_microsoftteamsv1_name->translation->language:en SET text = "Microsoft Teams V1";
RELATE i18n_key:service_microsoftteamsv1_name->translation->language:it SET text = "Microsoft Teams V1";
RELATE i18n_key:service_microsoftteamsv1_name->translation->language:de SET text = "Microsoft Teams V1";
RELATE i18n_key:service_microsoftteamsv1_name->translation->language:es SET text = "Microsoft Teams V1";
RELATE i18n_key:service_microsoftteamsv1_desc->translation->language:fr SET text = "Service Microsoft Teams V1 pour automatisation";
RELATE i18n_key:service_microsoftteamsv1_desc->translation->language:en SET text = "Microsoft Teams V1 service for automation";
RELATE i18n_key:service_microsoftteamsv1_desc->translation->language:it SET text = "Servizio Microsoft Teams V1 per automazione";
RELATE i18n_key:service_microsoftteamsv1_desc->translation->language:de SET text = "Microsoft Teams V1-Dienst für Automatisierung";
RELATE i18n_key:service_microsoftteamsv1_desc->translation->language:es SET text = "Servicio Microsoft Teams V1 para automatización";

