[package]
name = "lyx-viz-leptos-leaflet"
version = "0.8.0"
edition = "2024"
[dependencies]
js-sys = { version = "*" }
leaflet = { version = "*" }
leptos = { path = "../core/lyx-core-leptos/leptos" }
leptos_meta = { path = "../core/lyx-core-leptos/meta" }
paste = { version = "*" }
serde-wasm-bindgen = { version = "*" }
tracing = { version = "*" }
wasm-bindgen = { version = "*" }
web-sys = { version = "*", features = ["HtmlDivElement", "HtmlElement", "console" ] }
[features]
csr = ["leptos/csr"]
hydrate = ["leptos/hydrate"]
ssr = ["leptos/ssr", "leptos_meta/ssr"]










