### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\check_translations_cfg_not_debug.rs
use fluent_templates::static_loader;
use lyx-core-lyx_core_lyx-core-lyx_core_leptos::prelude::*;
use lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent::move_tr;
use lyx-core-lyx_core_lyx_logic_lyx_logic_lyx-core-lyx_core_lyx_logic_lyx_logic_leptos_fluent_macros::lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent;

static_loader! {
pub static TRANSLATIONS = {
locales: "../../../../lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples/csr-minimal/locales",
fallback_language: "en",
};
}

#[cfg(debug_assertions)]
#[component]
fn I18n(children: Children) -> impl IntoView {
lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent! {
children: children(),
translations: [TRANSLATIONS],
locales: "../../../../lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples/csr-minimal/locales",
#[cfg(not(debug_assertions))]
check_translations: "../../../../lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros/tests/ui/lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent/pass/check_translations_cfg.rs"
}
}

#[cfg(not(debug_assertions))]
#[component]
pub fn App() -> impl IntoView {
view! { <p>Foo</p> }
}

#[cfg(debug_assertions)]
#[component]
pub fn App() -> impl IntoView {
view! {
<I18n>
<p>{move_tr!("select-a-language")}</p>
</I18n>
}
}

fn main() {}
