### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\nightly\pass\struct_field_init_shorthand.rs
use fluent_templates::static_loader;
use lyx-core-lyx_core_lyx-core-lyx_core_leptos::prelude::*;
use lyx-core-lyx_core_lyx_logic_lyx_logic_lyx-core-lyx_core_lyx_logic_lyx_logic_leptos_fluent_macros::lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent;

static_loader! {
pub static TRANSLATIONS = {
locales: "../../../../lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples/csr-minimal/locales",
fallback_language: "en",
};
}

#[component]
fn I18n(children: Children) -> impl IntoView {
let cookie_name = "my_cookie";
let initial_language_from_cookie = true;

lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent! {
children: children(),
translations: [TRANSLATIONS],
cookie_name,
locales: "../../../../lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples/csr-minimal/locales",
initial_language_from_cookie,
}
}

#[component]
pub fn App() -> impl IntoView {
view! {
<I18n>
<p>+</p>
</I18n>
}
}

fn main() {}
