[package]
name = "app"
version = "0.8.0"
edition = "2024"

[dependencies]
leptos = { path = "../leptos", version = "0.8.0" }
leptos_meta = { path = "../leptos_meta", version = "*" }
leptos_router = { path = "../leptos_router", version = "*" }
leptos_axum = { version = "*", path = "../../../integrations/axum", optional = true }
axum = { version = "*", optional = true }
axum-extra = { version = "*", optional = true }
reqwest = { version = "*", optional = true }
time = { version = "*", optional = true }
tracing = { version = "*", optional = true }
url = { version = "*", optional = true }
uuid = { version = "*" }
wasm-bindgen = { version = "*", optional = true }
web-sys = { version = "*" }
sqlx = { version = "*", optional = true }

[features]
default = []
hydrate = ["leptos/hydrate", "leptos_meta/hydrate", "leptos_router/hydrate", "dep:wasm-bindgen"]
ssr = ["leptos/ssr", "leptos_meta/ssr", "leptos_router/ssr", "dep:sqlx", "dep:time", "dep:leptos_axum", "dep:axum", "dep:tracing", "dep:reqwest", "dep:url", "dep:axum-extra"]


[build-dependencies]
rustc_version = "*"





