[package]
name = "lyxal_state"
version = "0.1.0"
edition = "2021"

[dependencies]
lyxal_types = { path = "../lyxal_types" }
# On pointe vers les crates du fork SurrealDB
surrealdb-core = { path = "../../surrealdb-3.0.0-beta.2/surrealdb/core", default-features = false, features = ["kv-mem", "kv-lyxalkv"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
leptos = { version = "0.6", features = ["csr"] }
async-trait = "0.1"
tokio = { version = "1.0", features = ["sync"] }


