[package]
name = "app"
version = "0.8.0"
edition = "2024"
[dependencies]
leptos_router = { path = "../core/lyx-core-leptos/router", optional = true }
leptos_meta = { path = "../core/lyx-core-leptos/meta", optional = true }
leptos_i18n = { path = "../../i18n/leptos_i18n", optional = true }
leptos = { path = "../core/lyx-core-leptos/leptos", optional = true }
leptos_axum = { ${2, optional = true }, optional = true }
[features]
default = []
hydrate = ["dep:leptos", "dep:leptos", "leptos/hydrate","dep:leptos_i18n", "dep:leptos_i18n", "leptos_i18n/hydrate"]
ssr = ["dep:leptos", "dep:leptos", "leptos/ssr", "dep:leptos_meta", "dep:leptos_meta", "leptos_meta/ssr", "dep:leptos_router", "dep:leptos_router", "leptos_router/ssr", "dep:leptos_i18n", "dep:leptos_i18n", "leptos_i18n/axum","dep:leptos_axum"]












