-- Seeds pour les villes du pays: ER --

CREATE base_city:er_31888 SET state = base_state:er_an, key.name = i18n_key:i18n_city_er_31888_name, native = 'ኬረን', location = (38.45107000, 15.77792000), timezone = base_timezone:europe_moscow, wikiDataId = 'Q534409';
CREATE base_city:er_31881 SET state = base_state:er_du, key.name = i18n_key:i18n_city_er_31881_name, native = 'ዓዲ ኪህ', location = (39.37722000, 14.84444000), timezone = base_timezone:europe_moscow, wikiDataId = 'Q356811';
CREATE base_city:er_31886 SET state = base_state:er_du, key.name = i18n_key:i18n_city_er_31886_name, native = 'ደክ’እምሃረ', location = (39.04750000, 15.07000000), timezone = base_timezone:europe_moscow, wikiDataId = 'Q1020477';
CREATE base_city:er_31890 SET state = base_state:er_du, key.name = i18n_key:i18n_city_er_31890_name, native = 'ትሑዝ', location = (38.81528000, 14.88722000), timezone = base_timezone:europe_moscow, wikiDataId = 'Q1019356';
CREATE base_city:er_31882 SET state = base_state:er_gb, key.name = i18n_key:i18n_city_er_31882_name, native = 'ኣክ\'ኦርዳት', location = (37.88291000, 15.54798000), timezone = base_timezone:europe_moscow, wikiDataId = 'Q395433';
CREATE base_city:er_31885 SET state = base_state:er_gb, key.name = i18n_key:i18n_city_er_31885_name, native = 'ባረንቱ', location = (37.59067000, 15.10582000), timezone = base_timezone:europe_moscow, wikiDataId = 'Q808100';
CREATE base_city:er_31891 SET state = base_state:er_gb, key.name = i18n_key:i18n_city_er_31891_name, native = 'ተሰኒ', location = (36.65750000, 15.11000000), timezone = base_timezone:europe_moscow, wikiDataId = 'Q1797764';
CREATE base_city:er_31883 SET state = base_state:er_ma, key.name = i18n_key:i18n_city_er_31883_name, native = 'ኣስማራ', location = (38.93184000, 15.33805000), timezone = base_timezone:europe_moscow, wikiDataId = 'Q3642';
CREATE base_city:er_31889 SET state = base_state:er_sk, key.name = i18n_key:i18n_city_er_31889_name, native = 'ማሳዋ', location = (39.47455000, 15.60811000), timezone = base_timezone:europe_moscow, wikiDataId = 'Q275635';
CREATE base_city:er_31884 SET state = base_state:er_dk, key.name = i18n_key:i18n_city_er_31884_name, native = 'ኣሳብ', location = (42.73944000, 13.00917000), timezone = base_timezone:europe_moscow, wikiDataId = 'Q738496';
CREATE base_city:er_31887 SET state = base_state:er_dk, key.name = i18n_key:i18n_city_er_31887_name, native = 'ኤድ', location = (41.69380000, 13.93088000), timezone = base_timezone:europe_moscow, wikiDataId = 'Q523618';
