### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\fail\tr_macros_invalid_types.rs
use lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent::{move_tr, tr};

struct MyStruct(u32);

fn main() {
_ = tr!(1);

_ = move_tr!(MyStruct(1));

_ = tr!(());
}
