-- ===== Batch 26 I18N KEYS (33) =====

CREATE i18n_key:credential_type_kitemaker_api_name SET description = "Kitemaker API";
CREATE i18n_key:credential_type_kitemaker_api_description SET description = "Kitemaker API";
CREATE i18n_key:credential_type_kitemaker_api_tooltip SET description = "Kitemaker API";
CREATE i18n_key:credential_type_ko_bo_toolbox_api_name SET description = "KoBoToolbox API";
CREATE i18n_key:credential_type_ko_bo_toolbox_api_description SET description = "KoBoToolbox API";
CREATE i18n_key:credential_type_ko_bo_toolbox_api_tooltip SET description = "KoBoToolbox API";
CREATE i18n_key:credential_type_ldap_name SET description = "LDAP";
CREATE i18n_key:credential_type_ldap_description SET description = "LDAP";
CREATE i18n_key:credential_type_ldap_tooltip SET description = "LDAP";
CREATE i18n_key:credential_type_line_notify_oauth2_api_name SET description = "LINE Notify OAuth2 API";
CREATE i18n_key:credential_type_line_notify_oauth2_api_description SET description = "LINE Notify OAuth2 API";
CREATE i18n_key:credential_type_line_notify_oauth2_api_tooltip SET description = "LINE Notify OAuth2 API";
CREATE i18n_key:credential_type_lingva_nex_api_name SET description = "Lingvanex API";
CREATE i18n_key:credential_type_lingva_nex_api_description SET description = "Lingvanex API";
CREATE i18n_key:credential_type_lingva_nex_api_tooltip SET description = "Lingvanex API";
CREATE i18n_key:credential_type_linked_in_community_management_oauth2_api_name SET description = "LinkedIn Community Management OAuth2 API";
CREATE i18n_key:credential_type_linked_in_community_management_oauth2_api_description SET description = "LinkedIn Community Management OAuth2 API";
CREATE i18n_key:credential_type_linked_in_community_management_oauth2_api_tooltip SET description = "LinkedIn Community Management OAuth2 API";
CREATE i18n_key:credential_type_linked_in_oauth2_api_name SET description = "LinkedIn OAuth2 API";
CREATE i18n_key:credential_type_linked_in_oauth2_api_description SET description = "LinkedIn OAuth2 API";
CREATE i18n_key:credential_type_linked_in_oauth2_api_tooltip SET description = "LinkedIn OAuth2 API";
CREATE i18n_key:credential_type_lone_scale_api_name SET description = "LoneScale API";
CREATE i18n_key:credential_type_lone_scale_api_description SET description = "LoneScale API";
CREATE i18n_key:credential_type_lone_scale_api_tooltip SET description = "LoneScale API";
CREATE i18n_key:credential_type_magento2_api_name SET description = "Magento 2 API";
CREATE i18n_key:credential_type_magento2_api_description SET description = "Magento 2 API";
CREATE i18n_key:credential_type_magento2_api_tooltip SET description = "Magento 2 API";
CREATE i18n_key:credential_type_mailcheck_api_name SET description = "Mailcheck API";
CREATE i18n_key:credential_type_mailcheck_api_description SET description = "Mailcheck API";
CREATE i18n_key:credential_type_mailcheck_api_tooltip SET description = "Mailcheck API";
CREATE i18n_key:credential_type_mailer_lite_api_name SET description = "MailerLite API";
CREATE i18n_key:credential_type_mailer_lite_api_description SET description = "MailerLite API";
CREATE i18n_key:credential_type_mailer_lite_api_tooltip SET description = "MailerLite API";

