-- Batch 29 I18N KEYS (33)

CREATE i18n_key:credential_type_next_cloud_oauth2_api_name SET description = "NEXT CLOUD OAUTH2 API";
CREATE i18n_key:credential_type_next_cloud_oauth2_api_description SET description = "NEXT CLOUD OAUTH2 API";
CREATE i18n_key:credential_type_next_cloud_oauth2_api_tooltip SET description = "NEXT CLOUD OAUTH2 API";
CREATE i18n_key:credential_type_npm_api_name SET description = "NPM API";
CREATE i18n_key:credential_type_npm_api_description SET description = "NPM API";
CREATE i18n_key:credential_type_npm_api_tooltip SET description = "NPM API";
CREATE i18n_key:credential_type_o_auth1_api_name SET description = "O AUTH1 API";
CREATE i18n_key:credential_type_o_auth1_api_description SET description = "O AUTH1 API";
CREATE i18n_key:credential_type_o_auth1_api_tooltip SET description = "O AUTH1 API";
CREATE i18n_key:credential_type_o_auth2_api_name SET description = "O AUTH2 API";
CREATE i18n_key:credential_type_o_auth2_api_description SET description = "O AUTH2 API";
CREATE i18n_key:credential_type_o_auth2_api_tooltip SET description = "O AUTH2 API";
CREATE i18n_key:credential_type_one_simple_api_name SET description = "ONE SIMPLE API";
CREATE i18n_key:credential_type_one_simple_api_description SET description = "ONE SIMPLE API";
CREATE i18n_key:credential_type_one_simple_api_tooltip SET description = "ONE SIMPLE API";
CREATE i18n_key:credential_type_onfleet_api_name SET description = "ONFLEET API";
CREATE i18n_key:credential_type_onfleet_api_description SET description = "ONFLEET API";
CREATE i18n_key:credential_type_onfleet_api_tooltip SET description = "ONFLEET API";
CREATE i18n_key:credential_type_open_cti_api_name SET description = "OPEN CTI API";
CREATE i18n_key:credential_type_open_cti_api_description SET description = "OPEN CTI API";
CREATE i18n_key:credential_type_open_cti_api_tooltip SET description = "OPEN CTI API";
CREATE i18n_key:credential_type_oracle_db_api_name SET description = "ORACLE DB API";
CREATE i18n_key:credential_type_oracle_db_api_description SET description = "ORACLE DB API";
CREATE i18n_key:credential_type_oracle_db_api_tooltip SET description = "ORACLE DB API";
CREATE i18n_key:credential_type_orbit_api_name SET description = "ORBIT API";
CREATE i18n_key:credential_type_orbit_api_description SET description = "ORBIT API";
CREATE i18n_key:credential_type_orbit_api_tooltip SET description = "ORBIT API";
CREATE i18n_key:credential_type_oura_api_name SET description = "OURA API";
CREATE i18n_key:credential_type_oura_api_description SET description = "OURA API";
CREATE i18n_key:credential_type_oura_api_tooltip SET description = "OURA API";
CREATE i18n_key:credential_type_paddle_api_name SET description = "PADDLE API";
CREATE i18n_key:credential_type_paddle_api_description SET description = "PADDLE API";
CREATE i18n_key:credential_type_paddle_api_tooltip SET description = "PADDLE API";

