[package]
name = "app-1"
version = "0.8.0"
edition = "2024"
[lib]
crate-type = ["cdylib", "rlib"]
[dependencies]
console_error_panic_hook = { version = "*" }
leptos_meta = { path = "../../../meta", version = "*", optional = true }
leptos_router = { path = "../../../router", version = "*", optional = true }
tower = { version = "*", optional = true }
tower-http = { version = "*", optional = true, features = ["fs", "trace"] }
wasm-bindgen = { version = "*" }
thiserror = { version = "*" }
tracing = { version = "*", optional = true }
http = { version = "*" }
leptos_axum = { version = "*", optional = true }
leptos = { path = "../leptos", version = "*", optional = true }
leptos_axum = { path = "../../../integrations/axum", version = "*", optional = true }
tokio = { version = "*", optional = true, features = ["rt-multi-thread"] }
shared-server = { version = "*", default-features = false }
shared-server-2 = { path = "../shared-server-2", version = "*", optional = true }
tracing-subscriber = { version = "*", features = ["env-filter"] }
[profile.wasm-release]
opt-level = 'z'
lto = true
codegen-units = 1
[features]
hydrate = [
"leptos/hydrate",
"meta/hydrate",
"router/hydrate",
"shared-server/hydrate",
"shared-server-2/hydrate" ]
ssr = [
"shared-server/ssr",
"shared-server-2/ssr",
"dep:axum",
"dep:tokio",
"dep:tower",
"dep:tower-http",
"dep:axum",
"leptos/ssr",
"meta/ssr",
"router/ssr",
"dep:tracing" ]


[build-dependencies]
rustc_version = "*"






