[package]
name = "lyx-viz-lyx-viz-bevy"
version = "0.0.1"
edition = "2024"
[dependencies]
bevy = { version = "0.0.1", default-features = false }
crossbeam-channel = { version = "0.0.1" }
lyx-core-leptos = { path = "../../core/lyx-core-leptos/leptos", version = "0.0.1" }
lyx-logic-use = { path = "../../logic/lyx-logic-use", version = "0.0.1", features = ["use_raf_fn" ] }
paste = { version = "0.0.1" }
variadics_please = { version = "0.0.1" }
[dev-dependencies]
bevy = { version = "0.0.1", default-features = false, features = ["bevy_window" ] }
[features]
bevy_state = ["bevy/bevy_state"]
