[package]
name = "service_mode"
version = "0.8.0"
edition = "2024"
[lib]
crate-type = ["cdylib", "rlib"]
[dependencies]
axum = { optional = true, version = "0.8.0" }
clap = { optional = true, version = "*", features = ["derive"] }
console_error_panic_hook = { version = "*" }
leptos = { path = "../leptos", version = "*", features = ["tracing"], optional = true }
meta = { path = "../../../../meta", version = "*", optional = true }
axum = { path = "../../", version = "*", optional = true }
router = { path = "../../../../router", version = "*", optional = true }
tokio = { version = "*", optional = true, features = ["rt-multi-thread", "macros", "time" ] }
tower = { optional = true, version = "*" }
tower-http = { optional = true, version = "*", features = ["fs"] }
wasm-bindgen = { version = "*" }
[features]
hydrate = ["leptos/hydrate"]
ssr = [
"dep:axum",
"dep:clap",
"dep:tower",
"dep:tower-http",
"dep:tokio",
"leptos/ssr",
"meta/ssr",
"dep:axum",
"router/ssr" ]
[profile.release]
[profile.wasm-release]
opt-level = 'z'
lto = true
codegen-units = 1
[package.metadata.cargo-all-features]
skip_feature_sets = [["ssr", "hydrate"], []]
[package.metadata.leptos]
output-name = "service_mode"
site-root = { version = "*" }
site-pkg-dir = { version = "*" }
site-addr = { version = "*" }
reload-port = 3001
browserquery = { version = "*" }
watch = false
env = { version = "*" }
bin-features = ["ssr"]
bin-default-features = false
lib-features = ["hydrate"]
lib-default-features = false
lib-profile-release = { version = "*" }


[build-dependencies]
rustc_version = "*"






