[package]
name = "lyx-tool-cli"
version = "0.8.0"
edition = "2024"
# Config for 'cargo dist'

[dependencies]
brotli = { version = "*" }
clap = { version = "*", features = ["derive"] }
serde = { version = "*", features = ["derive"] }
anyhow = { version = "*" }
libflate = { version = "*" }
log = { version = "*" }

lightningcss = { version = "*", features = ["browserslist"] }
flexi_logger = { version = "*" }
tokio = { version = "*", default-features = false, features = ["full"] }
axum = { version = "*", features = ["ws"] }
# not using notify 5.0 because it uses Crossbeam which has an issue with tokio
notify = { version = "*" }
lazy_static = { version = "*" }
which = { version = "*" }
cargo_metadata = { version = "*", features = ["builder"] }
serde_json = { version = "*" }
wasm-bindgen-cli-support = { version = "*" }
ansi_term = { version = "*" }

reqwest = { version = "*", features = ["blocking", "rustls-tls", "json" ], default-features = false }
seahash = { version = "*" }
dirs = { version = "*" }
camino = { version = "*" }
dotenvy = { version = "*" }
itertools = { version = "*" }
derive_more = { version = "*", features = ["display"] }
flate2 = { version = "*" }
zip = { version = "*", default-features = false, features = ["deflate"] }
tar = { version = "*" }
dunce = { version = "*" }
bytes = { version = "*" }
leptos_hot_reload = { path = "../../core/leptos/leptos_hot_reload" }
pathdiff = { version = "*", features = ["camino"] }
semver = { version = "*" }
async-trait = { version = "*" }
md-5 = { version = "*" }
base64ct = { version = "*", features = ["alloc"] }
swc = { version = "*" }
swc_common = { version = "*" }
shlex = { version = "*" }

[dev-dependencies]
insta = { version = "*", features = ["yaml"] }
temp-dir = { version = "*" }

[features]
full_tests = []
no_downloads = []

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = { version = "*" }









