[package]
name = "lyx-core-meilisearch-searchbar"
version = "0.0.1"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
lyx-core-leptos = { path = "../../leptos", version = "0.0.1" }
serde = { version = "0.0.1", features = ["derive"] }
serde_json = "1"
wasm-bindgen = "0.2"
web-sys = { version = "0.0.1", features = ["HtmlInputElement", "HtmlElement", "Window"] }
simple_logger = { version = "0.0.1", optional = true }

[features]
default = []
ssr = ["lyx-core-leptos/ssr", "dep:simple_logger"]
hydrate = ["lyx-core-leptos/hydrate"]
