[package]
name = "leptos-windowing"
version = "0.8.0"
edition = "2024"

[dependencies]


default-struct-builder = { version = "*" }
leptos = { path = "../core/lyx-core-leptos/leptos", optional = true }
leptos-use = { path = "../../use", features = ["element"], optional = true }
reactive_stores = { path = "../core/lyx-core-leptos/reactive_stores" }
serde = { version = "*", features = ["derive"] }
web-sys = { version = "*" }

[features]
ssr = ["leptos-use/ssr", "leptos/ssr"]












