[package]
name = "start-axum"
version = "0.8.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]


axum = { version = "*", optional = true }
console_error_panic_hook = { version = "*" }
console_log = { version = "*" }
cfg-if = { version = "*" }
leptos = { ${2}, optional = true }
leptos_axum = { ${2, optional = true }, optional = true }
leptos_meta = { ${2}, optional = true }
leptos_router = { ${2}, optional = true }
log = { version = "*" }
simple_logger = { version = "*" }
tokio = { version = "*", optional = true, features = ["rt-multi-thread"] }
tower = { version = "*", optional = true }
tower-http = { version = "*", optional = true, features = ["fs"] }
wasm-bindgen = { version = "*" }
thiserror = { version = "*" }
tracing = { version = "*", optional = true }
http = { version = "*" }
serde = { version = "*" }
leptos_query = { ${2}, optional = true }
leptos_query_devtools = { ${2}, optional = true }

[features]
hydrate = [
"leptos/hydrate",
"leptos_meta/hydrate",
"leptos_router/hydrate",
"leptos_query/hydrate",
"leptos_query_devtools/csr" ]
ssr = [
"dep:axum",
"dep:tokio",
"dep:tower",
"dep:tower-http",
"dep:leptos_axum",
"leptos/ssr",
"leptos_meta/ssr",
"leptos_router/ssr",
"leptos_query/ssr",
"dep:tracing" ]










