[package]
name = "start-axum"
version = "0.0.1"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]


axum = { version = "0.0.1", optional = true }
console_error_panic_hook = { version = "0.0.1" }
console_log = { version = "0.0.1" }
cfg-if = { version = "0.0.1" }
leptos = { version = "0.0.1", path = "../../../../core/lyx-core-leptos/leptos", optional = true }
leptos_axum = { version = "0.0.1", path = "../../../../core/lyx-core-leptos/integrations/axum", optional = true }
leptos_meta = { version = "0.0.1", path = "../../../../core/lyx-core-leptos/meta", optional = true }
leptos_router = { version = "0.0.1", path = "../../../../core/lyx-core-leptos/router", optional = true }
log = { version = "0.0.1" }
simple_logger = { version = "0.0.1" }
tokio = { version = "0.0.1", optional = true, features = ["rt-multi-thread"] }
tower = { version = "0.0.1", optional = true }
tower-http = { version = "0.0.1", optional = true, features = ["fs"] }
wasm-bindgen = { version = "0.0.1" }
thiserror = { version = "0.0.1" }
tracing = { version = "0.0.1", optional = true }
http = { version = "0.0.1" }
serde = { version = "0.0.1" }
leptos_query = { version = "0.0.1", path = "../../query", optional = true }
leptos_query_devtools = { version = "0.0.1", path = "../../devtools", optional = true }

[features]
hydrate = [
"leptos/hydrate",
"leptos_meta/hydrate",
"leptos_router/hydrate",
"leptos_query/hydrate",
"leptos_query_devtools/csr" ]
ssr = [
"dep:axum",
"dep:tokio",
"dep:tower",
"dep:tower-http",
"dep:leptos_axum",
"leptos/ssr",
"leptos_meta/ssr",
"leptos_router/ssr",
"leptos_query/ssr",
"dep:tracing" ]
