### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_i18n\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_i18n_parser\src\lib.rs
#![forbid(unsafe_code)]
#![deny(warnings)]
#![allow(clippy::too_many_arguments)]

pub mod formatters;
pub mod parse_locales;
pub mod utils;
pub use parse_locales::error::Error;
