1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx-logic-windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
2: ```rust
3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx-logic-windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
4: 2: ```rust
5: 3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx-logic-windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
6: 4: 2: ```rust
7: 5: 3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx-logic-windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
8: 6: 4: 2: ```rust
9: 7: 5: 3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx-logic-windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
10: 8: 6: 4: 2: ```rust
11: 9: 7: 5: 3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
12: 10: 8: 6: 4: 2: ```rust
13: 11: 9: 7: 5: 3: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
14: 12: 10: 8: 6: 4: ```rust
15: 13: 11: 9: 7: 5: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
16: 14: 12: 10: 8: 6: ```rust
17: 15: 13: 11: 9: 7: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
18: 16: 14: 12: 10: 8: ```rust
19: 17: 15: 13: 11: 9: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
20: 18: 16: 14: 12: 10: ```rust
21: 19: 17: 15: 13: 11: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
22: 20: 18: 16: 14: 12: ```rust
23: 21: 19: 17: 15: 13: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
24: 22: 20: 18: 16: 14: ```rust
25: 23: 21: 19: 17: 15: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
26: 24: 22: 20: 18: 16: ```rust
27: 25: 23: 21: 19: 17: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
28: 26: 24: 22: 20: 18: ```rust
29: 27: 25: 23: 21: 19: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
30: 28: 26: 24: 22: 20: ```rust
31: 29: 27: 25: 23: 21: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
32: 30: 28: 26: 24: 22: ```rust
33: 31: 29: 27: 25: 23: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
34: 32: 30: 28: 26: 24: ```rust
35: 33: 31: 29: 27: 25: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
36: 34: 32: 30: 28: 26: ```rust
37: 35: 33: 31: 29: 27: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
38: 36: 34: 32: 30: 28: ```rust
39: 37: 35: 33: 31: 29: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
40: 38: 36: 34: 32: 30: ```rust
41: 39: 37: 35: 33: 31: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
42: 40: 38: 36: 34: 32: ```rust
43: 41: 39: 37: 35: 33: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
44: 42: 40: 38: 36: 34: ```rust
45: 43: 41: 39: 37: 35: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
46: 44: 42: 40: 38: 36: ```rust
47: 45: 43: 41: 39: 37: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
48: 46: 44: 42: 40: 38: ```rust
49: 47: 45: 43: 41: 39: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
50: 48: 46: 44: 42: 40: ```rust
51: 49: 47: 45: 43: 41: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
52: 50: 48: 46: 44: 42: ```rust
53: 51: 49: 47: 45: 43: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
54: 52: 50: 48: 46: 44: ```rust
55: 53: 51: 49: 47: 45: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
56: 54: 52: 50: 48: 46: ```rust
57: 55: 53: 51: 49: 47: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
58: 56: 54: 52: 50: 48: ```rust
59: 57: 55: 53: 51: 49: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
60: 58: 56: 54: 52: 50: ```rust
61: 59: 57: 55: 53: 51: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
62: 60: 58: 56: 54: 52: ```rust
63: 61: 59: 57: 55: 53: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
64: 62: 60: 58: 56: 54: ```rust
65: 63: 61: 59: 57: 55: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
66: 64: 62: 60: 58: 56: ```rust
67: 65: 63: 61: 59: 57: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
68: 66: 64: 62: 60: 58: ```rust
69: 67: 65: 63: 61: 59: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
70: 68: 66: 64: 62: 60: ```rust
71: 69: 67: 65: 63: 61: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
72: 70: 68: 66: 64: 62: ```rust
73: 71: 69: 67: 65: 63: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
74: 72: 70: 68: 66: 64: ```rust
75: 73: 71: 69: 67: 65: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
76: 74: 72: 70: 68: 66: ```rust
77: 75: 73: 71: 69: 67: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
78: 76: 74: 72: 70: 68: ```rust
79: 77: 75: 73: 71: 69: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
80: 78: 76: 74: 72: 70: ```rust
81: 79: 77: 75: 73: 71: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
82: 80: 78: 76: 74: 72: ```rust
83: 81: 79: 77: 75: 73: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
84: 82: 80: 78: 76: 74: ```rust
85: 83: 81: 79: 77: 75: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
86: 84: 82: 80: 78: 76: ```rust
87: 85: 83: 81: 79: 77: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
88: 86: 84: 82: 80: 78: ```rust
89: 87: 85: 83: 81: 79: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
90: 88: 86: 84: 82: 80: ```rust
91: 89: 87: 85: 83: 81: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
92: 90: 88: 86: 84: 82: ```rust
93: 91: 89: 87: 85: 83: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
94: 92: 90: 88: 86: 84: ```rust
95: 93: 91: 89: 87: 85: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
96: 94: 92: 90: 88: 86: ```rust
97: 95: 93: 91: 89: 87: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
98: 96: 94: 92: 90: 88: ```rust
99: 97: 95: 93: 91: 89: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
100: 98: 96: 94: 92: 90: ```rust
101: 99: 97: 95: 93: 91: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
102: 100: 98: 96: 94: 92: ```rust
103: 101: 99: 97: 95: 93: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
104: 102: 100: 98: 96: 94: ```rust
105: 103: 101: 99: 97: 95: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
106: 104: 102: 100: 98: 96: ```rust
107: 105: 103: 101: 99: 97: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
108: 106: 104: 102: 100: 98: ```rust
109: 107: 105: 103: 101: 99: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.rs
110: 108: 106: 104: 102: 100: ```rust
111: 109: 107: 105: 103: 101: use lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_leptos::prelude::*;
112: 110: 108: 106: 104: 102: use lyx-core-lyx_core_lyx-core-meta::*;
113: 111: 109: 107: 105: 103: use lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_pagination::*;
114: 112: 110: 108: 106: 104: use lyx-core-lyx_core_lyx-core-router::components::{FlatRoutes, Route, Router, RoutingProgress};
115: 113: 111: 109: 107: 105: use lyx-core-lyx_core_lyx-core-router::path;
116: 114: 112: 110: 108: 106: 
117: 115: 113: 111: 109: 107: use std::sync::Arc;
118: 116: 114: 112: 110: 108: use std::time::Duration;
119: 117: 115: 113: 111: 109: 
120: 118: 116: 114: 112: 110: use crate::loader::{Customer, CustomerLoader, CustomerQuery};
121: 119: 117: 115: 113: 111: 
122: 120: 118: 116: 114: 112: #[component]
123: 121: 119: 117: 115: 113: pub fn App() -> impl IntoView {
124: 122: 120: 118: 116: 114:     // Provides context that manages stylesheets, titles, meta tags, etc.
125: 123: 121: 119: 117: 115:     provide_meta_context();
126: 124: 122: 120: 118: 116:     let (is_routing, set_is_routing) = signal(false);
127: 125: 123: 121: 119: 117: 
128: 126: 124: 122: 120: 118:     view! {
129: 127: 125: 123: 121: 119:         <Stylesheet id="lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_leptos" href="/pkg/lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_serverfn-sqlx.css" />
130: 128: 126: 124: 122: 120:         <Title text="Welcome to Leptos Struct Table" />
131: 129: 127: 125: 123: 121: 
132: 130: 128: 126: 124: 122:         <Router set_is_routing>
133: 131: 129: 127: 125: 123:             <div class="routing-progress">
134: 132: 130: 128: 126: 124:                 <RoutingProgress is_routing max_time=Duration::from_millis(250) />
135: 133: 131: 129: 127: 125:             </div>
136: 134: 132: 130: 128: 126:             <main>
137: 135: 133: 131: 129: 127:                 <FlatRoutes fallback=|| "Not Found">
138: 136: 134: 132: 130: 128:                     <Route path=path!("") view=HomePage />
139: 137: 135: 133: 131: 129:                 </FlatRoutes>
140: 138: 136: 134: 132: 130:             </main>
141: 139: 137: 135: 133: 131:         </Router>
142: 140: 138: 136: 134: 132:     }
143: 141: 139: 137: 135: 133: }
144: 142: 140: 138: 136: 134: 
145: 143: 141: 139: 137: 135: #[component]
146: 144: 142: 140: 138: 136: fn HomePage() -> impl IntoView {
147: 145: 143: 141: 139: 137:     let state = PaginationState::new_store();
148: 146: 144: 142: 140: 138: 
149: 147: 145: 143: 141: 139:     let query = RwSignal::new(CustomerQuery::default());
150: 148: 146: 144: 142: 140: 
151: 149: 147: 145: 143: 141:     view! {
152: 150: 148: 146: 144: 142:         <div class="flex flex-col bg-white h-[100vh]">
153: 151: 149: 147: 145: 143:             <div class="py-2 px-5 border-b border-gray-300 bg-slate-100">
154: 152: 150: 148: 146: 144:                 <label class="block relative">
155: 153: 151: 149: 147: 145:                     <span class="flex absolute inset-y-0 left-0 items-center pl-3">
156: 154: 152: 150: 148: 146:                         <svg
157: 155: 153: 151: 149: 147:                             class="w-5 h-5 fill-black"
158: 156: 154: 152: 150: 148:                             xmlns="http://www.w3.org/2000/svg"
159: 157: 155: 153: 151: 149:                             x="0px"
160: 158: 156: 154: 152: 150:                             y="0px"
161: 159: 157: 155: 153: 151:                             width="30"
162: 160: 158: 156: 154: 152:                             height="30"
163: 161: 159: 157: 155: 153:                             viewBox="0 0 30 30"
164: 162: 160: 158: 156: 154:                         >
165: 163: 161: 159: 157: 155:                             <path d="M 13 3 C 7.4889971 3 3 7.4889971 3 13 C 3 18.511003 7.4889971 23 13 23 C 15.396508 23 17.597385 22.148986 19.322266 20.736328 L 25.292969 26.707031 A 1.0001 1.0001 0 1 0 26.707031 25.292969 L 20.736328 19.322266 C 22.148986 17.597385 23 15.396508 23 13 C 23 7.4889971 18.511003 3 13 3 z M 13 5 C 17.430123 5 21 8.5698774 21 13 C 21 17.430123 17.430123 21 13 21 C 8.5698774 21 5 17.430123 5 13 C 5 8.5698774 8.5698774 5 13 5 z"></path>
166: 164: 162: 160: 158: 156:                         </svg>
167: 165: 163: 161: 159: 157:                     </span>
168: 166: 164: 162: 160: 158:                     <input
169: 167: 165: 163: 161: 159:                         class="py-2 pr-4 pl-10 w-full bg-white rounded-full border focus:outline-none placeholder:font-italitc border-slate-300"
170: 168: 166: 164: 162: 160:                         placeholder="Search by name or company"
171: 169: 167: 165: 163: 161:                         type="text"
172: 170: 168: 166: 164: 162:                         value=move || query.read().name.clone()
173: 171: 169: 167: 165: 163:                         on:change=move |e| query.write().name = event_target_value(&e)
174: 172: 170: 168: 166: 164:                     />
175: 173: 171: 169: 167: 165:                 </label>
176: 174: 172: 170: 168: 166:             </div>
177: 175: 173: 171: 169: 167: 
178: 176: 174: 172: 170: 168:             <div class="grid grid-cols-4 gap-4 p-5 min-h-0 text-sm text-left text-gray-500 dark:text-gray-400 grow">
179: 177: 175: 173: 171: 169:                 <PaginatedFor
180: 178: 176: 174: 172: 170:                     loader=CustomerLoader
181: 179: 177: 175: 173: 171:                     state
182: 180: 178: 176: 174: 172:                     query
183: 181: 179: 177: 175: 173:                     item_count_per_page=12
184: 182: 180: 178: 176: 174:                     let:customer_item
185: 183: 181: 179: 177: 175:                 >
186: 184: 182: 180: 178: 176:                     <CustomerCard customer_item />
187: 185: 183: 181: 179: 177: 
188: 186: 184: 182: 180: 178:                     <Loading slot>
189: 187: 185: 183: 181: 179:                         // Skeleton loading
190: 188: 186: 184: 182: 180:                         <CustomerCardSkeleton />
191: 189: 187: 185: 183: 181:                     </Loading>
192: 190: 188: 186: 184: 182:                 </PaginatedFor>
193: 191: 189: 187: 185: 183:             </div>
194: 192: 190: 188: 186: 184:         </div>
195: 193: 191: 189: 187: 185: 
196: 194: 192: 190: 188: 186:         <div class="flex justify-between">
197: 195: 193: 191: 189: 187:             <nav aria-label="Page navigation" class="flex justify-start m-10">
198: 196: 194: 192: 190: 188:                 <PaginationPrev
199: 197: 195: 193: 191: 189:                     state
200: 198: 196: 194: 192: 190:                     attr:class="px-4 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-l-lg hover:bg-gray-100 hover:text-gray-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white dark:focus:ring-blue-500 dark:focus:text-white cursor-pointer select-none"
201: 199: 197: 195: 193: 191:                 >
202: 200: 198: 196: 194: 192:                     Prev
203: 201: 199: 197: 195: 193:                 </PaginationPrev>
204: 202: 200: 198: 196: 194:                 <PaginationNext
205: 203: 201: 199: 197: 195:                     state
206: 204: 202: 200: 198: 196:                     attr:class="px-4 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-r-lg hover:bg-gray-100 hover:text-gray-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white dark:focus:ring-blue-500 dark:focus:text-white border-l-0 cursor-pointer select-none"
207: 205: 203: 201: 199: 197:                 >
208: 206: 204: 202: 200: 198:                     Next
209: 207: 205: 203: 201: 199:                 </PaginationNext>
210: 208: 206: 204: 202: 200:             </nav>
211: 209: 207: 205: 203: 201: 
212: 210: 208: 206: 204: 202:             <nav aria-label="Page number navigation" class="flex justify-end m-10">
213: 211: 209: 207: 205: 203:                 <PaginationPages
214: 212: 210: 208: 206: 204:                     state
215: 213: 211: 209: 207: 205:                     ul_class="inline-flex text-sm"
216: 214: 212: 210: 208: 206:                     li_class="border border-gray-300 dark:border-gray-700 border-l-0 first:border-l first:rounded-l-lg last:rounded-r-lg bg-white dark:bg-gray-800 hover:bg-gray-100 dark:hover:bg-gray-700"
217: 215: 213: 211: 209: 207:                     active_class="bg-blue-600 font-bold hover:bg-blue-700 dark:bg-blue-600 dark:hover:bg-blue-700 first:rounded-l-lg last:rounded-r-lg *:text-white *:hover:text-white dark:*:text-white dark:*:hover:text-white"
218: 216: 214: 212: 210: 208:                     anchor_class="flex items-center justify-center px-4 py-2 text-sm font-medium text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-white cursor-pointer select-none"
219: 217: 215: 213: 211: 209:                     separator_class="self-center select-none mx-2 text-gray-500 dark:text-gray-400"
220: 218: 216: 214: 212: 210:                 />
221: 219: 217: 215: 213: 211:             </nav>
222: 220: 218: 216: 214: 212:         </div>
223: 221: 219: 217: 215: 213:     }
224: 222: 220: 218: 216: 214: }
225: 223: 221: 219: 217: 215: 
226: 224: 222: 220: 218: 216: #[component]
227: 225: 223: 221: 219: 217: pub fn CustomerCardSkeleton() -> impl IntoView {
228: 226: 224: 222: 220: 218:     view! {
229: 227: 225: 223: 221: 219:         <article class="overflow-hidden w-full max-w-sm bg-white rounded-lg shadow-lg dark:bg-gray-700">
230: 228: 226: 224: 222: 220:             <div class="flex flex-col gap-1 px-4 mt-4 mb-4">
231: 229: 227: 225: 223: 221:                 // Name skeleton - larger bar for full name
232: 230: 228: 226: 224: 222:                 <div class="w-3/4 h-6 bg-gray-300 rounded animate-pulse"></div>
233: 231: 229: 227: 225: 223: 
234: 232: 230: 228: 226: 224:                 // Company skeleton - medium bar for company name
235: 233: 231: 229: 227: 225:                 <div class="w-2/3 h-5 bg-gray-300 rounded animate-pulse"></div>
236: 234: 232: 230: 228: 226: 
237: 235: 233: 231: 229: 227:                 // Location skeleton - smaller bar for city and country
238: 236: 234: 232: 230: 228:                 <div class="w-1/2 h-4 bg-gray-300 rounded animate-pulse"></div>
239: 237: 235: 233: 231: 229:             </div>
240: 238: 236: 234: 232: 230:         </article>
241: 239: 237: 235: 233: 231:     }
242: 240: 238: 236: 234: 232: }
243: 241: 239: 237: 235: 233: 
244: 242: 240: 238: 236: 234: #[component]
245: 243: 241: 239: 237: 235: pub fn CustomerCard(customer_item: WindowItem<Customer>) -> impl IntoView {
246: 244: 242: 240: 238: 236:     let customer = Arc::clone(&customer_item.data);
247: 245: 243: 241: 239: 237: 
248: 246: 244: 242: 240: 238:     let handle_delete = move |_| {
249: 247: 245: 243: 241: 239:         customer_item.remove();
250: 248: 246: 244: 242: 240:     };
251: 249: 247: 245: 243: 241: 
252: 250: 248: 246: 244: 242:     view! {
253: 251: 249: 247: 245: 243:         <article class="relative overflow-hidden w-full max-w-sm min-h-0 bg-white rounded-lg shadow-lg dark:bg-gray-700">
254: 252: 250: 248: 246: 244:             <DeleteButton on:click=handle_delete />
255: 253: 251: 249: 247: 245: 
256: 254: 252: 250: 248: 246:             <div class="flex flex-col gap-1 px-4 mt-4 mb-4">
257: 255: 253: 251: 249: 247:                 <h2 class="text-lg font-semibold text-gray-800 dark:text-gray-50">
258: 256: 254: 252: 250: 248:                     {customer.first_name.clone()} " " {customer.last_name.clone()}
259: 257: 255: 253: 251: 249:                 </h2>
260: 258: 256: 254: 252: 250:                 <a
261: 259: 257: 255: 253: 251:                     class="font-semibold text-gray-800 dark:text-gray-50"
262: 260: 258: 256: 254: 252:                     href=customer.website.clone()
263: 261: 259: 257: 255: 253:                 >
264: 262: 260: 258: 256: 254:                     {customer.company.clone()}
265: 263: 261: 259: 257: 255:                 </a>
266: 264: 262: 260: 258: 256:                 <span class="font-normal text-gray-600 dark:text-gray-300">
267: 265: 263: 261: 259: 257:                     {customer.city.clone()} " in " {customer.country.clone()}
268: 266: 264: 262: 260: 258:                 </span>
269: 267: 265: 263: 261: 259:             </div>
270: 268: 266: 264: 262: 260:         </article>
271: 269: 267: 265: 263: 261:     }
272: 270: 268: 266: 264: 262: }
273: 271: 269: 267: 265: 263: 
274: 272: 270: 268: 266: 264: #[component]
275: 273: 271: 269: 267: 265: pub fn DeleteButton() -> impl IntoView {
276: 274: 272: 270: 268: 266:     view! {
277: 275: 273: 271: 269: 267:         <button
278: 276: 274: 272: 270: 268:             class="p-2 text-grey-500 opacity-50 hover:opacity-100 absolute top-0 right-0"
279: 277: 275: 273: 271: 269:             title="Delete customer"
280: 278: 276: 274: 272: 270:         >
281: 279: 277: 275: 273: 271:             <svg
282: 280: 278: 276: 274: 272:                 class="block size-6"
283: 281: 279: 277: 275: 273:                 fill="currentColor"
284: 282: 280: 278: 276: 274:                 viewBox="0 0 20 20"
285: 283: 281: 279: 277: 275:                 xmlns="http://www.w3.org/2000/svg"
286: 284: 282: 280: 278: 276:             >
287: 285: 283: 281: 279: 277:                 <path
288: 286: 284: 282: 280: 278:                     fill-rule="evenodd"
289: 287: 285: 283: 281: 279:                     d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
290: 288: 286: 284: 282: 280:                     clip-rule="evenodd"
291: 289: 287: 285: 283: 281:                 ></path>
292: 290: 288: 286: 284: 282:             </svg>
293: 291: 289: 287: 285: 283:         </button>
294: 292: 290: 288: 286: 284:     }
295: 293: 291: 289: 287: 285: }
296: 294: 292: 290: 288: 286: ```
297: 295: 293: 291: 289: 287: ```
298: 296: 294: 292: 290: 288: ```
299: 297: 295: 293: 291: 289: ```
300: 298: 296: 294: 292: 290: ```
301: 299: 297: 295: 293: 291: ```
302: 300: 298: 296: 294: 292: ```
303: 301: 299: 297: 295: 293: ```
304: 302: 300: 298: 296: 294: ```
305: 303: 301: 299: 297: 295: ```
306: 304: 302: 300: 298: 296: ```
307: 305: 303: 301: 299: 297: ```
308: 306: 304: 302: 300: 298: ```
309: 307: 305: 303: 301: 299: ```
310: 308: 306: 304: 302: 300: ```
311: 309: 307: 305: 303: 301: ```
312: 310: 308: 306: 304: 302: ```
313: 311: 309: 307: 305: 303: ```
314: 312: 310: 308: 306: 304: ```
315: 313: 311: 309: 307: 305: ```
316: 314: 312: 310: 308: 306: ```
317: 315: 313: 311: 309: 307: ```
318: 316: 314: 312: 310: 308: ```
319: 317: 315: 313: 311: 309: ```
320: 318: 316: 314: 312: 310: ```
321: 319: 317: 315: 313: 311: ```
322: 320: 318: 316: 314: 312: ```
323: 321: 319: 317: 315: 313: ```
324: 322: 320: 318: 316: 314: ```
325: 323: 321: 319: 317: 315: ```
326: 324: 322: 320: 318: 316: ```
327: 325: 323: 321: 319: 317: ```
328: 326: 324: 322: 320: 318: ```
329: 327: 325: 323: 321: 319: ```
330: 328: 326: 324: 322: 320: ```
331: 329: 327: 325: 323: 321: ```
332: 330: 328: 326: 324: 322: ```
333: 331: 329: 327: 325: 323: ```
334: 332: 330: 328: 326: 324: ```
335: 333: 331: 329: 327: 325: ```
336: 334: 332: 330: 328: 326: ```
337: 335: 333: 331: 329: 327: ```
338: 336: 334: 332: 330: 328: ```
339: 337: 335: 333: 331: 329: ```
340: 338: 336: 334: 332: 330: ```
341: 339: 337: 335: 333: 331: ```
342: 340: 338: 336: 334: 332: ```
343: 341: 339: 337: 335: 333: ```
344: 342: 340: 338: 336: 334: ```
345: 343: 341: 339: 337: 335: ```
346: 344: 342: 340: 338: ```
347: 345: 343: 341: ```
348: 346: 344: ```
349: 347: ```
350: ```
```

