### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx-logic-windowing\lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
```rust
1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx-logic-windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
2: ```rust
3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx-logic-windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
4: 2: ```rust
5: 3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx-logic-windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
6: 4: 2: ```rust
7: 5: 3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx-logic-windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
8: 6: 4: 2: ```rust
9: 7: 5: 3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx-logic-windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
10: 8: 6: 4: 2: ```rust
11: 9: 7: 5: 3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
12: 10: 8: 6: 4: 2: ```rust
13: 11: 9: 7: 5: 3: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
14: 12: 10: 8: 6: 4: ```rust
15: 13: 11: 9: 7: 5: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
16: 14: 12: 10: 8: 6: ```rust
17: 15: 13: 11: 9: 7: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
18: 16: 14: 12: 10: 8: ```rust
19: 17: 15: 13: 11: 9: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
20: 18: 16: 14: 12: 10: ```rust
21: 19: 17: 15: 13: 11: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
22: 20: 18: 16: 14: 12: ```rust
23: 21: 19: 17: 15: 13: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
24: 22: 20: 18: 16: 14: ```rust
25: 23: 21: 19: 17: 15: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
26: 24: 22: 20: 18: 16: ```rust
27: 25: 23: 21: 19: 17: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
28: 26: 24: 22: 20: 18: ```rust
29: 27: 25: 23: 21: 19: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
30: 28: 26: 24: 22: 20: ```rust
31: 29: 27: 25: 23: 21: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
32: 30: 28: 26: 24: 22: ```rust
33: 31: 29: 27: 25: 23: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
34: 32: 30: 28: 26: 24: ```rust
35: 33: 31: 29: 27: 25: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
36: 34: 32: 30: 28: 26: ```rust
37: 35: 33: 31: 29: 27: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
38: 36: 34: 32: 30: 28: ```rust
39: 37: 35: 33: 31: 29: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
40: 38: 36: 34: 32: 30: ```rust
41: 39: 37: 35: 33: 31: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
42: 40: 38: 36: 34: 32: ```rust
43: 41: 39: 37: 35: 33: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
44: 42: 40: 38: 36: 34: ```rust
45: 43: 41: 39: 37: 35: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
46: 44: 42: 40: 38: 36: ```rust
47: 45: 43: 41: 39: 37: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
48: 46: 44: 42: 40: 38: ```rust
49: 47: 45: 43: 41: 39: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
50: 48: 46: 44: 42: 40: ```rust
51: 49: 47: 45: 43: 41: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
52: 50: 48: 46: 44: 42: ```rust
53: 51: 49: 47: 45: 43: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
54: 52: 50: 48: 46: 44: ```rust
55: 53: 51: 49: 47: 45: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
56: 54: 52: 50: 48: 46: ```rust
57: 55: 53: 51: 49: 47: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
58: 56: 54: 52: 50: 48: ```rust
59: 57: 55: 53: 51: 49: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
60: 58: 56: 54: 52: 50: ```rust
61: 59: 57: 55: 53: 51: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
62: 60: 58: 56: 54: 52: ```rust
63: 61: 59: 57: 55: 53: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
64: 62: 60: 58: 56: 54: ```rust
65: 63: 61: 59: 57: 55: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
66: 64: 62: 60: 58: 56: ```rust
67: 65: 63: 61: 59: 57: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
68: 66: 64: 62: 60: 58: ```rust
69: 67: 65: 63: 61: 59: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
70: 68: 66: 64: 62: 60: ```rust
71: 69: 67: 65: 63: 61: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
72: 70: 68: 66: 64: 62: ```rust
73: 71: 69: 67: 65: 63: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
74: 72: 70: 68: 66: 64: ```rust
75: 73: 71: 69: 67: 65: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
76: 74: 72: 70: 68: 66: ```rust
77: 75: 73: 71: 69: 67: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
78: 76: 74: 72: 70: 68: ```rust
79: 77: 75: 73: 71: 69: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
80: 78: 76: 74: 72: 70: ```rust
81: 79: 77: 75: 73: 71: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
82: 80: 78: 76: 74: 72: ```rust
83: 81: 79: 77: 75: 73: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
84: 82: 80: 78: 76: 74: ```rust
85: 83: 81: 79: 77: 75: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
86: 84: 82: 80: 78: 76: ```rust
87: 85: 83: 81: 79: 77: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
88: 86: 84: 82: 80: 78: ```rust
89: 87: 85: 83: 81: 79: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
90: 88: 86: 84: 82: 80: ```rust
91: 89: 87: 85: 83: 81: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
92: 90: 88: 86: 84: 82: ```rust
93: 91: 89: 87: 85: 83: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
94: 92: 90: 88: 86: 84: ```rust
95: 93: 91: 89: 87: 85: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
96: 94: 92: 90: 88: 86: ```rust
97: 95: 93: 91: 89: 87: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
98: 96: 94: 92: 90: 88: ```rust
99: 97: 95: 93: 91: 89: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
100: 98: 96: 94: 92: 90: ```rust
101: 99: 97: 95: 93: 91: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
102: 100: 98: 96: 94: 92: ```rust
103: 101: 99: 97: 95: 93: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
104: 102: 100: 98: 96: 94: ```rust
105: 103: 101: 99: 97: 95: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
106: 104: 102: 100: 98: 96: ```rust
107: 105: 103: 101: 99: 97: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
108: 106: 104: 102: 100: 98: ```rust
109: 107: 105: 103: 101: 99: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\loader.rs
110: 108: 106: 104: 102: 100: ```rust
111: 109: 107: 105: 103: 101: use lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_leptos::prelude::*;
112: 110: 108: 106: 104: 102: use lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_pagination::ExactLoader;
113: 111: 109: 107: 105: 103: use serde::{Deserialize, Serialize};
114: 112: 110: 108: 106: 104: #[cfg(feature = "ssr")]
115: 113: 111: 109: 107: 105: use sqlx::QueryBuilder;
116: 114: 112: 110: 108: 106: use std::ops::Range;
117: 115: 113: 111: 109: 107: 
118: 116: 114: 112: 110: 108: #[derive(Serialize, Deserialize)]
119: 117: 115: 113: 111: 109: #[cfg_attr(feature = "ssr", derive(sqlx::FromRow))]
120: 118: 116: 114: 112: 110: pub struct Customer {
121: 119: 117: 115: 113: 111:     pub customer_id: String,
122: 120: 118: 116: 114: 112:     pub first_name: String,
123: 121: 119: 117: 115: 113:     pub last_name: String,
124: 122: 120: 118: 116: 114:     pub company: String,
125: 123: 121: 119: 117: 115:     pub city: String,
126: 124: 122: 120: 118: 116:     pub country: String,
127: 125: 123: 121: 119: 117:     pub phone: String,
128: 126: 124: 122: 120: 118:     pub email: String,
129: 127: 125: 123: 121: 119:     pub website: String,
130: 128: 126: 124: 122: 120: }
131: 129: 127: 125: 123: 121: 
132: 130: 128: 126: 124: 122: #[derive(Clone, Debug, Serialize, Deserialize)]
133: 131: 129: 127: 125: 123: pub struct CustomerServerQuery {
134: 132: 130: 128: 126: 124:     range: Range<usize>,
135: 133: 131: 129: 127: 125:     name: String,
136: 134: 132: 130: 128: 126: }
137: 135: 133: 131: 129: 127: 
138: 136: 134: 132: 130: 128: #[cfg(feature = "ssr")]
139: 137: 135: 133: 131: 129: fn build_query<'a>(builder: &mut QueryBuilder<'a, sqlx::Sqlite>, name: &'a String)
140: 138: 136: 134: 132: 130: {
141: 139: 137: 135: 133: 131:     if !name.is_empty() {
142: 140: 138: 136: 134: 132:         builder.push("WHERE first_name LIKE concat('%', ");
143: 141: 139: 137: 135: 133:         builder.push_bind(name);
144: 142: 140: 138: 136: 134:         builder.push(", '%') OR last_name LIKE concat('%', ");
145: 143: 141: 139: 137: 135:         builder.push_bind(name);
146: 144: 142: 140: 138: 136:         builder.push(", '%') OR company LIKE concat('%', ");
147: 145: 143: 141: 139: 137:         builder.push_bind(name);
148: 146: 144: 142: 140: 138:         builder.push(", '%') ");
149: 147: 145: 143: 141: 139:     }
150: 148: 146: 144: 142: 140: }
151: 149: 147: 145: 143: 141: 
152: 150: 148: 146: 144: 142: #[lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_server]
153: 151: 149: 147: 145: 143: pub async fn list_customers(query: CustomerServerQuery) -> Result<Vec<Customer>, ServerFnError> {
154: 152: 150: 148: 146: 144:     use crate::database::get_db;
155: 153: 151: 149: 147: 145: 
156: 154: 152: 150: 148: 146:     let CustomerServerQuery {  range, name } = query;
157: 155: 153: 151: 149: 147: 
158: 156: 154: 152: 150: 148:     let mut builder = QueryBuilder::new("SELECT customer_id, first_name, last_name, company, city, country, phone, email, website FROM customers ");
159: 157: 155: 153: 151: 149:     build_query(&mut builder, &name);
160: 158: 156: 154: 152: 150: 
161: 159: 157: 155: 153: 151:     builder.push(" LIMIT ");
162: 160: 158: 156: 154: 152:     builder.push_bind(range.len() as i64);
163: 161: 159: 157: 155: 153:     builder.push(" OFFSET ");
164: 162: 160: 158: 156: 154:     builder.push_bind(range.start as i64);
165: 163: 161: 159: 157: 155: 
166: 164: 162: 160: 158: 156:     builder
167: 165: 163: 161: 159: 157:         .build_query_as::<Customer>()
168: 166: 164: 162: 160: 158:         .fetch_all(get_db())
169: 167: 165: 163: 161: 159:         .await
170: 168: 166: 164: 162: 160:         .map_err(|e| ServerFnError::new(format!("{e:?}")))
171: 169: 167: 165: 163: 161: }
172: 170: 168: 166: 164: 162: 
173: 171: 169: 167: 165: 163: #[lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_server]
174: 172: 170: 168: 166: 164: pub async fn customer_count(name: String) -> Result<usize, ServerFnError> {
175: 173: 171: 169: 167: 165:     use crate::database::get_db;
176: 174: 172: 170: 168: 166: 
177: 175: 173: 171: 169: 167:     let mut builder = QueryBuilder::new("SELECT COUNT(*) FROM customers ");
178: 176: 174: 172: 170: 168: 
179: 177: 175: 173: 171: 169:     build_query(&mut builder, &name);
180: 178: 176: 174: 172: 170: 
181: 179: 177: 175: 173: 171:     let count: (i64,) = builder
182: 180: 178: 176: 174: 172:         .build_query_as::<(i64,)>()
183: 181: 179: 177: 175: 173:         .fetch_one(get_db())
184: 182: 180: 178: 176: 174:         .await
185: 183: 181: 179: 177: 175:         .map_err(|err| ServerFnError::new(format!("{err:?}")))?;
186: 184: 182: 180: 178: 176: 
187: 185: 183: 181: 179: 177: 
188: 186: 184: 182: 180: 178:     Ok(count.0 as usize)
189: 187: 185: 183: 181: 179: }
190: 188: 186: 184: 182: 180: 
191: 189: 187: 185: 183: 181: #[derive(Debug, Default)]
192: 190: 188: 186: 184: 182: pub struct CustomerQuery {
193: 191: 189: 187: 185: 183:     pub name: String,
194: 192: 190: 188: 186: 184: }
195: 193: 191: 189: 187: 185: 
196: 194: 192: 190: 188: 186: pub struct CustomerLoader;
197: 195: 193: 191: 189: 187: 
198: 196: 194: 192: 190: 188: impl ExactLoader for CustomerLoader {
199: 197: 195: 193: 191: 189:     type Item = Customer;
200: 198: 196: 194: 192: 190:     type Query = CustomerQuery;
201: 199: 197: 195: 193: 191:     type Error = ServerFnError;
202: 200: 198: 196: 194: 192: 
203: 201: 199: 197: 195: 193:     async fn load_items(&self, range: Range<usize>, query: &Self::Query) -> Result<Vec<Customer>, Self::Error> {
204: 202: 200: 198: 196: 194:         list_customers(CustomerServerQuery {
205: 203: 201: 199: 197: 195:             name: query.name.clone(),
206: 204: 202: 200: 198: 196:             range: range.clone(),
207: 205: 203: 201: 199: 197:         })
208: 206: 204: 202: 200: 198:         .await
209: 207: 205: 203: 201: 199:     }
210: 208: 206: 204: 202: 200: 
211: 209: 207: 205: 203: 201:     async fn item_count(&self, query: &Self::Query) -> Result<Option<usize>, Self::Error> {
212: 210: 208: 206: 204: 202:         customer_count(query.name.clone()).await.map(Some)
213: 211: 209: 207: 205: 203:     }
214: 212: 210: 208: 206: 204: }
215: 213: 211: 209: 207: 205: ```
216: 214: 212: 210: 208: 206: ```
217: 215: 213: 211: 209: 207: ```
218: 216: 214: 212: 210: 208: ```
219: 217: 215: 213: 211: 209: ```
220: 218: 216: 214: 212: 210: ```
221: 219: 217: 215: 213: 211: ```
222: 220: 218: 216: 214: 212: ```
223: 221: 219: 217: 215: 213: ```
224: 222: 220: 218: 216: 214: ```
225: 223: 221: 219: 217: 215: ```
226: 224: 222: 220: 218: 216: ```
227: 225: 223: 221: 219: 217: ```
228: 226: 224: 222: 220: 218: ```
229: 227: 225: 223: 221: 219: ```
230: 228: 226: 224: 222: 220: ```
231: 229: 227: 225: 223: 221: ```
232: 230: 228: 226: 224: 222: ```
233: 231: 229: 227: 225: 223: ```
234: 232: 230: 228: 226: 224: ```
235: 233: 231: 229: 227: 225: ```
236: 234: 232: 230: 228: 226: ```
237: 235: 233: 231: 229: 227: ```
238: 236: 234: 232: 230: 228: ```
239: 237: 235: 233: 231: 229: ```
240: 238: 236: 234: 232: 230: ```
241: 239: 237: 235: 233: 231: ```
242: 240: 238: 236: 234: 232: ```
243: 241: 239: 237: 235: 233: ```
244: 242: 240: 238: 236: 234: ```
245: 243: 241: 239: 237: 235: ```
246: 244: 242: 240: 238: 236: ```
247: 245: 243: 241: 239: 237: ```
248: 246: 244: 242: 240: 238: ```
249: 247: 245: 243: 241: 239: ```
250: 248: 246: 244: 242: 240: ```
251: 249: 247: 245: 243: 241: ```
252: 250: 248: 246: 244: 242: ```
253: 251: 249: 247: 245: 243: ```
254: 252: 250: 248: 246: 244: ```
255: 253: 251: 249: 247: 245: ```
256: 254: 252: 250: 248: 246: ```
257: 255: 253: 251: 249: 247: ```
258: 256: 254: 252: 250: 248: ```
259: 257: 255: 253: 251: 249: ```
260: 258: 256: 254: 252: 250: ```
261: 259: 257: 255: 253: 251: ```
262: 260: 258: 256: 254: 252: ```
263: 261: 259: 257: 255: 253: ```
264: 262: 260: 258: 256: 254: ```
265: 263: 261: 259: 257: ```
266: 264: 262: 260: ```
267: 265: 263: ```
268: 266: ```
269: ```
```
