1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx-logic-windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
2: ```rust
3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx-logic-windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
4: 2: ```rust
5: 3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx-logic-windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
6: 4: 2: ```rust
7: 5: 3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx-logic-windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
8: 6: 4: 2: ```rust
9: 7: 5: 3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx-logic-windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
10: 8: 6: 4: 2: ```rust
11: 9: 7: 5: 3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
12: 10: 8: 6: 4: 2: ```rust
13: 11: 9: 7: 5: 3: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
14: 12: 10: 8: 6: 4: ```rust
15: 13: 11: 9: 7: 5: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
16: 14: 12: 10: 8: 6: ```rust
17: 15: 13: 11: 9: 7: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
18: 16: 14: 12: 10: 8: ```rust
19: 17: 15: 13: 11: 9: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
20: 18: 16: 14: 12: 10: ```rust
21: 19: 17: 15: 13: 11: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
22: 20: 18: 16: 14: 12: ```rust
23: 21: 19: 17: 15: 13: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
24: 22: 20: 18: 16: 14: ```rust
25: 23: 21: 19: 17: 15: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
26: 24: 22: 20: 18: 16: ```rust
27: 25: 23: 21: 19: 17: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
28: 26: 24: 22: 20: 18: ```rust
29: 27: 25: 23: 21: 19: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
30: 28: 26: 24: 22: 20: ```rust
31: 29: 27: 25: 23: 21: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
32: 30: 28: 26: 24: 22: ```rust
33: 31: 29: 27: 25: 23: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
34: 32: 30: 28: 26: 24: ```rust
35: 33: 31: 29: 27: 25: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
36: 34: 32: 30: 28: 26: ```rust
37: 35: 33: 31: 29: 27: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
38: 36: 34: 32: 30: 28: ```rust
39: 37: 35: 33: 31: 29: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
40: 38: 36: 34: 32: 30: ```rust
41: 39: 37: 35: 33: 31: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
42: 40: 38: 36: 34: 32: ```rust
43: 41: 39: 37: 35: 33: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
44: 42: 40: 38: 36: 34: ```rust
45: 43: 41: 39: 37: 35: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
46: 44: 42: 40: 38: 36: ```rust
47: 45: 43: 41: 39: 37: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
48: 46: 44: 42: 40: 38: ```rust
49: 47: 45: 43: 41: 39: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
50: 48: 46: 44: 42: 40: ```rust
51: 49: 47: 45: 43: 41: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
52: 50: 48: 46: 44: 42: ```rust
53: 51: 49: 47: 45: 43: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
54: 52: 50: 48: 46: 44: ```rust
55: 53: 51: 49: 47: 45: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
56: 54: 52: 50: 48: 46: ```rust
57: 55: 53: 51: 49: 47: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
58: 56: 54: 52: 50: 48: ```rust
59: 57: 55: 53: 51: 49: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
60: 58: 56: 54: 52: 50: ```rust
61: 59: 57: 55: 53: 51: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
62: 60: 58: 56: 54: 52: ```rust
63: 61: 59: 57: 55: 53: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
64: 62: 60: 58: 56: 54: ```rust
65: 63: 61: 59: 57: 55: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
66: 64: 62: 60: 58: 56: ```rust
67: 65: 63: 61: 59: 57: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
68: 66: 64: 62: 60: 58: ```rust
69: 67: 65: 63: 61: 59: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
70: 68: 66: 64: 62: 60: ```rust
71: 69: 67: 65: 63: 61: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
72: 70: 68: 66: 64: 62: ```rust
73: 71: 69: 67: 65: 63: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
74: 72: 70: 68: 66: 64: ```rust
75: 73: 71: 69: 67: 65: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
76: 74: 72: 70: 68: 66: ```rust
77: 75: 73: 71: 69: 67: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
78: 76: 74: 72: 70: 68: ```rust
79: 77: 75: 73: 71: 69: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
80: 78: 76: 74: 72: 70: ```rust
81: 79: 77: 75: 73: 71: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
82: 80: 78: 76: 74: 72: ```rust
83: 81: 79: 77: 75: 73: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
84: 82: 80: 78: 76: 74: ```rust
85: 83: 81: 79: 77: 75: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
86: 84: 82: 80: 78: 76: ```rust
87: 85: 83: 81: 79: 77: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
88: 86: 84: 82: 80: 78: ```rust
89: 87: 85: 83: 81: 79: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
90: 88: 86: 84: 82: 80: ```rust
91: 89: 87: 85: 83: 81: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
92: 90: 88: 86: 84: 82: ```rust
93: 91: 89: 87: 85: 83: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
94: 92: 90: 88: 86: 84: ```rust
95: 93: 91: 89: 87: 85: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
96: 94: 92: 90: 88: 86: ```rust
97: 95: 93: 91: 89: 87: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
98: 96: 94: 92: 90: 88: ```rust
99: 97: 95: 93: 91: 89: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
100: 98: 96: 94: 92: 90: ```rust
101: 99: 97: 95: 93: 91: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
102: 100: 98: 96: 94: 92: ```rust
103: 101: 99: 97: 95: 93: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
104: 102: 100: 98: 96: 94: ```rust
105: 103: 101: 99: 97: 95: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
106: 104: 102: 100: 98: 96: ```rust
107: 105: 103: 101: 99: 97: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
108: 106: 104: 102: 100: 98: ```rust
109: 107: 105: 103: 101: 99: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_windowing\lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-core-lyx_core_lyx-logic-leptos-pagination\lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples\lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx\src\main.rs
110: 108: 106: 104: 102: 100: ```rust
111: 109: 107: 105: 103: 101: #[cfg(feature = "ssr")]
112: 110: 108: 106: 104: 102: #[tokio::main]
113: 111: 109: 107: 105: 103: async fn main() {
114: 112: 110: 108: 106: 104:     use axum::Router;
115: 113: 111: 109: 107: 105:     use lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_leptos::config::get_configuration;
116: 114: 112: 110: 108: 106:     use lyx-core-axum::{generate_route_list, LeptosRoutes};
117: 115: 113: 111: 109: 107:     use lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx::{shell, App};
118: 116: 114: 112: 110: 108: 
119: 117: 115: 113: 111: 109:     lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_lyx-platform-lyx_platform_lyx-logic-lyx_logic_serverfn_sqlx::database::init_db().await;
120: 118: 116: 114: 112: 110: 
121: 119: 117: 115: 113: 111:     let conf = get_configuration(Some("Cargo.toml")).unwrap();
122: 120: 118: 116: 114: 112:     let lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_leptos_options = conf.lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_leptos_options;
123: 121: 119: 117: 115: 113:     let addr = lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_leptos_options.site_addr;
124: 122: 120: 118: 116: 114:     let routes = generate_route_list(App);
125: 123: 121: 119: 117: 115: 
126: 124: 122: 120: 118: 116:     // build our lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_application with a route
127: 125: 123: 121: 119: 117:     let lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app = Router::new()
128: 126: 124: 122: 120: 118:         .lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_leptos_routes(&lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_leptos_options, routes, {
129: 127: 125: 123: 121: 119:             let lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_leptos_options = lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_leptos_options.clone();
130: 128: 126: 124: 122: 120:             move || shell(lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_leptos_options.clone())
131: 129: 127: 125: 123: 121:         })
132: 130: 128: 126: 124: 122:         .fallback(lyx-core-axum::file_and_error_handler(shell))
133: 131: 129: 127: 125: 123:         .with_state(lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_leptos_options);
134: 132: 130: 128: 126: 124: 
135: 133: 131: 129: 127: 125:     let listener = tokio::net::TcpListener::bind(&addr).await.unwrap();
136: 134: 132: 130: 128: 126:     println!("listening on http://{}", &addr);
137: 135: 133: 131: 129: 127:     axum::serve(listener, lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app.into_make_service())
138: 136: 134: 132: 130: 128:         .await
139: 137: 135: 133: 131: 129:         .unwrap();
140: 138: 136: 134: 132: 130: }
141: 139: 137: 135: 133: 131: 
142: 140: 138: 136: 134: 132: #[cfg(not(feature = "ssr"))]
143: 141: 139: 137: 135: 133: pub fn main() {
144: 142: 140: 138: 136: 134:     // no lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_client-side main function
145: 143: 141: 139: 137: 135:     // unless we want this to work with e.g., Trunk for a purely lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_client-side lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_lyx-platform-lyx_platform_app
146: 144: 142: 140: 138: 136:     // see lib.rs for hydration function instead
147: 145: 143: 141: 139: 137: }
148: 146: 144: 142: 140: 138: ```
149: 147: 145: 143: 141: 139: ```
150: 148: 146: 144: 142: 140: ```
151: 149: 147: 145: 143: 141: ```
152: 150: 148: 146: 144: 142: ```
153: 151: 149: 147: 145: 143: ```
154: 152: 150: 148: 146: 144: ```
155: 153: 151: 149: 147: 145: ```
156: 154: 152: 150: 148: 146: ```
157: 155: 153: 151: 149: 147: ```
158: 156: 154: 152: 150: 148: ```
159: 157: 155: 153: 151: 149: ```
160: 158: 156: 154: 152: 150: ```
161: 159: 157: 155: 153: 151: ```
162: 160: 158: 156: 154: 152: ```
163: 161: 159: 157: 155: 153: ```
164: 162: 160: 158: 156: 154: ```
165: 163: 161: 159: 157: 155: ```
166: 164: 162: 160: 158: 156: ```
167: 165: 163: 161: 159: 157: ```
168: 166: 164: 162: 160: 158: ```
169: 167: 165: 163: 161: 159: ```
170: 168: 166: 164: 162: 160: ```
171: 169: 167: 165: 163: 161: ```
172: 170: 168: 166: 164: 162: ```
173: 171: 169: 167: 165: 163: ```
174: 172: 170: 168: 166: 164: ```
175: 173: 171: 169: 167: 165: ```
176: 174: 172: 170: 168: 166: ```
177: 175: 173: 171: 169: 167: ```
178: 176: 174: 172: 170: 168: ```
179: 177: 175: 173: 171: 169: ```
180: 178: 176: 174: 172: 170: ```
181: 179: 177: 175: 173: 171: ```
182: 180: 178: 176: 174: 172: ```
183: 181: 179: 177: 175: 173: ```
184: 182: 180: 178: 176: 174: ```
185: 183: 181: 179: 177: 175: ```
186: 184: 182: 180: 178: 176: ```
187: 185: 183: 181: 179: 177: ```
188: 186: 184: 182: 180: 178: ```
189: 187: 185: 183: 181: 179: ```
190: 188: 186: 184: 182: 180: ```
191: 189: 187: 185: 183: 181: ```
192: 190: 188: 186: 184: 182: ```
193: 191: 189: 187: 185: 183: ```
194: 192: 190: 188: 186: 184: ```
195: 193: 191: 189: 187: 185: ```
196: 194: 192: 190: 188: 186: ```
197: 195: 193: 191: 189: 187: ```
198: 196: 194: 192: 190: ```
199: 197: 195: 193: ```
200: 198: 196: ```
201: 199: ```
202: ```
```

