### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\locales_scripts.rs
use lyx-core-lyx_core_lyx-core-lyx_core_leptos::prelude::*;
use lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent::{lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent, move_tr};

#[component]
fn I18n(children: Children) -> impl IntoView {
lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent! {
children: children(),
locales: "../../../../lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros/tests/ui/lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent/stable/pass/locales_scripts",
default_language: "sr-Latn",
}
}

#[component]
pub fn App() -> impl IntoView {
view! {
<I18n>
<p>{move_tr!("hello")}</p>
</I18n>
}
}

fn main() {}
