### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_fluent\lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros\tests\ui\lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent\stable\pass\tr_checker_single_file.rs
// Allow to pass a single file path to `check_translations` parameter of
// `lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent!` macro.
use lyx-core-lyx_core_lyx-core-lyx_core_leptos::prelude::*;
use lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent::move_tr;
use lyx-core-lyx_core_lyx_logic_lyx_logic_lyx-core-lyx_core_lyx_logic_lyx_logic_leptos_fluent_macros::lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent;

#[component]
pub fn I18n(children: Children) -> impl IntoView {
lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent! {
children: children(),
locales: "../../../../lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_examples/csr-minimal/locales",
check_translations: "../../../../lyx-core-lyx_core_lyx-logic-lyx-logic-lyx-core-lyx_core_lyx-logic-lyx-logic-leptos-fluent-macros/tests/ui/lyx-core-lyx_core_lyx_logic_lyx-core-lyx_core_lyx_logic_leptos_fluent/stable/pass/tr_checker_single_file.rs",
}
}

#[component]
pub fn App() -> impl IntoView {
view! {
<p>{move_tr!("select-a-language")}</p>
<p>{move_tr!("language-is-english")}</p>
<p>{move_tr!("language-is-spanish")}</p>
}
}

fn main() {}
