-- ===== ACUITY SCHEDULING I18N KEYS =====
-- ===== Date: 2025-11-05 =====

BEGIN

-- ACUITY SCHEDULING PROVIDER
CREATE i18n_key:provider_acuity_scheduling_name SET description = "acuity_scheduling name";
CREATE i18n_key:provider_acuity_scheduling_description SET description = "acuity_scheduling description";
CREATE i18n_key:provider_acuity_scheduling_tooltip SET description = "acuity_scheduling tooltip";

COMMIT;