-- =================================================================================================
-- I18N TRANSLATIONS: society_activity_nomenclature_type
-- =================================================================================================

-- NAFRev2
----------------------------------------------------------------------------------------------------

RELATE i18n_key:society_activity_nomenclature_type_nafrev2_name->translation->language:fr
    SET text = 'NAF Révision 2';

RELATE i18n_key:society_activity_nomenclature_type_nafrev2_name->translation->language:en
    SET text = 'French Business Classification Revision 2';

RELATE i18n_key:society_activity_nomenclature_type_nafrev2_name->translation->language:es
    SET text = 'Clasificación de Actividades Francesa Revisión 2';

RELATE i18n_key:society_activity_nomenclature_type_nafrev2_name->translation->language:de
    SET text = 'Französische Wirtschaftsklassifizierung Revision 2';

RELATE i18n_key:society_activity_nomenclature_type_nafrev2_name->translation->language:it
    SET text = 'Classificazione delle Attività Francese Revisione 2';

RELATE i18n_key:society_activity_nomenclature_type_nafrev2_description->translation->language:fr
    SET text = 'Nomenclature d\'Activités Française Révision 2 - En vigueur depuis 2008';

RELATE i18n_key:society_activity_nomenclature_type_nafrev2_description->translation->language:en
    SET text = 'French Business Classification Revision 2 - In force since 2008';

RELATE i18n_key:society_activity_nomenclature_type_nafrev2_description->translation->language:es
    SET text = 'Clasificación de Actividades Francesa Revisión 2 - En vigor desde 2008';

RELATE i18n_key:society_activity_nomenclature_type_nafrev2_description->translation->language:de
    SET text = 'Französische Wirtschaftsklassifizierung Revision 2 - Gültig seit 2008';

RELATE i18n_key:society_activity_nomenclature_type_nafrev2_description->translation->language:it
    SET text = 'Classificazione delle Attività Francese Revisione 2 - In vigore dal 2008';

-- NAFRev1
----------------------------------------------------------------------------------------------------

RELATE i18n_key:society_activity_nomenclature_type_nafrev1_name->translation->language:fr
    SET text = 'NAF Révision 1';

RELATE i18n_key:society_activity_nomenclature_type_nafrev1_name->translation->language:en
    SET text = 'French Business Classification Revision 1';

RELATE i18n_key:society_activity_nomenclature_type_nafrev1_name->translation->language:es
    SET text = 'Clasificación de Actividades Francesa Revisión 1';

RELATE i18n_key:society_activity_nomenclature_type_nafrev1_name->translation->language:de
    SET text = 'Französische Wirtschaftsklassifizierung Revision 1';

RELATE i18n_key:society_activity_nomenclature_type_nafrev1_name->translation->language:it
    SET text = 'Classificazione delle Attività Francese Revisione 1';

RELATE i18n_key:society_activity_nomenclature_type_nafrev1_description->translation->language:fr
    SET text = 'Nomenclature d\'Activités Française Révision 1 (NAF 2003) - Utilisée de 2003 à 2008';

RELATE i18n_key:society_activity_nomenclature_type_nafrev1_description->translation->language:en
    SET text = 'French Business Classification Revision 1 (NAF 2003) - Used from 2003 to 2008';

RELATE i18n_key:society_activity_nomenclature_type_nafrev1_description->translation->language:es
    SET text = 'Clasificación de Actividades Francesa Revisión 1 (NAF 2003) - Usada de 2003 a 2008';

RELATE i18n_key:society_activity_nomenclature_type_nafrev1_description->translation->language:de
    SET text = 'Französische Wirtschaftsklassifizierung Revision 1 (NAF 2003) - Verwendet von 2003 bis 2008';

RELATE i18n_key:society_activity_nomenclature_type_nafrev1_description->translation->language:it
    SET text = 'Classificazione delle Attività Francese Revisione 1 (NAF 2003) - Usata dal 2003 al 2008';

-- NAF1993
----------------------------------------------------------------------------------------------------

RELATE i18n_key:society_activity_nomenclature_type_naf1993_name->translation->language:fr
    SET text = 'NAF 1993';

RELATE i18n_key:society_activity_nomenclature_type_naf1993_name->translation->language:en
    SET text = 'French Business Classification 1993';

RELATE i18n_key:society_activity_nomenclature_type_naf1993_name->translation->language:es
    SET text = 'Clasificación de Actividades Francesa 1993';

RELATE i18n_key:society_activity_nomenclature_type_naf1993_name->translation->language:de
    SET text = 'Französische Wirtschaftsklassifizierung 1993';

RELATE i18n_key:society_activity_nomenclature_type_naf1993_name->translation->language:it
    SET text = 'Classificazione delle Attività Francese 1993';

RELATE i18n_key:society_activity_nomenclature_type_naf1993_description->translation->language:fr
    SET text = 'Nomenclature d\'Activités Française 1993 - Utilisée de 1993 à 2003';

RELATE i18n_key:society_activity_nomenclature_type_naf1993_description->translation->language:en
    SET text = 'French Business Classification 1993 - Used from 1993 to 2003';

RELATE i18n_key:society_activity_nomenclature_type_naf1993_description->translation->language:es
    SET text = 'Clasificación de Actividades Francesa 1993 - Usada de 1993 a 2003';

RELATE i18n_key:society_activity_nomenclature_type_naf1993_description->translation->language:de
    SET text = 'Französische Wirtschaftsklassifizierung 1993 - Verwendet von 1993 bis 2003';

RELATE i18n_key:society_activity_nomenclature_type_naf1993_description->translation->language:it
    SET text = 'Classificazione delle Attività Francese 1993 - Usata dal 1993 al 2003';

-- NAP
----------------------------------------------------------------------------------------------------

RELATE i18n_key:society_activity_nomenclature_type_nap_name->translation->language:fr
    SET text = 'NAP';

RELATE i18n_key:society_activity_nomenclature_type_nap_name->translation->language:en
    SET text = 'Product Activities Classification';

RELATE i18n_key:society_activity_nomenclature_type_nap_name->translation->language:es
    SET text = 'Clasificación de Actividades de Productos';

RELATE i18n_key:society_activity_nomenclature_type_nap_name->translation->language:de
    SET text = 'Produktaktivitätsklassifizierung';

RELATE i18n_key:society_activity_nomenclature_type_nap_name->translation->language:it
    SET text = 'Classificazione delle Attività di Prodotto';

RELATE i18n_key:society_activity_nomenclature_type_nap_description->translation->language:fr
    SET text = 'Nomenclature d\'Activités de Produits - Utilisée de 1973 à 1993';

RELATE i18n_key:society_activity_nomenclature_type_nap_description->translation->language:en
    SET text = 'Product Activities Classification - Used from 1973 to 1993';

RELATE i18n_key:society_activity_nomenclature_type_nap_description->translation->language:es
    SET text = 'Clasificación de Actividades de Productos - Usada de 1973 a 1993';

RELATE i18n_key:society_activity_nomenclature_type_nap_description->translation->language:de
    SET text = 'Produktaktivitätsklassifizierung - Verwendet von 1973 bis 1993';

RELATE i18n_key:society_activity_nomenclature_type_nap_description->translation->language:it
    SET text = 'Classificazione delle Attività di Prodotto - Usata dal 1973 al 1993';

