[package]
name = "lyxalism-runtime"
version.workspace = true
description = "Runtime for Lyxalism"
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
license-file.workspace = true

[dependencies]

# Lyxal internal crates
lyxal-types.workspace = true
lyxalism-types = { workspace = true, features = ["host"] }

# External crates
anyhow.workspace = true
async-trait.workspace = true
semver.workspace = true
serde.workspace = true
tar.workspace = true
toml.workspace = true
wasmtime.workspace = true
wasmtime-wasi.workspace = true
zstd.workspace = true

[lints]
workspace = true