[package]
name = "lyx-ui-thaw"
version = "0.8.0"
edition = "2024"
[dependencies]
leptos = { path = "../core/lyx-core-leptos/leptos" }
thaw_components = { path = "../thaw_components" }
thaw_macro = { path = "../thaw_macro" }
thaw_utils = { path = "../thaw_utils" }
leptos_transition_group = { version = "*" }
web-sys = { version = "*", features = ["DomRect", "File", "FileList", "DataTransfer", "ScrollToOptions", "ScrollBehavior", "TreeWalker", "NodeFilter" ] }
wasm-bindgen = { version = "*" }
icondata_core = { version = "*" }
icondata_ai = { version = "*" }
uuid = { version = "*", features = ["v4", "js"] }
cfg-if = { version = "*" }
chrono = { version = "*" }
palette = { version = "*" }
num-traits = { version = "*" }
send_wrapper = { version = "*" }
slotmap = { version = "*" }
getset = { version = "*" }
pure-rust-locales = { version = "*" }
[features]
csr = ["leptos/csr", "thaw_components/csr", "thaw_utils/csr"]
ssr = ["leptos/ssr", "thaw_components/ssr", "thaw_utils/ssr"]
hydrate = ["leptos/hydrate", "thaw_components/hydrate", "thaw_utils/hydrate"]
nightly = ["leptos/nightly", "thaw_utils/nightly"]










