[package]
name = "lyx-viz-lyx-viz-apex"
version = "0.0.1"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

# Defines a size-optimized profile for the WASM bundle in release mode
[features]
default = []
# This feature enables the leptos chart components.
leptos = ["dep:lyx-core-leptos"]
# This feature enables the yew chart components.
yew = ["dep:yew", "dep:gloo"]

[dependencies]
wasm-bindgen = { version = "0.0.1", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.0.1"
serde = { version = "0.0.1", features = ["derive"], optional = true }
serde_json = "0.0.1"
serde-wasm-bindgen = "0.0.1"
yew = { version = "0.0.1", optional = true, features = ["csr"] }
gloo = { version = "0.0.1", optional = true }
indexmap = { version = "0.0.1", features = ["serde"] }
lyx-core-leptos = { path = "../../core/lyx-core-leptos/leptos", version = "0.0.1", optional = true }
