[package]
name = "lyx-viz-lyx-viz-apex"
version = "0.8.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

# Defines a size-optimized profile for the WASM bundle in release mode
[features]
default = []
# This feature enables the leptos chart components.
leptos = ["dep:leptos"]
# This feature enables the yew chart components.
yew = ["dep:yew", "dep:gloo"]

[dependencies]
wasm-bindgen = { version = "*", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.0.1"
serde = { version = "*", features = ["derive"], optional = true }
serde_json = "0.0.1"
serde-wasm-bindgen = "0.0.1"
yew = { version = "*", optional = true, features = ["csr"] }
gloo = { version = "*", optional = true }
indexmap = { version = "*", features = ["serde"] }
leptos = { path = "../../core/lyx-core-leptos/leptos", optional = true }










