-- Seeds pour les villes du pays: NC --

CREATE base_city:nc_153638 SET state = base_state:nc_03, key.name = i18n_key:i18n_city_nc_153638_name, native = 'Lifou', location = (167.23330000, -20.96670000), timezone = base_timezone:asia_sakhalin, wikiDataId = 'Q9728';
CREATE base_city:nc_153639 SET state = base_state:nc_03, key.name = i18n_key:i18n_city_nc_153639_name, native = 'Marée', location = (167.98330000, -21.51670000), timezone = base_timezone:asia_sakhalin, wikiDataId = 'Q9729';
CREATE base_city:nc_153637 SET state = base_state:nc_02, key.name = i18n_key:i18n_city_nc_153637_name, native = 'Houaïlou', location = (165.62170000, -21.29090000), timezone = base_timezone:asia_sakhalin, wikiDataId = 'Q9716';
CREATE base_city:nc_153635 SET state = base_state:nc_02, key.name = i18n_key:i18n_city_nc_153635_name, native = 'Koné', location = (164.85180000, -21.05900000), timezone = base_timezone:asia_sakhalin, wikiDataId = 'Q9721';
CREATE base_city:nc_153636 SET state = base_state:nc_02, key.name = i18n_key:i18n_city_nc_153636_name, native = 'Poindié', location = (165.32930000, -20.94960000), timezone = base_timezone:asia_sakhalin, wikiDataId = 'Q9740';
CREATE base_city:nc_153634 SET state = base_state:nc_01, key.name = i18n_key:i18n_city_nc_153634_name, native = 'Bourail', location = (165.48040000, -21.57010000), timezone = base_timezone:asia_sakhalin, wikiDataId = 'Q9709';
CREATE base_city:nc_153632 SET state = base_state:nc_01, key.name = i18n_key:i18n_city_nc_153632_name, native = 'Muet', location = (166.45000000, -22.15000000), timezone = base_timezone:asia_sakhalin, wikiDataId = 'Q597896';
CREATE base_city:nc_153631 SET state = base_state:nc_01, key.name = i18n_key:i18n_city_nc_153631_name, native = 'Le Mont-Dore', location = (166.46650000, -22.21570000), timezone = base_timezone:asia_sakhalin, wikiDataId = 'Q9732';
CREATE base_city:nc_153630 SET state = base_state:nc_01, key.name = i18n_key:i18n_city_nc_153630_name, native = 'Nouméa', location = (166.45800000, -22.27580000), timezone = base_timezone:asia_sakhalin, wikiDataId = 'Q9733';
CREATE base_city:nc_153633 SET state = base_state:nc_01, key.name = i18n_key:i18n_city_nc_153633_name, native = 'Païta', location = (166.35050000, -22.13370000), timezone = base_timezone:asia_sakhalin, wikiDataId = 'Q9737';
