[package]
name = "view-tests"
version = "*"
edition = "2024"
[dependencies]
leptos = { path = "../leptos", version = "*", features = ["csr", "nightly"] }
console_log = { version = "*" }
log = { version = "*" }
console_error_panic_hook = { version = "*" }
[dev-dependencies]
wasm-bindgen-test = { version = "*" }


[build-dependencies]
rustc_version = "*"


