[package]
name = "openapi-openai-api-swagger-ui"
version = "*"
edition = "2024"
[lib]
crate-type = ["cdylib", "rlib"]
[dependencies]
axum = { version = "*", optional = true }
console_error_panic_hook = { version = "*" }
leptos = { path = "../leptos", version = "*", features = ["nightly"], optional = true }
axum = { path = "../../integrations/axum", version = "*", optional = true }
meta = { path = "../../meta", version = "*", features = ["nightly"], optional = true }
router = { path = "../../router", version = "*", features = ["nightly"], optional = true }
tokio = { version = "*", optional = true, features = ["rt-multi-thread"] }
tower = { version = "*", optional = true }
tower-http = { version = "*", optional = true, features = ["fs"] }
wasm-bindgen = { version = "*" }
thiserror = { version = "*" }
tracing = { version = "*", optional = true }
utoipa = { version = "*", optional = true, features = ["debug"] }
utoipa-swagger-ui = { version = "*", optional = true, features = ["axum"] }
http = { version = "*" }
serde = { version = "*" }
serde_json = { version = "*", optional = true }
openai_dive = { version = "*", optional = true }
reqwest = { version = "*" }
uuid = { version = "*", features = ["v4"] }
[features]
hydrate = ["leptos/hydrate", "meta/hydrate", "router/hydrate"]
ssr = [
"dep:openai_dive",
"dep:serde_json",
"dep:utoipa-swagger-ui",
"dep:utoipa",
"dep:axum",
"dep:tokio",
"dep:tower",
"dep:tower-http",
"dep:axum",
"leptos/ssr",
"meta/ssr",
"router/ssr",
"dep:tracing" ]
[profile.wasm-release]
opt-level = 'z'
lto = true
codegen-units = 1


[build-dependencies]
rustc_version = "*"




