[package]
name = "lyx-core-openapi-openai-api-swagger-ui"
version = "0.0.1"
edition = "2024"
[lib]
crate-type = ["cdylib", "rlib"]
[dependencies]
axum = { version = "0.0.1", optional = true }
console_error_panic_hook = { version = "0.0.1" }
lyx-core-leptos = { path = "../../leptos", version = "0.0.1", features = ["nightly"], optional = true }
lyx-core-axum = { path = "../../integrations/axum", version = "0.0.1", optional = true }
lyx-core-meta = { path = "../../meta", version = "0.0.1", features = ["nightly"], optional = true }
lyx-core-router = { path = "../../router", version = "0.0.1", features = ["nightly"], optional = true }
tokio = { version = "0.0.1", optional = true, features = ["rt-multi-thread"] }
tower = { version = "0.0.1", optional = true }
tower-http = { version = "0.0.1", optional = true, features = ["fs"] }
wasm-bindgen = { version = "0.0.1" }
thiserror = { version = "0.0.1" }
tracing = { version = "0.0.1", optional = true }
utoipa = { version = "0.0.1", optional = true, features = ["debug"] }
utoipa-swagger-ui = { version = "0.0.1", optional = true, features = ["axum"] }
http = { version = "0.0.1" }
serde = { version = "0.0.1" }
serde_json = { version = "0.0.1", optional = true }
openai_dive = { version = "0.0.1", optional = true }
reqwest = { version = "0.0.1" }
uuid = { version = "0.0.1", features = ["v4"] }
[features]
hydrate = ["lyx-core-leptos/hydrate", "lyx-core-meta/hydrate", "lyx-core-router/hydrate"]
ssr = [
"dep:openai_dive",
"dep:serde_json",
"dep:utoipa-swagger-ui",
"dep:utoipa",
"dep:axum",
"dep:tokio",
"dep:tower",
"dep:tower-http",
"dep:lyx-core-axum",
"lyx-core-leptos/ssr",
"lyx-core-meta/ssr",
"lyx-core-router/ssr",
"dep:tracing" ]
[profile.wasm-release]
opt-level = 'z'
lto = true
codegen-units = 1
