-- =============================================================================================
-- |
-- | Fichier     : i18n_unit_type_i18n_key_seeds.surql
-- | Module      : i18n
-- | Description : Peuple la table `i18n_key` avec les clés pour les noms des types d'unités.
-- |
-- =============================================================================================

CREATE i18n_key:'i18n.unit_type.weight.name' SET description = "Nom pour le type d'unité 'Poids'";
CREATE i18n_key:'i18n.unit_type.length.name' SET description = "Nom pour le type d'unité 'Longueur'";
CREATE i18n_key:'i18n.unit_type.volume.name' SET description = "Nom pour le type d'unité 'Volume'";
CREATE i18n_key:'i18n.unit_type.time.name' SET description = "Nom pour le type d'unité 'Temps'";
CREATE i18n_key:'i18n.unit_type.quantity.name' SET description = "Nom pour le type d'unité 'Quantité'";
CREATE i18n_key:'i18n.unit_type.surface.name' SET description = "Nom pour le type d'unité 'Surface'";
CREATE i18n_key:'i18n.unit_type.speed.name' SET description = "Nom pour le type d'unité 'Vitesse'";
CREATE i18n_key:'i18n.unit_type.temperature.name' SET description = "Nom pour le type d'unité 'Température'";
CREATE i18n_key:'i18n.unit_type.data.name' SET description = "Nom pour le type d'unité 'Données informatiques'";
CREATE i18n_key:'i18n.unit_type.pressure.name' SET description = "Nom pour le type d'unité 'Pression'";
CREATE i18n_key:'i18n.unit_type.angle.name' SET description = "Nom pour le type d'unité 'Angle'";
CREATE i18n_key:'i18n.unit_type.energy.name' SET description = "Nom pour le type d'unité 'Énergie'";
CREATE i18n_key:'i18n.unit_type.power.name' SET description = "Nom pour le type d'unité 'Puissance'";
CREATE i18n_key:'i18n.unit_type.frequency.name' SET description = "Nom pour le type d'unité 'Fréquence'";
