-- Batch 14: 200 traductions Lyxal (5 langues)

-- Netscaler Adc
RELATE i18n_key:service_netscaleradc_name->translation->language:fr SET text = "Netscaler Adc";
RELATE i18n_key:service_netscaleradc_name->translation->language:en SET text = "Netscaler Adc";
RELATE i18n_key:service_netscaleradc_name->translation->language:it SET text = "Netscaler Adc";
RELATE i18n_key:service_netscaleradc_name->translation->language:de SET text = "Netscaler Adc";
RELATE i18n_key:service_netscaleradc_name->translation->language:es SET text = "Netscaler Adc";
RELATE i18n_key:service_netscaleradc_desc->translation->language:fr SET text = "Service Netscaler Adc pour automatisation";
RELATE i18n_key:service_netscaleradc_desc->translation->language:en SET text = "Netscaler Adc service for automation";
RELATE i18n_key:service_netscaleradc_desc->translation->language:it SET text = "Servizio Netscaler Adc per automazione";
RELATE i18n_key:service_netscaleradc_desc->translation->language:de SET text = "Netscaler Adc-Dienst für Automatisierung";
RELATE i18n_key:service_netscaleradc_desc->translation->language:es SET text = "Servicio Netscaler Adc para automatización";

-- Next Cloud
RELATE i18n_key:service_nextcloud_name->translation->language:fr SET text = "Next Cloud";
RELATE i18n_key:service_nextcloud_name->translation->language:en SET text = "Next Cloud";
RELATE i18n_key:service_nextcloud_name->translation->language:it SET text = "Next Cloud";
RELATE i18n_key:service_nextcloud_name->translation->language:de SET text = "Next Cloud";
RELATE i18n_key:service_nextcloud_name->translation->language:es SET text = "Next Cloud";
RELATE i18n_key:service_nextcloud_desc->translation->language:fr SET text = "Service Next Cloud pour automatisation";
RELATE i18n_key:service_nextcloud_desc->translation->language:en SET text = "Next Cloud service for automation";
RELATE i18n_key:service_nextcloud_desc->translation->language:it SET text = "Servizio Next Cloud per automazione";
RELATE i18n_key:service_nextcloud_desc->translation->language:de SET text = "Next Cloud-Dienst für Automatisierung";
RELATE i18n_key:service_nextcloud_desc->translation->language:es SET text = "Servicio Next Cloud para automatización";

-- Noco DB
RELATE i18n_key:service_nocodb_name->translation->language:fr SET text = "Noco DB";
RELATE i18n_key:service_nocodb_name->translation->language:en SET text = "Noco DB";
RELATE i18n_key:service_nocodb_name->translation->language:it SET text = "Noco DB";
RELATE i18n_key:service_nocodb_name->translation->language:de SET text = "Noco DB";
RELATE i18n_key:service_nocodb_name->translation->language:es SET text = "Noco DB";
RELATE i18n_key:service_nocodb_desc->translation->language:fr SET text = "Service Noco DB pour automatisation";
RELATE i18n_key:service_nocodb_desc->translation->language:en SET text = "Noco DB service for automation";
RELATE i18n_key:service_nocodb_desc->translation->language:it SET text = "Servizio Noco DB per automazione";
RELATE i18n_key:service_nocodb_desc->translation->language:de SET text = "Noco DB-Dienst für Automatisierung";
RELATE i18n_key:service_nocodb_desc->translation->language:es SET text = "Servicio Noco DB para automatización";

-- No Op
RELATE i18n_key:service_noop_name->translation->language:fr SET text = "No Op";
RELATE i18n_key:service_noop_name->translation->language:en SET text = "No Op";
RELATE i18n_key:service_noop_name->translation->language:it SET text = "No Op";
RELATE i18n_key:service_noop_name->translation->language:de SET text = "No Op";
RELATE i18n_key:service_noop_name->translation->language:es SET text = "No Op";
RELATE i18n_key:service_noop_desc->translation->language:fr SET text = "Service No Op pour automatisation";
RELATE i18n_key:service_noop_desc->translation->language:en SET text = "No Op service for automation";
RELATE i18n_key:service_noop_desc->translation->language:it SET text = "Servizio No Op per automazione";
RELATE i18n_key:service_noop_desc->translation->language:de SET text = "No Op-Dienst für Automatisierung";
RELATE i18n_key:service_noop_desc->translation->language:es SET text = "Servicio No Op para automatización";

-- Notion
RELATE i18n_key:service_notion_name->translation->language:fr SET text = "Notion";
RELATE i18n_key:service_notion_name->translation->language:en SET text = "Notion";
RELATE i18n_key:service_notion_name->translation->language:it SET text = "Notion";
RELATE i18n_key:service_notion_name->translation->language:de SET text = "Notion";
RELATE i18n_key:service_notion_name->translation->language:es SET text = "Notion";
RELATE i18n_key:service_notion_desc->translation->language:fr SET text = "Service Notion pour automatisation";
RELATE i18n_key:service_notion_desc->translation->language:en SET text = "Notion service for automation";
RELATE i18n_key:service_notion_desc->translation->language:it SET text = "Servizio Notion per automazione";
RELATE i18n_key:service_notion_desc->translation->language:de SET text = "Notion-Dienst für Automatisierung";
RELATE i18n_key:service_notion_desc->translation->language:es SET text = "Servicio Notion para automatización";

-- Notion V1
RELATE i18n_key:service_notionv1_name->translation->language:fr SET text = "Notion V1";
RELATE i18n_key:service_notionv1_name->translation->language:en SET text = "Notion V1";
RELATE i18n_key:service_notionv1_name->translation->language:it SET text = "Notion V1";
RELATE i18n_key:service_notionv1_name->translation->language:de SET text = "Notion V1";
RELATE i18n_key:service_notionv1_name->translation->language:es SET text = "Notion V1";
RELATE i18n_key:service_notionv1_desc->translation->language:fr SET text = "Service Notion V1 pour automatisation";
RELATE i18n_key:service_notionv1_desc->translation->language:en SET text = "Notion V1 service for automation";
RELATE i18n_key:service_notionv1_desc->translation->language:it SET text = "Servizio Notion V1 per automazione";
RELATE i18n_key:service_notionv1_desc->translation->language:de SET text = "Notion V1-Dienst für Automatisierung";
RELATE i18n_key:service_notionv1_desc->translation->language:es SET text = "Servicio Notion V1 para automatización";

-- Notion V2
RELATE i18n_key:service_notionv2_name->translation->language:fr SET text = "Notion V2";
RELATE i18n_key:service_notionv2_name->translation->language:en SET text = "Notion V2";
RELATE i18n_key:service_notionv2_name->translation->language:it SET text = "Notion V2";
RELATE i18n_key:service_notionv2_name->translation->language:de SET text = "Notion V2";
RELATE i18n_key:service_notionv2_name->translation->language:es SET text = "Notion V2";
RELATE i18n_key:service_notionv2_desc->translation->language:fr SET text = "Service Notion V2 pour automatisation";
RELATE i18n_key:service_notionv2_desc->translation->language:en SET text = "Notion V2 service for automation";
RELATE i18n_key:service_notionv2_desc->translation->language:it SET text = "Servizio Notion V2 per automazione";
RELATE i18n_key:service_notionv2_desc->translation->language:de SET text = "Notion V2-Dienst für Automatisierung";
RELATE i18n_key:service_notionv2_desc->translation->language:es SET text = "Servicio Notion V2 para automatización";

-- Npm
RELATE i18n_key:service_npm_name->translation->language:fr SET text = "Npm";
RELATE i18n_key:service_npm_name->translation->language:en SET text = "Npm";
RELATE i18n_key:service_npm_name->translation->language:it SET text = "Npm";
RELATE i18n_key:service_npm_name->translation->language:de SET text = "Npm";
RELATE i18n_key:service_npm_name->translation->language:es SET text = "Npm";
RELATE i18n_key:service_npm_desc->translation->language:fr SET text = "Service Npm pour automatisation";
RELATE i18n_key:service_npm_desc->translation->language:en SET text = "Npm service for automation";
RELATE i18n_key:service_npm_desc->translation->language:it SET text = "Servizio Npm per automazione";
RELATE i18n_key:service_npm_desc->translation->language:de SET text = "Npm-Dienst für Automatisierung";
RELATE i18n_key:service_npm_desc->translation->language:es SET text = "Servicio Npm para automatización";

-- Odoo
RELATE i18n_key:service_odoo_name->translation->language:fr SET text = "Odoo";
RELATE i18n_key:service_odoo_name->translation->language:en SET text = "Odoo";
RELATE i18n_key:service_odoo_name->translation->language:it SET text = "Odoo";
RELATE i18n_key:service_odoo_name->translation->language:de SET text = "Odoo";
RELATE i18n_key:service_odoo_name->translation->language:es SET text = "Odoo";
RELATE i18n_key:service_odoo_desc->translation->language:fr SET text = "Service Odoo pour automatisation";
RELATE i18n_key:service_odoo_desc->translation->language:en SET text = "Odoo service for automation";
RELATE i18n_key:service_odoo_desc->translation->language:it SET text = "Servizio Odoo per automazione";
RELATE i18n_key:service_odoo_desc->translation->language:de SET text = "Odoo-Dienst für Automatisierung";
RELATE i18n_key:service_odoo_desc->translation->language:es SET text = "Servicio Odoo para automatización";

-- Okta
RELATE i18n_key:service_okta_name->translation->language:fr SET text = "Okta";
RELATE i18n_key:service_okta_name->translation->language:en SET text = "Okta";
RELATE i18n_key:service_okta_name->translation->language:it SET text = "Okta";
RELATE i18n_key:service_okta_name->translation->language:de SET text = "Okta";
RELATE i18n_key:service_okta_name->translation->language:es SET text = "Okta";
RELATE i18n_key:service_okta_desc->translation->language:fr SET text = "Service Okta pour automatisation";
RELATE i18n_key:service_okta_desc->translation->language:en SET text = "Okta service for automation";
RELATE i18n_key:service_okta_desc->translation->language:it SET text = "Servizio Okta per automazione";
RELATE i18n_key:service_okta_desc->translation->language:de SET text = "Okta-Dienst für Automatisierung";
RELATE i18n_key:service_okta_desc->translation->language:es SET text = "Servicio Okta para automatización";

-- One Simple Api
RELATE i18n_key:service_onesimpleapi_name->translation->language:fr SET text = "One Simple Api";
RELATE i18n_key:service_onesimpleapi_name->translation->language:en SET text = "One Simple Api";
RELATE i18n_key:service_onesimpleapi_name->translation->language:it SET text = "One Simple Api";
RELATE i18n_key:service_onesimpleapi_name->translation->language:de SET text = "One Simple Api";
RELATE i18n_key:service_onesimpleapi_name->translation->language:es SET text = "One Simple Api";
RELATE i18n_key:service_onesimpleapi_desc->translation->language:fr SET text = "Service One Simple Api pour automatisation";
RELATE i18n_key:service_onesimpleapi_desc->translation->language:en SET text = "One Simple Api service for automation";
RELATE i18n_key:service_onesimpleapi_desc->translation->language:it SET text = "Servizio One Simple Api per automazione";
RELATE i18n_key:service_onesimpleapi_desc->translation->language:de SET text = "One Simple Api-Dienst für Automatisierung";
RELATE i18n_key:service_onesimpleapi_desc->translation->language:es SET text = "Servicio One Simple Api para automatización";

-- Onfleet
RELATE i18n_key:service_onfleet_name->translation->language:fr SET text = "Onfleet";
RELATE i18n_key:service_onfleet_name->translation->language:en SET text = "Onfleet";
RELATE i18n_key:service_onfleet_name->translation->language:it SET text = "Onfleet";
RELATE i18n_key:service_onfleet_name->translation->language:de SET text = "Onfleet";
RELATE i18n_key:service_onfleet_name->translation->language:es SET text = "Onfleet";
RELATE i18n_key:service_onfleet_desc->translation->language:fr SET text = "Service Onfleet pour automatisation";
RELATE i18n_key:service_onfleet_desc->translation->language:en SET text = "Onfleet service for automation";
RELATE i18n_key:service_onfleet_desc->translation->language:it SET text = "Servizio Onfleet per automazione";
RELATE i18n_key:service_onfleet_desc->translation->language:de SET text = "Onfleet-Dienst für Automatisierung";
RELATE i18n_key:service_onfleet_desc->translation->language:es SET text = "Servicio Onfleet para automatización";

-- Open Ai
RELATE i18n_key:service_openai_name->translation->language:fr SET text = "Open Ai";
RELATE i18n_key:service_openai_name->translation->language:en SET text = "Open Ai";
RELATE i18n_key:service_openai_name->translation->language:it SET text = "Open Ai";
RELATE i18n_key:service_openai_name->translation->language:de SET text = "Open Ai";
RELATE i18n_key:service_openai_name->translation->language:es SET text = "Open Ai";
RELATE i18n_key:service_openai_desc->translation->language:fr SET text = "Service Open Ai pour automatisation";
RELATE i18n_key:service_openai_desc->translation->language:en SET text = "Open Ai service for automation";
RELATE i18n_key:service_openai_desc->translation->language:it SET text = "Servizio Open Ai per automazione";
RELATE i18n_key:service_openai_desc->translation->language:de SET text = "Open Ai-Dienst für Automatisierung";
RELATE i18n_key:service_openai_desc->translation->language:es SET text = "Servicio Open Ai para automatización";

-- Open Thesaurus
RELATE i18n_key:service_openthesaurus_name->translation->language:fr SET text = "Open Thesaurus";
RELATE i18n_key:service_openthesaurus_name->translation->language:en SET text = "Open Thesaurus";
RELATE i18n_key:service_openthesaurus_name->translation->language:it SET text = "Open Thesaurus";
RELATE i18n_key:service_openthesaurus_name->translation->language:de SET text = "Open Thesaurus";
RELATE i18n_key:service_openthesaurus_name->translation->language:es SET text = "Open Thesaurus";
RELATE i18n_key:service_openthesaurus_desc->translation->language:fr SET text = "Service Open Thesaurus pour automatisation";
RELATE i18n_key:service_openthesaurus_desc->translation->language:en SET text = "Open Thesaurus service for automation";
RELATE i18n_key:service_openthesaurus_desc->translation->language:it SET text = "Servizio Open Thesaurus per automazione";
RELATE i18n_key:service_openthesaurus_desc->translation->language:de SET text = "Open Thesaurus-Dienst für Automatisierung";
RELATE i18n_key:service_openthesaurus_desc->translation->language:es SET text = "Servicio Open Thesaurus para automatización";

-- Open Weather Map
RELATE i18n_key:service_openweathermap_name->translation->language:fr SET text = "Open Weather Map";
RELATE i18n_key:service_openweathermap_name->translation->language:en SET text = "Open Weather Map";
RELATE i18n_key:service_openweathermap_name->translation->language:it SET text = "Open Weather Map";
RELATE i18n_key:service_openweathermap_name->translation->language:de SET text = "Open Weather Map";
RELATE i18n_key:service_openweathermap_name->translation->language:es SET text = "Open Weather Map";
RELATE i18n_key:service_openweathermap_desc->translation->language:fr SET text = "Service Open Weather Map pour automatisation";
RELATE i18n_key:service_openweathermap_desc->translation->language:en SET text = "Open Weather Map service for automation";
RELATE i18n_key:service_openweathermap_desc->translation->language:it SET text = "Servizio Open Weather Map per automazione";
RELATE i18n_key:service_openweathermap_desc->translation->language:de SET text = "Open Weather Map-Dienst für Automatisierung";
RELATE i18n_key:service_openweathermap_desc->translation->language:es SET text = "Servicio Open Weather Map para automatización";

-- Oracle Sql
RELATE i18n_key:service_oraclesql_name->translation->language:fr SET text = "Oracle Sql";
RELATE i18n_key:service_oraclesql_name->translation->language:en SET text = "Oracle Sql";
RELATE i18n_key:service_oraclesql_name->translation->language:it SET text = "Oracle Sql";
RELATE i18n_key:service_oraclesql_name->translation->language:de SET text = "Oracle Sql";
RELATE i18n_key:service_oraclesql_name->translation->language:es SET text = "Oracle Sql";
RELATE i18n_key:service_oraclesql_desc->translation->language:fr SET text = "Service Oracle Sql pour automatisation";
RELATE i18n_key:service_oraclesql_desc->translation->language:en SET text = "Oracle Sql service for automation";
RELATE i18n_key:service_oraclesql_desc->translation->language:it SET text = "Servizio Oracle Sql per automazione";
RELATE i18n_key:service_oraclesql_desc->translation->language:de SET text = "Oracle Sql-Dienst für Automatisierung";
RELATE i18n_key:service_oraclesql_desc->translation->language:es SET text = "Servicio Oracle Sql para automatización";

-- Orbit
RELATE i18n_key:service_orbit_name->translation->language:fr SET text = "Orbit";
RELATE i18n_key:service_orbit_name->translation->language:en SET text = "Orbit";
RELATE i18n_key:service_orbit_name->translation->language:it SET text = "Orbit";
RELATE i18n_key:service_orbit_name->translation->language:de SET text = "Orbit";
RELATE i18n_key:service_orbit_name->translation->language:es SET text = "Orbit";
RELATE i18n_key:service_orbit_desc->translation->language:fr SET text = "Service Orbit pour automatisation";
RELATE i18n_key:service_orbit_desc->translation->language:en SET text = "Orbit service for automation";
RELATE i18n_key:service_orbit_desc->translation->language:it SET text = "Servizio Orbit per automazione";
RELATE i18n_key:service_orbit_desc->translation->language:de SET text = "Orbit-Dienst für Automatisierung";
RELATE i18n_key:service_orbit_desc->translation->language:es SET text = "Servicio Orbit para automatización";

-- Oura
RELATE i18n_key:service_oura_name->translation->language:fr SET text = "Oura";
RELATE i18n_key:service_oura_name->translation->language:en SET text = "Oura";
RELATE i18n_key:service_oura_name->translation->language:it SET text = "Oura";
RELATE i18n_key:service_oura_name->translation->language:de SET text = "Oura";
RELATE i18n_key:service_oura_name->translation->language:es SET text = "Oura";
RELATE i18n_key:service_oura_desc->translation->language:fr SET text = "Service Oura pour automatisation";
RELATE i18n_key:service_oura_desc->translation->language:en SET text = "Oura service for automation";
RELATE i18n_key:service_oura_desc->translation->language:it SET text = "Servizio Oura per automazione";
RELATE i18n_key:service_oura_desc->translation->language:de SET text = "Oura-Dienst für Automatisierung";
RELATE i18n_key:service_oura_desc->translation->language:es SET text = "Servicio Oura para automatización";

-- Paddle
RELATE i18n_key:service_paddle_name->translation->language:fr SET text = "Paddle";
RELATE i18n_key:service_paddle_name->translation->language:en SET text = "Paddle";
RELATE i18n_key:service_paddle_name->translation->language:it SET text = "Paddle";
RELATE i18n_key:service_paddle_name->translation->language:de SET text = "Paddle";
RELATE i18n_key:service_paddle_name->translation->language:es SET text = "Paddle";
RELATE i18n_key:service_paddle_desc->translation->language:fr SET text = "Service Paddle pour automatisation";
RELATE i18n_key:service_paddle_desc->translation->language:en SET text = "Paddle service for automation";
RELATE i18n_key:service_paddle_desc->translation->language:it SET text = "Servizio Paddle per automazione";
RELATE i18n_key:service_paddle_desc->translation->language:de SET text = "Paddle-Dienst für Automatisierung";
RELATE i18n_key:service_paddle_desc->translation->language:es SET text = "Servicio Paddle para automatización";

-- Pager Duty
RELATE i18n_key:service_pagerduty_name->translation->language:fr SET text = "Pager Duty";
RELATE i18n_key:service_pagerduty_name->translation->language:en SET text = "Pager Duty";
RELATE i18n_key:service_pagerduty_name->translation->language:it SET text = "Pager Duty";
RELATE i18n_key:service_pagerduty_name->translation->language:de SET text = "Pager Duty";
RELATE i18n_key:service_pagerduty_name->translation->language:es SET text = "Pager Duty";
RELATE i18n_key:service_pagerduty_desc->translation->language:fr SET text = "Service Pager Duty pour automatisation";
RELATE i18n_key:service_pagerduty_desc->translation->language:en SET text = "Pager Duty service for automation";
RELATE i18n_key:service_pagerduty_desc->translation->language:it SET text = "Servizio Pager Duty per automazione";
RELATE i18n_key:service_pagerduty_desc->translation->language:de SET text = "Pager Duty-Dienst für Automatisierung";
RELATE i18n_key:service_pagerduty_desc->translation->language:es SET text = "Servicio Pager Duty para automatización";

