-- Batch 9: 200 traductions Lyxal (5 langues)

-- High Level V2
RELATE i18n_key:service_highlevelv2_name->translation->language:fr SET text = "High Level V2";
RELATE i18n_key:service_highlevelv2_name->translation->language:en SET text = "High Level V2";
RELATE i18n_key:service_highlevelv2_name->translation->language:it SET text = "High Level V2";
RELATE i18n_key:service_highlevelv2_name->translation->language:de SET text = "High Level V2";
RELATE i18n_key:service_highlevelv2_name->translation->language:es SET text = "High Level V2";
RELATE i18n_key:service_highlevelv2_desc->translation->language:fr SET text = "Service High Level V2 pour automatisation";
RELATE i18n_key:service_highlevelv2_desc->translation->language:en SET text = "High Level V2 service for automation";
RELATE i18n_key:service_highlevelv2_desc->translation->language:it SET text = "Servizio High Level V2 per automazione";
RELATE i18n_key:service_highlevelv2_desc->translation->language:de SET text = "High Level V2-Dienst für Automatisierung";
RELATE i18n_key:service_highlevelv2_desc->translation->language:es SET text = "Servicio High Level V2 para automatización";

-- Home Assistant
RELATE i18n_key:service_homeassistant_name->translation->language:fr SET text = "Home Assistant";
RELATE i18n_key:service_homeassistant_name->translation->language:en SET text = "Home Assistant";
RELATE i18n_key:service_homeassistant_name->translation->language:it SET text = "Home Assistant";
RELATE i18n_key:service_homeassistant_name->translation->language:de SET text = "Home Assistant";
RELATE i18n_key:service_homeassistant_name->translation->language:es SET text = "Home Assistant";
RELATE i18n_key:service_homeassistant_desc->translation->language:fr SET text = "Service Home Assistant pour automatisation";
RELATE i18n_key:service_homeassistant_desc->translation->language:en SET text = "Home Assistant service for automation";
RELATE i18n_key:service_homeassistant_desc->translation->language:it SET text = "Servizio Home Assistant per automazione";
RELATE i18n_key:service_homeassistant_desc->translation->language:de SET text = "Home Assistant-Dienst für Automatisierung";
RELATE i18n_key:service_homeassistant_desc->translation->language:es SET text = "Servicio Home Assistant para automatización";

-- Html
RELATE i18n_key:service_html_name->translation->language:fr SET text = "Html";
RELATE i18n_key:service_html_name->translation->language:en SET text = "Html";
RELATE i18n_key:service_html_name->translation->language:it SET text = "Html";
RELATE i18n_key:service_html_name->translation->language:de SET text = "Html";
RELATE i18n_key:service_html_name->translation->language:es SET text = "Html";
RELATE i18n_key:service_html_desc->translation->language:fr SET text = "Service Html pour automatisation";
RELATE i18n_key:service_html_desc->translation->language:en SET text = "Html service for automation";
RELATE i18n_key:service_html_desc->translation->language:it SET text = "Servizio Html per automazione";
RELATE i18n_key:service_html_desc->translation->language:de SET text = "Html-Dienst für Automatisierung";
RELATE i18n_key:service_html_desc->translation->language:es SET text = "Servicio Html para automatización";

-- Html Extract
RELATE i18n_key:service_htmlextract_name->translation->language:fr SET text = "Html Extract";
RELATE i18n_key:service_htmlextract_name->translation->language:en SET text = "Html Extract";
RELATE i18n_key:service_htmlextract_name->translation->language:it SET text = "Html Extract";
RELATE i18n_key:service_htmlextract_name->translation->language:de SET text = "Html Extract";
RELATE i18n_key:service_htmlextract_name->translation->language:es SET text = "Html Extract";
RELATE i18n_key:service_htmlextract_desc->translation->language:fr SET text = "Service Html Extract pour automatisation";
RELATE i18n_key:service_htmlextract_desc->translation->language:en SET text = "Html Extract service for automation";
RELATE i18n_key:service_htmlextract_desc->translation->language:it SET text = "Servizio Html Extract per automazione";
RELATE i18n_key:service_htmlextract_desc->translation->language:de SET text = "Html Extract-Dienst für Automatisierung";
RELATE i18n_key:service_htmlextract_desc->translation->language:es SET text = "Servicio Html Extract para automatización";

-- Http Request
RELATE i18n_key:service_httprequest_name->translation->language:fr SET text = "Http Request";
RELATE i18n_key:service_httprequest_name->translation->language:en SET text = "Http Request";
RELATE i18n_key:service_httprequest_name->translation->language:it SET text = "Http Request";
RELATE i18n_key:service_httprequest_name->translation->language:de SET text = "Http Request";
RELATE i18n_key:service_httprequest_name->translation->language:es SET text = "Http Request";
RELATE i18n_key:service_httprequest_desc->translation->language:fr SET text = "Service Http Request pour automatisation";
RELATE i18n_key:service_httprequest_desc->translation->language:en SET text = "Http Request service for automation";
RELATE i18n_key:service_httprequest_desc->translation->language:it SET text = "Servizio Http Request per automazione";
RELATE i18n_key:service_httprequest_desc->translation->language:de SET text = "Http Request-Dienst für Automatisierung";
RELATE i18n_key:service_httprequest_desc->translation->language:es SET text = "Servicio Http Request para automatización";

-- Http Request V1
RELATE i18n_key:service_httprequestv1_name->translation->language:fr SET text = "Http Request V1";
RELATE i18n_key:service_httprequestv1_name->translation->language:en SET text = "Http Request V1";
RELATE i18n_key:service_httprequestv1_name->translation->language:it SET text = "Http Request V1";
RELATE i18n_key:service_httprequestv1_name->translation->language:de SET text = "Http Request V1";
RELATE i18n_key:service_httprequestv1_name->translation->language:es SET text = "Http Request V1";
RELATE i18n_key:service_httprequestv1_desc->translation->language:fr SET text = "Service Http Request V1 pour automatisation";
RELATE i18n_key:service_httprequestv1_desc->translation->language:en SET text = "Http Request V1 service for automation";
RELATE i18n_key:service_httprequestv1_desc->translation->language:it SET text = "Servizio Http Request V1 per automazione";
RELATE i18n_key:service_httprequestv1_desc->translation->language:de SET text = "Http Request V1-Dienst für Automatisierung";
RELATE i18n_key:service_httprequestv1_desc->translation->language:es SET text = "Servicio Http Request V1 para automatización";

-- Http Request V2
RELATE i18n_key:service_httprequestv2_name->translation->language:fr SET text = "Http Request V2";
RELATE i18n_key:service_httprequestv2_name->translation->language:en SET text = "Http Request V2";
RELATE i18n_key:service_httprequestv2_name->translation->language:it SET text = "Http Request V2";
RELATE i18n_key:service_httprequestv2_name->translation->language:de SET text = "Http Request V2";
RELATE i18n_key:service_httprequestv2_name->translation->language:es SET text = "Http Request V2";
RELATE i18n_key:service_httprequestv2_desc->translation->language:fr SET text = "Service Http Request V2 pour automatisation";
RELATE i18n_key:service_httprequestv2_desc->translation->language:en SET text = "Http Request V2 service for automation";
RELATE i18n_key:service_httprequestv2_desc->translation->language:it SET text = "Servizio Http Request V2 per automazione";
RELATE i18n_key:service_httprequestv2_desc->translation->language:de SET text = "Http Request V2-Dienst für Automatisierung";
RELATE i18n_key:service_httprequestv2_desc->translation->language:es SET text = "Servicio Http Request V2 para automatización";

-- Http Request V3
RELATE i18n_key:service_httprequestv3_name->translation->language:fr SET text = "Http Request V3";
RELATE i18n_key:service_httprequestv3_name->translation->language:en SET text = "Http Request V3";
RELATE i18n_key:service_httprequestv3_name->translation->language:it SET text = "Http Request V3";
RELATE i18n_key:service_httprequestv3_name->translation->language:de SET text = "Http Request V3";
RELATE i18n_key:service_httprequestv3_name->translation->language:es SET text = "Http Request V3";
RELATE i18n_key:service_httprequestv3_desc->translation->language:fr SET text = "Service Http Request V3 pour automatisation";
RELATE i18n_key:service_httprequestv3_desc->translation->language:en SET text = "Http Request V3 service for automation";
RELATE i18n_key:service_httprequestv3_desc->translation->language:it SET text = "Servizio Http Request V3 per automazione";
RELATE i18n_key:service_httprequestv3_desc->translation->language:de SET text = "Http Request V3-Dienst für Automatisierung";
RELATE i18n_key:service_httprequestv3_desc->translation->language:es SET text = "Servicio Http Request V3 para automatización";

-- Hubspot
RELATE i18n_key:service_hubspot_name->translation->language:fr SET text = "Hubspot";
RELATE i18n_key:service_hubspot_name->translation->language:en SET text = "Hubspot";
RELATE i18n_key:service_hubspot_name->translation->language:it SET text = "Hubspot";
RELATE i18n_key:service_hubspot_name->translation->language:de SET text = "Hubspot";
RELATE i18n_key:service_hubspot_name->translation->language:es SET text = "Hubspot";
RELATE i18n_key:service_hubspot_desc->translation->language:fr SET text = "Service Hubspot pour automatisation";
RELATE i18n_key:service_hubspot_desc->translation->language:en SET text = "Hubspot service for automation";
RELATE i18n_key:service_hubspot_desc->translation->language:it SET text = "Servizio Hubspot per automazione";
RELATE i18n_key:service_hubspot_desc->translation->language:de SET text = "Hubspot-Dienst für Automatisierung";
RELATE i18n_key:service_hubspot_desc->translation->language:es SET text = "Servicio Hubspot para automatización";

-- Hubspot V1
RELATE i18n_key:service_hubspotv1_name->translation->language:fr SET text = "Hubspot V1";
RELATE i18n_key:service_hubspotv1_name->translation->language:en SET text = "Hubspot V1";
RELATE i18n_key:service_hubspotv1_name->translation->language:it SET text = "Hubspot V1";
RELATE i18n_key:service_hubspotv1_name->translation->language:de SET text = "Hubspot V1";
RELATE i18n_key:service_hubspotv1_name->translation->language:es SET text = "Hubspot V1";
RELATE i18n_key:service_hubspotv1_desc->translation->language:fr SET text = "Service Hubspot V1 pour automatisation";
RELATE i18n_key:service_hubspotv1_desc->translation->language:en SET text = "Hubspot V1 service for automation";
RELATE i18n_key:service_hubspotv1_desc->translation->language:it SET text = "Servizio Hubspot V1 per automazione";
RELATE i18n_key:service_hubspotv1_desc->translation->language:de SET text = "Hubspot V1-Dienst für Automatisierung";
RELATE i18n_key:service_hubspotv1_desc->translation->language:es SET text = "Servicio Hubspot V1 para automatización";

-- Hubspot V2
RELATE i18n_key:service_hubspotv2_name->translation->language:fr SET text = "Hubspot V2";
RELATE i18n_key:service_hubspotv2_name->translation->language:en SET text = "Hubspot V2";
RELATE i18n_key:service_hubspotv2_name->translation->language:it SET text = "Hubspot V2";
RELATE i18n_key:service_hubspotv2_name->translation->language:de SET text = "Hubspot V2";
RELATE i18n_key:service_hubspotv2_name->translation->language:es SET text = "Hubspot V2";
RELATE i18n_key:service_hubspotv2_desc->translation->language:fr SET text = "Service Hubspot V2 pour automatisation";
RELATE i18n_key:service_hubspotv2_desc->translation->language:en SET text = "Hubspot V2 service for automation";
RELATE i18n_key:service_hubspotv2_desc->translation->language:it SET text = "Servizio Hubspot V2 per automazione";
RELATE i18n_key:service_hubspotv2_desc->translation->language:de SET text = "Hubspot V2-Dienst für Automatisierung";
RELATE i18n_key:service_hubspotv2_desc->translation->language:es SET text = "Servicio Hubspot V2 para automatización";

-- Humantic Ai
RELATE i18n_key:service_humanticai_name->translation->language:fr SET text = "Humantic Ai";
RELATE i18n_key:service_humanticai_name->translation->language:en SET text = "Humantic Ai";
RELATE i18n_key:service_humanticai_name->translation->language:it SET text = "Humantic Ai";
RELATE i18n_key:service_humanticai_name->translation->language:de SET text = "Humantic Ai";
RELATE i18n_key:service_humanticai_name->translation->language:es SET text = "Humantic Ai";
RELATE i18n_key:service_humanticai_desc->translation->language:fr SET text = "Service Humantic Ai pour automatisation";
RELATE i18n_key:service_humanticai_desc->translation->language:en SET text = "Humantic Ai service for automation";
RELATE i18n_key:service_humanticai_desc->translation->language:it SET text = "Servizio Humantic Ai per automazione";
RELATE i18n_key:service_humanticai_desc->translation->language:de SET text = "Humantic Ai-Dienst für Automatisierung";
RELATE i18n_key:service_humanticai_desc->translation->language:es SET text = "Servicio Humantic Ai para automatización";

-- Hunter
RELATE i18n_key:service_hunter_name->translation->language:fr SET text = "Hunter";
RELATE i18n_key:service_hunter_name->translation->language:en SET text = "Hunter";
RELATE i18n_key:service_hunter_name->translation->language:it SET text = "Hunter";
RELATE i18n_key:service_hunter_name->translation->language:de SET text = "Hunter";
RELATE i18n_key:service_hunter_name->translation->language:es SET text = "Hunter";
RELATE i18n_key:service_hunter_desc->translation->language:fr SET text = "Service Hunter pour automatisation";
RELATE i18n_key:service_hunter_desc->translation->language:en SET text = "Hunter service for automation";
RELATE i18n_key:service_hunter_desc->translation->language:it SET text = "Servizio Hunter per automazione";
RELATE i18n_key:service_hunter_desc->translation->language:de SET text = "Hunter-Dienst für Automatisierung";
RELATE i18n_key:service_hunter_desc->translation->language:es SET text = "Servicio Hunter para automatización";

-- ICalendar
RELATE i18n_key:service_icalendar_name->translation->language:fr SET text = "ICalendar";
RELATE i18n_key:service_icalendar_name->translation->language:en SET text = "ICalendar";
RELATE i18n_key:service_icalendar_name->translation->language:it SET text = "ICalendar";
RELATE i18n_key:service_icalendar_name->translation->language:de SET text = "ICalendar";
RELATE i18n_key:service_icalendar_name->translation->language:es SET text = "ICalendar";
RELATE i18n_key:service_icalendar_desc->translation->language:fr SET text = "Service ICalendar pour automatisation";
RELATE i18n_key:service_icalendar_desc->translation->language:en SET text = "ICalendar service for automation";
RELATE i18n_key:service_icalendar_desc->translation->language:it SET text = "Servizio ICalendar per automazione";
RELATE i18n_key:service_icalendar_desc->translation->language:de SET text = "ICalendar-Dienst für Automatisierung";
RELATE i18n_key:service_icalendar_desc->translation->language:es SET text = "Servicio ICalendar para automatización";

-- If
RELATE i18n_key:service_if_name->translation->language:fr SET text = "If";
RELATE i18n_key:service_if_name->translation->language:en SET text = "If";
RELATE i18n_key:service_if_name->translation->language:it SET text = "If";
RELATE i18n_key:service_if_name->translation->language:de SET text = "If";
RELATE i18n_key:service_if_name->translation->language:es SET text = "If";
RELATE i18n_key:service_if_desc->translation->language:fr SET text = "Service If pour automatisation";
RELATE i18n_key:service_if_desc->translation->language:en SET text = "If service for automation";
RELATE i18n_key:service_if_desc->translation->language:it SET text = "Servizio If per automazione";
RELATE i18n_key:service_if_desc->translation->language:de SET text = "If-Dienst für Automatisierung";
RELATE i18n_key:service_if_desc->translation->language:es SET text = "Servicio If para automatización";

-- If V1
RELATE i18n_key:service_ifv1_name->translation->language:fr SET text = "If V1";
RELATE i18n_key:service_ifv1_name->translation->language:en SET text = "If V1";
RELATE i18n_key:service_ifv1_name->translation->language:it SET text = "If V1";
RELATE i18n_key:service_ifv1_name->translation->language:de SET text = "If V1";
RELATE i18n_key:service_ifv1_name->translation->language:es SET text = "If V1";
RELATE i18n_key:service_ifv1_desc->translation->language:fr SET text = "Service If V1 pour automatisation";
RELATE i18n_key:service_ifv1_desc->translation->language:en SET text = "If V1 service for automation";
RELATE i18n_key:service_ifv1_desc->translation->language:it SET text = "Servizio If V1 per automazione";
RELATE i18n_key:service_ifv1_desc->translation->language:de SET text = "If V1-Dienst für Automatisierung";
RELATE i18n_key:service_ifv1_desc->translation->language:es SET text = "Servicio If V1 para automatización";

-- If V2
RELATE i18n_key:service_ifv2_name->translation->language:fr SET text = "If V2";
RELATE i18n_key:service_ifv2_name->translation->language:en SET text = "If V2";
RELATE i18n_key:service_ifv2_name->translation->language:it SET text = "If V2";
RELATE i18n_key:service_ifv2_name->translation->language:de SET text = "If V2";
RELATE i18n_key:service_ifv2_name->translation->language:es SET text = "If V2";
RELATE i18n_key:service_ifv2_desc->translation->language:fr SET text = "Service If V2 pour automatisation";
RELATE i18n_key:service_ifv2_desc->translation->language:en SET text = "If V2 service for automation";
RELATE i18n_key:service_ifv2_desc->translation->language:it SET text = "Servizio If V2 per automazione";
RELATE i18n_key:service_ifv2_desc->translation->language:de SET text = "If V2-Dienst für Automatisierung";
RELATE i18n_key:service_ifv2_desc->translation->language:es SET text = "Servicio If V2 para automatización";

-- Intercom
RELATE i18n_key:service_intercom_name->translation->language:fr SET text = "Intercom";
RELATE i18n_key:service_intercom_name->translation->language:en SET text = "Intercom";
RELATE i18n_key:service_intercom_name->translation->language:it SET text = "Intercom";
RELATE i18n_key:service_intercom_name->translation->language:de SET text = "Intercom";
RELATE i18n_key:service_intercom_name->translation->language:es SET text = "Intercom";
RELATE i18n_key:service_intercom_desc->translation->language:fr SET text = "Service Intercom pour automatisation";
RELATE i18n_key:service_intercom_desc->translation->language:en SET text = "Intercom service for automation";
RELATE i18n_key:service_intercom_desc->translation->language:it SET text = "Servizio Intercom per automazione";
RELATE i18n_key:service_intercom_desc->translation->language:de SET text = "Intercom-Dienst für Automatisierung";
RELATE i18n_key:service_intercom_desc->translation->language:es SET text = "Servicio Intercom para automatización";

-- Interval
RELATE i18n_key:service_interval_name->translation->language:fr SET text = "Interval";
RELATE i18n_key:service_interval_name->translation->language:en SET text = "Interval";
RELATE i18n_key:service_interval_name->translation->language:it SET text = "Interval";
RELATE i18n_key:service_interval_name->translation->language:de SET text = "Interval";
RELATE i18n_key:service_interval_name->translation->language:es SET text = "Interval";
RELATE i18n_key:service_interval_desc->translation->language:fr SET text = "Service Interval pour automatisation";
RELATE i18n_key:service_interval_desc->translation->language:en SET text = "Interval service for automation";
RELATE i18n_key:service_interval_desc->translation->language:it SET text = "Servizio Interval per automazione";
RELATE i18n_key:service_interval_desc->translation->language:de SET text = "Interval-Dienst für Automatisierung";
RELATE i18n_key:service_interval_desc->translation->language:es SET text = "Servicio Interval para automatización";

-- Invoice Ninja
RELATE i18n_key:service_invoiceninja_name->translation->language:fr SET text = "Invoice Ninja";
RELATE i18n_key:service_invoiceninja_name->translation->language:en SET text = "Invoice Ninja";
RELATE i18n_key:service_invoiceninja_name->translation->language:it SET text = "Invoice Ninja";
RELATE i18n_key:service_invoiceninja_name->translation->language:de SET text = "Invoice Ninja";
RELATE i18n_key:service_invoiceninja_name->translation->language:es SET text = "Invoice Ninja";
RELATE i18n_key:service_invoiceninja_desc->translation->language:fr SET text = "Service Invoice Ninja pour automatisation";
RELATE i18n_key:service_invoiceninja_desc->translation->language:en SET text = "Invoice Ninja service for automation";
RELATE i18n_key:service_invoiceninja_desc->translation->language:it SET text = "Servizio Invoice Ninja per automazione";
RELATE i18n_key:service_invoiceninja_desc->translation->language:de SET text = "Invoice Ninja-Dienst für Automatisierung";
RELATE i18n_key:service_invoiceninja_desc->translation->language:es SET text = "Servicio Invoice Ninja para automatización";

