[workspace]
members = ["printer", "cli", "formatter", "prettyplease"]
resolver = "2"

[workspace.package]
version = "0.8.0"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
leptosfmt-prettyplease = { path = "./prettyplease", features = [
    "verbatim",
] }
leptosfmt-formatter = { path = "./formatter" }
leptosfmt-pretty-printer = { version = "0.8.0" }

syn = { version = "*", features = ["visit", "full", "extra-traits"] }
proc-macro2 = { version = "*", features = ["span-locations"] }

[patch.crates-io]
leptosfmt-pretty-printer = { path = "./printer" }





