
[workspace.package]
edition = "2024"

[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"

[workspace.dependencies]
leptos-fluent = { ${2} }
end2end-csr-helpers = { path = "./tests/end2end/csr/helpers" }
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3"
gloo-utils = { version = "*", default-features = false }
fluent-templates = { version = "*", default-features = false, features = [
  "macros",
  "walkdir",
] }
leptos-fluent-csr-minimal-example = { path = "./examples/csr-minimal" }
leptos-fluent-csr-complete-example = { path = "./examples/csr-complete" }
web-sys-ec = "0.1.0"







