-- Seeds pour les villes du pays: GD --

CREATE base_city:gd_52030 SET state = base_state:gd_10, key.name = i18n_key:i18n_city_gd_52030_name, native = 'Hillsborough', location = (-61.45597000, 12.48292000), timezone = base_timezone:america_caracas, wikiDataId = 'Q3267362';
CREATE base_city:gd_52029 SET state = base_state:gd_01, key.name = i18n_key:i18n_city_gd_52029_name, native = 'Grenville', location = (-61.62498000, 12.12278000), timezone = base_timezone:america_caracas, wikiDataId = 'Q3116519';
CREATE base_city:gd_52031 SET state = base_state:gd_02, key.name = i18n_key:i18n_city_gd_52031_name, native = 'Saint David’s', location = (-61.66875000, 12.04903000), timezone = base_timezone:america_caracas, wikiDataId = 'Q3267362';
CREATE base_city:gd_52032 SET state = base_state:gd_03, key.name = i18n_key:i18n_city_gd_52032_name, native = 'Saint George\'s', location = (-61.75226000, 12.05288000), timezone = base_timezone:america_caracas, wikiDataId = 'Q41547';
CREATE base_city:gd_52028 SET state = base_state:gd_04, key.name = i18n_key:i18n_city_gd_52028_name, native = 'Fruit', location = (-61.72965000, 12.16462000), timezone = base_timezone:america_caracas, wikiDataId = 'Q375507';
CREATE base_city:gd_52034 SET state = base_state:gd_05, key.name = i18n_key:i18n_city_gd_52034_name, native = 'Victoria', location = (-61.70677000, 12.19021000), timezone = base_timezone:america_caracas, wikiDataId = 'Q12874663';
CREATE base_city:gd_52033 SET state = base_state:gd_06, key.name = i18n_key:i18n_city_gd_52033_name, native = 'Jumper', location = (-61.63917000, 12.21833000), timezone = base_timezone:america_caracas, wikiDataId = 'Q1318103';
