[package]
name = "tachys"
version = "0.8.0"
edition = "2024"

[dependencies]
next_tuple = { path = "../next_tuple" }
html-escape = { version = "0.8.0" }
erased = { version = "*" }
reactive_graph = { path = "../reactive_graph", version = "*" }
wasm-bindgen = { version = "*" }
web-sys = { version = "*", features = ["Element", "Node"] }

[features]
islands = []
nonce = []
nightly = []
csr = []
ssr = []
hydrate = []


[build-dependencies]
rustc_version = "*"





