[package]
name = "webrtc-media"
version = "0.11.0"
edition = "2024"
description = "A pure Rust implementation of WebRTC Media API"

[dependencies]
rtp = { version = "0.14.0", path = "../rtp" }

byteorder = "1"
bytes = "1"
thiserror = "1"
rand = "0.9"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
nearly_eq = "0.2"

[[bench]]
name = "audio_buffer"
harness = false
