### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\logic\lyx_logic_router\lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_lyx-core-lyx_core_lyx-logic-lyx_logic_lyx-logic-lyx_logic_leptos_typed_router_macro\src\lib.rs
use proc_macro::TokenStream;

mod route;

#[proc_macro_attribute]
pub fn route(args: TokenStream, tokens: TokenStream) -> TokenStream {
route::route_impl(args, tokens)
}
