[package]
name = "lyx-core-superposition"
version = "0.0.1"
edition = "2024"

[dependencies]
actix-files = { version = "0.0.1" }
actix-web = { version = "0.0.1" }
anyhow = { version = "0.0.1" }
aws-sdk-kms = { version = "0.0.1" }
chrono = { version = "0.0.1" }
lyx-core-context_aware_config = { path = "../context_aware_config", version = "0.0.1", optional = true }
diesel = { version = "0.0.1" }
dotenv = { version = "0.0.1" }
lyx-core-experimentation_platform = { path = "../experimentation_platform", version = "0.0.1" }
fred = { version = "0.0.1", optional = true }
lyx-platform-frontend = { path = "../../../../platform/lyx-plat-tauri/frontend", version = "0.0.1" }
idgenerator = { version = "0.0.1" }
lyx-core-leptos = { path = "../../../lyx-core-leptos/leptos", version = "0.0.1" }
lyx-core-actix = { path = "../../../lyx-core-leptos/integrations/actix", version = "0.0.1" }
log = { version = "0.0.1" }
regex = { version = "0.0.1" }
reqwest = { version = "0.0.1" }
rs-snowflake = { version = "0.0.1" }
serde = { version = "0.0.1" }
serde_json = { version = "0.0.1" }
lyx-core-service_utils = { path = "../service_utils", version = "0.0.1", optional = true }
lyx-core-superposition_derives = { path = "../superposition_derives", version = "0.0.1" }
lyx-core-superposition_macros = { path = "../superposition_macros", version = "0.0.1" }
lyx-core-superposition_types = { path = "../superposition_types", version = "0.0.1", features = ["api", "diesel_derives", "server" ] }
actix-http = { version = "0.0.1" }
tracing = { version = "0.0.1" }
tracing-subscriber = { version = "0.0.1" }
tracing-actix-web = { version = "0.0.1" }
json-subscriber = { version = "0.0.1", features = ["tracing-log"] }

[features]
high-performance-mode = [
"lyx-core-context_aware_config/high-performance-mode",
"lyx-core-service_utils/high-performance-mode",
"dep:fred" ]
