[package]
name = "superposition"
version = "0.8.0"
edition = "2024"

[dependencies]
actix-files = { version = "*" }
actix-web = { version = "*" }
anyhow = { version = "*" }
aws-sdk-kms = { version = "*" }
chrono = { version = "*" }
context_aware_config = { path = "../context_aware_config", optional = true }
diesel = { version = "*" }
dotenv = { version = "*" }
experimentation_platform = { path = "../experimentation_platform" }
fred = { version = "*", optional = true }
lyx-platform-frontend = { path = "../../../../platform/lyx-plat-tauri/frontend" }
idgenerator = { version = "*" }
leptos = { path = "../../../leptos/leptos" }
leptos_actix = { path = "../../../leptos/integrations/actix" }
log = { version = "*" }
regex = { version = "*" }
reqwest = { version = "*" }
rs-snowflake = { version = "*" }
serde = { version = "*" }
serde_json = { version = "*" }
service_utils = { path = "../service_utils", optional = true }
superposition_derives = { path = "../superposition_derives" }
superposition_macros = { path = "../superposition_macros" }
superposition_types = { path = "../superposition_types", features = ["api", "diesel_derives", "server" ] }
actix-http = { version = "*" }
tracing = { version = "*" }
tracing-subscriber = { version = "*" }
tracing-actix-web = { version = "*" }
json-subscriber = { version = "*", features = ["tracing-log"] }

[features]
high-performance-mode = [
"context_aware_config/high-performance-mode",
"service_utils/high-performance-mode",
"dep:fred" ]










