[package]
name = "leptos_i18n_codegen"
version = "0.8.0"
edition = "2024"

[dependencies]


proc-macro2 = { version = "*" }
quote = { version = "*" }
syn = { version = "*" }
icu_locale = { version = "*", features = ["compiled_data"] }
leptos_i18n_parser = { path = "../leptos_i18n_parser", optional = true }
tinystr = { version = "*" }

[features]
default = []
islands = []
dynamic_load = []
hydrate = []
csr = []
ssr = []
plurals = ["leptos_i18n_parser/plurals"]
format_datetime = ["leptos_i18n_parser/format_datetime"]
format_list = ["leptos_i18n_parser/format_list"]
format_nums = ["leptos_i18n_parser/format_nums"]
format_currency = ["leptos_i18n_parser/format_currency", "format_nums"]







