name: oxyde-cloud-deploy-action
description: Deploys your app to Oxyde Cloud
author: Maccesch <maccesch@synphonyte.com>
inputs:
  error:
    description: 'The error message to display, if any'
    required: false
    default: ''
  token:
    description: 'The GitHub token to use for downloading the action, defaults to workflow token'
    required: true
    default: ${{ github.token }}
  api-token:
    description: 'The Oxyde Cloud API token to use for deploying'
    required: true
  cloud-config-file:
    description: 'The path to the oxyde-cloud.toml to use'
    required: false
    default: 'oxyde-cloud.toml'
  debug:
    description: 'Enable debug logging'
    required: false
    default: ''
outputs:
  error:
    description: 'The description of any error that occurred'
    value: ${{ steps.run.outputs.error }}

runs:
  using: 'composite'
  steps:
    - name: Check if api-token is set
      shell: bash
      run: |
        [[ "${{ inputs.api-token }}" ]] || { echo "api-token is not set" ; exit 1; }
  
    - name: Set reusable variables
      shell: bash
      run: |
        echo "action_repo=oxyde-cloud-deploy-action" >> $GITHUB_ENV
        echo "action_org=Synphonyte" >> $GITHUB_ENV
        echo "binary_name=oxyde-cloud-deploy-action" >> $GITHUB_ENV

    - name: Add binary extension
      shell: bash
      if: runner.os == 'Windows'
      run: echo "binary_name=${{ env.binary_name }}.exe" >> $GITHUB_ENV

    - name: Get Action Version
      id: get_action_version
      shell: bash
      run: |
        finalComponent=$(basename "${{ github.action_path }}")
        if [ "$finalComponent" = "${{ env.action_repo }}" ]; then
          version=""
        else
          version="$finalComponent"
        fi
        echo "version=$version" >> "$GITHUB_OUTPUT"

    - name: Download Action
      shell: bash
      run: |
        gh release download ${{ steps.get_action_version.outputs.version }} --repo ${{ env.action_org }}/${{ env.action_repo }} --pattern '${{ runner.os }}.tgz'
        tar -xzf ${{ runner.os }}.tgz
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Run Action
      shell: bash
      id: run
      run: ./${{ runner.os }}/${{ env.binary_name }} "${{ inputs.error }}" "${{ inputs.api-token }}" "${{ inputs.cloud-config-file }}" "${{ inputs.debug }}"
