-- Clés i18n pour les villes du pays: FJ --

CREATE i18n_key:i18n_city_fj_39145_name SET description = 'Nom pour la ville \'Naitasiri Province\'';
CREATE i18n_key:i18n_city_fj_39146_name SET description = 'Nom pour la ville \'Namosi Province\'';
CREATE i18n_key:i18n_city_fj_39149_name SET description = 'Nom pour la ville \'Rewa Province\'';
CREATE i18n_key:i18n_city_fj_39150_name SET description = 'Nom pour la ville \'Serua Province\'';
CREATE i18n_key:i18n_city_fj_39151_name SET description = 'Nom pour la ville \'Suva\'';
CREATE i18n_key:i18n_city_fj_39152_name SET description = 'Nom pour la ville \'Tailevu Province\'';
CREATE i18n_key:i18n_city_fj_39137_name SET description = 'Nom pour la ville \'Kadavu Province\'';
CREATE i18n_key:i18n_city_fj_39139_name SET description = 'Nom pour la ville \'Lau Province\'';
CREATE i18n_key:i18n_city_fj_39141_name SET description = 'Nom pour la ville \'Levuka\'';
CREATE i18n_key:i18n_city_fj_39142_name SET description = 'Nom pour la ville \'Lomaiviti Province\'';
CREATE i18n_key:i18n_city_fj_39135_name SET description = 'Nom pour la ville \'Bua Province\'';
CREATE i18n_key:i18n_city_fj_39136_name SET description = 'Nom pour la ville \'Cakaudrove Province\'';
CREATE i18n_key:i18n_city_fj_39138_name SET description = 'Nom pour la ville \'Labasa\'';
CREATE i18n_key:i18n_city_fj_39143_name SET description = 'Nom pour la ville \'Macuata Province\'';
CREATE i18n_key:i18n_city_fj_39133_name SET description = 'Nom pour la ville \'Ba\'';
CREATE i18n_key:i18n_city_fj_39134_name SET description = 'Nom pour la ville \'Ba Province\'';
CREATE i18n_key:i18n_city_fj_39140_name SET description = 'Nom pour la ville \'Lautoka\'';
CREATE i18n_key:i18n_city_fj_39144_name SET description = 'Nom pour la ville \'Nadi\'';
CREATE i18n_key:i18n_city_fj_39147_name SET description = 'Nom pour la ville \'Nandronga and Navosa Province\'';
CREATE i18n_key:i18n_city_fj_39148_name SET description = 'Nom pour la ville \'Ra Province\'';
