-- Clés i18n pour les villes du pays: VC --

CREATE i18n_key:i18n_city_vc_130030_name SET description = 'Nom pour la ville \'Biabou\'';
CREATE i18n_key:i18n_city_vc_130031_name SET description = 'Nom pour la ville \'Byera Village\'';
CREATE i18n_key:i18n_city_vc_130033_name SET description = 'Nom pour la ville \'Georgetown\'';
CREATE i18n_key:i18n_city_vc_130037_name SET description = 'Nom pour la ville \'Port Elizabeth\'';
CREATE i18n_key:i18n_city_vc_130036_name SET description = 'Nom pour la ville \'Layou\'';
CREATE i18n_key:i18n_city_vc_130032_name SET description = 'Nom pour la ville \'Chateaubelair\'';
CREATE i18n_key:i18n_city_vc_130034_name SET description = 'Nom pour la ville \'Kingstown\'';
CREATE i18n_key:i18n_city_vc_130035_name SET description = 'Nom pour la ville \'Kingstown Park\'';
CREATE i18n_key:i18n_city_vc_130029_name SET description = 'Nom pour la ville \'Barrouallie\'';
