-- Seeds pour les villes du pays: VC --

CREATE base_city:vc_130030 SET state = base_state:vc_01, key.name = i18n_key:i18n_city_vc_130030_name, native = 'Biabou', location = (-61.13904000, 13.19430000), timezone = base_timezone:america_caracas, wikiDataId = 'Q767607';
CREATE base_city:vc_130031 SET state = base_state:vc_01, key.name = i18n_key:i18n_city_vc_130031_name, native = 'Byera Village', location = (-61.11954000, 13.25636000), timezone = base_timezone:america_caracas, wikiDataId = 'Q5004057';
CREATE base_city:vc_130033 SET state = base_state:vc_01, key.name = i18n_key:i18n_city_vc_130033_name, native = 'Georgetown', location = (-61.11850000, 13.28054000), timezone = base_timezone:america_caracas, wikiDataId = 'Q2495209';
CREATE base_city:vc_130037 SET state = base_state:vc_06, key.name = i18n_key:i18n_city_vc_130037_name, native = 'Port Elizabeth', location = (-61.23548000, 13.01102000), timezone = base_timezone:america_caracas, wikiDataId = 'Q2995389';
CREATE base_city:vc_130036 SET state = base_state:vc_02, key.name = i18n_key:i18n_city_vc_130036_name, native = 'Layou', location = (-61.27014000, 13.20175000), timezone = base_timezone:america_caracas, wikiDataId = 'Q2630835';
CREATE base_city:vc_130032 SET state = base_state:vc_03, key.name = i18n_key:i18n_city_vc_130032_name, native = 'Chateaubelair', location = (-61.24043000, 13.29069000), timezone = base_timezone:america_caracas, wikiDataId = 'Q672197';
CREATE base_city:vc_130034 SET state = base_state:vc_04, key.name = i18n_key:i18n_city_vc_130034_name, native = 'Kingstown', location = (-61.22742000, 13.15527000), timezone = base_timezone:america_caracas, wikiDataId = 'Q41474';
CREATE base_city:vc_130035 SET state = base_state:vc_04, key.name = i18n_key:i18n_city_vc_130035_name, native = 'Kingstown Park', location = (-61.23161000, 13.15924000), timezone = base_timezone:america_caracas, wikiDataId = 'Q41474';
CREATE base_city:vc_130029 SET state = base_state:vc_05, key.name = i18n_key:i18n_city_vc_130029_name, native = 'Barrouallie', location = (-61.27275000, 13.23676000), timezone = base_timezone:america_caracas, wikiDataId = 'Q2885705';
