[package]
name = "meta"
version = "*"
edition = "2024"

[dependencies]
leptos = { path = "../leptos", version = "*", optional = true }
or_poisoned = { path = "../or_poisoned", version = "*" }
indexmap = { version = "*" }
send_wrapper = { version = "*" }
tracing = { version = "*", optional = true }
wasm-bindgen = { version = "*" }
futures = { version = "*" }
web-sys = { version = "*", features = ["HtmlLinkElement", "HtmlMetaElement", "HtmlTitleElement"], optional = true }

[features]
nonce = []
nightly = []
hydrate = []
ssr = []
csr = []


[build-dependencies]
rustc_version = "*"


