# Stage 1: Builder
FROM docker.io/rockylinux/rockylinux:9 AS builder

RUN dnf install -y gcc-toolset-13 git cmake llvm-toolset patch zlib-devel python3.11

# Install rust
ARG RUST_VERSION=1.91.1
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > /tmp/rustup.sh
RUN bash /tmp/rustup.sh -y --default-toolchain ${RUST_VERSION}
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /surrealdb
COPY . .

# Build the binary
RUN cargo build --release

# Stage 2: Runtime
FROM cgr.dev/chainguard/glibc-dynamic:latest

COPY --from=builder /surrealdb/target/release/surreal /surreal

USER root
RUN chmod +x /surreal
RUN mkdir /data /logs \
	&& chown -R nonroot:nonroot /data \
	&& chmod -R 777 /data \
	&& chown -R nonroot:nonroot /logs \
	&& chmod -R 777 /logs

VOLUME /data /logs
ENV SURREAL_BIND="0.0.0.0:8000"

ENTRYPOINT ["/surreal"]
CMD ["start", "--log", "info", "--user", "root", "--pass", "root", "memory"]
