[package]
name = "reactive_graph"
version = "0.8.0"
edition = "2024"
[dependencies]
any_spawner = { path = "../any_spawner", version = "*" }
or_poisoned = { path = "../or_poisoned", version = "*" }
futures = { version = "*", default-features = true }
hydration_context = { path = "../hydration_context", version = "*", optional = true }
pin-project-lite = { version = "*", default-features = true }
rustc-hash = { version = "*", default-features = true }
serde = { version = "*", optional = true, features = ["derive" ], default-features = true }
slotmap = { version = "*", default-features = true }
thiserror = { version = "*", default-features = true }
tracing = { version = "*", optional = true, default-features = true }
guardian = { version = "*", default-features = true }
async-lock = { version = "*", default-features = true }
send_wrapper = { version = "*", features = ["futures" ], default-features = true }
subsecond = { version = "*", optional = true, default-features = true }
indexmap = { version = "*", default-features = true }
paste = { version = "*", default-features = true }
[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
web-sys = { version = "*", features = ["console"] }
[dev-dependencies]
tokio = { version = "*", features = ["rt-multi-thread", "macros" ], default-features = true }
tokio-test = { version = "*", default-features = true }
any_spawner = { path = "../any_spawner", version = "*", features = ["futures-executor", "tokio"] }
[build-dependencies]
rustc_version = { version = "*", default-features = true }
[features]
nonce = []
csr = []
hydrate = []
ssr = []
nightly = []
serde = ["dep:serde"]
tracing = ["dep:tracing"]
hydration = ["dep:hydration_context"]
effects = [
]
sandboxed-arenas = []
subsecond = ["dep:subsecond"]




