[package]
name = "lyx-platform-backend"
version = "0.8.0"
edition = "2024"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
axum = { version = "*", optional = true }
leptos = { path = "../core/lyx-core-leptos/leptos" }
leptos_axum = { path = "../../../core/leptos/integrations/axum", optional = true }
tower = { version = "*", optional = true }
tower-http = { version = "*", optional = true, features = ["fs", "cors", "trace" ] }

[features]
hydrate = ["leptos/hydrate"]
ssr = [
"leptos/ssr",
"dep:leptos_axum",
"dep:axum",
"dep:tower",
"dep:tower-http" ]










