[package]
name = "reactive_stores_macro"
version = "0.8.0"
edition = "2024"
[lib]
proc-macro = true
[dependencies]
convert_case = { version = "*", default-features = true }
proc-macro-error2 = { version = "*", default-features = true }
proc-macro2 = { version = "*", default-features = true }
quote = { version = "*", default-features = true }
syn = { version = "*", features = ["full"], default-features = true }


[build-dependencies]
rustc_version = "*"



