-- Batch 12: Cles i18n pour 50 ressources

CREATE i18n_key:resource_mautic_contact_name SET description = "Nom de la ressource Contact";
CREATE i18n_key:resource_mautic_contact_desc SET description = "Description de la ressource Contact";
CREATE i18n_key:resource_mautic_contact_tooltip SET description = "Tooltip de la ressource Contact";

CREATE i18n_key:resource_mautic_contactSegment_name SET description = "Nom de la ressource Contact Segment";
CREATE i18n_key:resource_mautic_contactSegment_desc SET description = "Description de la ressource Contact Segment";
CREATE i18n_key:resource_mautic_contactSegment_tooltip SET description = "Tooltip de la ressource Contact Segment";

CREATE i18n_key:resource_mautic_segmentEmail_name SET description = "Nom de la ressource Segment Email";
CREATE i18n_key:resource_mautic_segmentEmail_desc SET description = "Description de la ressource Segment Email";
CREATE i18n_key:resource_mautic_segmentEmail_tooltip SET description = "Tooltip de la ressource Segment Email";

CREATE i18n_key:resource_mautic_campaigncontact_name SET description = "Nom de la ressource CampaignContact";
CREATE i18n_key:resource_mautic_campaigncontact_desc SET description = "Description de la ressource CampaignContact";
CREATE i18n_key:resource_mautic_campaigncontact_tooltip SET description = "Tooltip de la ressource CampaignContact";

CREATE i18n_key:resource_mautic_companycontact_name SET description = "Nom de la ressource CompanyContact";
CREATE i18n_key:resource_mautic_companycontact_desc SET description = "Description de la ressource CompanyContact";
CREATE i18n_key:resource_mautic_companycontact_tooltip SET description = "Tooltip de la ressource CompanyContact";

CREATE i18n_key:resource_mautic_contactsegment_name SET description = "Nom de la ressource ContactSegment";
CREATE i18n_key:resource_mautic_contactsegment_desc SET description = "Description de la ressource ContactSegment";
CREATE i18n_key:resource_mautic_contactsegment_tooltip SET description = "Tooltip de la ressource ContactSegment";

CREATE i18n_key:resource_mautic_segmentemail_name SET description = "Nom de la ressource SegmentEmail";
CREATE i18n_key:resource_mautic_segmentemail_desc SET description = "Description de la ressource SegmentEmail";
CREATE i18n_key:resource_mautic_segmentemail_tooltip SET description = "Tooltip de la ressource SegmentEmail";

CREATE i18n_key:resource_medium_post_name SET description = "Nom de la ressource Post";
CREATE i18n_key:resource_medium_post_desc SET description = "Description de la ressource Post";
CREATE i18n_key:resource_medium_post_tooltip SET description = "Tooltip de la ressource Post";

CREATE i18n_key:resource_medium_publication_name SET description = "Nom de la ressource Publication";
CREATE i18n_key:resource_medium_publication_desc SET description = "Description de la ressource Publication";
CREATE i18n_key:resource_medium_publication_tooltip SET description = "Tooltip de la ressource Publication";

CREATE i18n_key:resource_merge_merge_name SET description = "Nom de la ressource Merge";
CREATE i18n_key:resource_merge_merge_desc SET description = "Description de la ressource Merge";
CREATE i18n_key:resource_merge_merge_tooltip SET description = "Tooltip de la ressource Merge";

CREATE i18n_key:resource_mergev1_mergev1_name SET description = "Nom de la ressource MergeV1";
CREATE i18n_key:resource_mergev1_mergev1_desc SET description = "Description de la ressource MergeV1";
CREATE i18n_key:resource_mergev1_mergev1_tooltip SET description = "Tooltip de la ressource MergeV1";

CREATE i18n_key:resource_mergev2_mergev2_name SET description = "Nom de la ressource MergeV2";
CREATE i18n_key:resource_mergev2_mergev2_desc SET description = "Description de la ressource MergeV2";
CREATE i18n_key:resource_mergev2_mergev2_tooltip SET description = "Tooltip de la ressource MergeV2";

CREATE i18n_key:resource_mergev3_mergev3_name SET description = "Nom de la ressource MergeV3";
CREATE i18n_key:resource_mergev3_mergev3_desc SET description = "Description de la ressource MergeV3";
CREATE i18n_key:resource_mergev3_mergev3_tooltip SET description = "Tooltip de la ressource MergeV3";

CREATE i18n_key:resource_messagebird_sms_name SET description = "Nom de la ressource SMS";
CREATE i18n_key:resource_messagebird_sms_desc SET description = "Description de la ressource SMS";
CREATE i18n_key:resource_messagebird_sms_tooltip SET description = "Tooltip de la ressource SMS";

CREATE i18n_key:resource_messagebird_balance_name SET description = "Nom de la ressource Balance";
CREATE i18n_key:resource_messagebird_balance_desc SET description = "Description de la ressource Balance";
CREATE i18n_key:resource_messagebird_balance_tooltip SET description = "Tooltip de la ressource Balance";

CREATE i18n_key:resource_metabase_alerts_name SET description = "Nom de la ressource Alert";
CREATE i18n_key:resource_metabase_alerts_desc SET description = "Description de la ressource Alert";
CREATE i18n_key:resource_metabase_alerts_tooltip SET description = "Tooltip de la ressource Alert";

CREATE i18n_key:resource_metabase_databases_name SET description = "Nom de la ressource Database";
CREATE i18n_key:resource_metabase_databases_desc SET description = "Description de la ressource Database";
CREATE i18n_key:resource_metabase_databases_tooltip SET description = "Tooltip de la ressource Database";

CREATE i18n_key:resource_metabase_metrics_name SET description = "Nom de la ressource Metric";
CREATE i18n_key:resource_metabase_metrics_desc SET description = "Description de la ressource Metric";
CREATE i18n_key:resource_metabase_metrics_tooltip SET description = "Tooltip de la ressource Metric";

CREATE i18n_key:resource_metabase_questions_name SET description = "Nom de la ressource Question";
CREATE i18n_key:resource_metabase_questions_desc SET description = "Description de la ressource Question";
CREATE i18n_key:resource_metabase_questions_tooltip SET description = "Tooltip de la ressource Question";

CREATE i18n_key:resource_metabase_alerts_name SET description = "Nom de la ressource Alerts";
CREATE i18n_key:resource_metabase_alerts_desc SET description = "Description de la ressource Alerts";
CREATE i18n_key:resource_metabase_alerts_tooltip SET description = "Tooltip de la ressource Alerts";

CREATE i18n_key:resource_metabase_databases_name SET description = "Nom de la ressource Databases";
CREATE i18n_key:resource_metabase_databases_desc SET description = "Description de la ressource Databases";
CREATE i18n_key:resource_metabase_databases_tooltip SET description = "Tooltip de la ressource Databases";

CREATE i18n_key:resource_metabase_metrics_name SET description = "Nom de la ressource Metrics";
CREATE i18n_key:resource_metabase_metrics_desc SET description = "Description de la ressource Metrics";
CREATE i18n_key:resource_metabase_metrics_tooltip SET description = "Tooltip de la ressource Metrics";

CREATE i18n_key:resource_metabase_questions_name SET description = "Nom de la ressource Questions";
CREATE i18n_key:resource_metabase_questions_desc SET description = "Description de la ressource Questions";
CREATE i18n_key:resource_metabase_questions_tooltip SET description = "Tooltip de la ressource Questions";

CREATE i18n_key:resource_azurecosmosdb_container_name SET description = "Nom de la ressource Container";
CREATE i18n_key:resource_azurecosmosdb_container_desc SET description = "Description de la ressource Container";
CREATE i18n_key:resource_azurecosmosdb_container_tooltip SET description = "Tooltip de la ressource Container";

CREATE i18n_key:resource_azurecosmosdb_item_name SET description = "Nom de la ressource Item";
CREATE i18n_key:resource_azurecosmosdb_item_desc SET description = "Description de la ressource Item";
CREATE i18n_key:resource_azurecosmosdb_item_tooltip SET description = "Tooltip de la ressource Item";

CREATE i18n_key:resource_microsoftdynamicscrm_account_name SET description = "Nom de la ressource Account";
CREATE i18n_key:resource_microsoftdynamicscrm_account_desc SET description = "Description de la ressource Account";
CREATE i18n_key:resource_microsoftdynamicscrm_account_tooltip SET description = "Tooltip de la ressource Account";

CREATE i18n_key:resource_microsoftentra_group_name SET description = "Nom de la ressource Group";
CREATE i18n_key:resource_microsoftentra_group_desc SET description = "Description de la ressource Group";
CREATE i18n_key:resource_microsoftentra_group_tooltip SET description = "Tooltip de la ressource Group";

CREATE i18n_key:resource_microsoftentra_user_name SET description = "Nom de la ressource User";
CREATE i18n_key:resource_microsoftentra_user_desc SET description = "Description de la ressource User";
CREATE i18n_key:resource_microsoftentra_user_tooltip SET description = "Tooltip de la ressource User";

CREATE i18n_key:resource_microsoftexcel_microsoftexcel_name SET description = "Nom de la ressource MicrosoftExcel";
CREATE i18n_key:resource_microsoftexcel_microsoftexcel_desc SET description = "Description de la ressource MicrosoftExcel";
CREATE i18n_key:resource_microsoftexcel_microsoftexcel_tooltip SET description = "Tooltip de la ressource MicrosoftExcel";

CREATE i18n_key:resource_microsoftexcelv1_table_name SET description = "Nom de la ressource Table";
CREATE i18n_key:resource_microsoftexcelv1_table_desc SET description = "Description de la ressource Table";
CREATE i18n_key:resource_microsoftexcelv1_table_tooltip SET description = "Tooltip de la ressource Table";

CREATE i18n_key:resource_microsoftexcelv1_workbook_name SET description = "Nom de la ressource Workbook";
CREATE i18n_key:resource_microsoftexcelv1_workbook_desc SET description = "Description de la ressource Workbook";
CREATE i18n_key:resource_microsoftexcelv1_workbook_tooltip SET description = "Tooltip de la ressource Workbook";

CREATE i18n_key:resource_microsoftexcelv1_worksheet_name SET description = "Nom de la ressource Worksheet";
CREATE i18n_key:resource_microsoftexcelv1_worksheet_desc SET description = "Description de la ressource Worksheet";
CREATE i18n_key:resource_microsoftexcelv1_worksheet_tooltip SET description = "Tooltip de la ressource Worksheet";

CREATE i18n_key:resource_microsoftexcelv2_microsoftexcelv2_name SET description = "Nom de la ressource MicrosoftExcelV2";
CREATE i18n_key:resource_microsoftexcelv2_microsoftexcelv2_desc SET description = "Description de la ressource MicrosoftExcelV2";
CREATE i18n_key:resource_microsoftexcelv2_microsoftexcelv2_tooltip SET description = "Tooltip de la ressource MicrosoftExcelV2";

CREATE i18n_key:resource_microsoftgraphsecurity_secureScore_name SET description = "Nom de la ressource Secure Score";
CREATE i18n_key:resource_microsoftgraphsecurity_secureScore_desc SET description = "Description de la ressource Secure Score";
CREATE i18n_key:resource_microsoftgraphsecurity_secureScore_tooltip SET description = "Tooltip de la ressource Secure Score";

CREATE i18n_key:resource_microsoftgraphsecurity_secureScoreControlProfile_name SET description = "Nom de la ressource Secure Score Control Profile";
CREATE i18n_key:resource_microsoftgraphsecurity_secureScoreControlProfile_desc SET description = "Description de la ressource Secure Score Control Profile";
CREATE i18n_key:resource_microsoftgraphsecurity_secureScoreControlProfile_tooltip SET description = "Tooltip de la ressource Secure Score Control Profile";

CREATE i18n_key:resource_microsoftonedrive_file_name SET description = "Nom de la ressource File";
CREATE i18n_key:resource_microsoftonedrive_file_desc SET description = "Description de la ressource File";
CREATE i18n_key:resource_microsoftonedrive_file_tooltip SET description = "Tooltip de la ressource File";

CREATE i18n_key:resource_microsoftonedrive_folder_name SET description = "Nom de la ressource Folder";
CREATE i18n_key:resource_microsoftonedrive_folder_desc SET description = "Description de la ressource Folder";
CREATE i18n_key:resource_microsoftonedrive_folder_tooltip SET description = "Tooltip de la ressource Folder";

CREATE i18n_key:resource_microsoftoutlook_microsoftoutlook_name SET description = "Nom de la ressource MicrosoftOutlook";
CREATE i18n_key:resource_microsoftoutlook_microsoftoutlook_desc SET description = "Description de la ressource MicrosoftOutlook";
CREATE i18n_key:resource_microsoftoutlook_microsoftoutlook_tooltip SET description = "Tooltip de la ressource MicrosoftOutlook";

CREATE i18n_key:resource_microsoftoutlookv1_draft_name SET description = "Nom de la ressource Draft";
CREATE i18n_key:resource_microsoftoutlookv1_draft_desc SET description = "Description de la ressource Draft";
CREATE i18n_key:resource_microsoftoutlookv1_draft_tooltip SET description = "Tooltip de la ressource Draft";

CREATE i18n_key:resource_microsoftoutlookv1_folder_name SET description = "Nom de la ressource Folder";
CREATE i18n_key:resource_microsoftoutlookv1_folder_desc SET description = "Description de la ressource Folder";
CREATE i18n_key:resource_microsoftoutlookv1_folder_tooltip SET description = "Tooltip de la ressource Folder";

CREATE i18n_key:resource_microsoftoutlookv1_folderMessage_name SET description = "Nom de la ressource Folder Message";
CREATE i18n_key:resource_microsoftoutlookv1_folderMessage_desc SET description = "Description de la ressource Folder Message";
CREATE i18n_key:resource_microsoftoutlookv1_folderMessage_tooltip SET description = "Tooltip de la ressource Folder Message";

CREATE i18n_key:resource_microsoftoutlookv1_message_name SET description = "Nom de la ressource Message";
CREATE i18n_key:resource_microsoftoutlookv1_message_desc SET description = "Description de la ressource Message";
CREATE i18n_key:resource_microsoftoutlookv1_message_tooltip SET description = "Tooltip de la ressource Message";

CREATE i18n_key:resource_microsoftoutlookv1_messageAttachment_name SET description = "Nom de la ressource Message Attachment";
CREATE i18n_key:resource_microsoftoutlookv1_messageAttachment_desc SET description = "Description de la ressource Message Attachment";
CREATE i18n_key:resource_microsoftoutlookv1_messageAttachment_tooltip SET description = "Tooltip de la ressource Message Attachment";

CREATE i18n_key:resource_microsoftoutlookv1_draftmessageshared_name SET description = "Nom de la ressource DraftMessageShared";
CREATE i18n_key:resource_microsoftoutlookv1_draftmessageshared_desc SET description = "Description de la ressource DraftMessageShared";
CREATE i18n_key:resource_microsoftoutlookv1_draftmessageshared_tooltip SET description = "Tooltip de la ressource DraftMessageShared";

CREATE i18n_key:resource_microsoftoutlookv1_messageattachment_name SET description = "Nom de la ressource MessageAttachment";
CREATE i18n_key:resource_microsoftoutlookv1_messageattachment_desc SET description = "Description de la ressource MessageAttachment";
CREATE i18n_key:resource_microsoftoutlookv1_messageattachment_tooltip SET description = "Tooltip de la ressource MessageAttachment";

CREATE i18n_key:resource_microsoftoutlookv2_microsoftoutlookv2_name SET description = "Nom de la ressource MicrosoftOutlookV2";
CREATE i18n_key:resource_microsoftoutlookv2_microsoftoutlookv2_desc SET description = "Description de la ressource MicrosoftOutlookV2";
CREATE i18n_key:resource_microsoftoutlookv2_microsoftoutlookv2_tooltip SET description = "Tooltip de la ressource MicrosoftOutlookV2";

CREATE i18n_key:resource_microsoftsharepoint_file_name SET description = "Nom de la ressource File";
CREATE i18n_key:resource_microsoftsharepoint_file_desc SET description = "Description de la ressource File";
CREATE i18n_key:resource_microsoftsharepoint_file_tooltip SET description = "Tooltip de la ressource File";

CREATE i18n_key:resource_microsoftsharepoint_item_name SET description = "Nom de la ressource Item";
CREATE i18n_key:resource_microsoftsharepoint_item_desc SET description = "Description de la ressource Item";
CREATE i18n_key:resource_microsoftsharepoint_item_tooltip SET description = "Tooltip de la ressource Item";

CREATE i18n_key:resource_microsoftsharepoint_list_name SET description = "Nom de la ressource List";
CREATE i18n_key:resource_microsoftsharepoint_list_desc SET description = "Description de la ressource List";
CREATE i18n_key:resource_microsoftsharepoint_list_tooltip SET description = "Tooltip de la ressource List";

CREATE i18n_key:resource_microsoftsql_microsoftsql_name SET description = "Nom de la ressource MicrosoftSql";
CREATE i18n_key:resource_microsoftsql_microsoftsql_desc SET description = "Description de la ressource MicrosoftSql";
CREATE i18n_key:resource_microsoftsql_microsoftsql_tooltip SET description = "Tooltip de la ressource MicrosoftSql";

