[package]
name = "hydration-test"
version = "0.8.0"
edition = "2024"
[lib]
crate-type = ["cdylib", "rlib"]
[dependencies]
leptos = { path = "../leptos", version = "0.8.0", features = ["nightly"], optional = true }
actix-web = { version = "*", optional = true }
actix-files = { version = "*", optional = true }
wasm-bindgen = { version = "*", optional = true }
gloo = { version = "*", optional = true }
console_error_panic_hook = { version = "*" }
futures = { version = "*" }
[features]
default = ["ssr"]
ssr = ["leptos/ssr", "dep:actix-files", "dep:actix-web"]
hydrate = ["leptos/hydrate", "dep:wasm-bindgen", "dep:gloo"]


[build-dependencies]
rustc_version = "*"





