[package]
name = "lyx-tooling-cli"
version = "0.8.0"
edition = "2024"

[dependencies]
lyx-tooling-formatter = { path = "../formatter" }
clap = { version = "*", features = ["derive"] }
rayon = { version = "*" }
glob = { version = "*" }
anyhow = { version = "*" }
toml = { version = "*" }
similar = { version = "*" }
console = { version = "*" }





