[package]
name = "lyx-platform-app"
version = "0.8.0"
edition = "2024"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
leptos_meta = { path = "../core/lyx-core-leptos/meta" }
lyx-platform-backend = { path = "../backend" }
leptos = { path = "../core/lyx-core-leptos/leptos" }
tracing = { version = "*" }
leptos_router = { path = "../core/lyx-core-leptos/router" }

[features]
csr = ["leptos/csr", "leptos_meta/csr", "leptos_router/csr"]
hydrate = [
"leptos/hydrate",
"leptos_meta/hydrate",
"lyx-platform-backend/hydrate",
"leptos_router/hydrate" ]
ssr = ["leptos/ssr", "leptos_meta/ssr", "lyx-platform-backend/ssr", "leptos_router/ssr"]










