-- Clés i18n pour les villes du pays: BQ --

CREATE i18n_key:i18n_city_bq_150058_name SET description = 'Nom pour la ville \'Boven Bolivia\'';
CREATE i18n_key:i18n_city_bq_150059_name SET description = 'Nom pour la ville \'Dorp Tera Kora\'';
CREATE i18n_key:i18n_city_bq_150060_name SET description = 'Nom pour la ville \'Oranjestad\'';
CREATE i18n_key:i18n_city_bq_150061_name SET description = 'Nom pour la ville \'Rincon\'';
CREATE i18n_key:i18n_city_bq_150062_name SET description = 'Nom pour la ville \'St. Johns\'';
CREATE i18n_key:i18n_city_bq_150063_name SET description = 'Nom pour la ville \'The Bottom\'';
CREATE i18n_key:i18n_city_bq_150064_name SET description = 'Nom pour la ville \'Windwardside\'';
CREATE i18n_key:i18n_city_bq_150065_name SET description = 'Nom pour la ville \'Zion\\'s Hill\'';
