[package]
name = "leptos_macro"
version = "0.8.0"
edition = "2024"
[lib]
proc-macro = true
[dependencies]
attribute-derive = { version = "*", features = ["syn-full" ], default-features = true }
cfg-if = { version = "*", default-features = true }
html-escape = { version = "*", default-features = true }
itertools = { version = "*", default-features = true }
prettyplease = { version = "*", default-features = true }
proc-macro-error2 = { version = "*", default-features = false }
proc-macro2 = { version = "*", default-features = true }
quote = { version = "*", default-features = true }
syn = { version = "*", features = ["full"], default-features = true }
rstml = { version = "*", default-features = true }
leptos_hot_reload = { path = "../leptos_hot_reload", version = "*" }
server_fn_macro = { path = "../server_fn_macro", version = "*", optional = true }
convert_case = { version = "*", default-features = true }
uuid = { version = "*", features = ["v4"], default-features = true }
tracing = { version = "*", optional = true, default-features = true }
[dev-dependencies]
log = { version = "*", default-features = true }
typed-builder = { version = "*", default-features = true }
trybuild = { version = "*", default-features = true }
leptos = { path = "../leptos", version = "*" }
router = { path = "../router", version = "*", features = ["ssr"] }
server_fn = { path = "../server_fn", version = "*", features = ["cbor"] }
insta = { version = "*", default-features = true }
serde = { version = "*", default-features = true }
[build-dependencies]
rustc_version = { version = "*", default-features = true }
[features]
stable = []
csr = []
hydrate = []
ssr = ["server_fn_macro/ssr"]
nightly = ["server_fn_macro/nightly"]
tracing = ["dep:tracing"]
islands = []
trace-components = []
trace-component-props = []
actix = ["server_fn_macro/actix"]
axum = ["server_fn_macro/axum"]
generic = ["server_fn_macro/generic"]
__internal_erase_components = []




