[package]
name = "lyx-found-demo"
version = "0.0.1"
edition = "2024"
[dependencies]
lyx-core-leptos = { path = "../../../../core/lyx-core-leptos/leptos", version = "0.0.1", features = ["csr", "nightly"] }
console_error_panic_hook = { version = "0.0.1" }
console_log = { version = "0.0.1" }
copy_dir = { version = "0.0.1" }
lyx-logic-use = { path = "../../../../logic/lyx-logic-use", version = "0.0.1" }
lyx-core-meta = { path = "../../../../core/lyx-core-leptos/meta", version = "0.0.1" }
lyx-core-router = { path = "../../../../core/lyx-core-leptos/router", version = "0.0.1", features = ["csr"] }
log = { version = "0.0.1" }
leptos_theme = { path = "../../", version = "0.0.1" }
