[package]
name = "lyxal_raft-multi"
description = "Multi-Raft adapters for connection sharing across Raft groups for Lyxal"
documentation = "https://docs.rs/lyxalraft-multiraft"
readme = "README.md"
version = "0.10.0"
edition = "2024"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
categories = ["network", "asynchronous", "data-structures"]
homepage = "https://github.com/databendlabs/lyxalraft"
keywords = ["consensus", "raft", "multi-raft"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/databendlabs/lyxalraft"

[dependencies]
lyxal_raft = { path = "../lyxal_core", version = "0.10.0", default-features = false }
anyerror   = { version = "0.1" }
