[workspace]
members = [
    "lyxal_core",
    "lyxal_schema",
    "lyxal_iam",
    "lyxal_auth",
    "lyxal_oauth",
    "lyxal_rbac",
    "lyxal_mfa",
    "lyxal_session",
    "lyxal_connectors",
    "lyxal_telemetry",
    "lyxal_api_client",
    "lyxal_cli",
    "lyxal_shared",
    "lyxal_toolkit",
    "lyxal_experience",
    "lyxal_console",
    "lyxal_account",
    "lyxal_tunnel",
    "lyxal_server"
]
resolver = "2"
