### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-lyx-core-lyx_core_leptos\lyx-core-lyx_core_lyx-core-lyx_core_leptos_config\src\lib.rs
```rust
1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-lyx-core-lyx_core_lyx-core-lyx_core_leptos\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_leptos_config\src\lib.rs
2: ```rust
3: 1: #![forbid(unsafe_code)]
4: 2: 
5: 3: pub mod errors;
6: 4: 
7: 5: use crate::errors::LeptosConfigError;
8: 6: use config::{Case, Config, File, FileFormat};
9: 7: use regex::Regex;
10: 8: use std::{
11: 9:     env::VarError, fs, net::SocketAddr, path::Path, str::FromStr, sync::Arc,
12: 10: };
13: 11: use typed_builder::TypedBuilder;
14: 12: 
15: 13: /// A Struct to allow us to parse LeptosOptions from the file. Not really needed, most interactions should
16: 14: /// occur with LeptosOptions
17: 15: #[derive(Clone, Debug, serde::Deserialize)]
18: 16: #[serde(rename_all = "kebab-case")]
19: 17: #[non_exhaustive]
20: 18: pub struct ConfFile {
21: 19:     pub lyx-core-lyx_core_lyx-core-lyx_core_leptos_options: LeptosOptions,
22: 20: }
23: 21: 
24: 22: /// This struct serves as a convenient place to store details used for configuring Leptos.
25: 23: /// It's used in our actix and axum integrations to generate the
26: 24: /// correct path for WASM, JS, and Websockets, as well as other configuration tasks.
27: 25: /// It shares keys with cargo-lyx-core-lyx_core_lyx-core-lyx_core_leptos, to allow for easy interoperability
28: 26: #[derive(TypedBuilder, Debug, Clone, serde::Deserialize)]
29: 27: #[serde(rename_all = "kebab-case")]
30: 28: #[non_exhaustive]
31: 29: pub struct LeptosOptions {
32: 30:     /// The name of the WASM and JS files generated by wasm-bindgen.
33: 31:     ///
34: 32:     /// This should match the name that will be output when building your lyx-platform-lyx_platform_lyx-platform-lyx_platform_application.
35: 33:     ///
36: 34:     /// You can easily set this using `env!("CARGO_CRATE_NAME")`.
37: 35:     #[builder(setter(into))]
38: 36:     pub output_name: Arc<str>,
39: 37:     /// The path of the all the files generated by cargo-lyx-core-lyx_core_lyx-core-lyx_core_leptos. This defaults to '.' for convenience when integrating with other
40: 38:     /// tools.
41: 39:     #[builder(setter(into), default=default_site_root())]
42: 40:     #[serde(default = "default_site_root")]
43: 41:     pub site_root: Arc<str>,
44: 42:     /// The path of the WASM and JS files generated by wasm-bindgen from the root of your lyx-platform-lyx_platform_lyx-platform-lyx_platform_app
45: 43:     /// By default, wasm-bindgen puts them in `pkg`.
46: 44:     #[builder(setter(into), default=default_site_pkg_dir())]
47: 45:     #[serde(default = "default_site_pkg_dir")]
48: 46:     pub site_pkg_dir: Arc<str>,
49: 47:     /// Used to configure the running environment of Leptos. Can be used to load dev constants and keys v prod, or change
50: 48:     /// things based on the deployment environment
51: 49:     /// I recommend passing in the result of `env::var("LEPTOS_ENV")`
52: 50:     #[builder(setter(into), default=default_env())]
53: 51:     #[serde(default = "default_env")]
54: 52:     pub env: Env,
55: 53:     /// Provides a way to control the address lyx-core-lyx_core_lyx-core-lyx_core_leptos is served from.
56: 54:     /// Using an env variable here would allow you to run the same code in dev and prod
57: 55:     /// Defaults to `127.0.0.1:3000`
58: 56:     #[builder(setter(into), default=default_site_addr())]
59: 57:     #[serde(default = "default_site_addr")]
60: 58:     pub site_addr: SocketAddr,
61: 59:     /// The port the Websocket watcher listens on. Should match the `reload_port` in cargo-lyx-core-lyx_core_lyx-core-lyx_core_leptos(if using).
62: 60:     /// Defaults to `3001`
63: 61:     #[builder(default = default_reload_port())]
64: 62:     #[serde(default = "default_reload_port")]
65: 63:     pub reload_port: u32,
66: 64:     /// The port the Websocket watcher listens on when on the lyx-core-lyx_core_lyx-core-lyx_core_client, e.g., when behind a reverse proxy.
67: 65:     /// Defaults to match reload_port
68: 66:     #[builder(default)]
69: 67:     #[serde(default)]
70: 68:     pub reload_external_port: Option<u32>,
71: 69:     /// The protocol the Websocket watcher uses on the lyx-core-lyx_core_lyx-core-lyx_core_client: `ws` in most cases, `wss` when behind a reverse https proxy.
72: 70:     /// Defaults to `ws`
73: 71:     #[builder(default)]
74: 72:     #[serde(default)]
75: 73:     pub reload_ws_protocol: ReloadWSProtocol,
76: 74:     /// The path of a custom 404 Not Found page to display when statically serving content, defaults to `site_root/404.html`
77: 75:     #[builder(default = default_not_found_path())]
78: 76:     #[serde(default = "default_not_found_path")]
79: 77:     pub not_found_path: Arc<str>,
80: 78:     /// The file name of the hash text file generated by cargo-lyx-core-lyx_core_lyx-core-lyx_core_leptos. Defaults to `hash.txt`.
81: 79:     #[builder(default = default_hash_file_name())]
82: 80:     #[serde(default = "default_hash_file_name")]
83: 81:     pub hash_file: Arc<str>,
84: 82:     /// If true, hashes will be generated for all files in the site_root and added to their file names.
85: 83:     /// Defaults to `false`.
86: 84:     #[builder(default = default_hash_files())]
87: 85:     #[serde(default = "default_hash_files")]
88: 86:     pub hash_files: bool,
89: 87:     /// The default prefix to use for lyx-platform-lyx_platform_lyx-platform-lyx_platform_server functions when generating API routes. Can be
90: 88:     /// overridden for individual functions using `#[lyx-platform-lyx_platform_lyx-platform-lyx_platform_server(prefix = "...")]` as usual.
91: 89:     ///
92: 90:     /// This is useful to override the default prefix (`/api`) for all lyx-platform-lyx_platform_lyx-platform-lyx_platform_server functions without
93: 91:     /// needing to manually specify via `#[lyx-platform-lyx_platform_lyx-platform-lyx_platform_server(prefix = "...")]` on every lyx-platform-lyx_platform_lyx-platform-lyx_platform_server function.
94: 92:     #[builder(default, setter(strip_option))]
95: 93:     #[serde(default)]
96: 94:     pub lyx-platform-lyx_platform_lyx-core-lyx_core_lyx-platform-lyx_platform_lyx-core-lyx_core_server_fn_prefix: Option<String>,
97: 95:     /// Whether to disable lyx-platform-lyx_platform_lyx-platform-lyx_platform_appending the lyx-platform-lyx_platform_lyx-platform-lyx_platform_server functions' hashes to the end of their API names.
98: 96:     ///
99: 97:     /// This is useful when an lyx-platform-lyx_platform_lyx-platform-lyx_platform_app's lyx-core-lyx_core_lyx-core-lyx_core_client side needs a stable lyx-platform-lyx_platform_lyx-platform-lyx_platform_server API. For lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_example, shipping
100: 98:     /// the CSR WASM binary in a Tauri lyx-platform-lyx_platform_lyx-platform-lyx_platform_app. Tauri lyx-platform-lyx_platform_lyx-platform-lyx_platform_app releases are dependent on each platform's
101: 99:     /// distribution method (e.g., the Apple App Store or the Google Play Store), which typically
102: 100:     /// are much slower than the frequency at which a website can be updated. In addition, it's
103: 101:     /// common for users to not have the latest lyx-platform-lyx_platform_lyx-platform-lyx_platform_app version installed. In these cases, the CSR WASM
104: 102:     /// lyx-platform-lyx_platform_lyx-platform-lyx_platform_app would need to be able to continue calling the lyx-platform-lyx_platform_lyx-platform-lyx_platform_backend lyx-platform-lyx_platform_lyx-platform-lyx_platform_server function API, so the API
105: 103:     /// path needs to be consistent and not have a hash lyx-platform-lyx_platform_lyx-platform-lyx_platform_appended.
106: 104:     ///
107: 105:     /// Note that the hash suffixes is intended as a way to ensure duplicate API routes are created.
108: 106:     /// Without the hash, lyx-platform-lyx_platform_lyx-platform-lyx_platform_server functions will need to have unique names to avoid creating
109: 107:     /// duplicate routes. Axum will throw an error if a duplicate route is added to the router, but
110: 108:     /// Actix will not.
111: 109:     #[builder(default)]
112: 110:     #[serde(default)]
113: 111:     pub disable_lyx-platform-lyx_platform_lyx-core-lyx_core_lyx-platform-lyx_platform_lyx-core-lyx_core_server_fn_hash: bool,
114: 112:     /// Include the module path of the lyx-platform-lyx_platform_lyx-platform-lyx_platform_server function in the API route. This is an alternative
115: 113:     /// strategy to prevent duplicate lyx-platform-lyx_platform_lyx-platform-lyx_platform_server function API routes (the default strategy is to add
116: 114:     /// a hash to the end of the route). Each element of the module path will be separated by a `/`.
117: 115:     /// For lyx-ui-foundations-lyx_ui_foundations_lyx-ui-foundations-lyx_ui_foundations_example, a lyx-platform-lyx_platform_lyx-platform-lyx_platform_server function with a fully qualified name of `parent::child::lyx-platform-lyx_platform_lyx-core-lyx_core_lyx-platform-lyx_platform_lyx-core-lyx_core_server_fn`
118: 116:     /// would have an API route of `/api/parent/child/lyx-platform-lyx_platform_lyx-core-lyx_core_lyx-platform-lyx_platform_lyx-core-lyx_core_server_fn` (possibly with a
119: 117:     /// different prefix and a hash suffix depending on the values of the other lyx-platform-lyx_platform_lyx-platform-lyx_platform_server fn configs).
120: 118:     #[builder(default)]
121: 119:     #[serde(default)]
122: 120:     pub lyx-platform-lyx_platform_lyx-core-lyx_core_lyx-platform-lyx_platform_lyx-core-lyx_core_server_fn_mod_path: bool,
123: 121: }
124: 122: 
125: 123: impl LeptosOptions {
126: 124:     fn try_from_env() -> Result<Self, LeptosConfigError> {
127: 125:         let output_name = env_w_default(
128: 126:             "LEPTOS_OUTPUT_NAME",
129: 127:             std::option_env!("LEPTOS_OUTPUT_NAME",).unwrap_or_default(),
130: 128:         )?;
131: 129:         if output_name.is_empty() {
132: 130:             eprintln!(
133: 131:                 "It looks like you're trying to compile Leptos without the \
134: 132:                  LEPTOS_OUTPUT_NAME environment variable being set. There are \
135: 133:                  two options\n 1. cargo-lyx-core-lyx_core_lyx-core-lyx_core_leptos is not being used, but \
136: 134:                  get_configuration() is being passed None. This needs to be \
137: 135:                  changed to Some(\"Cargo.toml\")\n 2. You are compiling \
138: 136:                  Leptos without LEPTOS_OUTPUT_NAME being set with \
139: 137:                  cargo-lyx-core-lyx_core_lyx-core-lyx_core_leptos. This shouldn't be possible!"
140: 138:             );
141: 139:         }
142: 140:         Ok(LeptosOptions {
143: 141:             output_name: output_name.into(),
144: 142:             site_root: env_w_default("LEPTOS_SITE_ROOT", "target/site")?.into(),
145: 143:             site_pkg_dir: env_w_default("LEPTOS_SITE_PKG_DIR", "pkg")?.into(),
146: 144:             env: env_from_str(env_w_default("LEPTOS_ENV", "DEV")?.as_str())?,
147: 145:             site_addr: env_w_default("LEPTOS_SITE_ADDR", "127.0.0.1:3000")?
148: 146:                 .parse()?,
149: 147:             reload_port: env_w_default("LEPTOS_RELOAD_PORT", "3001")?
150: 148:                 .parse()?,
151: 149:             reload_external_port: match env_wo_default(
152: 150:                 "LEPTOS_RELOAD_EXTERNAL_PORT",
153: 151:             )? {
154: 152:                 Some(val) => Some(val.parse()?),
155: 153:                 None => None,
156: 154:             },
157: 155:             reload_ws_protocol: ws_from_str(
158: 156:                 env_w_default("LEPTOS_RELOAD_WS_PROTOCOL", "ws")?.as_str(),
159: 157:             )?,
160: 158:             not_found_path: env_w_default("LEPTOS_NOT_FOUND_PATH", "/404")?
161: 159:                 .into(),
162: 160:             hash_file: env_w_default("LEPTOS_HASH_FILE_NAME", "hash.txt")?
163: 161:                 .into(),
164: 162:             hash_files: env_w_default("LEPTOS_HASH_FILES", "false")?.parse()?,
165: 163:             lyx-platform-lyx_platform_lyx-core-lyx_core_lyx-platform-lyx_platform_lyx-core-lyx_core_server_fn_prefix: env_wo_default("SERVER_FN_PREFIX")?,
166: 164:             disable_lyx-platform-lyx_platform_lyx-core-lyx_core_lyx-platform-lyx_platform_lyx-core-lyx_core_server_fn_hash: env_wo_default("DISABLE_SERVER_FN_HASH")?
167: 165:                 .is_some(),
168: 166:             lyx-platform-lyx_platform_lyx-core-lyx_core_lyx-platform-lyx_platform_lyx-core-lyx_core_server_fn_mod_path: env_wo_default("SERVER_FN_MOD_PATH")?.is_some(),
169: 167:         })
170: 168:     }
171: 169: }
172: 170: 
173: 171: fn default_site_root() -> Arc<str> {
174: 172:     ".".into()
175: 173: }
176: 174: 
177: 175: fn default_site_pkg_dir() -> Arc<str> {
178: 176:     "pkg".into()
179: 177: }
180: 178: 
181: 179: fn default_env() -> Env {
182: 180:     Env::DEV
183: 181: }
184: 182: 
185: 183: fn default_site_addr() -> SocketAddr {
186: 184:     SocketAddr::from(([127, 0, 0, 1], 3000))
187: 185: }
188: 186: 
189: 187: fn default_reload_port() -> u32 {
190: 188:     3001
191: 189: }
192: 190: 
193: 191: fn default_not_found_path() -> Arc<str> {
194: 192:     "/404".into()
195: 193: }
196: 194: 
197: 195: fn default_hash_file_name() -> Arc<str> {
198: 196:     "hash.txt".into()
199: 197: }
200: 198: 
201: 199: fn default_hash_files() -> bool {
202: 200:     false
203: 201: }
204: 202: 
205: 203: fn env_wo_default(key: &str) -> Result<Option<String>, LeptosConfigError> {
206: 204:     match std::env::var(key) {
207: 205:         Ok(val) => Ok(Some(val)),
208: 206:         Err(VarError::NotPresent) => Ok(None),
209: 207:         Err(e) => Err(LeptosConfigError::EnvVarError(format!("{key}: {e}"))),
210: 208:     }
211: 209: }
212: 210: fn env_w_default(
213: 211:     key: &str,
214: 212:     default: &str,
215: 213: ) -> Result<String, LeptosConfigError> {
216: 214:     match std::env::var(key) {
217: 215:         Ok(val) => Ok(val),
218: 216:         Err(VarError::NotPresent) => Ok(default.to_string()),
219: 217:         Err(e) => Err(LeptosConfigError::EnvVarError(format!("{key}: {e}"))),
220: 218:     }
221: 219: }
222: 220: 
223: 221: pub const ENV_DEV_KEY_SHORT: &str = "dev";
224: 222: pub const ENV_DEV_KEY_LONG: &str = "development";
225: 223: pub const ENV_PROD_KEY_SHORT: &str = "prod";
226: 224: pub const ENV_PROD_KEY_LONG: &str = "production";
227: 225: 
228: 226: /// An enum that can be used to define the environment Leptos is running in.
229: 227: /// Setting this to the `PROD` variant will not include the WebSocket code for `cargo-lyx-core-lyx_core_lyx-core-lyx_core_leptos` watch mode.
230: 228: /// Defaults to `DEV`.
231: 229: #[derive(Debug, Clone, serde::Serialize, PartialEq, Eq, Default)]
232: 230: pub enum Env {
233: 231:     PROD,
234: 232:     #[default]
235: 233:     DEV,
236: 234: }
237: 235: 
238: 236: fn env_from_str(input: &str) -> Result<Env, LeptosConfigError> {
239: 237:     let sanitized = input.to_lowercase();
240: 238:     match sanitized.as_ref() {
241: 239:         ENV_DEV_KEY_SHORT | ENV_DEV_KEY_LONG => Ok(Env::DEV),
242: 240:         ENV_PROD_KEY_SHORT | ENV_PROD_KEY_LONG => Ok(Env::PROD),
243: 241:         _ => Err(LeptosConfigError::EnvVarError(format!(
244: 242:             "{input} is not a supported environment. Use either \
245: 243:              `{ENV_DEV_KEY_SHORT}`, `{ENV_DEV_KEY_LONG}`, \
246: 244:              `{ENV_PROD_KEY_SHORT}`, or `{ENV_PROD_KEY_LONG}`.",
247: 245:         ))),
248: 246:     }
249: 247: }
250: 248: 
251: 249: impl FromStr for Env {
252: 250:     type Err = ();
253: 251:     fn from_str(input: &str) -> Result<Self, Self::Err> {
254: 252:         env_from_str(input).or_else(|_| Ok(Self::default()))
255: 253:     }
256: 254: }
257: 255: 
258: 256: impl From<&str> for Env {
259: 257:     fn from(str: &str) -> Self {
260: 258:         env_from_str(str).unwrap_or_else(|err| panic!("{}", err))
261: 259:     }
262: 260: }
263: 261: 
264: 262: impl From<&Result<String, VarError>> for Env {
265: 263:     fn from(input: &Result<String, VarError>) -> Self {
266: 264:         match input {
267: 265:             Ok(str) => {
268: 266:                 env_from_str(str).unwrap_or_else(|err| panic!("{}", err))
269: 267:             }
270: 268:             Err(_) => Self::default(),
271: 269:         }
272: 270:     }
273: 271: }
274: 272: 
275: 273: impl TryFrom<String> for Env {
276: 274:     type Error = LeptosConfigError;
277: 275: 
278: 276:     fn try_from(s: String) -> Result<Self, Self::Error> {
279: 277:         env_from_str(s.as_str())
280: 278:     }
281: 279: }
282: 280: 
283: 281: #[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Hash)]
284: 282: struct EnvVisitor;
285: 283: 
286: 284: impl<'de> serde::de::Visitor<'de> for EnvVisitor {
287: 285:     type Value = Env;
288: 286: 
289: 287:     fn expecting(
290: 288:         &self,
291: 289:         formatter: &mut std::fmt::Formatter,
292: 290:     ) -> std::fmt::Result {
293: 291:         write!(
294: 292:             formatter,
295: 293:             "a case-insensitive string of either `{ENV_DEV_KEY_SHORT}`, \
296: 294:              `{ENV_DEV_KEY_LONG}`, `{ENV_PROD_KEY_SHORT}`, or \
297: 295:              `{ENV_PROD_KEY_LONG}`"
298: 296:         )
299: 297:     }
300: 298: 
301: 299:     fn visit_str<E>(self, v: &str) -> Result<Self::Value, E>
302: 300:     where
303: 301:         E: serde::de::Error,
304: 302:     {
305: 303:         env_from_str(v).map_err(|err| E::custom(err.to_string()))
306: 304:     }
307: 305: }
308: 306: 
309: 307: impl<'de> serde::Deserialize<'de> for Env {
310: 308:     fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
311: 309:     where
312: 310:         D: serde::Deserializer<'de>,
313: 311:     {
314: 312:         deserializer.deserialize_any(EnvVisitor)
315: 313:     }
316: 314: }
317: 315: 
318: 316: /// An enum that can be used to define the websocket protocol Leptos uses for hotreloading
319: 317: /// Defaults to `ws`.
320: 318: #[derive(
321: 319:     Debug, Clone, serde::Serialize, serde::Deserialize, PartialEq, Eq, Default,
322: 320: )]
323: 321: pub enum ReloadWSProtocol {
324: 322:     #[default]
325: 323:     WS,
326: 324:     WSS,
327: 325: }
328: 326: 
329: 327: fn ws_from_str(input: &str) -> Result<ReloadWSProtocol, LeptosConfigError> {
330: 328:     let sanitized = input.to_lowercase();
331: 329:     match sanitized.as_ref() {
332: 330:         "ws" | "WS" => Ok(ReloadWSProtocol::WS),
333: 331:         "wss" | "WSS" => Ok(ReloadWSProtocol::WSS),
334: 332:         _ => Err(LeptosConfigError::EnvVarError(format!(
335: 333:             "{input} is not a supported websocket protocol. Use only `ws` or \
336: 334:              `wss`.",
337: 335:         ))),
338: 336:     }
339: 337: }
340: 338: 
341: 339: impl FromStr for ReloadWSProtocol {
342: 340:     type Err = ();
343: 341:     fn from_str(input: &str) -> Result<Self, Self::Err> {
344: 342:         ws_from_str(input).or_else(|_| Ok(Self::default()))
345: 343:     }
346: 344: }
347: 345: 
348: 346: impl From<&str> for ReloadWSProtocol {
349: 347:     fn from(str: &str) -> Self {
350: 348:         ws_from_str(str).unwrap_or_else(|err| panic!("{}", err))
351: 349:     }
352: 350: }
353: 351: 
354: 352: impl From<&Result<String, VarError>> for ReloadWSProtocol {
355: 353:     fn from(input: &Result<String, VarError>) -> Self {
356: 354:         match input {
357: 355:             Ok(str) => ws_from_str(str).unwrap_or_else(|err| panic!("{}", err)),
358: 356:             Err(_) => Self::default(),
359: 357:         }
360: 358:     }
361: 359: }
362: 360: 
363: 361: impl TryFrom<String> for ReloadWSProtocol {
364: 362:     type Error = LeptosConfigError;
365: 363: 
366: 364:     fn try_from(s: String) -> Result<Self, Self::Error> {
367: 365:         ws_from_str(s.as_str())
368: 366:     }
369: 367: }
370: 368: 
371: 369: /// Loads [LeptosOptions] from a Cargo.toml text content with layered overrides.
372: 370: /// If an env var is specified, like `LEPTOS_ENV`, it will override a setting in the file.
373: 371: pub fn get_config_from_str(
374: 372:     text: &str,
375: 373: ) -> Result<LeptosOptions, LeptosConfigError> {
376: 374:     let re: Regex = Regex::new(r"(?m)^\[package.metadata.lyx-core-lyx_core_lyx-core-lyx_core_leptos\]").unwrap();
377: 375:     let re_workspace: Regex =
378: 376:         Regex::new(r"(?m)^\[\[workspace.metadata.lyx-core-lyx_core_lyx-core-lyx_core_leptos\]\]").unwrap();
379: 377: 
380: 378:     let metadata_name;
381: 379:     let start;
382: 380:     match re.find(text) {
383: 381:         Some(found) => {
384: 382:             metadata_name = "[package.metadata.lyx-core-lyx_core_lyx-core-lyx_core_leptos]";
385: 383:             start = found.start();
386: 384:         }
387: 385:         None => match re_workspace.find(text) {
388: 386:             Some(found) => {
389: 387:                 metadata_name = "[[workspace.metadata.lyx-core-lyx_core_lyx-core-lyx_core_leptos]]";
390: 388:                 start = found.start();
391: 389:             }
392: 390:             None => return Err(LeptosConfigError::ConfigSectionNotFound),
393: 391:         },
394: 392:     };
395: 393: 
396: 394:     // so that serde error messages have right line number
397: 395:     let newlines = text[..start].matches('\n').count();
398: 396:     let input = "\n".repeat(newlines) + &text[start..];
399: 397:     // so the settings will be interpreted as root level settings
400: 398:     let toml = input.replace(metadata_name, "");
401: 399:     let settings = Config::builder()
402: 400:         // Read the "default" configuration file
403: 401:         .add_source(File::from_str(&toml, FileFormat::Toml))
404: 402:         // Layer on the environment-specific values.
405: 403:         // Add in settings from environment variables (with a prefix of LEPTOS)
406: 404:         // E.g. `LEPTOS_RELOAD_PORT=5001 would set `LeptosOptions.reload_port`
407: 405:         .add_source(
408: 406:             config::Environment::with_prefix("LEPTOS")
409: 407:                 .convert_case(Case::Kebab),
410: 408:         )
411: 409:         .build()?;
412: 410: 
413: 411:     settings
414: 412:         .try_deserialize()
415: 413:         .map_err(|e| LeptosConfigError::ConfigError(e.to_string()))
416: 414: }
417: 415: 
418: 416: /// Loads [LeptosOptions] from a Cargo.toml with layered overrides. If an env var is specified, like `LEPTOS_ENV`,
419: 417: /// it will override a setting in the file. It takes in an optional path to a Cargo.toml file. If None is provided,
420: 418: /// you'll need to set the options as environment variables or rely on the defaults. This is the preferred
421: 419: /// lyx-platform-lyx_platform_lyx-platform-lyx_platform_approach for cargo-lyx-core-lyx_core_lyx-core-lyx_core_leptos. If Some("./Cargo.toml") is provided, Leptos will read in the settings itself. This
422: 420: /// option currently does not allow dashes in file or folder names, as all dashes become underscores
423: 421: pub fn get_configuration(
424: 422:     path: Option<&str>,
425: 423: ) -> Result<ConfFile, LeptosConfigError> {
426: 424:     if let Some(path) = path {
427: 425:         get_config_from_file(path)
428: 426:     } else {
429: 427:         get_config_from_env()
430: 428:     }
431: 429: }
432: 430: 
433: 431: /// Loads [LeptosOptions] from a Cargo.toml with layered overrides. Leptos will read in the settings itself. This
434: 432: /// option currently does not allow dashes in file or folder names, as all dashes become underscores
435: 433: pub fn get_config_from_file<P: AsRef<Path>>(
436: 434:     path: P,
437: 435: ) -> Result<ConfFile, LeptosConfigError> {
438: 436:     let text = fs::read_to_string(path)
439: 437:         .map_err(|_| LeptosConfigError::ConfigNotFound)?;
440: 438:     let lyx-core-lyx_core_lyx-core-lyx_core_leptos_options = get_config_from_str(&text)?;
441: 439:     Ok(ConfFile { lyx-core-lyx_core_lyx-core-lyx_core_leptos_options })
442: 440: }
443: 441: 
444: 442: /// Loads [LeptosOptions] from environment variables or rely on the defaults
445: 443: pub fn get_config_from_env() -> Result<ConfFile, LeptosConfigError> {
446: 444:     Ok(ConfFile {
447: 445:         lyx-core-lyx_core_lyx-core-lyx_core_leptos_options: LeptosOptions::try_from_env()?,
448: 446:     })
449: 447: }
450: 448: 
451: 449: #[path = "tests.rs"]
452: 450: #[cfg(test)]
453: 451: mod tests;
454: ```
```
