[package]
name = "shared-server-1"
version = "*"
edition = "2024"
[lib]
crate-type = ["cdylib", "rlib"]
[dependencies]
axum = { version = "*", optional = true }
leptos = { path = "../leptos", version = "*", optional = true }
axum = { path = "../../../integrations/axum", version = "*", optional = true }
tokio = { version = "*", optional = true, features = ["rt-multi-thread"] }
tower-http = { version = "*", optional = true, features = ["trace"] }
tracing = { version = "*", optional = true }
tracing-subscriber = { version = "*", optional = true }
[features]
default = ["ssr"]
hydrate = ["leptos/hydrate"]
ssr = [
"dep:axum",
"dep:tokio",
"dep:axum",
"dep:tracing",
"dep:tracing-subscriber",
"dep:tower-http",
"leptos/ssr" ]


[build-dependencies]
rustc_version = "*"




