-- Clés i18n pour les villes du pays: TV --

CREATE i18n_key:i18n_city_tv_108993_name SET description = 'Nom pour la ville \'Alapi Village\'';
CREATE i18n_key:i18n_city_tv_108995_name SET description = 'Nom pour la ville \'Fakaifou Village\'';
CREATE i18n_key:i18n_city_tv_108996_name SET description = 'Nom pour la ville \'Funafuti\'';
CREATE i18n_key:i18n_city_tv_109001_name SET description = 'Nom pour la ville \'Toga Village\'';
CREATE i18n_key:i18n_city_tv_108997_name SET description = 'Nom pour la ville \'Kulia Village\'';
CREATE i18n_key:i18n_city_tv_108998_name SET description = 'Nom pour la ville \'Niulakita\'';
CREATE i18n_key:i18n_city_tv_109000_name SET description = 'Nom pour la ville \'Tanrake Village\'';
CREATE i18n_key:i18n_city_tv_108999_name SET description = 'Nom pour la ville \'Savave Village\'';
CREATE i18n_key:i18n_city_tv_108994_name SET description = 'Nom pour la ville \'Asau Village\'';
