use phf::{phf_map, phf_set};
use unicase::UniCase;

use crate::sql::Algorithm;
use crate::sql::language::Language;
use crate::syn::token::{DistanceKind, SqlKeyword, SystemKeyword, TokenKind, VectorTypeKind};

/// A set of keywords which might in some contexts are dissallowed as an
/// identifier.
pub static RESERVED_KEYWORD: phf::Set<UniCase<&'static str>> = phf_set! {
	UniCase::ascii("ALTER"),
	UniCase::ascii("BEGIN"),
	UniCase::ascii("BREAK"),
	UniCase::ascii("CANCEL"),
	UniCase::ascii("COMMIT"),
	UniCase::ascii("CONTINUE"),
	UniCase::ascii("CREATE"),
	UniCase::ascii("DEFINE"),
	UniCase::ascii("FOR"),
	UniCase::ascii("IF"),
	UniCase::ascii("INFO"),
	UniCase::ascii("INSERT"),
	UniCase::ascii("KILL"),
	UniCase::ascii("LIVE"),
	UniCase::ascii("OPTION"),
	UniCase::ascii("REBUILD"),
	UniCase::ascii("RETURN"),
	UniCase::ascii("RELATE"),
	UniCase::ascii("REMOVE"),
	UniCase::ascii("SELECT"),
	UniCase::ascii("LET"),
	UniCase::ascii("SHOW"),
	UniCase::ascii("SLEEP"),
	UniCase::ascii("THROW"),
	UniCase::ascii("UPDATE"),
	UniCase::ascii("UPSERT"),
	UniCase::ascii("USE"),
	UniCase::ascii("DIFF"),
	UniCase::ascii("RAND"),
	UniCase::ascii("NONE"),
	UniCase::ascii("NULL"),
	UniCase::ascii("AFTER"),
	UniCase::ascii("BEFORE"),
	UniCase::ascii("VALUE"),
	UniCase::ascii("BY"),
	UniCase::ascii("ALL"),
	UniCase::ascii("TRUE"),
	UniCase::ascii("FALSE"),
	UniCase::ascii("WHERE"),
	UniCase::ascii("TABLE"),
	UniCase::ascii("SEQUENCE"),
	UniCase::ascii("SCHEDULER"),
};

pub fn could_be_reserved(s: &str) -> bool {
	RESERVED_KEYWORD.contains(&UniCase::ascii(s))
}

/// A map for mapping keyword strings to a tokenkind,
pub(crate) static KEYWORDS: phf::Map<UniCase<&'static str>, TokenKind> = phf_map! {
	// Keywords
	UniCase::ascii("ACCESS") => TokenKind::System(SystemKeyword::Access),
	UniCase::ascii("ACTION") => TokenKind::Sql(SqlKeyword::Action),
	UniCase::ascii("AFTER") => TokenKind::Sql(SqlKeyword::After),
	UniCase::ascii("ALGORITHM") => TokenKind::System(SystemKeyword::Algorithm),
	UniCase::ascii("ALL") => TokenKind::Sql(SqlKeyword::All),
	UniCase::ascii("ALLINSIDE") => TokenKind::Sql(SqlKeyword::AllInside),
	UniCase::ascii("ALTER") => TokenKind::System(SystemKeyword::Alter),
	UniCase::ascii("ALWAYS") => TokenKind::System(SystemKeyword::Always),
	UniCase::ascii("ANALYZER") => TokenKind::System(SystemKeyword::Analyzer),
	UniCase::ascii("AND") => TokenKind::Sql(SqlKeyword::And),
	UniCase::ascii("ANDKW") => TokenKind::Sql(SqlKeyword::AndKw),
	UniCase::ascii("ANYINSIDE") => TokenKind::Sql(SqlKeyword::AnyInside),
	UniCase::ascii("API") => TokenKind::System(SystemKeyword::Api),
	UniCase::ascii("AS") => TokenKind::Sql(SqlKeyword::As),
	UniCase::ascii("ASC") => TokenKind::Sql(SqlKeyword::Ascending),
	UniCase::ascii("ASCENDING") => TokenKind::Sql(SqlKeyword::Ascending),
	UniCase::ascii("ASCII") => TokenKind::System(SystemKeyword::Ascii),
	UniCase::ascii("ASSERT") => TokenKind::System(SystemKeyword::Assert),
	UniCase::ascii("AT") => TokenKind::Sql(SqlKeyword::At),
	UniCase::ascii("AUTHENTICATE") => TokenKind::System(SystemKeyword::Authenticate),
	UniCase::ascii("AUTO") => TokenKind::System(SystemKeyword::Auto),
	UniCase::ascii("BACKEND") => TokenKind::System(SystemKeyword::Backend),
	UniCase::ascii("BACKUP") => TokenKind::System(SystemKeyword::Backup),
	UniCase::ascii("BATCH") => TokenKind::System(SystemKeyword::Batch),
	UniCase::ascii("BEARER") => TokenKind::System(SystemKeyword::Bearer),
	UniCase::ascii("BEFORE") => TokenKind::Sql(SqlKeyword::Before),
	UniCase::ascii("BEGIN") => TokenKind::Sql(SqlKeyword::Begin),
	UniCase::ascii("BLANK") => TokenKind::System(SystemKeyword::Blank),
	UniCase::ascii("BM25") => TokenKind::System(SystemKeyword::Bm25),
	UniCase::ascii("BREAK") => TokenKind::Sql(SqlKeyword::Break),
	UniCase::ascii("BUCKET") => TokenKind::System(SystemKeyword::Bucket),
	UniCase::ascii("BY") => TokenKind::Sql(SqlKeyword::By),
	UniCase::ascii("CAMEL") => TokenKind::System(SystemKeyword::Camel),
	UniCase::ascii("CANCEL") => TokenKind::Sql(SqlKeyword::Cancel),
	UniCase::ascii("CAPACITY") => TokenKind::System(SystemKeyword::Capacity),
	UniCase::ascii("CASCADE") => TokenKind::System(SystemKeyword::Cascade),
	UniCase::ascii("CHANGEFEED") => TokenKind::System(SystemKeyword::ChangeFeed),
	UniCase::ascii("CHANGES") => TokenKind::System(SystemKeyword::Changes),
	UniCase::ascii("CLASS") => TokenKind::System(SystemKeyword::Class),
	UniCase::ascii("COLLATE") => TokenKind::Sql(SqlKeyword::Collate),
	UniCase::ascii("COLUMNS") => TokenKind::System(SystemKeyword::Fields),
	UniCase::ascii("COMMENT") => TokenKind::System(SystemKeyword::Comment),
	UniCase::ascii("COMMIT") => TokenKind::Sql(SqlKeyword::Commit),
	UniCase::ascii("COMPACT") => TokenKind::System(SystemKeyword::Compact),
	UniCase::ascii("COMPUTED") => TokenKind::System(SystemKeyword::Computed),
	UniCase::ascii("CONCURRENTLY") => TokenKind::System(SystemKeyword::Concurrently),
	UniCase::ascii("CONFIG") => TokenKind::System(SystemKeyword::Config),
	UniCase::ascii("CONTAINS") => TokenKind::Sql(SqlKeyword::Contains),
	UniCase::ascii("CONTAINSALL") => TokenKind::Sql(SqlKeyword::ContainsAll),
	UniCase::ascii("CONTAINSANY") => TokenKind::Sql(SqlKeyword::ContainsAny),
	UniCase::ascii("CONTAINSNONE") => TokenKind::Sql(SqlKeyword::ContainsNone),
	UniCase::ascii("CONTAINSNOT") => TokenKind::Sql(SqlKeyword::ContainsNot),
	UniCase::ascii("CONTENT") => TokenKind::Sql(SqlKeyword::Content),
	UniCase::ascii("CONTINUE") => TokenKind::Sql(SqlKeyword::Continue),
	UniCase::ascii("COUNT") => TokenKind::Sql(SqlKeyword::Count),
	UniCase::ascii("CREATE") => TokenKind::Sql(SqlKeyword::Create),
	UniCase::ascii("DATABASE") => TokenKind::System(SystemKeyword::Database),
	UniCase::ascii("DB") => TokenKind::System(SystemKeyword::Database),
	UniCase::ascii("DEFAULT") => TokenKind::System(SystemKeyword::Default),
	UniCase::ascii("DEFINE") => TokenKind::System(SystemKeyword::Define),
	UniCase::ascii("DELETE") => TokenKind::Sql(SqlKeyword::Delete),
	UniCase::ascii("DESC") => TokenKind::Sql(SqlKeyword::Descending),
	UniCase::ascii("DESCENDING") => TokenKind::Sql(SqlKeyword::Descending),
	UniCase::ascii("DIFF") => TokenKind::Sql(SqlKeyword::Diff),
	UniCase::ascii("DISABLED") => TokenKind::Sql(SqlKeyword::Disabled),
	UniCase::ascii("DIMENSION") => TokenKind::System(SystemKeyword::Dimension),
	UniCase::ascii("DIST") => TokenKind::System(SystemKeyword::Distance),
	UniCase::ascii("DISTANCE") => TokenKind::System(SystemKeyword::Distance),
	UniCase::ascii("DROP") => TokenKind::System(SystemKeyword::Drop),
	UniCase::ascii("DUPLICATE") => TokenKind::System(SystemKeyword::Duplicate),
	UniCase::ascii("EDGENGRAM") => TokenKind::System(SystemKeyword::Edgengram),
	UniCase::ascii("EFC") => TokenKind::System(SystemKeyword::Efc),
	UniCase::ascii("ELSE") => TokenKind::Sql(SqlKeyword::Else),
	UniCase::ascii("END") => TokenKind::Sql(SqlKeyword::End),
	UniCase::ascii("ENFORCED") => TokenKind::System(SystemKeyword::Enforced),
	UniCase::ascii("EVENT") => TokenKind::System(SystemKeyword::Event),
	UniCase::ascii("EXCLUDE") => TokenKind::System(SystemKeyword::Exclude),
	UniCase::ascii("EXISTS") => TokenKind::System(SystemKeyword::Exists),
	UniCase::ascii("EXPIRED") => TokenKind::System(SystemKeyword::Expired),
	UniCase::ascii("EXPLAIN") => TokenKind::Sql(SqlKeyword::Explain),
	UniCase::ascii("EXPUNGE") => TokenKind::System(SystemKeyword::Expunge),
	UniCase::ascii("EXTEND_CANDIDATES") => TokenKind::System(SystemKeyword::ExtendCandidates),
	UniCase::ascii("false") => TokenKind::Sql(SqlKeyword::False),
	UniCase::ascii("FETCH") => TokenKind::Sql(SqlKeyword::Fetch),
	UniCase::ascii("FIELD") => TokenKind::System(SystemKeyword::Field),
	UniCase::ascii("FIELDS") => TokenKind::System(SystemKeyword::Fields),
	UniCase::ascii("FILTERS") => TokenKind::System(SystemKeyword::Filters),
	UniCase::ascii("FLEX") => TokenKind::System(SystemKeyword::Flexible),
	UniCase::ascii("FLEXI") => TokenKind::System(SystemKeyword::Flexible),
	UniCase::ascii("FLEXIBLE") => TokenKind::System(SystemKeyword::Flexible),
	UniCase::ascii("FOR") => TokenKind::Sql(SqlKeyword::For),
	UniCase::ascii("FROM") => TokenKind::Sql(SqlKeyword::From),
	UniCase::ascii("FULL") => TokenKind::System(SystemKeyword::Full),
	UniCase::ascii("FULLTEXT") => TokenKind::System(SystemKeyword::Fulltext),
	UniCase::ascii("FUNCTION") => TokenKind::System(SystemKeyword::Function),
	UniCase::ascii("FUNCTIONS") => TokenKind::System(SystemKeyword::Functions),
	UniCase::ascii("GRANT") => TokenKind::System(SystemKeyword::Grant),
	UniCase::ascii("GRAPHQL") => TokenKind::System(SystemKeyword::Graphql),
	UniCase::ascii("GROUP") => TokenKind::Sql(SqlKeyword::Group),
	UniCase::ascii("HEADER") => TokenKind::System(SystemKeyword::Header),
	UniCase::ascii("HEADERS") => TokenKind::System(SystemKeyword::Headers),
	UniCase::ascii("HIGHLIGHTS") => TokenKind::System(SystemKeyword::Highlights),
	UniCase::ascii("HNSW") => TokenKind::System(SystemKeyword::Hnsw),
	UniCase::ascii("IF") => TokenKind::Sql(SqlKeyword::If),
	UniCase::ascii("IGNORE") => TokenKind::System(SystemKeyword::Ignore),
	UniCase::ascii("IN") => TokenKind::Sql(SqlKeyword::In),
	UniCase::ascii("INCLUDE") => TokenKind::System(SystemKeyword::Include),
	UniCase::ascii("INDEX") => TokenKind::System(SystemKeyword::Index),
	UniCase::ascii("INFO") => TokenKind::System(SystemKeyword::Info),
	UniCase::ascii("INSERT") => TokenKind::Sql(SqlKeyword::Insert),
	UniCase::ascii("INSIDE") => TokenKind::Sql(SqlKeyword::Inside),
	UniCase::ascii("INTERSECTS") => TokenKind::Sql(SqlKeyword::Intersects),
	UniCase::ascii("INTO") => TokenKind::Sql(SqlKeyword::Into),
	UniCase::ascii("IS") => TokenKind::Sql(SqlKeyword::Is),
	UniCase::ascii("ISSUER") => TokenKind::System(SystemKeyword::Issuer),
	UniCase::ascii("JWKS") => TokenKind::System(SystemKeyword::Jwks),
	UniCase::ascii("JWT") => TokenKind::System(SystemKeyword::Jwt),
	UniCase::ascii("KEEP_PRUNED_CONNECTIONS") => TokenKind::System(SystemKeyword::KeepPrunedConnections),
	UniCase::ascii("KEY") => TokenKind::Sql(SqlKeyword::Key),
	UniCase::ascii("KILL") => TokenKind::System(SystemKeyword::Kill),
	UniCase::ascii("KV") => TokenKind::System(SystemKeyword::Root),
	UniCase::ascii("LET") => TokenKind::Sql(SqlKeyword::Let),
	UniCase::ascii("LIMIT") => TokenKind::Sql(SqlKeyword::Limit),
	UniCase::ascii("LIVE") => TokenKind::System(SystemKeyword::Live),
	UniCase::ascii("LM") => TokenKind::System(SystemKeyword::Lm),
	UniCase::ascii("LOWERCASE") => TokenKind::System(SystemKeyword::Lowercase),
	UniCase::ascii("M") => TokenKind::System(SystemKeyword::M),
	UniCase::ascii("M0") => TokenKind::System(SystemKeyword::M0),
	UniCase::ascii("MAPPER") => TokenKind::System(SystemKeyword::Mapper),
	UniCase::ascii("MERGE") => TokenKind::Sql(SqlKeyword::Merge),
	UniCase::ascii("MIDDLEWARE") => TokenKind::System(SystemKeyword::Middleware),
	UniCase::ascii("ML") => TokenKind::System(SystemKeyword::ML),
	UniCase::ascii("MODEL") => TokenKind::System(SystemKeyword::Model),
	UniCase::ascii("MODULE") => TokenKind::System(SystemKeyword::Module),
	UniCase::ascii("NAMESPACE") => TokenKind::System(SystemKeyword::Namespace),
	UniCase::ascii("NGRAM") => TokenKind::System(SystemKeyword::Ngram),
	UniCase::ascii("NO") => TokenKind::System(SystemKeyword::No),
	UniCase::ascii("NOINDEX") => TokenKind::System(SystemKeyword::NoIndex),
	UniCase::ascii("NONE") => TokenKind::Sql(SqlKeyword::None),
	UniCase::ascii("NONEINSIDE") => TokenKind::Sql(SqlKeyword::NoneInside),
	UniCase::ascii("NORMAL") => TokenKind::System(SystemKeyword::Normal),
	UniCase::ascii("NOT") => TokenKind::Sql(SqlKeyword::Not),
	UniCase::ascii("NOTINSIDE") => TokenKind::Sql(SqlKeyword::NotInside),
	UniCase::ascii("NS") => TokenKind::System(SystemKeyword::Namespace),
	UniCase::ascii("NULL") => TokenKind::Sql(SqlKeyword::Null),
	UniCase::ascii("NUMERIC") => TokenKind::System(SystemKeyword::Numeric),
	UniCase::ascii("OMIT") => TokenKind::System(SystemKeyword::Omit),
	UniCase::ascii("ON") => TokenKind::Sql(SqlKeyword::On),
	UniCase::ascii("ONLY") => TokenKind::Sql(SqlKeyword::Only),
	UniCase::ascii("OPTION") => TokenKind::System(SystemKeyword::Option),
	UniCase::ascii("OR") => TokenKind::Sql(SqlKeyword::OrKw),
	UniCase::ascii("ORDER") => TokenKind::Sql(SqlKeyword::Order),
	UniCase::ascii("ORIGINAL") => TokenKind::System(SystemKeyword::Original),
	UniCase::ascii("OUT") => TokenKind::Sql(SqlKeyword::Out),
	UniCase::ascii("OUTSIDE") => TokenKind::Sql(SqlKeyword::Outside),
	UniCase::ascii("OVERWRITE") => TokenKind::System(SystemKeyword::Overwrite),
	UniCase::ascii("PARALLEL") => TokenKind::Sql(SqlKeyword::Parallel),
	UniCase::ascii("PARAM") => TokenKind::System(SystemKeyword::Param),
	UniCase::ascii("PASSHASH") => TokenKind::System(SystemKeyword::Passhash),
	UniCase::ascii("PASSWORD") => TokenKind::System(SystemKeyword::Password),
	UniCase::ascii("PATCH") => TokenKind::Sql(SqlKeyword::Patch),
	UniCase::ascii("PERMISSIONS") => TokenKind::System(SystemKeyword::Permissions),
	UniCase::ascii("POSTINGS_CACHE") => TokenKind::System(SystemKeyword::PostingsCache),
	UniCase::ascii("POSTINGS_ORDER") => TokenKind::System(SystemKeyword::PostingsOrder),
	UniCase::ascii("PREPARE") => TokenKind::System(SystemKeyword::Prepare),
	UniCase::ascii("PUNCT") => TokenKind::System(SystemKeyword::Punct),
	UniCase::ascii("PURGE") => TokenKind::System(SystemKeyword::Purge),
	UniCase::ascii("RANGE") => TokenKind::System(SystemKeyword::Range),
	UniCase::ascii("READONLY") => TokenKind::System(SystemKeyword::Readonly),
	UniCase::ascii("REBUILD") => TokenKind::System(SystemKeyword::Rebuild),
	UniCase::ascii("REFERENCE") => TokenKind::System(SystemKeyword::Reference),
	UniCase::ascii("REFRESH") => TokenKind::System(SystemKeyword::Refresh),
	UniCase::ascii("REJECT") => TokenKind::System(SystemKeyword::Reject),
	UniCase::ascii("RELATE") => TokenKind::Sql(SqlKeyword::Relate),
	UniCase::ascii("RELATION") => TokenKind::System(SystemKeyword::Relation),
	UniCase::ascii("REMOVE") => TokenKind::System(SystemKeyword::Remove),
	UniCase::ascii("REPLACE") => TokenKind::System(SystemKeyword::Replace),
	UniCase::ascii("RESTORE") => TokenKind::System(SystemKeyword::Restore),
	UniCase::ascii("RETURN") => TokenKind::Sql(SqlKeyword::Return),
	UniCase::ascii("REVOKE") => TokenKind::System(SystemKeyword::Revoke),
	UniCase::ascii("REVOKED") => TokenKind::System(SystemKeyword::Revoked),
	UniCase::ascii("ROLES") => TokenKind::System(SystemKeyword::Roles),
	UniCase::ascii("ROOT") => TokenKind::System(SystemKeyword::Root),
	UniCase::ascii("SC") => TokenKind::System(SystemKeyword::Scope),
	UniCase::ascii("SCHEDULER") => TokenKind::System(SystemKeyword::Scheduler),
	UniCase::ascii("SCHEMAFUL") => TokenKind::System(SystemKeyword::Schemafull),
	UniCase::ascii("SCHEMAFULL") => TokenKind::System(SystemKeyword::Schemafull),
	UniCase::ascii("SCHEMALESS") => TokenKind::System(SystemKeyword::Schemaless),
	UniCase::ascii("SELECT") => TokenKind::Sql(SqlKeyword::Select),
	UniCase::ascii("SEQUENCE") => TokenKind::System(SystemKeyword::Sequence),
	UniCase::ascii("SESSION") => TokenKind::System(SystemKeyword::Session),
	UniCase::ascii("SET") => TokenKind::Sql(SqlKeyword::Set),
	UniCase::ascii("SHOW") => TokenKind::System(SystemKeyword::Show),
	UniCase::ascii("SIGNIN") => TokenKind::System(SystemKeyword::Signin),
	UniCase::ascii("SIGNUP") => TokenKind::System(SystemKeyword::Signup),
	UniCase::ascii("SINCE") => TokenKind::System(SystemKeyword::Since),
	UniCase::ascii("SLEEP") => TokenKind::System(SystemKeyword::Sleep),
	UniCase::ascii("SNOWBALL") => TokenKind::System(SystemKeyword::Snowball),
	UniCase::ascii("SPLIT") => TokenKind::Sql(SqlKeyword::Split),
	UniCase::ascii("START") => TokenKind::Sql(SqlKeyword::Start),
	UniCase::ascii("STRICT") => TokenKind::System(SystemKeyword::Strict),
	UniCase::ascii("STRUCTURE") => TokenKind::System(SystemKeyword::Structure),
	UniCase::ascii("SYSTEM") => TokenKind::System(SystemKeyword::System),
	UniCase::ascii("TABLE") => TokenKind::System(SystemKeyword::Table),
	UniCase::ascii("TABLES") => TokenKind::System(SystemKeyword::Tables),
	UniCase::ascii("TB") => TokenKind::System(SystemKeyword::Table),
	UniCase::ascii("TEMPFILES") => TokenKind::System(SystemKeyword::TempFiles),
	UniCase::ascii("TERMS_CACHE") => TokenKind::System(SystemKeyword::TermsCache),
	UniCase::ascii("TERMS_ORDER") => TokenKind::System(SystemKeyword::TermsOrder),
	UniCase::ascii("THEN") => TokenKind::Sql(SqlKeyword::Then),
	UniCase::ascii("THROW") => TokenKind::Sql(SqlKeyword::Throw),
	UniCase::ascii("TIMEOUT") => TokenKind::Sql(SqlKeyword::Timeout),
	UniCase::ascii("TO") => TokenKind::System(SystemKeyword::To),
	UniCase::ascii("TOKEN") => TokenKind::System(SystemKeyword::Token),
	UniCase::ascii("TOKENIZERS") => TokenKind::System(SystemKeyword::Tokenizers),
	UniCase::ascii("TRANSACTION") => TokenKind::Sql(SqlKeyword::Transaction),
	UniCase::ascii("true") => TokenKind::Sql(SqlKeyword::True),
	UniCase::ascii("TYPE") => TokenKind::System(SystemKeyword::Type),
	UniCase::ascii("UNIQUE") => TokenKind::System(SystemKeyword::Unique),
	UniCase::ascii("UNSET") => TokenKind::Sql(SqlKeyword::Unset),
	UniCase::ascii("UPDATE") => TokenKind::Sql(SqlKeyword::Update),
	UniCase::ascii("UPPERCASE") => TokenKind::System(SystemKeyword::Uppercase),
	UniCase::ascii("UPSERT") => TokenKind::Sql(SqlKeyword::Upsert),
	UniCase::ascii("URL") => TokenKind::System(SystemKeyword::Url),
	UniCase::ascii("USE") => TokenKind::Sql(SqlKeyword::Use),
	UniCase::ascii("USER") => TokenKind::System(SystemKeyword::User),
	UniCase::ascii("VALUE") => TokenKind::Sql(SqlKeyword::Value),
	UniCase::ascii("VALUES") => TokenKind::Sql(SqlKeyword::Values),
	UniCase::ascii("VERSION") => TokenKind::Sql(SqlKeyword::Version),
	UniCase::ascii("VS") => TokenKind::System(SystemKeyword::Vs),
	UniCase::ascii("WEBHOOK") => TokenKind::System(SystemKeyword::Webhook),
	UniCase::ascii("WHEN") => TokenKind::System(SystemKeyword::When),
	UniCase::ascii("WHERE") => TokenKind::Sql(SqlKeyword::Where),
	UniCase::ascii("WITH") => TokenKind::Sql(SqlKeyword::With),

	// Types
	UniCase::ascii("ANY") => TokenKind::Sql(SqlKeyword::Any),
	UniCase::ascii("ARRAY") => TokenKind::System(SystemKeyword::Array),
	UniCase::ascii("BOOL") => TokenKind::System(SystemKeyword::Bool),
	UniCase::ascii("BYTES") => TokenKind::System(SystemKeyword::Bytes),
	UniCase::ascii("COLLECTION") => TokenKind::System(SystemKeyword::Collection),
	UniCase::ascii("DATETIME") => TokenKind::System(SystemKeyword::Datetime),
	UniCase::ascii("DECIMAL") => TokenKind::System(SystemKeyword::Decimal),
	UniCase::ascii("DURATION") => TokenKind::System(SystemKeyword::Duration),
	UniCase::ascii("FEATURE") => TokenKind::System(SystemKeyword::Feature),
	UniCase::ascii("FILE") => TokenKind::System(SystemKeyword::File),
	UniCase::ascii("FLOAT") => TokenKind::System(SystemKeyword::Float),
	UniCase::ascii("GEOMETRY") => TokenKind::System(SystemKeyword::Geometry),
	UniCase::ascii("fn") => TokenKind::System(SystemKeyword::Fn),
	UniCase::ascii("silo") => TokenKind::System(SystemKeyword::Silo),
	UniCase::ascii("mod") => TokenKind::System(SystemKeyword::Mod),
	UniCase::ascii("INT") => TokenKind::System(SystemKeyword::Int),
	UniCase::ascii("LINE") => TokenKind::System(SystemKeyword::Line),
	UniCase::ascii("MULTILINE") => TokenKind::System(SystemKeyword::MultiLine),
	UniCase::ascii("MULTIPOINT") => TokenKind::System(SystemKeyword::MultiPoint),
	UniCase::ascii("MULTIPOLYGON") => TokenKind::System(SystemKeyword::MultiPolygon),
	UniCase::ascii("NUMBER") => TokenKind::System(SystemKeyword::Number),
	UniCase::ascii("OBJECT") => TokenKind::System(SystemKeyword::Object),
	UniCase::ascii("POINT") => TokenKind::System(SystemKeyword::Point),
	UniCase::ascii("POLYGON") => TokenKind::System(SystemKeyword::Polygon),
	UniCase::ascii("RAND") => TokenKind::Sql(SqlKeyword::Random),
	UniCase::ascii("RECORD") => TokenKind::System(SystemKeyword::Record),
	UniCase::ascii("REFERENCES") => TokenKind::System(SystemKeyword::References),
	UniCase::ascii("REGEX") => TokenKind::System(SystemKeyword::Regex),
	UniCase::ascii("STRING") => TokenKind::System(SystemKeyword::String),
	UniCase::ascii("ULID") => TokenKind::System(SystemKeyword::Ulid),
	UniCase::ascii("UUID") => TokenKind::System(SystemKeyword::Uuid),
	UniCase::ascii("VECTOR") => TokenKind::System(SystemKeyword::Vector),

	// Languages
	UniCase::ascii("AR") => TokenKind::Language(Language::Arabic),
	UniCase::ascii("ARA") => TokenKind::Language(Language::Arabic),
	UniCase::ascii("ARABIC") => TokenKind::Language(Language::Arabic),
	UniCase::ascii("DA") => TokenKind::Language(Language::Danish),
	UniCase::ascii("DAN") => TokenKind::Language(Language::Danish),
	UniCase::ascii("DANISH") => TokenKind::Language(Language::Danish),
	UniCase::ascii("DE") => TokenKind::Language(Language::German),
	UniCase::ascii("DEU") => TokenKind::Language(Language::German),
	UniCase::ascii("DUTCH") => TokenKind::Language(Language::Dutch),
	UniCase::ascii("EL") => TokenKind::Language(Language::Greek),
	UniCase::ascii("ELL") => TokenKind::Language(Language::Greek),
	UniCase::ascii("EN") => TokenKind::Language(Language::English),
	UniCase::ascii("ENG") => TokenKind::Language(Language::English),
	UniCase::ascii("ENGLISH") => TokenKind::Language(Language::English),
	UniCase::ascii("ES") => TokenKind::Language(Language::Spanish),
	UniCase::ascii("FI") => TokenKind::Language(Language::Finnish),
	UniCase::ascii("FIN") => TokenKind::Language(Language::Finnish),
	UniCase::ascii("FINNISH") => TokenKind::Language(Language::Finnish),
	UniCase::ascii("FR") => TokenKind::Language(Language::French),
	UniCase::ascii("FRA") => TokenKind::Language(Language::French),
	UniCase::ascii("FRENCH") => TokenKind::Language(Language::French),
	UniCase::ascii("GERMAN") => TokenKind::Language(Language::German),
	UniCase::ascii("GREEK") => TokenKind::Language(Language::Greek),
	UniCase::ascii("HU") => TokenKind::Language(Language::Hungarian),
	UniCase::ascii("HUN") => TokenKind::Language(Language::Hungarian),
	UniCase::ascii("HUNGARIAN") => TokenKind::Language(Language::Hungarian),
	UniCase::ascii("IT") => TokenKind::Language(Language::Italian),
	UniCase::ascii("ITA") => TokenKind::Language(Language::Italian),
	UniCase::ascii("ITALIAN") => TokenKind::Language(Language::Italian),
	UniCase::ascii("NL") => TokenKind::Language(Language::Dutch),
	UniCase::ascii("NLD") => TokenKind::Language(Language::Dutch),
	UniCase::ascii("NOR") => TokenKind::Language(Language::Norwegian),
	UniCase::ascii("NORWEGIAN") => TokenKind::Language(Language::Norwegian),
	UniCase::ascii("POR") => TokenKind::Language(Language::Portuguese),
	UniCase::ascii("PORTUGUESE") => TokenKind::Language(Language::Portuguese),
	UniCase::ascii("PT") => TokenKind::Language(Language::Portuguese),
	UniCase::ascii("RO") => TokenKind::Language(Language::Romanian),
	UniCase::ascii("ROMANIAN") => TokenKind::Language(Language::Romanian),
	UniCase::ascii("RON") => TokenKind::Language(Language::Romanian),
	UniCase::ascii("RU") => TokenKind::Language(Language::Russian),
	UniCase::ascii("RUS") => TokenKind::Language(Language::Russian),
	UniCase::ascii("RUSSIAN") => TokenKind::Language(Language::Russian),
	UniCase::ascii("SPA") => TokenKind::Language(Language::Spanish),
	UniCase::ascii("SPANISH") => TokenKind::Language(Language::Spanish),
	UniCase::ascii("SV") => TokenKind::Language(Language::Swedish),
	UniCase::ascii("SWE") => TokenKind::Language(Language::Swedish),
	UniCase::ascii("SWEDISH") => TokenKind::Language(Language::Swedish),
	UniCase::ascii("TA") => TokenKind::Language(Language::Tamil),
	UniCase::ascii("TAM") => TokenKind::Language(Language::Tamil),
	UniCase::ascii("TAMIL") => TokenKind::Language(Language::Tamil),
	UniCase::ascii("TR") => TokenKind::Language(Language::Turkish),
	UniCase::ascii("TUR") => TokenKind::Language(Language::Turkish),
	UniCase::ascii("TURKISH") => TokenKind::Language(Language::Turkish),

	// Algorithms
	UniCase::ascii("EDDSA") => TokenKind::Algorithm(Algorithm::EdDSA),
	UniCase::ascii("ES256") => TokenKind::Algorithm(Algorithm::Es256),
	UniCase::ascii("ES384") => TokenKind::Algorithm(Algorithm::Es384),
	UniCase::ascii("ES512") => TokenKind::Algorithm(Algorithm::Es512),
	UniCase::ascii("HS256") => TokenKind::Algorithm(Algorithm::Hs256),
	UniCase::ascii("HS384") => TokenKind::Algorithm(Algorithm::Hs384),
	UniCase::ascii("HS512") => TokenKind::Algorithm(Algorithm::Hs512),
	UniCase::ascii("PS256") => TokenKind::Algorithm(Algorithm::Ps256),
	UniCase::ascii("PS384") => TokenKind::Algorithm(Algorithm::Ps384),
	UniCase::ascii("PS512") => TokenKind::Algorithm(Algorithm::Ps512),
	UniCase::ascii("RS256") => TokenKind::Algorithm(Algorithm::Rs256),
	UniCase::ascii("RS384") => TokenKind::Algorithm(Algorithm::Rs384),
	UniCase::ascii("RS512") => TokenKind::Algorithm(Algorithm::Rs512),

	// Distance
	UniCase::ascii("CHEBYSHEV") => TokenKind::Distance(DistanceKind::Chebyshev),
	UniCase::ascii("COSINE") => TokenKind::Distance(DistanceKind::Cosine),
	UniCase::ascii("EUCLIDEAN") => TokenKind::Distance(DistanceKind::Euclidean),
	UniCase::ascii("HAMMING") => TokenKind::Distance(DistanceKind::Hamming),
	UniCase::ascii("JACCARD") => TokenKind::Distance(DistanceKind::Jaccard),
	UniCase::ascii("MANHATTAN") => TokenKind::Distance(DistanceKind::Manhattan),
	UniCase::ascii("MINKOWSKI") => TokenKind::Distance(DistanceKind::Minkowski),
	UniCase::ascii("PEARSON") => TokenKind::Distance(DistanceKind::Pearson),

	// VectorTypes
	UniCase::ascii("F32") => TokenKind::VectorType(VectorTypeKind::F32),
	UniCase::ascii("F64") => TokenKind::VectorType(VectorTypeKind::F64),
	UniCase::ascii("I16") => TokenKind::VectorType(VectorTypeKind::I16),
	UniCase::ascii("I32") => TokenKind::VectorType(VectorTypeKind::I32),
	UniCase::ascii("I64") => TokenKind::VectorType(VectorTypeKind::I64),

	// HTTP methods
	UniCase::ascii("GET") => TokenKind::Sql(SqlKeyword::Get),
	UniCase::ascii("POST") => TokenKind::Sql(SqlKeyword::Post),
	UniCase::ascii("PUT") => TokenKind::Sql(SqlKeyword::Put),
	UniCase::ascii("TRACE") => TokenKind::Sql(SqlKeyword::Trace)
};
