[workspace]
resolver = "2"
package.license = "MIT OR Apache-2.0"
package.homepage = "https://juspay.io/open-source/superposition"
package.repository = "https://github.com/juspay/superposition"
package.readme = "README.md"
package.authors = ["superposition@juspay.in"]
package.version = "*"
package.rust-version = "1.75.0"
package.edition = "2024"

members = [
    "crates/service_utils",
    "crates/context_aware_config",
    "crates/experimentation_platform",
    "crates/experimentation_client",
    "crates/cac_client",
    "crates/frontend",
    "crates/cac_toml",
    "crates/superposition",
    "crates/superposition_types",
    "crates/superposition_macros",
    "crates/superposition_derives",
    "crates/superposition_core",
    "crates/superposition_provider",
    "crates/superposition_sdk",
    "examples/experimentation_client_integration_example",
    "examples/cac_client_integration_example",
    "examples/superposition-demo-app",
]

[[workspace.metadata.leptos]]
name = "cac"
bin-package = "juspay_superposition"
output-name = "frontend"
lib-package = "frontend"
site-root = "target/site"
site-pkg-dir = "pkg"
style-file = "crates/frontend/styles/style.css"
assets-dir = "crates/frontend/assets"

[workspace.dependencies]
actix-web = "4.5.0"
anyhow = "1.0.75"
aws-sdk-kms = { version = "*" }
base64 = "0.21.2"
bigdecimal = { version = "*", features = ["serde"] }
cfg-if = "1.0.0"
chrono = { version = "*", features = ["serde"] }
derive_more = "^0.99"
diesel = { version = "*", package = "juspay_diesel", features = [
    "postgres",
    "r2d2",
    "serde_json",
    "chrono",
    "uuid",
    "postgres_backend",
    "numeric",
] }
fred = { version = "*" }
futures-util = "0.3.28"
itertools = { version = "*" }
jsonlogic = { version = "*", package = "juspay_jsonlogic" }
jsonschema = "~0.17"
leptos = { version = "*" }
log = { version = "*", features = ["kv_unstable_serde"] }
once_cell = { version = "*" }
regex = "1.9.1"
reqwest = { version = "*", features = ["json"] }
rs-snowflake = "0.6.0"
serde = { version = "*", features = ["derive"] }
serde_json = { version = "*" }
secrecy = "0.10"
strum = "0.25"
strum_macros = "0.25"
toml = { version = "*", features = ["preserve_order"] }
actix-http = "3.3.1"
tracing = "0.1.44"
tracing-subscriber = { version = "*", features = ["env-filter", "fmt", "json"] }
tracing-actix-web = "0.7.21"
url = "2.5.0"
uuid = { version = "*", features = ["v4", "serde", "js"] }
uniffi = { version = "*", features = [ "cli" ] }
superposition = { path = "./crates/superposition" }
superposition_types = { path = "./crates/superposition_types" }
superposition_derives = { path = "./crates/superposition_derives" }
superposition_macros = { path = "./crates/superposition_macros" }
superposition_core = { path = "./crates/superposition_core" }
superposition_provider = { path = "./crates/superposition_provider" }
superposition_sdk = { path = "./crates/superposition_sdk" }
service_utils = { path = "./crates/service_utils" }

[workspace.lints.clippy]
mod_module_files = "warn"
manual_range_contains = "allow"


[patch.crates-io]
leptos = { path = "../leptos/leptos" }
leptos_meta = { path = "../leptos/meta" }
leptos_router = { path = "../leptos/router" }
leptos_axum = { path = "../leptos/integrations/axum" }
leptos_actix = { path = "../leptos/integrations/actix" }
leptos_dom = { path = "../leptos/leptos_dom" }
leptos_macro = { path = "../leptos/leptos_macro" }
leptos_server = { path = "../leptos/leptos_server" }
leptos_config = { path = "../leptos/leptos_config" }
reactive_graph = { path = "../leptos/reactive_graph" }
reactive_stores = { path = "../leptos/reactive_stores" }
reactive_stores_macro = { path = "../leptos/reactive_stores_macro" }
server_fn = { path = "../leptos/server_fn" }
server_fn_macro = { path = "../leptos/server_fn_macro" }
tachys = { path = "../leptos/tachys" }
hydration_context = { path = "../leptos/hydration_context" }
throw_error = { path = "../leptos/any_error" }
any_spawner = { path = "../leptos/any_spawner" }
either_of = { path = "../leptos/either_of" }
oco_ref = { path = "../leptos/oco" }
or_poisoned = { path = "../leptos/or_poisoned" }
next_tuple = { path = "../leptos/next_tuple" }
leptos-use = { path = "../logic/lyx-logic-use" }
tailwind_fuse = { path = "../../ui-foundations/lyx-found-tailwind/fuse" }










