[package]
name = "devtools"
version = "0.8.0"
edition = "2024"

[dependencies]


cfg-if = { version = "*" }
leptos = { path = "../core/lyx-core-leptos/leptos" }
query = { path = "../query" }
js-sys = { version = "*" , optional = true }
web-sys = { version = "*", optional = true, features = ["DomRect"] }
wasm-bindgen = { version = "*" , optional = true }

[features]
csr = ["dep:web-sys", "wasm-bindgen", "js-sys"]
force = []

#











