[package]
name = "superposition_types"
version = "0.8.0"
edition = "2024"

[dependencies]
# env
actix-web = { version = "*", optional = true }
anyhow = { version = "*", optional = true }
base64 = { version = "*", optional = true }
bigdecimal = { version = "*" }
chrono = { version = "*" }
derive_more = { version = "*" }
diesel = { version = "*", optional = true }
diesel-derive-enum = { version = "*", optional = true, features = ["postgres" ] }
jsonlogic = { version = "*" }
log = { version = "*" }
regex = { version = "*" }
serde = { version = "*" }
serde_json = { version = "*" }
serde_urlencoded = { version = "*" }
strum = { version = "*" }
strum_macros = { version = "*" }
superposition_derives = { path = "../superposition_derives", optional = true }
thiserror = { version = "*", optional = true }
uuid = { version = "*" }
uniffi = { version = "*" }

[dev-dependencies]
uniffi = { version = "*" }

[features]
diesel_derives = [
"dep:diesel",
"superposition_derives/diesel_derives",
"dep:diesel-derive-enum",
"dep:base64" ]
disable_db_data_validation = []
result = ["dep:diesel", "dep:anyhow", "dep:thiserror", "dep:actix-web"]
server = ["dep:actix-web"]
experimentation = []
api = []







