[package]
name = "frontend"
version = "0.0.1"
edition = "2024"
[lib]
crate-type = ["cdylib", "rlib"]
[dependencies]
app = { version = "0.0.1", path = "../../../../../platform/lyx-plat-tauri/app", optional = false, default-features = false, features = ["hydrate"] }
leptos = { version = "0.0.1", path = "../../../leptos", optional = false, features = [ "hydrate" ] }
ids = { version = "0.0.1", path = "../ids", optional = false }
