[package]
name = "lyx-comm-ws"
version = "0.8.0"
edition = "2024"

[dependencies]
json-patch = { version = "*" }
leptos = { path = "../core/lyx-core-leptos/leptos" }

serde = { version = "*", features = ["derive"] }
serde_json = { version = "*" }
thiserror = { version = "*" }
async-trait = { version = "*" }

futures = { version = "*", default-features = false }
tokio = { version = "*", features = ["sync"] }
dashmap = { version = "*" }
nanoid = { version = "*", optional = true }
gloo-timers = { version = "*", optional = true, features = ["futures"] }

[dev-dependencies]
tokio = { version = "*", features = ["time"] }
[features]
default = []
ssr = ["leptos/ssr", "dep:nanoid","tokio/rt-multi-thread"]
csr = ["leptos/csr","dep:gloo-timers"]
hydrate = ["leptos/hydrate","dep:gloo-timers"]










