[workspace]
resolver = "3"
members = ["trading-charts", "wasmbind-macro", "example"]
default-members = ["trading-charts", "wasmbind-macro"]

[workspace.package]
version = "0.8.0"
edition = "2021"
authors = ["Frédéric Meyer <frederic.meyer.77@gmail.com>"]
description = "Rust binding of Lightweight Charts for Leptos"
repository = "https://github.com/corebreaker/rs-trading-charts"
documentation = "https://docs.rs/trading-charts/"
readme = "README.md"
license = "MIT"
keywords = [
    "leptos",
]

categories = [
    "finance",
    "web-programming",
    "wasm",
]

# Pour exécuter ces commandes avec `cargo run-script`, il faut d'abord l'installer : `cargo install cargo-run-script`
[workspace.metadata.scripts]
fmt = "cargo +nightly fmt --all"
gc = "cargo sweep -r -t 10 ."

[workspace.dependencies]
console_error_panic_hook = "0.1"
console_log = "1.0"
emitix = { version = "*", features = ["leptos"] }
js-sys = "0.3"
leptos = { version = "*", features = ["csr"] }
log = "0.4"
serde = { version = "*", features = ["derive"] }
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2"
web-sys = { version = "*", features = ["Document", "Element", "HtmlElement", "Node", "Window"] }


[patch.crates-io]
leptos = { path = "../core/lyx-core-leptos/leptos" }
leptos_meta = { path = "../core/lyx-core-leptos/meta" }
leptos_router = { path = "../core/lyx-core-leptos/router" }
leptos_axum = { path = "../../core/leptos/integrations/axum" }
leptos_actix = { path = "../../core/leptos/integrations/actix" }
leptos_dom = { path = "../../core/leptos/leptos_dom" }
leptos_macro = { path = "../../core/leptos/leptos_macro" }
leptos_server = { path = "../../core/leptos/leptos_server" }
leptos_config = { path = "../../core/leptos/leptos_config" }
reactive_graph = { path = "../../core/leptos/reactive_graph" }
reactive_stores = { path = "../../core/leptos/reactive_stores" }
reactive_stores_macro = { path = "../../core/leptos/reactive_stores_macro" }
server_fn = { path = "../../core/leptos/server_fn" }
server_fn_macro = { path = "../../core/leptos/server_fn_macro" }
tachys = { path = "../core/lyx-core-leptos/tachys" }
hydration_context = { path = "../../core/leptos/hydration_context" }
throw_error = { path = "../../core/leptos/any_error" }
any_spawner = { path = "../../core/leptos/any_spawner" }
either_of = { path = "../../core/leptos/either_of" }
oco_ref = { path = "../../core/leptos/oco" }
or_poisoned = { path = "../../core/leptos/or_poisoned" }
next_tuple = { path = "../../core/leptos/next_tuple" }
leptos-use = { path = "../logic/lyx-logic-use" }
tailwind_fuse = { path = "../../ui-foundations/lyx-found-tailwind/fuse" }







