### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\leptos\leptos\Cargo.toml
[package]
name = "leptos"
version = "0.8.0"
edition = "2024"

[dependencies]
base64 = { version = "0.8.0", optional = true }
leptos_dom = { path = "../leptos_dom", version = "*" }
leptos_macro = { path = "../leptos_macro", version = "*" }
reactive_graph = { path = "../reactive_graph", version = "*" }
tachys = { path = "../tachys", version = "*" }
any_spawner = { path = "../any_spawner", version = "*" }
server_fn = { path = "../server_fn", version = "*" }
serde = { version = "*", features = ["derive"] }

[features]
nonce = ["dep:base64"]
nightly = ["leptos_macro/nightly", "leptos_dom/nightly"]
hydrate = ["leptos_dom/hydrate", "leptos_macro/hydrate"]
ssr = ["leptos_dom/ssr", "leptos_macro/ssr", "server_fn/ssr"]
csr = ["leptos_dom/csr", "leptos_macro/csr"]


[build-dependencies]
rustc_version = "*"





