### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-leptos\leptos\Cargo.toml
[package]
name = "lyx-core-leptos"
version = "0.0.1"
edition = "2024"

[dependencies]
base64 = { version = "0.21", optional = true }
lyx-core-leptos_dom = { path = "../leptos_dom", version = "0.0.1" }
lyx-core-leptos_macro = { path = "../leptos_macro", version = "0.0.1" }
lyx-core-reactive_graph = { path = "../reactive_graph", version = "0.0.1" }
lyx-core-tachys = { path = "../tachys", version = "0.0.1" }
lyx-core-any_spawner = { path = "../any_spawner", version = "0.0.1" }
lyx-core-server_fn = { path = "../server_fn", version = "0.0.1" }
serde = { version = "0.0.1", features = ["derive"] }

[features]
nonce = ["dep:base64"]
nightly = ["lyx-core-leptos_macro/nightly", "lyx-core-leptos_dom/nightly"]
hydrate = ["lyx-core-leptos_dom/hydrate", "lyx-core-leptos_macro/hydrate"]
ssr = ["lyx-core-leptos_dom/ssr", "lyx-core-leptos_macro/ssr", "lyx-core-server_fn/ssr"]
csr = ["lyx-core-leptos_dom/csr", "lyx-core-leptos_macro/csr"]
