-- =============================================================================================
-- |
-- | Fichier     : i18n_week_start_i18n_key_seeds.surql
-- | Module      : i18n
-- | Description : Peuple la table `i18n_key` avec les clés pour les jours de la semaine.
-- |
-- =============================================================================================

CREATE i18n_key:'i18n.week_day.1.name' SET description = "Nom pour le jour 'Lundi'";
CREATE i18n_key:'i18n.week_day.2.name' SET description = "Nom pour le jour 'Mardi'";
CREATE i18n_key:'i18n.week_day.3.name' SET description = "Nom pour le jour 'Mercredi'";
CREATE i18n_key:'i18n.week_day.4.name' SET description = "Nom pour le jour 'Jeudi'";
CREATE i18n_key:'i18n.week_day.5.name' SET description = "Nom pour le jour 'Vendredi'";
CREATE i18n_key:'i18n.week_day.6.name' SET description = "Nom pour le jour 'Samedi'";
CREATE i18n_key:'i18n.week_day.7.name' SET description = "Nom pour le jour 'Dimanche'";
