[package]
name = "sample-crumbs"
version = "0.8.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
src = { path = "../src", optional = true }
leptos = { path = "../../leptos/leptos", optional = true }
axum = { version = "*", optional = true }
leptos_axum = { path = "../../leptos/integrations/axum", optional = true }
tokio = { version = "*", optional = true }
wasm-bindgen = { version = "*" }

[features]
default = ["ssr"]
hydrate = ["leptos/hydrate"]
ssr = [
"dep:axum",
"dep:tokio",
"dep:leptos_axum",
"leptos/ssr",
"src/ssr"
]










