[workspace]
resolver = "2"
members = ["singlestage", "docs", "singlestage_macro", "docs_macro"]

[workspace.package]
version = "*"
authors = ["Adam Doyle <adam@doordesk.net>"]
edition = "2024"
rust-version = "1.75.0"
description = "A UI component library for Leptos based on Basecoat UI and shadcn/ui"
homepage = "https://singlestage.doordesk.net"
repository = "https://github.com/adoyle0/singlestage-ui"
license = "MIT"
keywords = ["leptos", "ui", "components", "basecoat", "shadcn"]
categories = ["web-programming", "gui", "wasm"]

[workspace.dependencies]
leptos = "0.8"
leptos_meta = "0.8"
leptos_router = "0.8"
leptos_axum = "0.8"

# Singlestage
icondata_core = "0.1"

# Singlestage build
reqwest = "0.12"
sha256 = "1.6"

# Docs
axum = "0.8"
console_error_panic_hook = "0.1"
icondata = "0.6"
tokio = "1"
tower = "0.5"
tower-http = "0.6"
uuid = "1.17"
wasm-bindgen = "0.2"

# Macros
serde = "1.0"
syntect = "5"
toml = "0.9"
quote = "1.0"
syn = "2.0"

[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"


[patch.crates-io]
leptos = { path = "../../core/lyx-core-leptos/leptos" }
leptos_meta = { path = "../../core/lyx-core-leptos/meta" }
leptos_router = { path = "../../core/lyx-core-leptos/router" }
leptos_axum = { path = "../../core/lyx-core-leptos/integrations/axum" }
leptos_actix = { path = "../../core/lyx-core-leptos/integrations/actix" }
leptos_dom = { path = "../../core/lyx-core-leptos/leptos_dom" }
leptos_macro = { path = "../../core/lyx-core-leptos/leptos_macro" }
leptos_server = { path = "../../core/lyx-core-leptos/leptos_server" }
leptos_config = { path = "../../core/lyx-core-leptos/leptos_config" }
reactive_graph = { path = "../../core/lyx-core-leptos/reactive_graph" }
reactive_stores = { path = "../../core/lyx-core-leptos/reactive_stores" }
reactive_stores_macro = { path = "../../core/lyx-core-leptos/reactive_stores_macro" }
server_fn = { path = "../../core/lyx-core-leptos/server_fn" }
server_fn_macro = { path = "../../core/lyx-core-leptos/server_fn_macro" }
tachys = { path = "../../core/lyx-core-leptos/tachys" }
hydration_context = { path = "../../core/lyx-core-leptos/hydration_context" }
throw_error = { path = "../../core/lyx-core-leptos/any_error" }
any_spawner = { path = "../../core/lyx-core-leptos/any_spawner" }
either_of = { path = "../../core/lyx-core-leptos/either_of" }
oco_ref = { path = "../../core/lyx-core-leptos/oco" }
or_poisoned = { path = "../../core/lyx-core-leptos/or_poisoned" }
next_tuple = { path = "../../core/lyx-core-leptos/next_tuple" }
leptos-use = { path = "../../logic/lyx-logic-use" }
tailwind_fuse = { path = "../../ui-foundations/lyx-found-tailwind/fuse" }









