-- Clés i18n pour les villes du pays: BH --

CREATE i18n_key:i18n_city_bh_9757_name SET description = 'Nom pour la ville \'Jidd Ḩafş\'';
CREATE i18n_key:i18n_city_bh_9760_name SET description = 'Nom pour la ville \'Manama\'';
CREATE i18n_key:i18n_city_bh_9761_name SET description = 'Nom pour la ville \'Sitrah\'';
CREATE i18n_key:i18n_city_bh_9758_name SET description = 'Nom pour la ville \'Madīnat Ḩamad\'';
CREATE i18n_key:i18n_city_bh_9754_name SET description = 'Nom pour la ville \'Al Ḩadd\'';
CREATE i18n_key:i18n_city_bh_9753_name SET description = 'Nom pour la ville \'Al Muharraq\'';
CREATE i18n_key:i18n_city_bh_9755_name SET description = 'Nom pour la ville \'Ar Rifā‘\'';
CREATE i18n_key:i18n_city_bh_9756_name SET description = 'Nom pour la ville \'Dār Kulayb\'';
CREATE i18n_key:i18n_city_bh_9759_name SET description = 'Nom pour la ville \'Madīnat ‘Īsá\'';
