### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-config\crates\lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_context_override_request.rs
```rust
1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_context_override_request.rs
2: ```rust
3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_context_override_request.rs
4: 2: ```rust
5: 3: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_context_override_request.rs
6: 4: ```rust
7: 5: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_context_override_request.rs
8: 6: ```rust
9: 7: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_context_override_request.rs
10: 8: ```rust
11: 9: // Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
12: 10: pub fn ser_update_context_override_request(
13: 11:                          object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
14: 12:                          input: &crate::types::UpdateContextOverrideRequest,
15: 13:                     ) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
16: 14:      {
17: 15:         #[allow(unused_mut)]
18: 16:         let mut object_1 = object.key("context").start_object();
19: 17:         crate::protocol_serde::shape_context_identifier::ser_context_identifier(&mut object_1, &input.context)?;
20: 18:         object_1.finish();
21: 19:     }
22: 20:      {
23: 21:         #[allow(unused_mut)]
24: 22:         let mut object_2 = object.key("override").start_object();
25: 23:         for (key_3, value_4) in &input.r#override {
26: 24:              {
27: 25:                 object_2.key(key_3.as_str()).document(value_4);
28: 26:             }
29: 27:         }
30: 28:         object_2.finish();
31: 29:     }
32: 30:     if let Some(var_5) = &input.description {
33: 31:         object.key("description").string(var_5.as_str());
34: 32:     }
35: 33:      {
36: 34:         object.key("change_reason").string(input.change_reason.as_str());
37: 35:     }
38: 36:     Ok(())
39: 37: }
40: 38: 
41: 39: ```
42: 40: ```
43: 41: ```
44: 42: ```
45: ```
```
