### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-config\crates\lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_validate_context_input.rs
```rust
1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_validate_context_input.rs
2: ```rust
3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_validate_context_input.rs
4: 2: ```rust
5: 3: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_validate_context_input.rs
6: 4: ```rust
7: 5: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_validate_context_input.rs
8: 6: ```rust
9: 7: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_validate_context_input.rs
10: 8: ```rust
11: 9: // Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
12: 10: pub fn ser_validate_context_input_input(
13: 11:                          object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
14: 12:                          input: &crate::operation::validate_context::ValidateContextInput,
15: 13:                     ) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
16: 14:     if let Some(var_1) = &input.context {
17: 15:         #[allow(unused_mut)]
18: 16:         let mut object_2 = object.key("context").start_object();
19: 17:         for (key_3, value_4) in var_1 {
20: 18:              {
21: 19:                 object_2.key(key_3.as_str()).document(value_4);
22: 20:             }
23: 21:         }
24: 22:         object_2.finish();
25: 23:     }
26: 24:     Ok(())
27: 25: }
28: 26: 
29: 27: ```
30: 28: ```
31: 29: ```
32: 30: ```
33: ```
```
