### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-config\crates\lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_override_input.rs
```rust
1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_override_input.rs
2: ```rust
3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_override_input.rs
4: 2: ```rust
5: 3: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_override_input.rs
6: 4: ```rust
7: 5: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_override_input.rs
8: 6: ```rust
9: 7: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_override_input.rs
10: 8: ```rust
11: 9: // Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
12: 10: pub fn ser_request_http_payload(payload: &::std::option::Option<crate::types::UpdateContextOverrideRequest>) -> ::std::result::Result<::std::vec::Vec<u8>, ::aws_smithy_types::error::operation::BuildError> {
13: 11:     let payload = match payload.as_ref() {
14: 12:                                     Some(t) => t,
15: 13:                                     None => return Ok(
16: 14:         crate::protocol_serde::rest_json_unset_struct_payload()
17: 15:     )};
18: 16:     Ok(
19: 17:         crate::protocol_serde::shape_update_override_input::ser_request_payload(payload)?
20: 18:     )
21: 19: }
22: 20: 
23: 21: pub fn ser_request_payload(input: &crate::types::UpdateContextOverrideRequest) -> std::result::Result<::std::vec::Vec<u8>, ::aws_smithy_types::error::operation::SerializationError> {
24: 22:     let mut out = String::new();
25: 23:     let mut object = ::aws_smithy_json::serialize::JsonObjectWriter::new(&mut out);
26: 24:     crate::protocol_serde::shape_update_context_override_request::ser_update_context_override_request(&mut object, input)?;
27: 25:     object.finish();
28: 26:     Ok(out.into_bytes())
29: 27: }
30: 28: 
31: 29: ```
32: 30: ```
33: 31: ```
34: 32: ```
35: ```
```
