### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-config\crates\lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_type_templates_response.rs
```rust
1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_type_templates_response.rs
2: ```rust
3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_type_templates_response.rs
4: 2: ```rust
5: 3: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_type_templates_response.rs
6: 4: ```rust
7: 5: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_type_templates_response.rs
8: 6: ```rust
9: 7: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_type_templates_response.rs
10: 8: ```rust
11: 9: // Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
12: 10: pub(crate) fn de_type_templates_response<'a, I>(tokens: &mut ::std::iter::Peekable<I>) -> ::std::result::Result<Option<crate::types::TypeTemplatesResponse>, ::aws_smithy_json::deserialize::error::DeserializeError>
13: 11:                         where I: Iterator<Item = Result<::aws_smithy_json::deserialize::Token<'a>, ::aws_smithy_json::deserialize::error::DeserializeError>> {
14: 12:     match tokens.next().transpose()? {
15: 13:         Some(::aws_smithy_json::deserialize::Token::ValueNull { .. }) => Ok(None),
16: 14:                         Some(::aws_smithy_json::deserialize::Token::StartObject { .. }) => {
17: 15:             #[allow(unused_mut)]
18: 16:             let mut builder = crate::types::builders::TypeTemplatesResponseBuilder::default();
19: 17:             loop {
20: 18:                 match tokens.next().transpose()? {
21: 19:                     Some(::aws_smithy_json::deserialize::Token::EndObject { .. }) => break,
22: 20:                                             Some(::aws_smithy_json::deserialize::Token::ObjectKey { key, .. }) => {
23: 21:                         match key.to_unescaped()?.as_ref() {
24: 22:                             "type_name" => {
25: 23:                                 builder = builder.set_type_name(
26: 24:                                     ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
27: 25:                                         s.to_unescaped().map(|u|
28: 26:                                             u.into_owned()
29: 27:                                         )
30: 28:                                     ).transpose()?
31: 29:                                 );
32: 30:                             }
33: 31:                             "type_schema" => {
34: 32:                                 builder = builder.set_type_schema(
35: 33:                                     crate::protocol_serde::shape_object::de_object(tokens)?
36: 34:                                 );
37: 35:                             }
38: 36:                             "description" => {
39: 37:                                 builder = builder.set_description(
40: 38:                                     ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
41: 39:                                         s.to_unescaped().map(|u|
42: 40:                                             u.into_owned()
43: 41:                                         )
44: 42:                                     ).transpose()?
45: 43:                                 );
46: 44:                             }
47: 45:                             "change_reason" => {
48: 46:                                 builder = builder.set_change_reason(
49: 47:                                     ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
50: 48:                                         s.to_unescaped().map(|u|
51: 49:                                             u.into_owned()
52: 50:                                         )
53: 51:                                     ).transpose()?
54: 52:                                 );
55: 53:                             }
56: 54:                             "created_by" => {
57: 55:                                 builder = builder.set_created_by(
58: 56:                                     ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
59: 57:                                         s.to_unescaped().map(|u|
60: 58:                                             u.into_owned()
61: 59:                                         )
62: 60:                                     ).transpose()?
63: 61:                                 );
64: 62:                             }
65: 63:                             "created_at" => {
66: 64:                                 builder = builder.set_created_at(
67: 65:                                     ::aws_smithy_json::deserialize::token::expect_timestamp_or_null(tokens.next(), ::aws_smithy_types::date_time::Format::DateTimeWithOffset)?
68: 66:                                 );
69: 67:                             }
70: 68:                             "last_modified_at" => {
71: 69:                                 builder = builder.set_last_modified_at(
72: 70:                                     ::aws_smithy_json::deserialize::token::expect_timestamp_or_null(tokens.next(), ::aws_smithy_types::date_time::Format::DateTimeWithOffset)?
73: 71:                                 );
74: 72:                             }
75: 73:                             "last_modified_by" => {
76: 74:                                 builder = builder.set_last_modified_by(
77: 75:                                     ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
78: 76:                                         s.to_unescaped().map(|u|
79: 77:                                             u.into_owned()
80: 78:                                         )
81: 79:                                     ).transpose()?
82: 80:                                 );
83: 81:                             }
84: 82:                             _ => ::aws_smithy_json::deserialize::token::skip_value(tokens)?
85: 83:                         }
86: 84:                     }
87: 85:                     other => return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(format!("expected object key or end object, found: {:?}", other)))
88: 86:                 }
89: 87:             }
90: 88:             Ok(Some(crate::serde_util::type_templates_response_correct_errors(builder).build().map_err(|err|::aws_smithy_json::deserialize::error::DeserializeError::custom_source("Response was invalid", err))?))
91: 89:         }
92: 90:         _ => {
93: 91:             Err(::aws_smithy_json::deserialize::error::DeserializeError::custom("expected start object or null"))
94: 92:         }
95: 93:     }
96: 94: }
97: 95: 
98: 96: ```
99: 97: ```
100: 98: ```
101: 99: ```
102: ```
```
