### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-config\crates\lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_override.rs
```rust
1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_override.rs
2: ```rust
3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_override.rs
4: 2: ```rust
5: 3: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_override.rs
6: 4: ```rust
7: 5: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_override.rs
8: 6: ```rust
9: 7: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_override.rs
10: 8: ```rust
11: 9: // Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
12: 10: #[allow(clippy::unnecessary_wraps)]
13: 11: pub fn de_update_override_http_error(_response_status: u16, _response_headers: &::aws_smithy_runtime_api::http::Headers, _response_body: &[u8]) -> std::result::Result<crate::operation::update_override::UpdateOverrideOutput, crate::operation::update_override::UpdateOverrideError> {
14: 12:     #[allow(unused_mut)]
15: 13:     let mut generic_builder = crate::protocol_serde::parse_http_error_metadata(_response_status, _response_headers, _response_body).map_err(crate::operation::update_override::UpdateOverrideError::unhandled)?;
16: 14:     let generic = generic_builder.build();
17: 15:     let error_code = match generic.code() {
18: 16:                                 Some(code) => code,
19: 17:                                 None => return Err(crate::operation::update_override::UpdateOverrideError::unhandled(generic))
20: 18:                             };
21: 19:     
22: 20:                             let _error_message = generic.message().map(|msg|msg.to_owned());
23: 21:     Err(match error_code {
24: 22:         "ResourceNotFound" => crate::operation::update_override::UpdateOverrideError::ResourceNotFound({
25: 23:             #[allow(unused_mut)]
26: 24:             let mut tmp =
27: 25:                  {
28: 26:                     #[allow(unused_mut)]
29: 27:                     let mut output = crate::types::error::builders::ResourceNotFoundBuilder::default();
30: 28:                     output = crate::protocol_serde::shape_resource_not_found::de_resource_not_found_json_err(_response_body, output).map_err(crate::operation::update_override::UpdateOverrideError::unhandled)?;
31: 29:                     let output = output.meta(generic);
32: 30:                     output.build()
33: 31:                 }
34: 32:             ;
35: 33:             if tmp.message.is_none() {
36: 34:                                                             tmp.message = _error_message;
37: 35:                                                         }
38: 36:             tmp
39: 37:         }),
40: 38:         "InternalServerError" => crate::operation::update_override::UpdateOverrideError::InternalServerError({
41: 39:             #[allow(unused_mut)]
42: 40:             let mut tmp =
43: 41:                  {
44: 42:                     #[allow(unused_mut)]
45: 43:                     let mut output = crate::types::error::builders::InternalServerErrorBuilder::default();
46: 44:                     output = crate::protocol_serde::shape_internal_lyx-platform-lyx_platform_lyx-platform-lyx_platform_server_error::de_internal_lyx-platform-lyx_platform_lyx-platform-lyx_platform_server_error_json_err(_response_body, output).map_err(crate::operation::update_override::UpdateOverrideError::unhandled)?;
47: 45:                     let output = output.meta(generic);
48: 46:                     output.build()
49: 47:                 }
50: 48:             ;
51: 49:             if tmp.message.is_none() {
52: 50:                                                             tmp.message = _error_message;
53: 51:                                                         }
54: 52:             tmp
55: 53:         }),
56: 54:         _ => crate::operation::update_override::UpdateOverrideError::generic(generic)
57: 55:     })
58: 56: }
59: 57: 
60: 58: #[allow(clippy::unnecessary_wraps)]
61: 59: pub fn de_update_override_http_response(_response_status: u16, _response_headers: &::aws_smithy_runtime_api::http::Headers, _response_body: &[u8]) -> std::result::Result<crate::operation::update_override::UpdateOverrideOutput, crate::operation::update_override::UpdateOverrideError> {
62: 60:     Ok({
63: 61:         #[allow(unused_mut)]
64: 62:         let mut output = crate::operation::update_override::builders::UpdateOverrideOutputBuilder::default();
65: 63:         output = crate::protocol_serde::shape_update_override::de_update_override(_response_body, output).map_err(crate::operation::update_override::UpdateOverrideError::unhandled)?;
66: 64:         crate::serde_util::update_override_output_output_correct_errors(output).build().map_err(crate::operation::update_override::UpdateOverrideError::unhandled)?
67: 65:     })
68: 66: }
69: 67: 
70: 68: pub fn ser_update_override_headers(
71: 69:                     input: &crate::operation::update_override::UpdateOverrideInput,
72: 70:                     mut builder: ::http::request::Builder
73: 71:                 ) -> std::result::Result<::http::request::Builder, ::aws_smithy_types::error::operation::BuildError> {
74: 72:     if let ::std::option::Option::Some(inner_1) = &input.workspace_id {
75: 73:         let formatted_2 = inner_1.as_str();
76: 74:         let header_value = formatted_2;
77: 75:                             let header_value: ::http::HeaderValue = header_value.parse().map_err(|err| {
78: 76:                                 ::aws_smithy_types::error::operation::BuildError::invalid_field("workspace_id", format!(
79: 77:                                 "`{}` cannot be used as a header value: {}",
80: 78:                                 &header_value,
81: 79:                                 err
82: 80:                             ))
83: 81:                             })?;
84: 82:                             builder = builder.header("x-workspace", header_value);
85: 83:     }
86: 84:     if let ::std::option::Option::Some(inner_3) = &input.org_id {
87: 85:         let formatted_4 = inner_3.as_str();
88: 86:         let header_value = formatted_4;
89: 87:                             let header_value: ::http::HeaderValue = header_value.parse().map_err(|err| {
90: 88:                                 ::aws_smithy_types::error::operation::BuildError::invalid_field("org_id", format!(
91: 89:                                 "`{}` cannot be used as a header value: {}",
92: 90:                                 &header_value,
93: 91:                                 err
94: 92:                             ))
95: 93:                             })?;
96: 94:                             builder = builder.header("x-org-id", header_value);
97: 95:     }
98: 96:     if let ::std::option::Option::Some(inner_5) = &input.config_tags {
99: 97:         let formatted_6 = inner_5.as_str();
100: 98:         let header_value = formatted_6;
101: 99:                             let header_value: ::http::HeaderValue = header_value.parse().map_err(|err| {
102: 100:                                 ::aws_smithy_types::error::operation::BuildError::invalid_field("config_tags", format!(
103: 101:                                 "`{}` cannot be used as a header value: {}",
104: 102:                                 &header_value,
105: 103:                                 err
106: 104:                             ))
107: 105:                             })?;
108: 106:                             builder = builder.header("x-config-tags", header_value);
109: 107:     }
110: 108:     Ok(builder)
111: 109: }
112: 110: 
113: 111: pub(crate) fn de_update_override(value: &[u8], mut builder: crate::operation::update_override::builders::UpdateOverrideOutputBuilder) -> ::std::result::Result<crate::operation::update_override::builders::UpdateOverrideOutputBuilder, ::aws_smithy_json::deserialize::error::DeserializeError> {
114: 112:     let mut tokens_owned = ::aws_smithy_json::deserialize::json_token_iter(crate::protocol_serde::or_empty_doc(value)).peekable();
115: 113:                         let tokens = &mut tokens_owned;
116: 114:                         ::aws_smithy_json::deserialize::token::expect_start_object(tokens.next())?;
117: 115:     loop {
118: 116:         match tokens.next().transpose()? {
119: 117:             Some(::aws_smithy_json::deserialize::Token::EndObject { .. }) => break,
120: 118:                                     Some(::aws_smithy_json::deserialize::Token::ObjectKey { key, .. }) => {
121: 119:                 match key.to_unescaped()?.as_ref() {
122: 120:                     "change_reason" => {
123: 121:                         builder = builder.set_change_reason(
124: 122:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
125: 123:                                 s.to_unescaped().map(|u|
126: 124:                                     u.into_owned()
127: 125:                                 )
128: 126:                             ).transpose()?
129: 127:                         );
130: 128:                     }
131: 129:                     "created_at" => {
132: 130:                         builder = builder.set_created_at(
133: 131:                             ::aws_smithy_json::deserialize::token::expect_timestamp_or_null(tokens.next(), ::aws_smithy_types::date_time::Format::DateTimeWithOffset)?
134: 132:                         );
135: 133:                     }
136: 134:                     "created_by" => {
137: 135:                         builder = builder.set_created_by(
138: 136:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
139: 137:                                 s.to_unescaped().map(|u|
140: 138:                                     u.into_owned()
141: 139:                                 )
142: 140:                             ).transpose()?
143: 141:                         );
144: 142:                     }
145: 143:                     "description" => {
146: 144:                         builder = builder.set_description(
147: 145:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
148: 146:                                 s.to_unescaped().map(|u|
149: 147:                                     u.into_owned()
150: 148:                                 )
151: 149:                             ).transpose()?
152: 150:                         );
153: 151:                     }
154: 152:                     "id" => {
155: 153:                         builder = builder.set_id(
156: 154:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
157: 155:                                 s.to_unescaped().map(|u|
158: 156:                                     u.into_owned()
159: 157:                                 )
160: 158:                             ).transpose()?
161: 159:                         );
162: 160:                     }
163: 161:                     "last_modified_at" => {
164: 162:                         builder = builder.set_last_modified_at(
165: 163:                             ::aws_smithy_json::deserialize::token::expect_timestamp_or_null(tokens.next(), ::aws_smithy_types::date_time::Format::DateTimeWithOffset)?
166: 164:                         );
167: 165:                     }
168: 166:                     "last_modified_by" => {
169: 167:                         builder = builder.set_last_modified_by(
170: 168:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
171: 169:                                 s.to_unescaped().map(|u|
172: 170:                                     u.into_owned()
173: 171:                                 )
174: 172:                             ).transpose()?
175: 173:                         );
176: 174:                     }
177: 175:                     "override" => {
178: 176:                         builder = builder.set_override(
179: 177:                             crate::protocol_serde::shape_overrides::de_overrides(tokens)?
180: 178:                         );
181: 179:                     }
182: 180:                     "override_id" => {
183: 181:                         builder = builder.set_override_id(
184: 182:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
185: 183:                                 s.to_unescaped().map(|u|
186: 184:                                     u.into_owned()
187: 185:                                 )
188: 186:                             ).transpose()?
189: 187:                         );
190: 188:                     }
191: 189:                     "value" => {
192: 190:                         builder = builder.set_value(
193: 191:                             crate::protocol_serde::shape_condition::de_condition(tokens)?
194: 192:                         );
195: 193:                     }
196: 194:                     "weight" => {
197: 195:                         builder = builder.set_weight(
198: 196:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
199: 197:                                 s.to_unescaped().map(|u|
200: 198:                                     u.into_owned()
201: 199:                                 )
202: 200:                             ).transpose()?
203: 201:                         );
204: 202:                     }
205: 203:                     _ => ::aws_smithy_json::deserialize::token::skip_value(tokens)?
206: 204:                 }
207: 205:             }
208: 206:             other => return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(format!("expected object key or end object, found: {:?}", other)))
209: 207:         }
210: 208:     }
211: 209:     if tokens.next().is_some() {
212: 210:         return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom("found more JSON tokens after completing parsing"));
213: 211:     }
214: 212:     Ok(builder)
215: 213: }
216: 214: 
217: 215: ```
218: 216: ```
219: 217: ```
220: 218: ```
221: ```
```
