1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_organisation_input.rs
2: ```rust
3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_organisation_input.rs
4: 2: ```rust
5: 3: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_organisation_input.rs
6: 4: ```rust
7: 5: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_organisation_input.rs
8: 6: ```rust
9: 7: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_organisation_input.rs
10: 8: ```rust
11: 9: // Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
12: 10: pub fn ser_update_organisation_input_input(
13: 11:                          object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
14: 12:                          input: &crate::operation::update_organisation::UpdateOrganisationInput,
15: 13:                     ) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
16: 14:     if let Some(var_1) = &input.admin_email {
17: 15:         object.key("admin_email").string(var_1.as_str());
18: 16:     }
19: 17:     if let Some(var_2) = &input.contact_email {
20: 18:         object.key("contact_email").string(var_2.as_str());
21: 19:     }
22: 20:     if let Some(var_3) = &input.contact_phone {
23: 21:         object.key("contact_phone").string(var_3.as_str());
24: 22:     }
25: 23:     if let Some(var_4) = &input.country_code {
26: 24:         object.key("country_code").string(var_4.as_str());
27: 25:     }
28: 26:     if let Some(var_5) = &input.sector {
29: 27:         object.key("sector").string(var_5.as_str());
30: 28:     }
31: 29:     if let Some(var_6) = &input.status {
32: 30:         object.key("status").string(var_6.as_str());
33: 31:     }
34: 32:     Ok(())
35: 33: }
36: 34: 
37: 35: ```
38: 36: ```
39: 37: ```
40: 38: ```
41: ```
```

