### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-config\crates\lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_variable_response.rs
```rust
1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_variable_response.rs
2: ```rust
3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_variable_response.rs
4: 2: ```rust
5: 3: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_variable_response.rs
6: 4: ```rust
7: 5: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_variable_response.rs
8: 6: ```rust
9: 7: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_variable_response.rs
10: 8: ```rust
11: 9: // Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
12: 10: pub(crate) fn de_variable_response<'a, I>(tokens: &mut ::std::iter::Peekable<I>) -> ::std::result::Result<Option<crate::types::VariableResponse>, ::aws_smithy_json::deserialize::error::DeserializeError>
13: 11:                         where I: Iterator<Item = Result<::aws_smithy_json::deserialize::Token<'a>, ::aws_smithy_json::deserialize::error::DeserializeError>> {
14: 12:     match tokens.next().transpose()? {
15: 13:         Some(::aws_smithy_json::deserialize::Token::ValueNull { .. }) => Ok(None),
16: 14:                         Some(::aws_smithy_json::deserialize::Token::StartObject { .. }) => {
17: 15:             #[allow(unused_mut)]
18: 16:             let mut builder = crate::types::builders::VariableResponseBuilder::default();
19: 17:             loop {
20: 18:                 match tokens.next().transpose()? {
21: 19:                     Some(::aws_smithy_json::deserialize::Token::EndObject { .. }) => break,
22: 20:                                             Some(::aws_smithy_json::deserialize::Token::ObjectKey { key, .. }) => {
23: 21:                         match key.to_unescaped()?.as_ref() {
24: 22:                             "name" => {
25: 23:                                 builder = builder.set_name(
26: 24:                                     ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
27: 25:                                         s.to_unescaped().map(|u|
28: 26:                                             u.into_owned()
29: 27:                                         )
30: 28:                                     ).transpose()?
31: 29:                                 );
32: 30:                             }
33: 31:                             "value" => {
34: 32:                                 builder = builder.set_value(
35: 33:                                     ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
36: 34:                                         s.to_unescaped().map(|u|
37: 35:                                             u.into_owned()
38: 36:                                         )
39: 37:                                     ).transpose()?
40: 38:                                 );
41: 39:                             }
42: 40:                             "description" => {
43: 41:                                 builder = builder.set_description(
44: 42:                                     ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
45: 43:                                         s.to_unescaped().map(|u|
46: 44:                                             u.into_owned()
47: 45:                                         )
48: 46:                                     ).transpose()?
49: 47:                                 );
50: 48:                             }
51: 49:                             "change_reason" => {
52: 50:                                 builder = builder.set_change_reason(
53: 51:                                     ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
54: 52:                                         s.to_unescaped().map(|u|
55: 53:                                             u.into_owned()
56: 54:                                         )
57: 55:                                     ).transpose()?
58: 56:                                 );
59: 57:                             }
60: 58:                             "created_by" => {
61: 59:                                 builder = builder.set_created_by(
62: 60:                                     ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
63: 61:                                         s.to_unescaped().map(|u|
64: 62:                                             u.into_owned()
65: 63:                                         )
66: 64:                                     ).transpose()?
67: 65:                                 );
68: 66:                             }
69: 67:                             "created_at" => {
70: 68:                                 builder = builder.set_created_at(
71: 69:                                     ::aws_smithy_json::deserialize::token::expect_timestamp_or_null(tokens.next(), ::aws_smithy_types::date_time::Format::DateTimeWithOffset)?
72: 70:                                 );
73: 71:                             }
74: 72:                             "last_modified_by" => {
75: 73:                                 builder = builder.set_last_modified_by(
76: 74:                                     ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
77: 75:                                         s.to_unescaped().map(|u|
78: 76:                                             u.into_owned()
79: 77:                                         )
80: 78:                                     ).transpose()?
81: 79:                                 );
82: 80:                             }
83: 81:                             "last_modified_at" => {
84: 82:                                 builder = builder.set_last_modified_at(
85: 83:                                     ::aws_smithy_json::deserialize::token::expect_timestamp_or_null(tokens.next(), ::aws_smithy_types::date_time::Format::DateTimeWithOffset)?
86: 84:                                 );
87: 85:                             }
88: 86:                             _ => ::aws_smithy_json::deserialize::token::skip_value(tokens)?
89: 87:                         }
90: 88:                     }
91: 89:                     other => return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(format!("expected object key or end object, found: {:?}", other)))
92: 90:                 }
93: 91:             }
94: 92:             Ok(Some(crate::serde_util::variable_response_correct_errors(builder).build().map_err(|err|::aws_smithy_json::deserialize::error::DeserializeError::custom_source("Response was invalid", err))?))
95: 93:         }
96: 94:         _ => {
97: 95:             Err(::aws_smithy_json::deserialize::error::DeserializeError::custom("expected start object or null"))
98: 96:         }
99: 97:     }
100: 98: }
101: 99: 
102: 100: ```
103: 101: ```
104: 102: ```
105: 103: ```
106: ```
```
