### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-config\crates\lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_validate_context.rs
```rust
1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_validate_context.rs
2: ```rust
3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_validate_context.rs
4: 2: ```rust
5: 3: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_validate_context.rs
6: 4: ```rust
7: 5: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_validate_context.rs
8: 6: ```rust
9: 7: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_validate_context.rs
10: 8: ```rust
11: 9: // Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
12: 10: #[allow(clippy::unnecessary_wraps)]
13: 11: pub fn de_validate_context_http_error(_response_status: u16, _response_headers: &::aws_smithy_runtime_api::http::Headers, _response_body: &[u8]) -> std::result::Result<crate::operation::validate_context::ValidateContextOutput, crate::operation::validate_context::ValidateContextError> {
14: 12:     #[allow(unused_mut)]
15: 13:     let mut generic_builder = crate::protocol_serde::parse_http_error_metadata(_response_status, _response_headers, _response_body).map_err(crate::operation::validate_context::ValidateContextError::unhandled)?;
16: 14:     let generic = generic_builder.build();
17: 15:     let error_code = match generic.code() {
18: 16:                                 Some(code) => code,
19: 17:                                 None => return Err(crate::operation::validate_context::ValidateContextError::unhandled(generic))
20: 18:                             };
21: 19:     
22: 20:                             let _error_message = generic.message().map(|msg|msg.to_owned());
23: 21:     Err(match error_code {
24: 22:         "InternalServerError" => crate::operation::validate_context::ValidateContextError::InternalServerError({
25: 23:             #[allow(unused_mut)]
26: 24:             let mut tmp =
27: 25:                  {
28: 26:                     #[allow(unused_mut)]
29: 27:                     let mut output = crate::types::error::builders::InternalServerErrorBuilder::default();
30: 28:                     output = crate::protocol_serde::shape_internal_lyx-platform-lyx_platform_lyx-platform-lyx_platform_server_error::de_internal_lyx-platform-lyx_platform_lyx-platform-lyx_platform_server_error_json_err(_response_body, output).map_err(crate::operation::validate_context::ValidateContextError::unhandled)?;
31: 29:                     let output = output.meta(generic);
32: 30:                     output.build()
33: 31:                 }
34: 32:             ;
35: 33:             if tmp.message.is_none() {
36: 34:                                                             tmp.message = _error_message;
37: 35:                                                         }
38: 36:             tmp
39: 37:         }),
40: 38:         _ => crate::operation::validate_context::ValidateContextError::generic(generic)
41: 39:     })
42: 40: }
43: 41: 
44: 42: #[allow(clippy::unnecessary_wraps)]
45: 43: pub fn de_validate_context_http_response(_response_status: u16, _response_headers: &::aws_smithy_runtime_api::http::Headers, _response_body: &[u8]) -> std::result::Result<crate::operation::validate_context::ValidateContextOutput, crate::operation::validate_context::ValidateContextError> {
46: 44:     Ok({
47: 45:         #[allow(unused_mut)]
48: 46:         let mut output = crate::operation::validate_context::builders::ValidateContextOutputBuilder::default();
49: 47:         output.build()
50: 48:     })
51: 49: }
52: 50: 
53: 51: pub fn ser_validate_context_headers(
54: 52:                     input: &crate::operation::validate_context::ValidateContextInput,
55: 53:                     mut builder: ::http::request::Builder
56: 54:                 ) -> std::result::Result<::http::request::Builder, ::aws_smithy_types::error::operation::BuildError> {
57: 55:     if let ::std::option::Option::Some(inner_1) = &input.workspace_id {
58: 56:         let formatted_2 = inner_1.as_str();
59: 57:         let header_value = formatted_2;
60: 58:                             let header_value: ::http::HeaderValue = header_value.parse().map_err(|err| {
61: 59:                                 ::aws_smithy_types::error::operation::BuildError::invalid_field("workspace_id", format!(
62: 60:                                 "`{}` cannot be used as a header value: {}",
63: 61:                                 &header_value,
64: 62:                                 err
65: 63:                             ))
66: 64:                             })?;
67: 65:                             builder = builder.header("x-workspace", header_value);
68: 66:     }
69: 67:     if let ::std::option::Option::Some(inner_3) = &input.org_id {
70: 68:         let formatted_4 = inner_3.as_str();
71: 69:         let header_value = formatted_4;
72: 70:                             let header_value: ::http::HeaderValue = header_value.parse().map_err(|err| {
73: 71:                                 ::aws_smithy_types::error::operation::BuildError::invalid_field("org_id", format!(
74: 72:                                 "`{}` cannot be used as a header value: {}",
75: 73:                                 &header_value,
76: 74:                                 err
77: 75:                             ))
78: 76:                             })?;
79: 77:                             builder = builder.header("x-org-id", header_value);
80: 78:     }
81: 79:     Ok(builder)
82: 80: }
83: 81: 
84: 82: pub fn ser_validate_context_input(input: &crate::operation::validate_context::ValidateContextInput) -> ::std::result::Result<::aws_smithy_types::body::SdkBody, ::aws_smithy_types::error::operation::SerializationError> {
85: 83:     let mut out = String::new();
86: 84:     let mut object = ::aws_smithy_json::serialize::JsonObjectWriter::new(&mut out);
87: 85:     crate::protocol_serde::shape_validate_context_input::ser_validate_context_input_input(&mut object, input)?;
88: 86:     object.finish();
89: 87:     Ok(::aws_smithy_types::body::SdkBody::from(out))
90: 88: }
91: 89: 
92: 90: ```
93: 91: ```
94: 92: ```
95: 93: ```
96: ```
```
