1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_dimension.rs
2: ```rust
3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_dimension.rs
4: 2: ```rust
5: 3: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_dimension.rs
6: 4: ```rust
7: 5: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_dimension.rs
8: 6: ```rust
9: 7: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_dimension.rs
10: 8: ```rust
11: 9: // Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
12: 10: #[allow(clippy::unnecessary_wraps)]
13: 11: pub fn de_update_dimension_http_error(_response_status: u16, _response_headers: &::aws_smithy_runtime_api::http::Headers, _response_body: &[u8]) -> std::result::Result<crate::operation::update_dimension::UpdateDimensionOutput, crate::operation::update_dimension::UpdateDimensionError> {
14: 12:     #[allow(unused_mut)]
15: 13:     let mut generic_builder = crate::protocol_serde::parse_http_error_metadata(_response_status, _response_headers, _response_body).map_err(crate::operation::update_dimension::UpdateDimensionError::unhandled)?;
16: 14:     let generic = generic_builder.build();
17: 15:     let error_code = match generic.code() {
18: 16:                                 Some(code) => code,
19: 17:                                 None => return Err(crate::operation::update_dimension::UpdateDimensionError::unhandled(generic))
20: 18:                             };
21: 19:     
22: 20:                             let _error_message = generic.message().map(|msg|msg.to_owned());
23: 21:     Err(match error_code {
24: 22:         "ResourceNotFound" => crate::operation::update_dimension::UpdateDimensionError::ResourceNotFound({
25: 23:             #[allow(unused_mut)]
26: 24:             let mut tmp =
27: 25:                  {
28: 26:                     #[allow(unused_mut)]
29: 27:                     let mut output = crate::types::error::builders::ResourceNotFoundBuilder::default();
30: 28:                     output = crate::protocol_serde::shape_resource_not_found::de_resource_not_found_json_err(_response_body, output).map_err(crate::operation::update_dimension::UpdateDimensionError::unhandled)?;
31: 29:                     let output = output.meta(generic);
32: 30:                     output.build()
33: 31:                 }
34: 32:             ;
35: 33:             if tmp.message.is_none() {
36: 34:                                                             tmp.message = _error_message;
37: 35:                                                         }
38: 36:             tmp
39: 37:         }),
40: 38:         "InternalServerError" => crate::operation::update_dimension::UpdateDimensionError::InternalServerError({
41: 39:             #[allow(unused_mut)]
42: 40:             let mut tmp =
43: 41:                  {
44: 42:                     #[allow(unused_mut)]
45: 43:                     let mut output = crate::types::error::builders::InternalServerErrorBuilder::default();
46: 44:                     output = crate::protocol_serde::shape_internal_lyx-platform-lyx_platform_lyx-platform-lyx_platform_server_error::de_internal_lyx-platform-lyx_platform_lyx-platform-lyx_platform_server_error_json_err(_response_body, output).map_err(crate::operation::update_dimension::UpdateDimensionError::unhandled)?;
47: 45:                     let output = output.meta(generic);
48: 46:                     output.build()
49: 47:                 }
50: 48:             ;
51: 49:             if tmp.message.is_none() {
52: 50:                                                             tmp.message = _error_message;
53: 51:                                                         }
54: 52:             tmp
55: 53:         }),
56: 54:         _ => crate::operation::update_dimension::UpdateDimensionError::generic(generic)
57: 55:     })
58: 56: }
59: 57: 
60: 58: #[allow(clippy::unnecessary_wraps)]
61: 59: pub fn de_update_dimension_http_response(_response_status: u16, _response_headers: &::aws_smithy_runtime_api::http::Headers, _response_body: &[u8]) -> std::result::Result<crate::operation::update_dimension::UpdateDimensionOutput, crate::operation::update_dimension::UpdateDimensionError> {
62: 60:     Ok({
63: 61:         #[allow(unused_mut)]
64: 62:         let mut output = crate::operation::update_dimension::builders::UpdateDimensionOutputBuilder::default();
65: 63:         output = crate::protocol_serde::shape_update_dimension::de_update_dimension(_response_body, output).map_err(crate::operation::update_dimension::UpdateDimensionError::unhandled)?;
66: 64:         crate::serde_util::update_dimension_output_output_correct_errors(output).build().map_err(crate::operation::update_dimension::UpdateDimensionError::unhandled)?
67: 65:     })
68: 66: }
69: 67: 
70: 68: pub fn ser_update_dimension_headers(
71: 69:                     input: &crate::operation::update_dimension::UpdateDimensionInput,
72: 70:                     mut builder: ::http::request::Builder
73: 71:                 ) -> std::result::Result<::http::request::Builder, ::aws_smithy_types::error::operation::BuildError> {
74: 72:     if let ::std::option::Option::Some(inner_1) = &input.workspace_id {
75: 73:         let formatted_2 = inner_1.as_str();
76: 74:         let header_value = formatted_2;
77: 75:                             let header_value: ::http::HeaderValue = header_value.parse().map_err(|err| {
78: 76:                                 ::aws_smithy_types::error::operation::BuildError::invalid_field("workspace_id", format!(
79: 77:                                 "`{}` cannot be used as a header value: {}",
80: 78:                                 &header_value,
81: 79:                                 err
82: 80:                             ))
83: 81:                             })?;
84: 82:                             builder = builder.header("x-workspace", header_value);
85: 83:     }
86: 84:     if let ::std::option::Option::Some(inner_3) = &input.org_id {
87: 85:         let formatted_4 = inner_3.as_str();
88: 86:         let header_value = formatted_4;
89: 87:                             let header_value: ::http::HeaderValue = header_value.parse().map_err(|err| {
90: 88:                                 ::aws_smithy_types::error::operation::BuildError::invalid_field("org_id", format!(
91: 89:                                 "`{}` cannot be used as a header value: {}",
92: 90:                                 &header_value,
93: 91:                                 err
94: 92:                             ))
95: 93:                             })?;
96: 94:                             builder = builder.header("x-org-id", header_value);
97: 95:     }
98: 96:     Ok(builder)
99: 97: }
100: 98: 
101: 99: pub fn ser_update_dimension_input(input: &crate::operation::update_dimension::UpdateDimensionInput) -> ::std::result::Result<::aws_smithy_types::body::SdkBody, ::aws_smithy_types::error::operation::SerializationError> {
102: 100:     let mut out = String::new();
103: 101:     let mut object = ::aws_smithy_json::serialize::JsonObjectWriter::new(&mut out);
104: 102:     crate::protocol_serde::shape_update_dimension_input::ser_update_dimension_input_input(&mut object, input)?;
105: 103:     object.finish();
106: 104:     Ok(::aws_smithy_types::body::SdkBody::from(out))
107: 105: }
108: 106: 
109: 107: pub(crate) fn de_update_dimension(value: &[u8], mut builder: crate::operation::update_dimension::builders::UpdateDimensionOutputBuilder) -> ::std::result::Result<crate::operation::update_dimension::builders::UpdateDimensionOutputBuilder, ::aws_smithy_json::deserialize::error::DeserializeError> {
110: 108:     let mut tokens_owned = ::aws_smithy_json::deserialize::json_token_iter(crate::protocol_serde::or_empty_doc(value)).peekable();
111: 109:                         let tokens = &mut tokens_owned;
112: 110:                         ::aws_smithy_json::deserialize::token::expect_start_object(tokens.next())?;
113: 111:     loop {
114: 112:         match tokens.next().transpose()? {
115: 113:             Some(::aws_smithy_json::deserialize::Token::EndObject { .. }) => break,
116: 114:                                     Some(::aws_smithy_json::deserialize::Token::ObjectKey { key, .. }) => {
117: 115:                 match key.to_unescaped()?.as_ref() {
118: 116:                     "change_reason" => {
119: 117:                         builder = builder.set_change_reason(
120: 118:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
121: 119:                                 s.to_unescaped().map(|u|
122: 120:                                     u.into_owned()
123: 121:                                 )
124: 122:                             ).transpose()?
125: 123:                         );
126: 124:                     }
127: 125:                     "created_at" => {
128: 126:                         builder = builder.set_created_at(
129: 127:                             ::aws_smithy_json::deserialize::token::expect_timestamp_or_null(tokens.next(), ::aws_smithy_types::date_time::Format::DateTimeWithOffset)?
130: 128:                         );
131: 129:                     }
132: 130:                     "created_by" => {
133: 131:                         builder = builder.set_created_by(
134: 132:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
135: 133:                                 s.to_unescaped().map(|u|
136: 134:                                     u.into_owned()
137: 135:                                 )
138: 136:                             ).transpose()?
139: 137:                         );
140: 138:                     }
141: 139:                     "dependency_graph" => {
142: 140:                         builder = builder.set_dependency_graph(
143: 141:                             crate::protocol_serde::shape_dependency_graph::de_dependency_graph(tokens)?
144: 142:                         );
145: 143:                     }
146: 144:                     "description" => {
147: 145:                         builder = builder.set_description(
148: 146:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
149: 147:                                 s.to_unescaped().map(|u|
150: 148:                                     u.into_owned()
151: 149:                                 )
152: 150:                             ).transpose()?
153: 151:                         );
154: 152:                     }
155: 153:                     "dimension" => {
156: 154:                         builder = builder.set_dimension(
157: 155:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
158: 156:                                 s.to_unescaped().map(|u|
159: 157:                                     u.into_owned()
160: 158:                                 )
161: 159:                             ).transpose()?
162: 160:                         );
163: 161:                     }
164: 162:                     "dimension_type" => {
165: 163:                         builder = builder.set_dimension_type(
166: 164:                             crate::protocol_serde::shape_dimension_type::de_dimension_type(tokens)?
167: 165:                         );
168: 166:                     }
169: 167:                     "last_modified_at" => {
170: 168:                         builder = builder.set_last_modified_at(
171: 169:                             ::aws_smithy_json::deserialize::token::expect_timestamp_or_null(tokens.next(), ::aws_smithy_types::date_time::Format::DateTimeWithOffset)?
172: 170:                         );
173: 171:                     }
174: 172:                     "last_modified_by" => {
175: 173:                         builder = builder.set_last_modified_by(
176: 174:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
177: 175:                                 s.to_unescaped().map(|u|
178: 176:                                     u.into_owned()
179: 177:                                 )
180: 178:                             ).transpose()?
181: 179:                         );
182: 180:                     }
183: 181:                     "mandatory" => {
184: 182:                         builder = builder.set_mandatory(
185: 183:                             ::aws_smithy_json::deserialize::token::expect_bool_or_null(tokens.next())?
186: 184:                         );
187: 185:                     }
188: 186:                     "position" => {
189: 187:                         builder = builder.set_position(
190: 188:                             ::aws_smithy_json::deserialize::token::expect_number_or_null(tokens.next())?
191: 189:                                                 .map(i32::try_from)
192: 190:                                                 .transpose()?
193: 191:                         );
194: 192:                     }
195: 193:                     "schema" => {
196: 194:                         builder = builder.set_schema(
197: 195:                             crate::protocol_serde::shape_object::de_object(tokens)?
198: 196:                         );
199: 197:                     }
200: 198:                     "value_compute_function_name" => {
201: 199:                         builder = builder.set_value_compute_function_name(
202: 200:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
203: 201:                                 s.to_unescaped().map(|u|
204: 202:                                     u.into_owned()
205: 203:                                 )
206: 204:                             ).transpose()?
207: 205:                         );
208: 206:                     }
209: 207:                     "value_validation_function_name" => {
210: 208:                         builder = builder.set_value_validation_function_name(
211: 209:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
212: 210:                                 s.to_unescaped().map(|u|
213: 211:                                     u.into_owned()
214: 212:                                 )
215: 213:                             ).transpose()?
216: 214:                         );
217: 215:                     }
218: 216:                     _ => ::aws_smithy_json::deserialize::token::skip_value(tokens)?
219: 217:                 }
220: 218:             }
221: 219:             other => return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(format!("expected object key or end object, found: {:?}", other)))
222: 220:         }
223: 221:     }
224: 222:     if tokens.next().is_some() {
225: 223:         return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom("found more JSON tokens after completing parsing"));
226: 224:     }
227: 225:     Ok(builder)
228: 226: }
229: 227: 
230: 228: ```
231: 229: ```
232: 230: ```
233: 231: ```
234: ```
```

