### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-config\crates\lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_workspace.rs
```rust
1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_workspace.rs
2: ```rust
3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_workspace.rs
4: 2: ```rust
5: 3: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_workspace.rs
6: 4: ```rust
7: 5: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_workspace.rs
8: 6: ```rust
9: 7: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_workspace.rs
10: 8: ```rust
11: 9: // Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
12: 10: #[allow(clippy::unnecessary_wraps)]
13: 11: pub fn de_update_workspace_http_error(_response_status: u16, _response_headers: &::aws_smithy_runtime_api::http::Headers, _response_body: &[u8]) -> std::result::Result<crate::operation::update_workspace::UpdateWorkspaceOutput, crate::operation::update_workspace::UpdateWorkspaceError> {
14: 12:     #[allow(unused_mut)]
15: 13:     let mut generic_builder = crate::protocol_serde::parse_http_error_metadata(_response_status, _response_headers, _response_body).map_err(crate::operation::update_workspace::UpdateWorkspaceError::unhandled)?;
16: 14:     let generic = generic_builder.build();
17: 15:     let error_code = match generic.code() {
18: 16:                                 Some(code) => code,
19: 17:                                 None => return Err(crate::operation::update_workspace::UpdateWorkspaceError::unhandled(generic))
20: 18:                             };
21: 19:     
22: 20:                             let _error_message = generic.message().map(|msg|msg.to_owned());
23: 21:     Err(match error_code {
24: 22:         "ResourceNotFound" => crate::operation::update_workspace::UpdateWorkspaceError::ResourceNotFound({
25: 23:             #[allow(unused_mut)]
26: 24:             let mut tmp =
27: 25:                  {
28: 26:                     #[allow(unused_mut)]
29: 27:                     let mut output = crate::types::error::builders::ResourceNotFoundBuilder::default();
30: 28:                     output = crate::protocol_serde::shape_resource_not_found::de_resource_not_found_json_err(_response_body, output).map_err(crate::operation::update_workspace::UpdateWorkspaceError::unhandled)?;
31: 29:                     let output = output.meta(generic);
32: 30:                     output.build()
33: 31:                 }
34: 32:             ;
35: 33:             if tmp.message.is_none() {
36: 34:                                                             tmp.message = _error_message;
37: 35:                                                         }
38: 36:             tmp
39: 37:         }),
40: 38:         "InternalServerError" => crate::operation::update_workspace::UpdateWorkspaceError::InternalServerError({
41: 39:             #[allow(unused_mut)]
42: 40:             let mut tmp =
43: 41:                  {
44: 42:                     #[allow(unused_mut)]
45: 43:                     let mut output = crate::types::error::builders::InternalServerErrorBuilder::default();
46: 44:                     output = crate::protocol_serde::shape_internal_lyx-platform-lyx_platform_lyx-platform-lyx_platform_server_error::de_internal_lyx-platform-lyx_platform_lyx-platform-lyx_platform_server_error_json_err(_response_body, output).map_err(crate::operation::update_workspace::UpdateWorkspaceError::unhandled)?;
47: 45:                     let output = output.meta(generic);
48: 46:                     output.build()
49: 47:                 }
50: 48:             ;
51: 49:             if tmp.message.is_none() {
52: 50:                                                             tmp.message = _error_message;
53: 51:                                                         }
54: 52:             tmp
55: 53:         }),
56: 54:         _ => crate::operation::update_workspace::UpdateWorkspaceError::generic(generic)
57: 55:     })
58: 56: }
59: 57: 
60: 58: #[allow(clippy::unnecessary_wraps)]
61: 59: pub fn de_update_workspace_http_response(_response_status: u16, _response_headers: &::aws_smithy_runtime_api::http::Headers, _response_body: &[u8]) -> std::result::Result<crate::operation::update_workspace::UpdateWorkspaceOutput, crate::operation::update_workspace::UpdateWorkspaceError> {
62: 60:     Ok({
63: 61:         #[allow(unused_mut)]
64: 62:         let mut output = crate::operation::update_workspace::builders::UpdateWorkspaceOutputBuilder::default();
65: 63:         output = crate::protocol_serde::shape_update_workspace::de_update_workspace(_response_body, output).map_err(crate::operation::update_workspace::UpdateWorkspaceError::unhandled)?;
66: 64:         crate::serde_util::update_workspace_output_output_correct_errors(output).build().map_err(crate::operation::update_workspace::UpdateWorkspaceError::unhandled)?
67: 65:     })
68: 66: }
69: 67: 
70: 68: pub fn ser_update_workspace_headers(
71: 69:                     input: &crate::operation::update_workspace::UpdateWorkspaceInput,
72: 70:                     mut builder: ::http::request::Builder
73: 71:                 ) -> std::result::Result<::http::request::Builder, ::aws_smithy_types::error::operation::BuildError> {
74: 72:     if let ::std::option::Option::Some(inner_1) = &input.org_id {
75: 73:         let formatted_2 = inner_1.as_str();
76: 74:         let header_value = formatted_2;
77: 75:                             let header_value: ::http::HeaderValue = header_value.parse().map_err(|err| {
78: 76:                                 ::aws_smithy_types::error::operation::BuildError::invalid_field("org_id", format!(
79: 77:                                 "`{}` cannot be used as a header value: {}",
80: 78:                                 &header_value,
81: 79:                                 err
82: 80:                             ))
83: 81:                             })?;
84: 82:                             builder = builder.header("x-org-id", header_value);
85: 83:     }
86: 84:     Ok(builder)
87: 85: }
88: 86: 
89: 87: pub fn ser_update_workspace_input(input: &crate::operation::update_workspace::UpdateWorkspaceInput) -> ::std::result::Result<::aws_smithy_types::body::SdkBody, ::aws_smithy_types::error::operation::SerializationError> {
90: 88:     let mut out = String::new();
91: 89:     let mut object = ::aws_smithy_json::serialize::JsonObjectWriter::new(&mut out);
92: 90:     crate::protocol_serde::shape_update_workspace_input::ser_update_workspace_input_input(&mut object, input)?;
93: 91:     object.finish();
94: 92:     Ok(::aws_smithy_types::body::SdkBody::from(out))
95: 93: }
96: 94: 
97: 95: pub(crate) fn de_update_workspace(value: &[u8], mut builder: crate::operation::update_workspace::builders::UpdateWorkspaceOutputBuilder) -> ::std::result::Result<crate::operation::update_workspace::builders::UpdateWorkspaceOutputBuilder, ::aws_smithy_json::deserialize::error::DeserializeError> {
98: 96:     let mut tokens_owned = ::aws_smithy_json::deserialize::json_token_iter(crate::protocol_serde::or_empty_doc(value)).peekable();
99: 97:                         let tokens = &mut tokens_owned;
100: 98:                         ::aws_smithy_json::deserialize::token::expect_start_object(tokens.next())?;
101: 99:     loop {
102: 100:         match tokens.next().transpose()? {
103: 101:             Some(::aws_smithy_json::deserialize::Token::EndObject { .. }) => break,
104: 102:                                     Some(::aws_smithy_json::deserialize::Token::ObjectKey { key, .. }) => {
105: 103:                 match key.to_unescaped()?.as_ref() {
106: 104:                     "allow_experiment_self_lyx-platform-lyx_platform_lyx-platform-lyx_platform_approval" => {
107: 105:                         builder = builder.set_allow_experiment_self_lyx-platform-lyx_platform_lyx-platform-lyx_platform_approval(
108: 106:                             ::aws_smithy_json::deserialize::token::expect_bool_or_null(tokens.next())?
109: 107:                         );
110: 108:                     }
111: 109:                     "auto_populate_control" => {
112: 110:                         builder = builder.set_auto_populate_control(
113: 111:                             ::aws_smithy_json::deserialize::token::expect_bool_or_null(tokens.next())?
114: 112:                         );
115: 113:                     }
116: 114:                     "config_version" => {
117: 115:                         builder = builder.set_config_version(
118: 116:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
119: 117:                                 s.to_unescaped().map(|u|
120: 118:                                     u.into_owned()
121: 119:                                 )
122: 120:                             ).transpose()?
123: 121:                         );
124: 122:                     }
125: 123:                     "created_at" => {
126: 124:                         builder = builder.set_created_at(
127: 125:                             ::aws_smithy_json::deserialize::token::expect_timestamp_or_null(tokens.next(), ::aws_smithy_types::date_time::Format::DateTimeWithOffset)?
128: 126:                         );
129: 127:                     }
130: 128:                     "created_by" => {
131: 129:                         builder = builder.set_created_by(
132: 130:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
133: 131:                                 s.to_unescaped().map(|u|
134: 132:                                     u.into_owned()
135: 133:                                 )
136: 134:                             ).transpose()?
137: 135:                         );
138: 136:                     }
139: 137:                     "enable_change_reason_validation" => {
140: 138:                         builder = builder.set_enable_change_reason_validation(
141: 139:                             ::aws_smithy_json::deserialize::token::expect_bool_or_null(tokens.next())?
142: 140:                         );
143: 141:                     }
144: 142:                     "enable_context_validation" => {
145: 143:                         builder = builder.set_enable_context_validation(
146: 144:                             ::aws_smithy_json::deserialize::token::expect_bool_or_null(tokens.next())?
147: 145:                         );
148: 146:                     }
149: 147:                     "last_modified_at" => {
150: 148:                         builder = builder.set_last_modified_at(
151: 149:                             ::aws_smithy_json::deserialize::token::expect_timestamp_or_null(tokens.next(), ::aws_smithy_types::date_time::Format::DateTimeWithOffset)?
152: 150:                         );
153: 151:                     }
154: 152:                     "last_modified_by" => {
155: 153:                         builder = builder.set_last_modified_by(
156: 154:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
157: 155:                                 s.to_unescaped().map(|u|
158: 156:                                     u.into_owned()
159: 157:                                 )
160: 158:                             ).transpose()?
161: 159:                         );
162: 160:                     }
163: 161:                     "mandatory_dimensions" => {
164: 162:                         builder = builder.set_mandatory_dimensions(
165: 163:                             crate::protocol_serde::shape_list_mandatory_dimensions::de_list_mandatory_dimensions(tokens)?
166: 164:                         );
167: 165:                     }
168: 166:                     "metrics" => {
169: 167:                         builder = builder.set_metrics(
170: 168:                             Some(::aws_smithy_json::deserialize::token::expect_document(tokens)?)
171: 169:                         );
172: 170:                     }
173: 171:                     "organisation_id" => {
174: 172:                         builder = builder.set_organisation_id(
175: 173:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
176: 174:                                 s.to_unescaped().map(|u|
177: 175:                                     u.into_owned()
178: 176:                                 )
179: 177:                             ).transpose()?
180: 178:                         );
181: 179:                     }
182: 180:                     "organisation_name" => {
183: 181:                         builder = builder.set_organisation_name(
184: 182:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
185: 183:                                 s.to_unescaped().map(|u|
186: 184:                                     u.into_owned()
187: 185:                                 )
188: 186:                             ).transpose()?
189: 187:                         );
190: 188:                     }
191: 189:                     "workspace_admin_email" => {
192: 190:                         builder = builder.set_workspace_admin_email(
193: 191:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
194: 192:                                 s.to_unescaped().map(|u|
195: 193:                                     u.into_owned()
196: 194:                                 )
197: 195:                             ).transpose()?
198: 196:                         );
199: 197:                     }
200: 198:                     "workspace_name" => {
201: 199:                         builder = builder.set_workspace_name(
202: 200:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
203: 201:                                 s.to_unescaped().map(|u|
204: 202:                                     u.into_owned()
205: 203:                                 )
206: 204:                             ).transpose()?
207: 205:                         );
208: 206:                     }
209: 207:                     "workspace_schema_name" => {
210: 208:                         builder = builder.set_workspace_schema_name(
211: 209:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
212: 210:                                 s.to_unescaped().map(|u|
213: 211:                                     u.into_owned()
214: 212:                                 )
215: 213:                             ).transpose()?
216: 214:                         );
217: 215:                     }
218: 216:                     "workspace_status" => {
219: 217:                         builder = builder.set_workspace_status(
220: 218:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
221: 219:                                 s.to_unescaped().map(|u|
222: 220:                                     crate::types::WorkspaceStatus::from(u.as_ref())
223: 221:                                 )
224: 222:                             ).transpose()?
225: 223:                         );
226: 224:                     }
227: 225:                     _ => ::aws_smithy_json::deserialize::token::skip_value(tokens)?
228: 226:                 }
229: 227:             }
230: 228:             other => return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(format!("expected object key or end object, found: {:?}", other)))
231: 229:         }
232: 230:     }
233: 231:     if tokens.next().is_some() {
234: 232:         return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom("found more JSON tokens after completing parsing"));
235: 233:     }
236: 234:     Ok(builder)
237: 235: }
238: 236: 
239: 237: ```
240: 238: ```
241: 239: ```
242: 240: ```
243: ```
```
