### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-config\crates\lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_dimension_input.rs
```rust
1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_dimension_input.rs
2: ```rust
3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_dimension_input.rs
4: 2: ```rust
5: 3: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_dimension_input.rs
6: 4: ```rust
7: 5: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_dimension_input.rs
8: 6: ```rust
9: 7: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_dimension_input.rs
10: 8: ```rust
11: 9: // Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
12: 10: pub fn ser_update_dimension_input_input(
13: 11:                          object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
14: 12:                          input: &crate::operation::update_dimension::UpdateDimensionInput,
15: 13:                     ) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
16: 14:     if let Some(var_1) = &input.change_reason {
17: 15:         object.key("change_reason").string(var_1.as_str());
18: 16:     }
19: 17:     if let Some(var_2) = &input.description {
20: 18:         object.key("description").string(var_2.as_str());
21: 19:     }
22: 20:     if let Some(var_3) = &input.position {
23: 21:         object.key("position").number(#[allow(clippy::useless_conversion)]::aws_smithy_types::Number::NegInt((*var_3).into()));
24: 22:     }
25: 23:     if let Some(var_4) = &input.schema {
26: 24:         #[allow(unused_mut)]
27: 25:         let mut object_5 = object.key("schema").start_object();
28: 26:         for (key_6, value_7) in var_4 {
29: 27:              {
30: 28:                 object_5.key(key_6.as_str()).document(value_7);
31: 29:             }
32: 30:         }
33: 31:         object_5.finish();
34: 32:     }
35: 33:     if let Some(var_8) = &input.value_compute_function_name {
36: 34:         object.key("value_compute_function_name").string(var_8.as_str());
37: 35:     }
38: 36:     if let Some(var_9) = &input.value_validation_function_name {
39: 37:         object.key("value_validation_function_name").string(var_9.as_str());
40: 38:     }
41: 39:     Ok(())
42: 40: }
43: 41: 
44: 42: ```
45: 43: ```
46: 44: ```
47: 45: ```
48: ```
```
