1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_variable_list.rs
2: ```rust
3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_variable_list.rs
4: 2: ```rust
5: 3: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_variable_list.rs
6: 4: ```rust
7: 5: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_variable_list.rs
8: 6: ```rust
9: 7: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_variable_list.rs
10: 8: ```rust
11: 9: // Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
12: 10: pub(crate) fn de_variable_list<'a, I>(tokens: &mut ::std::iter::Peekable<I>) -> ::std::result::Result<Option<::std::vec::Vec::<crate::types::VariableResponse>>, ::aws_smithy_json::deserialize::error::DeserializeError>
13: 11:                         where I: Iterator<Item = Result<::aws_smithy_json::deserialize::Token<'a>, ::aws_smithy_json::deserialize::error::DeserializeError>> {
14: 12:     match tokens.next().transpose()? {
15: 13:         Some(::aws_smithy_json::deserialize::Token::ValueNull { .. }) => Ok(None),
16: 14:                         Some(::aws_smithy_json::deserialize::Token::StartArray { .. }) => {
17: 15:             let mut items = Vec::new();
18: 16:             loop {
19: 17:                 match tokens.peek() {
20: 18:                     Some(Ok(::aws_smithy_json::deserialize::Token::EndArray { .. })) => {
21: 19:                         tokens.next().transpose().unwrap(); break;
22: 20:                     }
23: 21:                     _ =>  {
24: 22:                         let value =
25: 23:                             crate::protocol_serde::shape_variable_response::de_variable_response(tokens)?
26: 24:                         ;
27: 25:                         if let Some(value) = value {
28: 26:                                                                         items.push(value);
29: 27:                                                                     }
30: 28:                     }
31: 29:                 }
32: 30:             }
33: 31:             Ok(Some(items))
34: 32:         }
35: 33:         _ => {
36: 34:             Err(::aws_smithy_json::deserialize::error::DeserializeError::custom("expected start array or null"))
37: 35:         }
38: 36:     }
39: 37: }
40: 38: 
41: 39: ```
42: 40: ```
43: 41: ```
44: 42: ```
45: ```
```

