1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_variant.rs
2: ```rust
3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_variant.rs
4: 2: ```rust
5: 3: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_variant.rs
6: 4: ```rust
7: 5: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_variant.rs
8: 6: ```rust
9: 7: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_variant.rs
10: 8: ```rust
11: 9: // Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
12: 10: pub fn ser_variant(
13: 11:                          object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
14: 12:                          input: &crate::types::Variant,
15: 13:                     ) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
16: 14:      {
17: 15:         object.key("id").string(input.id.as_str());
18: 16:     }
19: 17:      {
20: 18:         object.key("variant_type").string(input.variant_type.as_str());
21: 19:     }
22: 20:     if let Some(var_1) = &input.context_id {
23: 21:         object.key("context_id").string(var_1.as_str());
24: 22:     }
25: 23:     if let Some(var_2) = &input.override_id {
26: 24:         object.key("override_id").string(var_2.as_str());
27: 25:     }
28: 26:      {
29: 27:         #[allow(unused_mut)]
30: 28:         let mut object_3 = object.key("overrides").start_object();
31: 29:         for (key_4, value_5) in &input.overrides {
32: 30:              {
33: 31:                 object_3.key(key_4.as_str()).document(value_5);
34: 32:             }
35: 33:         }
36: 34:         object_3.finish();
37: 35:     }
38: 36:     Ok(())
39: 37: }
40: 38: 
41: 39: pub(crate) fn de_variant<'a, I>(tokens: &mut ::std::iter::Peekable<I>) -> ::std::result::Result<Option<crate::types::Variant>, ::aws_smithy_json::deserialize::error::DeserializeError>
42: 40:                         where I: Iterator<Item = Result<::aws_smithy_json::deserialize::Token<'a>, ::aws_smithy_json::deserialize::error::DeserializeError>> {
43: 41:     match tokens.next().transpose()? {
44: 42:         Some(::aws_smithy_json::deserialize::Token::ValueNull { .. }) => Ok(None),
45: 43:                         Some(::aws_smithy_json::deserialize::Token::StartObject { .. }) => {
46: 44:             #[allow(unused_mut)]
47: 45:             let mut builder = crate::types::builders::VariantBuilder::default();
48: 46:             loop {
49: 47:                 match tokens.next().transpose()? {
50: 48:                     Some(::aws_smithy_json::deserialize::Token::EndObject { .. }) => break,
51: 49:                                             Some(::aws_smithy_json::deserialize::Token::ObjectKey { key, .. }) => {
52: 50:                         match key.to_unescaped()?.as_ref() {
53: 51:                             "id" => {
54: 52:                                 builder = builder.set_id(
55: 53:                                     ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
56: 54:                                         s.to_unescaped().map(|u|
57: 55:                                             u.into_owned()
58: 56:                                         )
59: 57:                                     ).transpose()?
60: 58:                                 );
61: 59:                             }
62: 60:                             "variant_type" => {
63: 61:                                 builder = builder.set_variant_type(
64: 62:                                     ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
65: 63:                                         s.to_unescaped().map(|u|
66: 64:                                             crate::types::VariantType::from(u.as_ref())
67: 65:                                         )
68: 66:                                     ).transpose()?
69: 67:                                 );
70: 68:                             }
71: 69:                             "context_id" => {
72: 70:                                 builder = builder.set_context_id(
73: 71:                                     ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
74: 72:                                         s.to_unescaped().map(|u|
75: 73:                                             u.into_owned()
76: 74:                                         )
77: 75:                                     ).transpose()?
78: 76:                                 );
79: 77:                             }
80: 78:                             "override_id" => {
81: 79:                                 builder = builder.set_override_id(
82: 80:                                     ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
83: 81:                                         s.to_unescaped().map(|u|
84: 82:                                             u.into_owned()
85: 83:                                         )
86: 84:                                     ).transpose()?
87: 85:                                 );
88: 86:                             }
89: 87:                             "overrides" => {
90: 88:                                 builder = builder.set_overrides(
91: 89:                                     crate::protocol_serde::shape_overrides::de_overrides(tokens)?
92: 90:                                 );
93: 91:                             }
94: 92:                             _ => ::aws_smithy_json::deserialize::token::skip_value(tokens)?
95: 93:                         }
96: 94:                     }
97: 95:                     other => return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(format!("expected object key or end object, found: {:?}", other)))
98: 96:                 }
99: 97:             }
100: 98:             Ok(Some(crate::serde_util::variant_correct_errors(builder).build().map_err(|err|::aws_smithy_json::deserialize::error::DeserializeError::custom_source("Response was invalid", err))?))
101: 99:         }
102: 100:         _ => {
103: 101:             Err(::aws_smithy_json::deserialize::error::DeserializeError::custom("expected start object or null"))
104: 102:         }
105: 103:     }
106: 104: }
107: 105: 
108: 106: ```
109: 107: ```
110: 108: ```
111: 109: ```
112: ```
```

