1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_organisation.rs
2: ```rust
3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_organisation.rs
4: 2: ```rust
5: 3: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_organisation.rs
6: 4: ```rust
7: 5: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_organisation.rs
8: 6: ```rust
9: 7: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_organisation.rs
10: 8: ```rust
11: 9: // Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
12: 10: #[allow(clippy::unnecessary_wraps)]
13: 11: pub fn de_update_organisation_http_error(_response_status: u16, _response_headers: &::aws_smithy_runtime_api::http::Headers, _response_body: &[u8]) -> std::result::Result<crate::operation::update_organisation::UpdateOrganisationOutput, crate::operation::update_organisation::UpdateOrganisationError> {
14: 12:     #[allow(unused_mut)]
15: 13:     let mut generic_builder = crate::protocol_serde::parse_http_error_metadata(_response_status, _response_headers, _response_body).map_err(crate::operation::update_organisation::UpdateOrganisationError::unhandled)?;
16: 14:     let generic = generic_builder.build();
17: 15:     let error_code = match generic.code() {
18: 16:                                 Some(code) => code,
19: 17:                                 None => return Err(crate::operation::update_organisation::UpdateOrganisationError::unhandled(generic))
20: 18:                             };
21: 19:     
22: 20:                             let _error_message = generic.message().map(|msg|msg.to_owned());
23: 21:     Err(match error_code {
24: 22:         "ResourceNotFound" => crate::operation::update_organisation::UpdateOrganisationError::ResourceNotFound({
25: 23:             #[allow(unused_mut)]
26: 24:             let mut tmp =
27: 25:                  {
28: 26:                     #[allow(unused_mut)]
29: 27:                     let mut output = crate::types::error::builders::ResourceNotFoundBuilder::default();
30: 28:                     output = crate::protocol_serde::shape_resource_not_found::de_resource_not_found_json_err(_response_body, output).map_err(crate::operation::update_organisation::UpdateOrganisationError::unhandled)?;
31: 29:                     let output = output.meta(generic);
32: 30:                     output.build()
33: 31:                 }
34: 32:             ;
35: 33:             if tmp.message.is_none() {
36: 34:                                                             tmp.message = _error_message;
37: 35:                                                         }
38: 36:             tmp
39: 37:         }),
40: 38:         "InternalServerError" => crate::operation::update_organisation::UpdateOrganisationError::InternalServerError({
41: 39:             #[allow(unused_mut)]
42: 40:             let mut tmp =
43: 41:                  {
44: 42:                     #[allow(unused_mut)]
45: 43:                     let mut output = crate::types::error::builders::InternalServerErrorBuilder::default();
46: 44:                     output = crate::protocol_serde::shape_internal_lyx-platform-lyx_platform_lyx-platform-lyx_platform_server_error::de_internal_lyx-platform-lyx_platform_lyx-platform-lyx_platform_server_error_json_err(_response_body, output).map_err(crate::operation::update_organisation::UpdateOrganisationError::unhandled)?;
47: 45:                     let output = output.meta(generic);
48: 46:                     output.build()
49: 47:                 }
50: 48:             ;
51: 49:             if tmp.message.is_none() {
52: 50:                                                             tmp.message = _error_message;
53: 51:                                                         }
54: 52:             tmp
55: 53:         }),
56: 54:         _ => crate::operation::update_organisation::UpdateOrganisationError::generic(generic)
57: 55:     })
58: 56: }
59: 57: 
60: 58: #[allow(clippy::unnecessary_wraps)]
61: 59: pub fn de_update_organisation_http_response(_response_status: u16, _response_headers: &::aws_smithy_runtime_api::http::Headers, _response_body: &[u8]) -> std::result::Result<crate::operation::update_organisation::UpdateOrganisationOutput, crate::operation::update_organisation::UpdateOrganisationError> {
62: 60:     Ok({
63: 61:         #[allow(unused_mut)]
64: 62:         let mut output = crate::operation::update_organisation::builders::UpdateOrganisationOutputBuilder::default();
65: 63:         output = crate::protocol_serde::shape_update_organisation::de_update_organisation(_response_body, output).map_err(crate::operation::update_organisation::UpdateOrganisationError::unhandled)?;
66: 64:         crate::serde_util::update_organisation_output_output_correct_errors(output).build().map_err(crate::operation::update_organisation::UpdateOrganisationError::unhandled)?
67: 65:     })
68: 66: }
69: 67: 
70: 68: pub fn ser_update_organisation_input(input: &crate::operation::update_organisation::UpdateOrganisationInput) -> ::std::result::Result<::aws_smithy_types::body::SdkBody, ::aws_smithy_types::error::operation::SerializationError> {
71: 69:     let mut out = String::new();
72: 70:     let mut object = ::aws_smithy_json::serialize::JsonObjectWriter::new(&mut out);
73: 71:     crate::protocol_serde::shape_update_organisation_input::ser_update_organisation_input_input(&mut object, input)?;
74: 72:     object.finish();
75: 73:     Ok(::aws_smithy_types::body::SdkBody::from(out))
76: 74: }
77: 75: 
78: 76: pub(crate) fn de_update_organisation(value: &[u8], mut builder: crate::operation::update_organisation::builders::UpdateOrganisationOutputBuilder) -> ::std::result::Result<crate::operation::update_organisation::builders::UpdateOrganisationOutputBuilder, ::aws_smithy_json::deserialize::error::DeserializeError> {
79: 77:     let mut tokens_owned = ::aws_smithy_json::deserialize::json_token_iter(crate::protocol_serde::or_empty_doc(value)).peekable();
80: 78:                         let tokens = &mut tokens_owned;
81: 79:                         ::aws_smithy_json::deserialize::token::expect_start_object(tokens.next())?;
82: 80:     loop {
83: 81:         match tokens.next().transpose()? {
84: 82:             Some(::aws_smithy_json::deserialize::Token::EndObject { .. }) => break,
85: 83:                                     Some(::aws_smithy_json::deserialize::Token::ObjectKey { key, .. }) => {
86: 84:                 match key.to_unescaped()?.as_ref() {
87: 85:                     "admin_email" => {
88: 86:                         builder = builder.set_admin_email(
89: 87:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
90: 88:                                 s.to_unescaped().map(|u|
91: 89:                                     u.into_owned()
92: 90:                                 )
93: 91:                             ).transpose()?
94: 92:                         );
95: 93:                     }
96: 94:                     "contact_email" => {
97: 95:                         builder = builder.set_contact_email(
98: 96:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
99: 97:                                 s.to_unescaped().map(|u|
100: 98:                                     u.into_owned()
101: 99:                                 )
102: 100:                             ).transpose()?
103: 101:                         );
104: 102:                     }
105: 103:                     "contact_phone" => {
106: 104:                         builder = builder.set_contact_phone(
107: 105:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
108: 106:                                 s.to_unescaped().map(|u|
109: 107:                                     u.into_owned()
110: 108:                                 )
111: 109:                             ).transpose()?
112: 110:                         );
113: 111:                     }
114: 112:                     "country_code" => {
115: 113:                         builder = builder.set_country_code(
116: 114:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
117: 115:                                 s.to_unescaped().map(|u|
118: 116:                                     u.into_owned()
119: 117:                                 )
120: 118:                             ).transpose()?
121: 119:                         );
122: 120:                     }
123: 121:                     "created_at" => {
124: 122:                         builder = builder.set_created_at(
125: 123:                             ::aws_smithy_json::deserialize::token::expect_timestamp_or_null(tokens.next(), ::aws_smithy_types::date_time::Format::DateTimeWithOffset)?
126: 124:                         );
127: 125:                     }
128: 126:                     "created_by" => {
129: 127:                         builder = builder.set_created_by(
130: 128:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
131: 129:                                 s.to_unescaped().map(|u|
132: 130:                                     u.into_owned()
133: 131:                                 )
134: 132:                             ).transpose()?
135: 133:                         );
136: 134:                     }
137: 135:                     "id" => {
138: 136:                         builder = builder.set_id(
139: 137:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
140: 138:                                 s.to_unescaped().map(|u|
141: 139:                                     u.into_owned()
142: 140:                                 )
143: 141:                             ).transpose()?
144: 142:                         );
145: 143:                     }
146: 144:                     "name" => {
147: 145:                         builder = builder.set_name(
148: 146:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
149: 147:                                 s.to_unescaped().map(|u|
150: 148:                                     u.into_owned()
151: 149:                                 )
152: 150:                             ).transpose()?
153: 151:                         );
154: 152:                     }
155: 153:                     "sector" => {
156: 154:                         builder = builder.set_sector(
157: 155:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
158: 156:                                 s.to_unescaped().map(|u|
159: 157:                                     u.into_owned()
160: 158:                                 )
161: 159:                             ).transpose()?
162: 160:                         );
163: 161:                     }
164: 162:                     "status" => {
165: 163:                         builder = builder.set_status(
166: 164:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
167: 165:                                 s.to_unescaped().map(|u|
168: 166:                                     crate::types::OrgStatus::from(u.as_ref())
169: 167:                                 )
170: 168:                             ).transpose()?
171: 169:                         );
172: 170:                     }
173: 171:                     "updated_at" => {
174: 172:                         builder = builder.set_updated_at(
175: 173:                             ::aws_smithy_json::deserialize::token::expect_timestamp_or_null(tokens.next(), ::aws_smithy_types::date_time::Format::DateTimeWithOffset)?
176: 174:                         );
177: 175:                     }
178: 176:                     "updated_by" => {
179: 177:                         builder = builder.set_updated_by(
180: 178:                             ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
181: 179:                                 s.to_unescaped().map(|u|
182: 180:                                     u.into_owned()
183: 181:                                 )
184: 182:                             ).transpose()?
185: 183:                         );
186: 184:                     }
187: 185:                     _ => ::aws_smithy_json::deserialize::token::skip_value(tokens)?
188: 186:                 }
189: 187:             }
190: 188:             other => return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(format!("expected object key or end object, found: {:?}", other)))
191: 189:         }
192: 190:     }
193: 191:     if tokens.next().is_some() {
194: 192:         return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom("found more JSON tokens after completing parsing"));
195: 193:     }
196: 194:     Ok(builder)
197: 195: }
198: 196: 
199: 197: ```
200: 198: ```
201: 199: ```
202: 200: ```
203: ```
```

