1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_webhook_input.rs
2: ```rust
3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_webhook_input.rs
4: 2: ```rust
5: 3: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_webhook_input.rs
6: 4: ```rust
7: 5: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_webhook_input.rs
8: 6: ```rust
9: 7: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_webhook_input.rs
10: 8: ```rust
11: 9: // Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
12: 10: pub fn ser_update_webhook_input_input(
13: 11:                          object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
14: 12:                          input: &crate::operation::update_webhook::UpdateWebhookInput,
15: 13:                     ) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
16: 14:     if let Some(var_1) = &input.change_reason {
17: 15:         object.key("change_reason").string(var_1.as_str());
18: 16:     }
19: 17:     if let Some(var_2) = &input.custom_headers {
20: 18:         #[allow(unused_mut)]
21: 19:         let mut object_3 = object.key("custom_headers").start_object();
22: 20:         for (key_4, value_5) in var_2 {
23: 21:              {
24: 22:                 object_3.key(key_4.as_str()).document(value_5);
25: 23:             }
26: 24:         }
27: 25:         object_3.finish();
28: 26:     }
29: 27:     if let Some(var_6) = &input.description {
30: 28:         object.key("description").string(var_6.as_str());
31: 29:     }
32: 30:     if let Some(var_7) = &input.enabled {
33: 31:         object.key("enabled").boolean(*var_7);
34: 32:     }
35: 33:     if let Some(var_8) = &input.events {
36: 34:         let mut array_9 = object.key("events").start_array();
37: 35:         for item_10 in var_8 {
38: 36:              {
39: 37:                 array_9.value().string(item_10.as_str());
40: 38:             }
41: 39:         }
42: 40:         array_9.finish();
43: 41:     }
44: 42:     if let Some(var_11) = &input.method {
45: 43:         object.key("method").string(var_11.as_str());
46: 44:     }
47: 45:     if let Some(var_12) = &input.url {
48: 46:         object.key("url").string(var_12.as_str());
49: 47:     }
50: 48:     if let Some(var_13) = &input.version {
51: 49:         object.key("version").string(var_13.as_str());
52: 50:     }
53: 51:     Ok(())
54: 52: }
55: 53: 
56: 54: ```
57: 55: ```
58: 56: ```
59: 57: ```
60: ```
```

