### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-config\crates\lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_workspace_input.rs
```rust
1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx-core-config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_workspace_input.rs
2: ```rust
3: 1: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_workspace_input.rs
4: 2: ```rust
5: 3: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_workspace_input.rs
6: 4: ```rust
7: 5: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_workspace_input.rs
8: 6: ```rust
9: 7: ### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\lyx_core_config\crates\lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_lyx-core-lyx_core_superposition_sdk\src\protocol_serde\shape_update_workspace_input.rs
10: 8: ```rust
11: 9: // Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
12: 10: pub fn ser_update_workspace_input_input(
13: 11:                          object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
14: 12:                          input: &crate::operation::update_workspace::UpdateWorkspaceInput,
15: 13:                     ) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
16: 14:     if let Some(var_1) = &input.allow_experiment_self_lyx-platform-lyx_platform_lyx-platform-lyx_platform_approval {
17: 15:         object.key("allow_experiment_self_lyx-platform-lyx_platform_lyx-platform-lyx_platform_approval").boolean(*var_1);
18: 16:     }
19: 17:     if let Some(var_2) = &input.auto_populate_control {
20: 18:         object.key("auto_populate_control").boolean(*var_2);
21: 19:     }
22: 20:     if let Some(var_3) = &input.config_version {
23: 21:         object.key("config_version").string(var_3.as_str());
24: 22:     }
25: 23:     if let Some(var_4) = &input.enable_change_reason_validation {
26: 24:         object.key("enable_change_reason_validation").boolean(*var_4);
27: 25:     }
28: 26:     if let Some(var_5) = &input.enable_context_validation {
29: 27:         object.key("enable_context_validation").boolean(*var_5);
30: 28:     }
31: 29:     if let Some(var_6) = &input.mandatory_dimensions {
32: 30:         let mut array_7 = object.key("mandatory_dimensions").start_array();
33: 31:         for item_8 in var_6 {
34: 32:              {
35: 33:                 array_7.value().string(item_8.as_str());
36: 34:             }
37: 35:         }
38: 36:         array_7.finish();
39: 37:     }
40: 38:     if let Some(var_9) = &input.metrics {
41: 39:         object.key("metrics").document(var_9);
42: 40:     }
43: 41:     if let Some(var_10) = &input.workspace_admin_email {
44: 42:         object.key("workspace_admin_email").string(var_10.as_str());
45: 43:     }
46: 44:     if let Some(var_11) = &input.workspace_status {
47: 45:         object.key("workspace_status").string(var_11.as_str());
48: 46:     }
49: 47:     Ok(())
50: 48: }
51: 49: 
52: 50: ```
53: 51: ```
54: 52: ```
55: 53: ```
56: ```
```
