### C:\Users\Administrator\Downloads\zed-0.222.1-pre\lyxal_ui\crates\core\leptos\router\Cargo.toml
[package]
name = "router"
version = "*"
edition = "2024"

[dependencies]
server_fn = { path = "../server_fn", version = "*", optional = true }
leptos_dom = { path = "../leptos_dom", version = "*" }
leptos_macro = { path = "../leptos_macro", version = "*" }
reactive_graph = { path = "../reactive_graph", version = "*" }
tachys = { path = "../tachys", version = "*" }
serde = { version = "*" }
tracing = { version = "*" }
web-sys = { version = "*", features = ["Location", "History", "Window", "Element"] }

[features]
nonce = []
nightly = []
hydrate = []
ssr = ["dep:server_fn"]
csr = []


[build-dependencies]
rustc_version = "*"



