[package]
name = "lyx-spec-image"
version = "0.8.0"
edition = "2024"

[dependencies]
leptos = { path = "../core/lyx-core-leptos/leptos" }
leptos_router = { path = "../core/lyx-core-leptos/router" }
leptos_meta = { path = "../core/lyx-core-leptos/meta" }

wasm-bindgen = { version = "*" }
web-sys = { version = "*", optional = true, features = ["HtmlImageElement"] }

tokio = { version = "*", optional = true, features = ["rt-multi-thread", "rt", "fs"] }
axum = { version = "*", optional = true, features = ["macros"] }
tower = { version = "*", optional = true }
tower-http = { version = "*", optional = true, features = ["fs"] }

image = { version = "*", optional = true }
webp = { version = "*", optional = true }
serde = { version = "*", features = ["derive"] }
serde_qs = { version = "*" }
thiserror = { version = "*", optional = true }
base64 = { version = "*" }
tracing = { version = "*", optional = true }
dashmap = { version = "*", optional = true }

[features]
ssr = [
"leptos_router/ssr", "leptos_meta/ssr" , "leptos/ssr",
"dep:webp", "dep:image",
"dep:tokio", "dep:axum", "dep:tower", "dep:tower-http",
"dep:tracing", "dep:dashmap", "dep:thiserror"
]
hydrate = [ "dep:web-sys","leptos/hydrate", "leptos_router/hydrate" ]

[dev-dependencies]
leptos_axum = { path = "../../core/leptos/integrations/axum" , optional = true }











