[package]
name = "context_aware_config"
version = "0.8.0"
edition = "2024"

[dependencies]
actix-http = { version = "*" }
actix-web = { version = "*" }
anyhow = { version = "*" }
bigdecimal = { version = "*" }
blake3 = { version = "*" }
cac_client = { path = "../cac_client" }
chrono = { version = "*" }
diesel = { version = "*", features = ["numeric"] }
fred = { version = "*", optional = true, features = ["metrics"] }
itertools = { version = "*" }
jsonlogic = { version = "*" }
jsonschema = { version = "*" }
log = { version = "*" }
num-bigint = { version = "*" }
serde = { version = "*" }
serde_json = { version = "*" }
secrecy = { version = "*" }
service_utils = { path = "../service_utils" }
superposition_derives = { path = "../superposition_derives" }
superposition_macros = { path = "../superposition_macros" }
superposition_types = { path = "../superposition_types", features = ["api", "result", "diesel_derives", "server" ], optional = true }
uuid = { version = "*" }

[features]
disable_db_data_validation = ["superposition_types/disable_db_data_validation"]
high-performance-mode = ["dep:fred"]







