[package]
name = "lyx-ui-foundations-yew"
version = "0.8.0"
edition = "2024"

[features]
default = []
icons = ["dep:lyx-ui-foundations-yew", "lyx-ui-foundations-yew/all-icons"]

[dependencies]

lyx-ui-foundations-yew = { path = "../../packages/yew", optional = true }
yew = { version = "*", features = ["csr"] }





