-- Clés i18n pour les villes du pays: SB --

CREATE i18n_key:i18n_city_sb_102905_name SET description = 'Nom pour la ville \'Tulagi\'';
CREATE i18n_key:i18n_city_sb_102902_name SET description = 'Nom pour la ville \'Honiara\'';
CREATE i18n_key:i18n_city_sb_102900_name SET description = 'Nom pour la ville \'Buala\'';
CREATE i18n_key:i18n_city_sb_102903_name SET description = 'Nom pour la ville \'Kirakira\'';
CREATE i18n_key:i18n_city_sb_102899_name SET description = 'Nom pour la ville \'Auki\'';
CREATE i18n_key:i18n_city_sb_102904_name SET description = 'Nom pour la ville \'Lata\'';
CREATE i18n_key:i18n_city_sb_102901_name SET description = 'Nom pour la ville \'Gizo\'';
