[package]
name = "hydration_context"
version = "0.8.0"
edition = "2024"
[dependencies]
any_error = { path = "../any_error", version = "0.8.0" }
or_poisoned = { path = "../or_poisoned", version = "*" }
futures = { version = "*", default-features = true }
serde = { version = "*", features = ["derive"], default-features = true }
wasm-bindgen = { version = "*", optional = true, default-features = true }
js-sys = { version = "*", optional = true, default-features = true }
pin-project-lite = { version = "*", default-features = true }
[features]
browser = ["dep:wasm-bindgen", "dep:js-sys"]


[build-dependencies]
rustc_version = "*"



