[package]
name = "start-csr"
version = "0.8.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { path = "../core/lyx-core-leptos/leptos" }
leptos_meta = { path = "../core/lyx-core-leptos/meta" }
leptos_router = { path = "../core/lyx-core-leptos/router" }
console_log = { version = "*" }
log = { version = "*" }
console_error_panic_hook = { version = "*" }
query = { path = "../../query" }
devtools = { path = "../../devtools" }
gloo-timers = { version = "*" }
serde = { version = "*" }
reqwest = { version = "*", features = ["json"] }
leptos-use = { path = "../../../use" }
leptos_theme = { path = "../../../../ui-foundations/lyx-found-theme" }

# utils
# strum = { version = "*", features = ["derive", "strum_macros"] }
# strum_macros = "0.25"

[dev-dependencies]


wasm-bindgen = { version = "*" }
wasm-bindgen-test = { version = "*" }
web-sys = { version = "*", features = ["Document"] }

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"











