[package]
name = "lyx-ui-singlestage"
version = "0.8.0"
edition = "2024"
[dependencies]
singlestage_macro = { path = "../singlestage_macro", optional = true }
reactive_stores = { path = "../../../core/lyx-core-leptos/reactive_stores", optional = true }
leptos = { path = "../../../core/lyx-core-leptos/leptos" }
leptos_meta = { path = "../../../core/lyx-core-leptos/meta" }
serde = { version = "*" }
uuid = { version = "*", features = ["v4", "js"] }
[build-dependencies]
reqwest = { version = "*", features = ["blocking"] }
sha256 = { version = "*" }
[features]
csr = ["leptos/csr"]
ssr = ["leptos/ssr"]
hydrate = ["leptos/hydrate"]
islands = ["serde/derive", "leptos/islands"]
nightly = ["leptos/nightly"]
stores = ["dep:reactive_stores"]
default = [
"accordion",
"alert",
"aspect_ratio",
"avatar",
"badge",
"breadcrumb",
"button",
"button_group",
"card",
"carousel",
"checkbox",
"context_menu",
"dialog",
"dropdown",
"empty",
"icon",
"field",
"input",
"input_group",
"item",
"kbd",
"label",
"link",
"pagination",
"popover",
"progress",
"radio",
"scroll_area",
"select",
"separator",
"sidebar",
"skeleton",
"slider",
"spinner",
"switch",
"table",
"tabs",
"textarea",
"theme_provider",
"toggle",
"tooltip" ]
accordion = []
alert = []
aspect_ratio = []
avatar = []
badge = []
breadcrumb = ["dropdown"]
button = ["input_group"]
button_group = []
card = []
carousel = []
checkbox = ["field", "label"]
context_menu = []
dialog = []
dropdown = ["button"]
empty = []
icon = ["macro"]
field = []
input = ["field", "label"]
input_group = []
item = []
kbd = []
macro = ["dep:singlestage_macro"]
label = []
link = []
pagination = ["button"]
popover = []
progress = []
radio = ["field", "label"]
scroll_area = []
select = ["field"]
separator = []
sidebar = []
skeleton = []
slider = ["field", "label"]
spinner = []
switch = ["field", "checkbox", "label"]
table = []
tabs = []
textarea = ["field", "label"]
theme_provider = []
toggle = []
tooltip = []











