-- Clés i18n pour les villes du pays: GQ --

CREATE i18n_key:i18n_city_gq_52397_name SET description = 'Nom pour la ville \'San Antonio de Palé\'';
CREATE i18n_key:i18n_city_gq_52387_name SET description = 'Nom pour la ville \'Malabo\'';
CREATE i18n_key:i18n_city_gq_52395_name SET description = 'Nom pour la ville \'Rebola\'';
CREATE i18n_key:i18n_city_gq_52398_name SET description = 'Nom pour la ville \'Santiago de Baney\'';
CREATE i18n_key:i18n_city_gq_52385_name SET description = 'Nom pour la ville \'Luba\'';
CREATE i18n_key:i18n_city_gq_52376_name SET description = 'Nom pour la ville \'Acurenam\'';
CREATE i18n_key:i18n_city_gq_52380_name SET description = 'Nom pour la ville \'Bicurga\'';
CREATE i18n_key:i18n_city_gq_52384_name SET description = 'Nom pour la ville \'Evinayong\'';
CREATE i18n_key:i18n_city_gq_52383_name SET description = 'Nom pour la ville \'Ebebiyin\'';
CREATE i18n_key:i18n_city_gq_52390_name SET description = 'Nom pour la ville \'Mikomeseng\'';
CREATE i18n_key:i18n_city_gq_52392_name SET description = 'Nom pour la ville \'Ncue\'';
CREATE i18n_key:i18n_city_gq_52393_name SET description = 'Nom pour la ville \'Nsang\'';
CREATE i18n_key:i18n_city_gq_52379_name SET description = 'Nom pour la ville \'Bata\'';
CREATE i18n_key:i18n_city_gq_52381_name SET description = 'Nom pour la ville \'Bitica\'';
CREATE i18n_key:i18n_city_gq_52382_name SET description = 'Nom pour la ville \'Cogo\'';
CREATE i18n_key:i18n_city_gq_52386_name SET description = 'Nom pour la ville \'Machinda\'';
CREATE i18n_key:i18n_city_gq_52388_name SET description = 'Nom pour la ville \'Mbini\'';
CREATE i18n_key:i18n_city_gq_52396_name SET description = 'Nom pour la ville \'Río Campo\'';
CREATE i18n_key:i18n_city_gq_52375_name SET description = 'Nom pour la ville \'Aconibe\'';
CREATE i18n_key:i18n_city_gq_52378_name SET description = 'Nom pour la ville \'Añisoc\'';
CREATE i18n_key:i18n_city_gq_52377_name SET description = 'Nom pour la ville \'Ayene\'';
CREATE i18n_key:i18n_city_gq_52389_name SET description = 'Nom pour la ville \'Mengomeyén\'';
CREATE i18n_key:i18n_city_gq_52391_name SET description = 'Nom pour la ville \'Mongomo\'';
CREATE i18n_key:i18n_city_gq_52394_name SET description = 'Nom pour la ville \'Nsok\'';
