[workspace]
resolver = "2"
members = ["macros", "lib"]

[patch.crates-io]
leptos = { path = "../leptos/leptos" }
leptos_meta = { path = "../leptos/meta" }
leptos_router = { path = "../leptos/router" }
leptos_axum = { path = "../leptos/integrations/axum" }
leptos_actix = { path = "../leptos/integrations/actix" }
leptos_dom = { path = "../leptos/leptos_dom" }
leptos_macro = { path = "../leptos/leptos_macro" }
leptos_server = { path = "../leptos/leptos_server" }
leptos_config = { path = "../leptos/leptos_config" }
reactive_graph = { path = "../leptos/reactive_graph" }
reactive_stores = { path = "../leptos/reactive_stores" }
reactive_stores_macro = { path = "../leptos/reactive_stores_macro" }
server_fn = { path = "../leptos/server_fn" }
server_fn_macro = { path = "../leptos/server_fn_macro" }
tachys = { path = "../leptos/tachys" }
hydration_context = { path = "../leptos/hydration_context" }
throw_error = { path = "../leptos/any_error" }
any_spawner = { path = "../leptos/any_spawner" }
either_of = { path = "../leptos/either_of" }
oco_ref = { path = "../leptos/oco" }
or_poisoned = { path = "../leptos/or_poisoned" }
next_tuple = { path = "../leptos/next_tuple" }
leptos-use = { path = "../logic/lyx-logic-use" }
tailwind_fuse = { path = "../../ui-foundations/lyx-found-tailwind/fuse" }







