[package]
name = "lyx-core-leptos_config"
version = "0.0.1"
edition = "2024"
[dependencies]
config = { version = "0.0.1", default-features = false, features = ["toml", "convert-case" ] }
regex = { version = "0.0.1", default-features = true }
serde = { version = "0.0.1", features = ["derive", "rc" ], default-features = true }
thiserror = { version = "0.0.1", default-features = true }
typed-builder = { version = "0.0.1", default-features = true }
[dev-dependencies]
tokio = { version = "0.0.1", features = ["rt", "macros" ], default-features = true }
tempfile = { version = "0.0.1", default-features = true }
temp-env = { version = "0.0.1", features = ["async_closure" ], default-features = true }
