[package]
name = "leptos_config"
version = "0.8.0"
edition = "2024"
[dependencies]
config = { version = "*", default-features = false, features = ["toml", "convert-case" ] }
regex = { version = "*", default-features = true }
serde = { version = "*", features = ["derive", "rc" ], default-features = true }
thiserror = { version = "*", default-features = true }
typed-builder = { version = "*", default-features = true }
[dev-dependencies]
tokio = { version = "*", features = ["rt", "macros" ], default-features = true }
tempfile = { version = "*", default-features = true }
temp-env = { version = "*", features = ["async_closure" ], default-features = true }


[build-dependencies]
rustc_version = "*"


