-- Batch 5: Cles i18n pour 100 tools

CREATE i18n_key:tool_customerio_campaign_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_customerio_campaign_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_customerio_campaign_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_customerio_campaign_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_customerio_campaign_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_customerio_campaign_getMany_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_customerio_campaign_getMany_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_customerio_campaign_getMany_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_customerio_campaign_getMany_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_customerio_campaign_getMany_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_customerio_segment_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_customerio_segment_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_customerio_segment_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_customerio_segment_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_customerio_segment_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_customerio_segment_getMany_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_customerio_segment_getMany_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_customerio_segment_getMany_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_customerio_segment_getMany_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_customerio_segment_getMany_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_datatable_row_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_datatable_row_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_datatable_row_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_datatable_row_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_datatable_row_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_datatable_row_getMany_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_datatable_row_getMany_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_datatable_row_getMany_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_datatable_row_getMany_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_datatable_row_getMany_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_datetime_datetime_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_datetime_datetime_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_datetime_datetime_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_datetime_datetime_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_datetime_datetime_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_datetime_datetime_getMany_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_datetime_datetime_getMany_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_datetime_datetime_getMany_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_datetime_datetime_getMany_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_datetime_datetime_getMany_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_datetimev1_datetimev1_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_datetimev1_datetimev1_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_datetimev1_datetimev1_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_datetimev1_datetimev1_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_datetimev1_datetimev1_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_datetimev1_datetimev1_getMany_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_datetimev1_datetimev1_getMany_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_datetimev1_datetimev1_getMany_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_datetimev1_datetimev1_getMany_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_datetimev1_datetimev1_getMany_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_datetimev2_addtodate_addToDate_name SET description = "Nom du tool Add to a Date";
CREATE i18n_key:tool_datetimev2_addtodate_addToDate_desc SET description = "Description du tool Add to a Date";
CREATE i18n_key:tool_datetimev2_addtodate_addToDate_tooltip SET description = "Tooltip du tool Add to a Date";
CREATE i18n_key:tool_datetimev2_addtodate_addToDate_success SET description = "Message de succes du tool Add to a Date";
CREATE i18n_key:tool_datetimev2_addtodate_addToDate_error SET description = "Message d'erreur du tool Add to a Date";

CREATE i18n_key:tool_datetimev2_addtodate_extractDate_name SET description = "Nom du tool Extract Part of a Date";
CREATE i18n_key:tool_datetimev2_addtodate_extractDate_desc SET description = "Description du tool Extract Part of a Date";
CREATE i18n_key:tool_datetimev2_addtodate_extractDate_tooltip SET description = "Tooltip du tool Extract Part of a Date";
CREATE i18n_key:tool_datetimev2_addtodate_extractDate_success SET description = "Message de succes du tool Extract Part of a Date";
CREATE i18n_key:tool_datetimev2_addtodate_extractDate_error SET description = "Message d'erreur du tool Extract Part of a Date";

CREATE i18n_key:tool_datetimev2_addtodate_formatDate_name SET description = "Nom du tool Format a Date";
CREATE i18n_key:tool_datetimev2_addtodate_formatDate_desc SET description = "Description du tool Format a Date";
CREATE i18n_key:tool_datetimev2_addtodate_formatDate_tooltip SET description = "Tooltip du tool Format a Date";
CREATE i18n_key:tool_datetimev2_addtodate_formatDate_success SET description = "Message de succes du tool Format a Date";
CREATE i18n_key:tool_datetimev2_addtodate_formatDate_error SET description = "Message d'erreur du tool Format a Date";

CREATE i18n_key:tool_datetimev2_addtodate_getCurrentDate_name SET description = "Nom du tool Get Current Date";
CREATE i18n_key:tool_datetimev2_addtodate_getCurrentDate_desc SET description = "Description du tool Get Current Date";
CREATE i18n_key:tool_datetimev2_addtodate_getCurrentDate_tooltip SET description = "Tooltip du tool Get Current Date";
CREATE i18n_key:tool_datetimev2_addtodate_getCurrentDate_success SET description = "Message de succes du tool Get Current Date";
CREATE i18n_key:tool_datetimev2_addtodate_getCurrentDate_error SET description = "Message d'erreur du tool Get Current Date";

CREATE i18n_key:tool_datetimev2_addtodate_getTimeBetweenDates_name SET description = "Nom du tool Get Time Between Dates";
CREATE i18n_key:tool_datetimev2_addtodate_getTimeBetweenDates_desc SET description = "Description du tool Get Time Between Dates";
CREATE i18n_key:tool_datetimev2_addtodate_getTimeBetweenDates_tooltip SET description = "Tooltip du tool Get Time Between Dates";
CREATE i18n_key:tool_datetimev2_addtodate_getTimeBetweenDates_success SET description = "Message de succes du tool Get Time Between Dates";
CREATE i18n_key:tool_datetimev2_addtodate_getTimeBetweenDates_error SET description = "Message d'erreur du tool Get Time Between Dates";

CREATE i18n_key:tool_datetimev2_addtodate_roundDate_name SET description = "Nom du tool Round a Date";
CREATE i18n_key:tool_datetimev2_addtodate_roundDate_desc SET description = "Description du tool Round a Date";
CREATE i18n_key:tool_datetimev2_addtodate_roundDate_tooltip SET description = "Tooltip du tool Round a Date";
CREATE i18n_key:tool_datetimev2_addtodate_roundDate_success SET description = "Message de succes du tool Round a Date";
CREATE i18n_key:tool_datetimev2_addtodate_roundDate_error SET description = "Message d'erreur du tool Round a Date";

CREATE i18n_key:tool_datetimev2_addtodate_subtractFromDate_name SET description = "Nom du tool Subtract From a Date";
CREATE i18n_key:tool_datetimev2_addtodate_subtractFromDate_desc SET description = "Description du tool Subtract From a Date";
CREATE i18n_key:tool_datetimev2_addtodate_subtractFromDate_tooltip SET description = "Tooltip du tool Subtract From a Date";
CREATE i18n_key:tool_datetimev2_addtodate_subtractFromDate_success SET description = "Message de succes du tool Subtract From a Date";
CREATE i18n_key:tool_datetimev2_addtodate_subtractFromDate_error SET description = "Message d'erreur du tool Subtract From a Date";

CREATE i18n_key:tool_datetimev2_currentdate_addToDate_name SET description = "Nom du tool Add to a Date";
CREATE i18n_key:tool_datetimev2_currentdate_addToDate_desc SET description = "Description du tool Add to a Date";
CREATE i18n_key:tool_datetimev2_currentdate_addToDate_tooltip SET description = "Tooltip du tool Add to a Date";
CREATE i18n_key:tool_datetimev2_currentdate_addToDate_success SET description = "Message de succes du tool Add to a Date";
CREATE i18n_key:tool_datetimev2_currentdate_addToDate_error SET description = "Message d'erreur du tool Add to a Date";

CREATE i18n_key:tool_datetimev2_currentdate_extractDate_name SET description = "Nom du tool Extract Part of a Date";
CREATE i18n_key:tool_datetimev2_currentdate_extractDate_desc SET description = "Description du tool Extract Part of a Date";
CREATE i18n_key:tool_datetimev2_currentdate_extractDate_tooltip SET description = "Tooltip du tool Extract Part of a Date";
CREATE i18n_key:tool_datetimev2_currentdate_extractDate_success SET description = "Message de succes du tool Extract Part of a Date";
CREATE i18n_key:tool_datetimev2_currentdate_extractDate_error SET description = "Message d'erreur du tool Extract Part of a Date";

CREATE i18n_key:tool_datetimev2_currentdate_formatDate_name SET description = "Nom du tool Format a Date";
CREATE i18n_key:tool_datetimev2_currentdate_formatDate_desc SET description = "Description du tool Format a Date";
CREATE i18n_key:tool_datetimev2_currentdate_formatDate_tooltip SET description = "Tooltip du tool Format a Date";
CREATE i18n_key:tool_datetimev2_currentdate_formatDate_success SET description = "Message de succes du tool Format a Date";
CREATE i18n_key:tool_datetimev2_currentdate_formatDate_error SET description = "Message d'erreur du tool Format a Date";

CREATE i18n_key:tool_datetimev2_currentdate_getCurrentDate_name SET description = "Nom du tool Get Current Date";
CREATE i18n_key:tool_datetimev2_currentdate_getCurrentDate_desc SET description = "Description du tool Get Current Date";
CREATE i18n_key:tool_datetimev2_currentdate_getCurrentDate_tooltip SET description = "Tooltip du tool Get Current Date";
CREATE i18n_key:tool_datetimev2_currentdate_getCurrentDate_success SET description = "Message de succes du tool Get Current Date";
CREATE i18n_key:tool_datetimev2_currentdate_getCurrentDate_error SET description = "Message d'erreur du tool Get Current Date";

CREATE i18n_key:tool_datetimev2_currentdate_getTimeBetweenDates_name SET description = "Nom du tool Get Time Between Dates";
CREATE i18n_key:tool_datetimev2_currentdate_getTimeBetweenDates_desc SET description = "Description du tool Get Time Between Dates";
CREATE i18n_key:tool_datetimev2_currentdate_getTimeBetweenDates_tooltip SET description = "Tooltip du tool Get Time Between Dates";
CREATE i18n_key:tool_datetimev2_currentdate_getTimeBetweenDates_success SET description = "Message de succes du tool Get Time Between Dates";
CREATE i18n_key:tool_datetimev2_currentdate_getTimeBetweenDates_error SET description = "Message d'erreur du tool Get Time Between Dates";

CREATE i18n_key:tool_datetimev2_currentdate_roundDate_name SET description = "Nom du tool Round a Date";
CREATE i18n_key:tool_datetimev2_currentdate_roundDate_desc SET description = "Description du tool Round a Date";
CREATE i18n_key:tool_datetimev2_currentdate_roundDate_tooltip SET description = "Tooltip du tool Round a Date";
CREATE i18n_key:tool_datetimev2_currentdate_roundDate_success SET description = "Message de succes du tool Round a Date";
CREATE i18n_key:tool_datetimev2_currentdate_roundDate_error SET description = "Message d'erreur du tool Round a Date";

CREATE i18n_key:tool_datetimev2_currentdate_subtractFromDate_name SET description = "Nom du tool Subtract From a Date";
CREATE i18n_key:tool_datetimev2_currentdate_subtractFromDate_desc SET description = "Description du tool Subtract From a Date";
CREATE i18n_key:tool_datetimev2_currentdate_subtractFromDate_tooltip SET description = "Tooltip du tool Subtract From a Date";
CREATE i18n_key:tool_datetimev2_currentdate_subtractFromDate_success SET description = "Message de succes du tool Subtract From a Date";
CREATE i18n_key:tool_datetimev2_currentdate_subtractFromDate_error SET description = "Message d'erreur du tool Subtract From a Date";

CREATE i18n_key:tool_datetimev2_extractdate_addToDate_name SET description = "Nom du tool Add to a Date";
CREATE i18n_key:tool_datetimev2_extractdate_addToDate_desc SET description = "Description du tool Add to a Date";
CREATE i18n_key:tool_datetimev2_extractdate_addToDate_tooltip SET description = "Tooltip du tool Add to a Date";
CREATE i18n_key:tool_datetimev2_extractdate_addToDate_success SET description = "Message de succes du tool Add to a Date";
CREATE i18n_key:tool_datetimev2_extractdate_addToDate_error SET description = "Message d'erreur du tool Add to a Date";

CREATE i18n_key:tool_datetimev2_extractdate_extractDate_name SET description = "Nom du tool Extract Part of a Date";
CREATE i18n_key:tool_datetimev2_extractdate_extractDate_desc SET description = "Description du tool Extract Part of a Date";
CREATE i18n_key:tool_datetimev2_extractdate_extractDate_tooltip SET description = "Tooltip du tool Extract Part of a Date";
CREATE i18n_key:tool_datetimev2_extractdate_extractDate_success SET description = "Message de succes du tool Extract Part of a Date";
CREATE i18n_key:tool_datetimev2_extractdate_extractDate_error SET description = "Message d'erreur du tool Extract Part of a Date";

CREATE i18n_key:tool_datetimev2_extractdate_formatDate_name SET description = "Nom du tool Format a Date";
CREATE i18n_key:tool_datetimev2_extractdate_formatDate_desc SET description = "Description du tool Format a Date";
CREATE i18n_key:tool_datetimev2_extractdate_formatDate_tooltip SET description = "Tooltip du tool Format a Date";
CREATE i18n_key:tool_datetimev2_extractdate_formatDate_success SET description = "Message de succes du tool Format a Date";
CREATE i18n_key:tool_datetimev2_extractdate_formatDate_error SET description = "Message d'erreur du tool Format a Date";

CREATE i18n_key:tool_datetimev2_extractdate_getCurrentDate_name SET description = "Nom du tool Get Current Date";
CREATE i18n_key:tool_datetimev2_extractdate_getCurrentDate_desc SET description = "Description du tool Get Current Date";
CREATE i18n_key:tool_datetimev2_extractdate_getCurrentDate_tooltip SET description = "Tooltip du tool Get Current Date";
CREATE i18n_key:tool_datetimev2_extractdate_getCurrentDate_success SET description = "Message de succes du tool Get Current Date";
CREATE i18n_key:tool_datetimev2_extractdate_getCurrentDate_error SET description = "Message d'erreur du tool Get Current Date";

CREATE i18n_key:tool_datetimev2_extractdate_getTimeBetweenDates_name SET description = "Nom du tool Get Time Between Dates";
CREATE i18n_key:tool_datetimev2_extractdate_getTimeBetweenDates_desc SET description = "Description du tool Get Time Between Dates";
CREATE i18n_key:tool_datetimev2_extractdate_getTimeBetweenDates_tooltip SET description = "Tooltip du tool Get Time Between Dates";
CREATE i18n_key:tool_datetimev2_extractdate_getTimeBetweenDates_success SET description = "Message de succes du tool Get Time Between Dates";
CREATE i18n_key:tool_datetimev2_extractdate_getTimeBetweenDates_error SET description = "Message d'erreur du tool Get Time Between Dates";

CREATE i18n_key:tool_datetimev2_extractdate_roundDate_name SET description = "Nom du tool Round a Date";
CREATE i18n_key:tool_datetimev2_extractdate_roundDate_desc SET description = "Description du tool Round a Date";
CREATE i18n_key:tool_datetimev2_extractdate_roundDate_tooltip SET description = "Tooltip du tool Round a Date";
CREATE i18n_key:tool_datetimev2_extractdate_roundDate_success SET description = "Message de succes du tool Round a Date";
CREATE i18n_key:tool_datetimev2_extractdate_roundDate_error SET description = "Message d'erreur du tool Round a Date";

CREATE i18n_key:tool_datetimev2_extractdate_subtractFromDate_name SET description = "Nom du tool Subtract From a Date";
CREATE i18n_key:tool_datetimev2_extractdate_subtractFromDate_desc SET description = "Description du tool Subtract From a Date";
CREATE i18n_key:tool_datetimev2_extractdate_subtractFromDate_tooltip SET description = "Tooltip du tool Subtract From a Date";
CREATE i18n_key:tool_datetimev2_extractdate_subtractFromDate_success SET description = "Message de succes du tool Subtract From a Date";
CREATE i18n_key:tool_datetimev2_extractdate_subtractFromDate_error SET description = "Message d'erreur du tool Subtract From a Date";

CREATE i18n_key:tool_datetimev2_formatdate_addToDate_name SET description = "Nom du tool Add to a Date";
CREATE i18n_key:tool_datetimev2_formatdate_addToDate_desc SET description = "Description du tool Add to a Date";
CREATE i18n_key:tool_datetimev2_formatdate_addToDate_tooltip SET description = "Tooltip du tool Add to a Date";
CREATE i18n_key:tool_datetimev2_formatdate_addToDate_success SET description = "Message de succes du tool Add to a Date";
CREATE i18n_key:tool_datetimev2_formatdate_addToDate_error SET description = "Message d'erreur du tool Add to a Date";

CREATE i18n_key:tool_datetimev2_formatdate_extractDate_name SET description = "Nom du tool Extract Part of a Date";
CREATE i18n_key:tool_datetimev2_formatdate_extractDate_desc SET description = "Description du tool Extract Part of a Date";
CREATE i18n_key:tool_datetimev2_formatdate_extractDate_tooltip SET description = "Tooltip du tool Extract Part of a Date";
CREATE i18n_key:tool_datetimev2_formatdate_extractDate_success SET description = "Message de succes du tool Extract Part of a Date";
CREATE i18n_key:tool_datetimev2_formatdate_extractDate_error SET description = "Message d'erreur du tool Extract Part of a Date";

CREATE i18n_key:tool_datetimev2_formatdate_formatDate_name SET description = "Nom du tool Format a Date";
CREATE i18n_key:tool_datetimev2_formatdate_formatDate_desc SET description = "Description du tool Format a Date";
CREATE i18n_key:tool_datetimev2_formatdate_formatDate_tooltip SET description = "Tooltip du tool Format a Date";
CREATE i18n_key:tool_datetimev2_formatdate_formatDate_success SET description = "Message de succes du tool Format a Date";
CREATE i18n_key:tool_datetimev2_formatdate_formatDate_error SET description = "Message d'erreur du tool Format a Date";

CREATE i18n_key:tool_datetimev2_formatdate_getCurrentDate_name SET description = "Nom du tool Get Current Date";
CREATE i18n_key:tool_datetimev2_formatdate_getCurrentDate_desc SET description = "Description du tool Get Current Date";
CREATE i18n_key:tool_datetimev2_formatdate_getCurrentDate_tooltip SET description = "Tooltip du tool Get Current Date";
CREATE i18n_key:tool_datetimev2_formatdate_getCurrentDate_success SET description = "Message de succes du tool Get Current Date";
CREATE i18n_key:tool_datetimev2_formatdate_getCurrentDate_error SET description = "Message d'erreur du tool Get Current Date";

CREATE i18n_key:tool_datetimev2_formatdate_getTimeBetweenDates_name SET description = "Nom du tool Get Time Between Dates";
CREATE i18n_key:tool_datetimev2_formatdate_getTimeBetweenDates_desc SET description = "Description du tool Get Time Between Dates";
CREATE i18n_key:tool_datetimev2_formatdate_getTimeBetweenDates_tooltip SET description = "Tooltip du tool Get Time Between Dates";
CREATE i18n_key:tool_datetimev2_formatdate_getTimeBetweenDates_success SET description = "Message de succes du tool Get Time Between Dates";
CREATE i18n_key:tool_datetimev2_formatdate_getTimeBetweenDates_error SET description = "Message d'erreur du tool Get Time Between Dates";

CREATE i18n_key:tool_datetimev2_formatdate_roundDate_name SET description = "Nom du tool Round a Date";
CREATE i18n_key:tool_datetimev2_formatdate_roundDate_desc SET description = "Description du tool Round a Date";
CREATE i18n_key:tool_datetimev2_formatdate_roundDate_tooltip SET description = "Tooltip du tool Round a Date";
CREATE i18n_key:tool_datetimev2_formatdate_roundDate_success SET description = "Message de succes du tool Round a Date";
CREATE i18n_key:tool_datetimev2_formatdate_roundDate_error SET description = "Message d'erreur du tool Round a Date";

CREATE i18n_key:tool_datetimev2_formatdate_subtractFromDate_name SET description = "Nom du tool Subtract From a Date";
CREATE i18n_key:tool_datetimev2_formatdate_subtractFromDate_desc SET description = "Description du tool Subtract From a Date";
CREATE i18n_key:tool_datetimev2_formatdate_subtractFromDate_tooltip SET description = "Tooltip du tool Subtract From a Date";
CREATE i18n_key:tool_datetimev2_formatdate_subtractFromDate_success SET description = "Message de succes du tool Subtract From a Date";
CREATE i18n_key:tool_datetimev2_formatdate_subtractFromDate_error SET description = "Message d'erreur du tool Subtract From a Date";

CREATE i18n_key:tool_datetimev2_rounddate_addToDate_name SET description = "Nom du tool Add to a Date";
CREATE i18n_key:tool_datetimev2_rounddate_addToDate_desc SET description = "Description du tool Add to a Date";
CREATE i18n_key:tool_datetimev2_rounddate_addToDate_tooltip SET description = "Tooltip du tool Add to a Date";
CREATE i18n_key:tool_datetimev2_rounddate_addToDate_success SET description = "Message de succes du tool Add to a Date";
CREATE i18n_key:tool_datetimev2_rounddate_addToDate_error SET description = "Message d'erreur du tool Add to a Date";

CREATE i18n_key:tool_datetimev2_rounddate_extractDate_name SET description = "Nom du tool Extract Part of a Date";
CREATE i18n_key:tool_datetimev2_rounddate_extractDate_desc SET description = "Description du tool Extract Part of a Date";
CREATE i18n_key:tool_datetimev2_rounddate_extractDate_tooltip SET description = "Tooltip du tool Extract Part of a Date";
CREATE i18n_key:tool_datetimev2_rounddate_extractDate_success SET description = "Message de succes du tool Extract Part of a Date";
CREATE i18n_key:tool_datetimev2_rounddate_extractDate_error SET description = "Message d'erreur du tool Extract Part of a Date";

CREATE i18n_key:tool_datetimev2_rounddate_formatDate_name SET description = "Nom du tool Format a Date";
CREATE i18n_key:tool_datetimev2_rounddate_formatDate_desc SET description = "Description du tool Format a Date";
CREATE i18n_key:tool_datetimev2_rounddate_formatDate_tooltip SET description = "Tooltip du tool Format a Date";
CREATE i18n_key:tool_datetimev2_rounddate_formatDate_success SET description = "Message de succes du tool Format a Date";
CREATE i18n_key:tool_datetimev2_rounddate_formatDate_error SET description = "Message d'erreur du tool Format a Date";

CREATE i18n_key:tool_datetimev2_rounddate_getCurrentDate_name SET description = "Nom du tool Get Current Date";
CREATE i18n_key:tool_datetimev2_rounddate_getCurrentDate_desc SET description = "Description du tool Get Current Date";
CREATE i18n_key:tool_datetimev2_rounddate_getCurrentDate_tooltip SET description = "Tooltip du tool Get Current Date";
CREATE i18n_key:tool_datetimev2_rounddate_getCurrentDate_success SET description = "Message de succes du tool Get Current Date";
CREATE i18n_key:tool_datetimev2_rounddate_getCurrentDate_error SET description = "Message d'erreur du tool Get Current Date";

CREATE i18n_key:tool_datetimev2_rounddate_getTimeBetweenDates_name SET description = "Nom du tool Get Time Between Dates";
CREATE i18n_key:tool_datetimev2_rounddate_getTimeBetweenDates_desc SET description = "Description du tool Get Time Between Dates";
CREATE i18n_key:tool_datetimev2_rounddate_getTimeBetweenDates_tooltip SET description = "Tooltip du tool Get Time Between Dates";
CREATE i18n_key:tool_datetimev2_rounddate_getTimeBetweenDates_success SET description = "Message de succes du tool Get Time Between Dates";
CREATE i18n_key:tool_datetimev2_rounddate_getTimeBetweenDates_error SET description = "Message d'erreur du tool Get Time Between Dates";

CREATE i18n_key:tool_datetimev2_rounddate_roundDate_name SET description = "Nom du tool Round a Date";
CREATE i18n_key:tool_datetimev2_rounddate_roundDate_desc SET description = "Description du tool Round a Date";
CREATE i18n_key:tool_datetimev2_rounddate_roundDate_tooltip SET description = "Tooltip du tool Round a Date";
CREATE i18n_key:tool_datetimev2_rounddate_roundDate_success SET description = "Message de succes du tool Round a Date";
CREATE i18n_key:tool_datetimev2_rounddate_roundDate_error SET description = "Message d'erreur du tool Round a Date";

CREATE i18n_key:tool_datetimev2_rounddate_subtractFromDate_name SET description = "Nom du tool Subtract From a Date";
CREATE i18n_key:tool_datetimev2_rounddate_subtractFromDate_desc SET description = "Description du tool Subtract From a Date";
CREATE i18n_key:tool_datetimev2_rounddate_subtractFromDate_tooltip SET description = "Tooltip du tool Subtract From a Date";
CREATE i18n_key:tool_datetimev2_rounddate_subtractFromDate_success SET description = "Message de succes du tool Subtract From a Date";
CREATE i18n_key:tool_datetimev2_rounddate_subtractFromDate_error SET description = "Message d'erreur du tool Subtract From a Date";

CREATE i18n_key:tool_datetimev2_subtractfromdate_addToDate_name SET description = "Nom du tool Add to a Date";
CREATE i18n_key:tool_datetimev2_subtractfromdate_addToDate_desc SET description = "Description du tool Add to a Date";
CREATE i18n_key:tool_datetimev2_subtractfromdate_addToDate_tooltip SET description = "Tooltip du tool Add to a Date";
CREATE i18n_key:tool_datetimev2_subtractfromdate_addToDate_success SET description = "Message de succes du tool Add to a Date";
CREATE i18n_key:tool_datetimev2_subtractfromdate_addToDate_error SET description = "Message d'erreur du tool Add to a Date";

CREATE i18n_key:tool_datetimev2_subtractfromdate_extractDate_name SET description = "Nom du tool Extract Part of a Date";
CREATE i18n_key:tool_datetimev2_subtractfromdate_extractDate_desc SET description = "Description du tool Extract Part of a Date";
CREATE i18n_key:tool_datetimev2_subtractfromdate_extractDate_tooltip SET description = "Tooltip du tool Extract Part of a Date";
CREATE i18n_key:tool_datetimev2_subtractfromdate_extractDate_success SET description = "Message de succes du tool Extract Part of a Date";
CREATE i18n_key:tool_datetimev2_subtractfromdate_extractDate_error SET description = "Message d'erreur du tool Extract Part of a Date";

CREATE i18n_key:tool_datetimev2_subtractfromdate_formatDate_name SET description = "Nom du tool Format a Date";
CREATE i18n_key:tool_datetimev2_subtractfromdate_formatDate_desc SET description = "Description du tool Format a Date";
CREATE i18n_key:tool_datetimev2_subtractfromdate_formatDate_tooltip SET description = "Tooltip du tool Format a Date";
CREATE i18n_key:tool_datetimev2_subtractfromdate_formatDate_success SET description = "Message de succes du tool Format a Date";
CREATE i18n_key:tool_datetimev2_subtractfromdate_formatDate_error SET description = "Message d'erreur du tool Format a Date";

CREATE i18n_key:tool_datetimev2_subtractfromdate_getCurrentDate_name SET description = "Nom du tool Get Current Date";
CREATE i18n_key:tool_datetimev2_subtractfromdate_getCurrentDate_desc SET description = "Description du tool Get Current Date";
CREATE i18n_key:tool_datetimev2_subtractfromdate_getCurrentDate_tooltip SET description = "Tooltip du tool Get Current Date";
CREATE i18n_key:tool_datetimev2_subtractfromdate_getCurrentDate_success SET description = "Message de succes du tool Get Current Date";
CREATE i18n_key:tool_datetimev2_subtractfromdate_getCurrentDate_error SET description = "Message d'erreur du tool Get Current Date";

CREATE i18n_key:tool_datetimev2_subtractfromdate_getTimeBetweenDates_name SET description = "Nom du tool Get Time Between Dates";
CREATE i18n_key:tool_datetimev2_subtractfromdate_getTimeBetweenDates_desc SET description = "Description du tool Get Time Between Dates";
CREATE i18n_key:tool_datetimev2_subtractfromdate_getTimeBetweenDates_tooltip SET description = "Tooltip du tool Get Time Between Dates";
CREATE i18n_key:tool_datetimev2_subtractfromdate_getTimeBetweenDates_success SET description = "Message de succes du tool Get Time Between Dates";
CREATE i18n_key:tool_datetimev2_subtractfromdate_getTimeBetweenDates_error SET description = "Message d'erreur du tool Get Time Between Dates";

CREATE i18n_key:tool_datetimev2_subtractfromdate_roundDate_name SET description = "Nom du tool Round a Date";
CREATE i18n_key:tool_datetimev2_subtractfromdate_roundDate_desc SET description = "Description du tool Round a Date";
CREATE i18n_key:tool_datetimev2_subtractfromdate_roundDate_tooltip SET description = "Tooltip du tool Round a Date";
CREATE i18n_key:tool_datetimev2_subtractfromdate_roundDate_success SET description = "Message de succes du tool Round a Date";
CREATE i18n_key:tool_datetimev2_subtractfromdate_roundDate_error SET description = "Message d'erreur du tool Round a Date";

CREATE i18n_key:tool_datetimev2_subtractfromdate_subtractFromDate_name SET description = "Nom du tool Subtract From a Date";
CREATE i18n_key:tool_datetimev2_subtractfromdate_subtractFromDate_desc SET description = "Description du tool Subtract From a Date";
CREATE i18n_key:tool_datetimev2_subtractfromdate_subtractFromDate_tooltip SET description = "Tooltip du tool Subtract From a Date";
CREATE i18n_key:tool_datetimev2_subtractfromdate_subtractFromDate_success SET description = "Message de succes du tool Subtract From a Date";
CREATE i18n_key:tool_datetimev2_subtractfromdate_subtractFromDate_error SET description = "Message d'erreur du tool Subtract From a Date";

CREATE i18n_key:tool_debughelper_debughelper_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_debughelper_debughelper_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_debughelper_debughelper_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_debughelper_debughelper_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_debughelper_debughelper_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_debughelper_debughelper_getMany_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_debughelper_debughelper_getMany_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_debughelper_debughelper_getMany_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_debughelper_debughelper_getMany_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_debughelper_debughelper_getMany_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_deepl_language_translate_name SET description = "Nom du tool Translate";
CREATE i18n_key:tool_deepl_language_translate_desc SET description = "Description du tool Translate";
CREATE i18n_key:tool_deepl_language_translate_tooltip SET description = "Tooltip du tool Translate";
CREATE i18n_key:tool_deepl_language_translate_success SET description = "Message de succes du tool Translate";
CREATE i18n_key:tool_deepl_language_translate_error SET description = "Message d'erreur du tool Translate";

CREATE i18n_key:tool_deepl_text_translate_name SET description = "Nom du tool Translate";
CREATE i18n_key:tool_deepl_text_translate_desc SET description = "Description du tool Translate";
CREATE i18n_key:tool_deepl_text_translate_tooltip SET description = "Tooltip du tool Translate";
CREATE i18n_key:tool_deepl_text_translate_success SET description = "Message de succes du tool Translate";
CREATE i18n_key:tool_deepl_text_translate_error SET description = "Message d'erreur du tool Translate";

CREATE i18n_key:tool_demio_event_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_demio_event_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_demio_event_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_demio_event_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_demio_event_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_demio_event_getMany_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_demio_event_getMany_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_demio_event_getMany_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_demio_event_getMany_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_demio_event_getMany_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_demio_report_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_demio_report_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_demio_report_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_demio_report_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_demio_report_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_demio_report_getMany_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_demio_report_getMany_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_demio_report_getMany_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_demio_report_getMany_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_demio_report_getMany_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_dhl_shipment_get_name SET description = "Nom du tool Get Tracking Details";
CREATE i18n_key:tool_dhl_shipment_get_desc SET description = "Description du tool Get Tracking Details";
CREATE i18n_key:tool_dhl_shipment_get_tooltip SET description = "Tooltip du tool Get Tracking Details";
CREATE i18n_key:tool_dhl_shipment_get_success SET description = "Message de succes du tool Get Tracking Details";
CREATE i18n_key:tool_dhl_shipment_get_error SET description = "Message d'erreur du tool Get Tracking Details";

CREATE i18n_key:tool_discord_discord_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_discord_discord_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_discord_discord_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_discord_discord_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_discord_discord_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_discord_discord_getMany_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_discord_discord_getMany_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_discord_discord_getMany_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_discord_discord_getMany_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_discord_discord_getMany_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_discordv1_discordv1_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_discordv1_discordv1_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_discordv1_discordv1_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_discordv1_discordv1_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_discordv1_discordv1_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_discordv1_discordv1_getMany_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_discordv1_discordv1_getMany_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_discordv1_discordv1_getMany_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_discordv1_discordv1_getMany_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_discordv1_discordv1_getMany_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_discordv2_discordv2_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_discordv2_discordv2_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_discordv2_discordv2_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_discordv2_discordv2_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_discordv2_discordv2_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_discordv2_discordv2_getMany_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_discordv2_discordv2_getMany_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_discordv2_discordv2_getMany_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_discordv2_discordv2_getMany_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_discordv2_discordv2_getMany_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_discourse_category_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_discourse_category_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_discourse_category_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_discourse_category_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_discourse_category_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_discourse_category_getMany_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_discourse_category_getMany_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_discourse_category_getMany_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_discourse_category_getMany_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_discourse_category_getMany_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_discourse_group_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_discourse_group_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_discourse_group_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_discourse_group_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_discourse_group_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_discourse_group_getMany_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_discourse_group_getMany_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_discourse_group_getMany_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_discourse_group_getMany_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_discourse_group_getMany_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_discourse_post_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_discourse_post_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_discourse_post_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_discourse_post_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_discourse_post_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_discourse_post_getMany_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_discourse_post_getMany_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_discourse_post_getMany_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_discourse_post_getMany_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_discourse_post_getMany_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_discourse_user_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_discourse_user_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_discourse_user_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_discourse_user_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_discourse_user_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_discourse_user_getMany_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_discourse_user_getMany_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_discourse_user_getMany_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_discourse_user_getMany_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_discourse_user_getMany_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_discourse_userGroup_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_discourse_userGroup_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_discourse_userGroup_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_discourse_userGroup_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_discourse_userGroup_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_discourse_userGroup_getMany_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_discourse_userGroup_getMany_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_discourse_userGroup_getMany_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_discourse_userGroup_getMany_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_discourse_userGroup_getMany_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_discourse_usergroup_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_discourse_usergroup_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_discourse_usergroup_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_discourse_usergroup_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_discourse_usergroup_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_discourse_usergroup_getMany_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_discourse_usergroup_getMany_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_discourse_usergroup_getMany_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_discourse_usergroup_getMany_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_discourse_usergroup_getMany_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_disqus_forum_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_disqus_forum_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_disqus_forum_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_disqus_forum_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_disqus_forum_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_disqus_forum_getCategories_name SET description = "Nom du tool Get All Categories";
CREATE i18n_key:tool_disqus_forum_getCategories_desc SET description = "Description du tool Get All Categories";
CREATE i18n_key:tool_disqus_forum_getCategories_tooltip SET description = "Tooltip du tool Get All Categories";
CREATE i18n_key:tool_disqus_forum_getCategories_success SET description = "Message de succes du tool Get All Categories";
CREATE i18n_key:tool_disqus_forum_getCategories_error SET description = "Message d'erreur du tool Get All Categories";

CREATE i18n_key:tool_disqus_forum_getThreads_name SET description = "Nom du tool Get All Threads";
CREATE i18n_key:tool_disqus_forum_getThreads_desc SET description = "Description du tool Get All Threads";
CREATE i18n_key:tool_disqus_forum_getThreads_tooltip SET description = "Tooltip du tool Get All Threads";
CREATE i18n_key:tool_disqus_forum_getThreads_success SET description = "Message de succes du tool Get All Threads";
CREATE i18n_key:tool_disqus_forum_getThreads_error SET description = "Message d'erreur du tool Get All Threads";

CREATE i18n_key:tool_disqus_forum_getPosts_name SET description = "Nom du tool Get All Posts";
CREATE i18n_key:tool_disqus_forum_getPosts_desc SET description = "Description du tool Get All Posts";
CREATE i18n_key:tool_disqus_forum_getPosts_tooltip SET description = "Tooltip du tool Get All Posts";
CREATE i18n_key:tool_disqus_forum_getPosts_success SET description = "Message de succes du tool Get All Posts";
CREATE i18n_key:tool_disqus_forum_getPosts_error SET description = "Message d'erreur du tool Get All Posts";

CREATE i18n_key:tool_drift_contact_get_name SET description = "Nom du tool Get";
CREATE i18n_key:tool_drift_contact_get_desc SET description = "Description du tool Get";
CREATE i18n_key:tool_drift_contact_get_tooltip SET description = "Tooltip du tool Get";
CREATE i18n_key:tool_drift_contact_get_success SET description = "Message de succes du tool Get";
CREATE i18n_key:tool_drift_contact_get_error SET description = "Message d'erreur du tool Get";

CREATE i18n_key:tool_drift_contact_getMany_name SET description = "Nom du tool Get Many";
CREATE i18n_key:tool_drift_contact_getMany_desc SET description = "Description du tool Get Many";
CREATE i18n_key:tool_drift_contact_getMany_tooltip SET description = "Tooltip du tool Get Many";
CREATE i18n_key:tool_drift_contact_getMany_success SET description = "Message de succes du tool Get Many";
CREATE i18n_key:tool_drift_contact_getMany_error SET description = "Message d'erreur du tool Get Many";

CREATE i18n_key:tool_dropbox_file_copy_name SET description = "Nom du tool Copy";
CREATE i18n_key:tool_dropbox_file_copy_desc SET description = "Description du tool Copy";
CREATE i18n_key:tool_dropbox_file_copy_tooltip SET description = "Tooltip du tool Copy";
CREATE i18n_key:tool_dropbox_file_copy_success SET description = "Message de succes du tool Copy";
CREATE i18n_key:tool_dropbox_file_copy_error SET description = "Message d'erreur du tool Copy";

CREATE i18n_key:tool_dropbox_file_delete_name SET description = "Nom du tool Delete";
CREATE i18n_key:tool_dropbox_file_delete_desc SET description = "Description du tool Delete";
CREATE i18n_key:tool_dropbox_file_delete_tooltip SET description = "Tooltip du tool Delete";
CREATE i18n_key:tool_dropbox_file_delete_success SET description = "Message de succes du tool Delete";
CREATE i18n_key:tool_dropbox_file_delete_error SET description = "Message d'erreur du tool Delete";

CREATE i18n_key:tool_dropbox_file_download_name SET description = "Nom du tool Download";
CREATE i18n_key:tool_dropbox_file_download_desc SET description = "Description du tool Download";
CREATE i18n_key:tool_dropbox_file_download_tooltip SET description = "Tooltip du tool Download";
CREATE i18n_key:tool_dropbox_file_download_success SET description = "Message de succes du tool Download";
CREATE i18n_key:tool_dropbox_file_download_error SET description = "Message d'erreur du tool Download";

CREATE i18n_key:tool_dropbox_file_move_name SET description = "Nom du tool Move";
CREATE i18n_key:tool_dropbox_file_move_desc SET description = "Description du tool Move";
CREATE i18n_key:tool_dropbox_file_move_tooltip SET description = "Tooltip du tool Move";
CREATE i18n_key:tool_dropbox_file_move_success SET description = "Message de succes du tool Move";
CREATE i18n_key:tool_dropbox_file_move_error SET description = "Message d'erreur du tool Move";

CREATE i18n_key:tool_dropbox_file_upload_name SET description = "Nom du tool Upload";
CREATE i18n_key:tool_dropbox_file_upload_desc SET description = "Description du tool Upload";
CREATE i18n_key:tool_dropbox_file_upload_tooltip SET description = "Tooltip du tool Upload";
CREATE i18n_key:tool_dropbox_file_upload_success SET description = "Message de succes du tool Upload";
CREATE i18n_key:tool_dropbox_file_upload_error SET description = "Message d'erreur du tool Upload";

CREATE i18n_key:tool_dropbox_folder_copy_name SET description = "Nom du tool Copy";
CREATE i18n_key:tool_dropbox_folder_copy_desc SET description = "Description du tool Copy";
CREATE i18n_key:tool_dropbox_folder_copy_tooltip SET description = "Tooltip du tool Copy";
CREATE i18n_key:tool_dropbox_folder_copy_success SET description = "Message de succes du tool Copy";
CREATE i18n_key:tool_dropbox_folder_copy_error SET description = "Message d'erreur du tool Copy";

CREATE i18n_key:tool_dropbox_folder_delete_name SET description = "Nom du tool Delete";
CREATE i18n_key:tool_dropbox_folder_delete_desc SET description = "Description du tool Delete";
CREATE i18n_key:tool_dropbox_folder_delete_tooltip SET description = "Tooltip du tool Delete";
CREATE i18n_key:tool_dropbox_folder_delete_success SET description = "Message de succes du tool Delete";
CREATE i18n_key:tool_dropbox_folder_delete_error SET description = "Message d'erreur du tool Delete";

CREATE i18n_key:tool_dropbox_folder_download_name SET description = "Nom du tool Download";
CREATE i18n_key:tool_dropbox_folder_download_desc SET description = "Description du tool Download";
CREATE i18n_key:tool_dropbox_folder_download_tooltip SET description = "Tooltip du tool Download";
CREATE i18n_key:tool_dropbox_folder_download_success SET description = "Message de succes du tool Download";
CREATE i18n_key:tool_dropbox_folder_download_error SET description = "Message d'erreur du tool Download";

CREATE i18n_key:tool_dropbox_folder_move_name SET description = "Nom du tool Move";
CREATE i18n_key:tool_dropbox_folder_move_desc SET description = "Description du tool Move";
CREATE i18n_key:tool_dropbox_folder_move_tooltip SET description = "Tooltip du tool Move";
CREATE i18n_key:tool_dropbox_folder_move_success SET description = "Message de succes du tool Move";
CREATE i18n_key:tool_dropbox_folder_move_error SET description = "Message d'erreur du tool Move";

CREATE i18n_key:tool_dropbox_folder_upload_name SET description = "Nom du tool Upload";
CREATE i18n_key:tool_dropbox_folder_upload_desc SET description = "Description du tool Upload";
CREATE i18n_key:tool_dropbox_folder_upload_tooltip SET description = "Tooltip du tool Upload";
CREATE i18n_key:tool_dropbox_folder_upload_success SET description = "Message de succes du tool Upload";
CREATE i18n_key:tool_dropbox_folder_upload_error SET description = "Message d'erreur du tool Upload";

CREATE i18n_key:tool_dropbox_search_copy_name SET description = "Nom du tool Copy";
CREATE i18n_key:tool_dropbox_search_copy_desc SET description = "Description du tool Copy";
CREATE i18n_key:tool_dropbox_search_copy_tooltip SET description = "Tooltip du tool Copy";
CREATE i18n_key:tool_dropbox_search_copy_success SET description = "Message de succes du tool Copy";
CREATE i18n_key:tool_dropbox_search_copy_error SET description = "Message d'erreur du tool Copy";

CREATE i18n_key:tool_dropbox_search_delete_name SET description = "Nom du tool Delete";
CREATE i18n_key:tool_dropbox_search_delete_desc SET description = "Description du tool Delete";
CREATE i18n_key:tool_dropbox_search_delete_tooltip SET description = "Tooltip du tool Delete";
CREATE i18n_key:tool_dropbox_search_delete_success SET description = "Message de succes du tool Delete";
CREATE i18n_key:tool_dropbox_search_delete_error SET description = "Message d'erreur du tool Delete";

CREATE i18n_key:tool_dropbox_search_download_name SET description = "Nom du tool Download";
CREATE i18n_key:tool_dropbox_search_download_desc SET description = "Description du tool Download";
CREATE i18n_key:tool_dropbox_search_download_tooltip SET description = "Tooltip du tool Download";
CREATE i18n_key:tool_dropbox_search_download_success SET description = "Message de succes du tool Download";
CREATE i18n_key:tool_dropbox_search_download_error SET description = "Message d'erreur du tool Download";

CREATE i18n_key:tool_dropbox_search_move_name SET description = "Nom du tool Move";
CREATE i18n_key:tool_dropbox_search_move_desc SET description = "Description du tool Move";
CREATE i18n_key:tool_dropbox_search_move_tooltip SET description = "Tooltip du tool Move";
CREATE i18n_key:tool_dropbox_search_move_success SET description = "Message de succes du tool Move";
CREATE i18n_key:tool_dropbox_search_move_error SET description = "Message d'erreur du tool Move";

CREATE i18n_key:tool_dropbox_search_upload_name SET description = "Nom du tool Upload";
CREATE i18n_key:tool_dropbox_search_upload_desc SET description = "Description du tool Upload";
CREATE i18n_key:tool_dropbox_search_upload_tooltip SET description = "Tooltip du tool Upload";
CREATE i18n_key:tool_dropbox_search_upload_success SET description = "Message de succes du tool Upload";
CREATE i18n_key:tool_dropbox_search_upload_error SET description = "Message d'erreur du tool Upload";

