[package]
description = "WebRTC for lyxal_network under WASM environment"
edition.workspace = true
name = "lyxal_network-webrtc-websys"
version = "0.4.0"
publish = true

[dependencies]
bytes = "1"
futures = { workspace = true }
getrandom = { workspace = true, features = ["js"] }
hex = "0.4.3"
js-sys = { version = "0.3" }
lyxal_network-core = { workspace = true }
lyxal_network-identity = { workspace = true }
lyxal_network-webrtc-utils = { workspace = true }
send_wrapper = { version = "0.6.0", features = ["futures"] }
thiserror = { workspace = true }
tracing = { workspace = true }
wasm-bindgen = { version = "0.2.90" }
wasm-bindgen-futures = { version = "0.4.42" }
web-sys = { version = "0.3.70", features = ["Document", "Location", "MessageEvent", "Navigator", "RtcCertificate", "RtcConfiguration", "RtcDataChannel", "RtcDataChannelEvent", "RtcDataChannelInit", "RtcDataChannelState", "RtcDataChannelType", "RtcPeerConnection", "RtcSdpType", "RtcSessionDescription", "RtcSessionDescriptionInit", "Window"] }

[lints]
workspace = true
