[package]
name = "experimentation_client"
version = "0.8.0"
edition = "2024"

[dependencies]
chrono = { version = "*" }
derive_more = { version = "*" }
log = { version = "*" }
once_cell = { version = "*" }
reqwest = { version = "*" }
serde_json = { version = "*" }
superposition_types = { path = "../superposition_types", features = ["experimentation", "api" ] }
tokio = { version = "*", features = ["full"] }

[lib]
name = "experimentation_client"
crate-type = ["cdylib", "lib"]

[build-dependencies]
cbindgen = { version = "*" }







