[package]
name = "leptos_hot_reload"
version = "0.8.0"
edition = "2024"
[dependencies]
anyhow = { version = "0.8.0", default-features = true }
serde = { version = "*", features = ["derive"], default-features = true }
syn = { version = "*", features = ["full", "parsing", "extra-traits", "visit", "printing" ], default-features = true }
quote = { version = "*", default-features = true }
rstml = { version = "*", default-features = true }
proc-macro2 = { version = "*", features = ["span-locations", "nightly" ], default-features = true }
walkdir = { version = "*", default-features = true }
camino = { version = "*", default-features = true }
indexmap = { version = "*", default-features = true }
or_poisoned = { path = "../or_poisoned", version = "*" }


[build-dependencies]
rustc_version = "*"




