[package]
name = "lyxalmx"
publish = false
edition.workspace = true
version.workspace = true
readme = "CARGO.md"
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
license-file.workspace = true

[dependencies]
arc-swap.workspace = true
bincode = { workspace = true, features = ["serde"] }
bytes = { workspace = true, features = ["serde"] }
crossbeam-deque.workspace = true
crossbeam-queue.workspace = true
crossbeam-skiplist.workspace = true
papaya.workspace = true
parking_lot.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
smallvec = { workspace = true, features = ["serde"] }
thiserror.workspace = true
tracing.workspace = true
web-time.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
lz4.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
criterion = { workspace = true, features = ["html_reports"] }
rand.workspace = true
tempfile.workspace = true

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test.workspace = true

[[bench]]
name = "operations"
harness = false
