[package]
name = "query"
version = "0.8.0"
edition = "2024"

[dependencies]
leptos = { path = "../../../core/lyx-core-leptos/leptos" }
cfg-if = { version = "*" }
js-sys = { version = "*" , optional = true }
web-sys = { version = "*", optional = true }
miniserde = { version = "*" , optional = true }
gloo-timers = { version = "*" , optional = true }
tokio = { version = "*", optional = true }
slotmap = { version = "*" }
futures-channel = { version = "*" }
futures = { version = "*" }
async-trait = { version = "*" }
indexed_db_futures = { version = "*" , optional = true }
async_cell = { version = "*" , optional = true }

[features]
hydrate = ["js-sys", "dep:web-sys", "gloo-timers", "async_cell"]
csr = ["js-sys", "dep:web-sys", "gloo-timers", "async_cell"]
ssr = ["dep:tokio"]
local_storage = ["miniserde", "web-sys/Storage"]
indexed_db = [ "miniserde", "indexed_db_futures"]

[dev-dependencies]
leptos_axum = { path = "../../../core/lyx-core-leptos/integrations/axum" }
serde = { version = "*" }












