-- ===== APITEMPLATEIO I18N TRANSLATIONS =====
-- ===== Date: 2025-11-05 =====
-- ===== Langues: FR, EN, IT, DE, ES =====
-- ===== Total: 5 traductions =====

BEGIN

-- APITEMPLATEIO PROVIDER
-- APITEMPLATEIO NAME
RELATE i18n_key:provider_apitemplateio_name->translation->language:fr SET text = "APITEMPLATEIO";
RELATE i18n_key:provider_apitemplateio_name->translation->language:en SET text = "APITEMPLATEIO";
RELATE i18n_key:provider_apitemplateio_name->translation->language:it SET text = "APITEMPLATEIO";
RELATE i18n_key:provider_apitemplateio_name->translation->language:de SET text = "APITEMPLATEIO";
RELATE i18n_key:provider_apitemplateio_name->translation->language:es SET text = "APITEMPLATEIO";

-- APITEMPLATEIO DESCRIPTION
RELATE i18n_key:provider_apitemplateio_description->translation->language:fr SET text = "APITEMPLATEIO Provider";
RELATE i18n_key:provider_apitemplateio_description->translation->language:en SET text = "APITEMPLATEIO Provider";
RELATE i18n_key:provider_apitemplateio_description->translation->language:it SET text = "APITEMPLATEIO Provider";
RELATE i18n_key:provider_apitemplateio_description->translation->language:de SET text = "APITEMPLATEIO Provider";
RELATE i18n_key:provider_apitemplateio_description->translation->language:es SET text = "APITEMPLATEIO Provider";

-- APITEMPLATEIO TOOLTIP
RELATE i18n_key:provider_apitemplateio_tooltip->translation->language:fr SET text = "Pour APITEMPLATEIO";
RELATE i18n_key:provider_apitemplateio_tooltip->translation->language:en SET text = "For APITEMPLATEIO";
RELATE i18n_key:provider_apitemplateio_tooltip->translation->language:it SET text = "Per APITEMPLATEIO";
RELATE i18n_key:provider_apitemplateio_tooltip->translation->language:de SET text = "Für APITEMPLATEIO";
RELATE i18n_key:provider_apitemplateio_tooltip->translation->language:es SET text = "Para APITEMPLATEIO";

COMMIT;