[package]
name = "rtc-interceptor"
version.workspace = true
edition.workspace = true

[dependencies]
shared = { workspace = true, default-features = false, features = [] }
sansio.workspace = true
interceptor-derive.workspace = true

rtp.workspace = true
rtcp.workspace = true
rand = "0.8"
log = "0.4.29"

[dev-dependencies]
