[package]
name = "sso_auth_axum"
version = "0.8.0"
edition = "2024"
[lib]
crate-type = ["cdylib", "rlib"]
[dependencies]
oauth2 = { version = "*", optional = true }
anyhow = { version = "*" }
console_log = { version = "*" }
rand = { version = "*", optional = true, features = ["min_const_gen"] }
console_error_panic_hook = { version = "*" }
futures = { version = "*" }
leptos = { path = "../leptos", version = "*", optional = true }
leptos_meta = { path = "../../meta", version = "*", optional = true }
leptos_axum = { path = "../../integrations/axum", version = "*", optional = true }
leptos_router = { path = "../../router", version = "*", optional = true }
log = { version = "*" }
simple_logger = { version = "*" }
serde = { version = "*", features = ["derive"] }
serde_json = { version = "*", optional = true }
leptos_axum = { version = "*", optional = true, features = ["macros"] }
tower = { version = "*", optional = true }
tower-http = { version = "*", optional = true, features = ["fs"] }
tokio = { version = "*", optional = true, features = ["full"] }
http = { version = "*" }
sqlx = { version = "*", optional = true, features = ["runtime-tokio-rustls", "sqlite" ] }
thiserror = { version = "*" }
wasm-bindgen = { version = "*" }
axum_session_auth = { version = "*", optional = true, features = ["sqlite-rustls" ] }
axum_session = { version = "*", optional = true, features = ["sqlite-rustls" ] }
async-trait = { version = "*", optional = true }
reqwest = { version = "*", optional = true, features = ["json"] }
[features]
hydrate = ["leptos/hydrate", "meta/hydrate", "router/hydrate"]
ssr = [
"dep:serde_json",
"dep:axum",
"dep:tower",
"dep:tower-http",
"dep:tokio",
"dep:reqwest",
"dep:oauth2",
"dep:axum_session_auth",
"dep:axum_session",
"dep:async-trait",
"dep:sqlx",
"dep:rand",
"leptos/ssr",
"meta/ssr",
"router/ssr",
"dep:axum" ]


[build-dependencies]
rustc_version = "*"






