[package]
name = "lyx-viz-trading-charts"
version = "0.0.1"
edition = "2024"
[dependencies]
gloo-console = { version = "0.0.1" }
chrono = { version = "0.0.1", features = ["alloc", "serde", "wasmbind"] }
wasmbind-macro = { version = "0.0.1", package = "wasmbind-js-file-macro" }
emitix = { version = "0.0.1" }
js-sys = { version = "0.0.1" }
lyx-core-leptos = { path = "../../../core/lyx-core-leptos/leptos", version = "0.0.1" }
serde = { version = "0.0.1" }
serde-wasm-bindgen = { version = "0.0.1" }
wasm-bindgen = { version = "0.0.1" }
web-sys = { version = "0.0.1" }
[build-dependencies]
npm_rs = { version = "0.0.1" }
log = { version = "0.0.1" }
